<?php require dirname(__DIR__).'/layouts/admin_start.php';$editing=!empty($shipment['id']);$sent=($shipment['status']??'')==='awaiting_receipt'; ?>
<section class="shipment-builder">
<header class="shipment-page-heading shipment-page-actions"><a class="button button-secondary" href="<?= $editing?'/samples/shipments/view?id='.(int)$shipment['id']:'/samples' ?>">Voltar</a></header>
<?php if($sent): ?><div class="shipment-notice">Esta remessa ainda não foi recebida pelo LCQH e pode ser alterada.</div><?php endif; ?>
<?php if($errors): ?><div class="alert alert-error"><ul><?php foreach($errors as $error): ?><li><?= htmlspecialchars($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form id="shipment-form" method="post" action="<?= $editing?'/samples/shipments/edit':'/samples/shipments/create' ?>"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><?php if($editing): ?><input type="hidden" name="id" value="<?= (int)$shipment['id'] ?>"><?php endif; ?>
<section class="shipment-section"><div class="shipment-section-heading"><div><h3>Dados do envio</h3><p>Defina a origem, a finalidade e os responsáveis pela conferência.</p></div></div><div class="shipment-fields">
<label><span>Unidade / origem *</span><select name="origin_unit_id" required <?= $sent?'data-origin-locked="1"':'' ?>><?php if(count($units)!==1): ?><option value="">Selecione uma unidade de processamento</option><?php endif; ?><?php foreach($units as $u): ?><option value="<?= (int)$u['id'] ?>" <?= (string)($shipment['origin_unit_id']??(count($units)===1?$u['id']:''))===(string)$u['id']?'selected':'' ?>><?= htmlspecialchars(str_starts_with(mb_strtolower($u['name']),'processamento')?$u['name']:'Processamento '.$u['name']) ?></option><?php endforeach; ?></select></label>
<label><span>Finalidade *</span><select name="purpose" required><option value="">Selecione</option><?php foreach($purposes as $key=>$label): ?><option value="<?= htmlspecialchars($key) ?>" <?= ($shipment['purpose']??'quality_control')===$key?'selected':'' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select></label>
<label data-patient-field hidden><span>Nome do paciente *</span><input name="patient_name" maxlength="255" value="<?= htmlspecialchars($shipment['patient_name']??($samples[0]['patient_name']??'')) ?>" autocomplete="off"></label>
<div class="validation-shipment-fields" data-validation-fields hidden><label><span>Validação / PV *</span><select name="validation_id"><option value="">Selecione a unidade primeiro</option></select></label><small data-validation-message aria-live="polite"></small></div><div class="validation-shipment-fields" data-phase-field hidden><label><span>Etapa / Fase *</span><select name="validation_phase_id"><option value="">Selecione</option></select></label></div>
<label><span>Responsável pelo envio</span><input readonly value="<?= htmlspecialchars($userAuth['name']) ?>"></label>
<label><span>Conferido por *</span><input name="checked_by" maxlength="180" required value="<?= htmlspecialchars($shipment['checked_by']??'') ?>" placeholder="Nome de quem realizou a conferência"></label>
<label class="span-2"><span>Observação</span><textarea name="notes" rows="3" placeholder="Inclua informações relevantes para esta remessa"><?= htmlspecialchars($shipment['notes']??'') ?></textarea></label>
</div></section>

<section class="shipment-section"><div class="shipment-section-heading with-action"><div class="heading-copy"><div><h3>Amostras</h3><p>Adicione e preencha cada amostra que compõe esta remessa.</p></div></div><button class="button button-secondary button-add" id="add-sample" type="button"><span aria-hidden="true">＋</span> Adicionar amostra</button></div><div id="samples-list" class="samples-list"></div></section>
<template id="sample-row"><article class="sample-card"><strong class="sample-number" data-sample-title aria-label="Amostra 01">01</strong><div class="sample-fields"><input type="hidden" data-field="id"><label><span>Hemocomponente *</span><select data-field="blood_component_id" required><option value="">Selecione</option><?php foreach($components as $c): ?><option value="<?= (int)$c['id'] ?>"><?= htmlspecialchars($c['code'].' - '.$c['name']) ?></option><?php endforeach; ?></select></label><label><span>Data de produção *</span><input type="date" data-field="production_date" required></label><label><span>Marca da bolsa *</span><select data-field="bag_brand_id" required><option value="">Selecione</option><?php foreach($brands as $b): ?><option value="<?= (int)$b['id'] ?>"><?= htmlspecialchars($b['name'].(!empty($b['reference_number'])?' | Ref. '.$b['reference_number']:'')) ?></option><?php endforeach; ?></select></label><label><span>Nº da doação *</span><input data-field="donation_number" maxlength="120" required autocomplete="off" placeholder="Informe o número"></label></div><button class="remove-button remove-row" type="button" aria-label="Remover amostra"><span aria-hidden="true">×</span><span class="remove-label">Remover</span></button></article></template>

<section class="shipment-section"><div class="shipment-section-heading"><div class="heading-copy"><div><h3>Caixas térmicas <small>(opcional)</small></h3><p>Se optar pelo controle térmico, mantenha caixas separadas para faixas incompatíveis. A identificação da caixa é opcional.</p></div></div></div><div id="thermal-groups" class="thermal-groups"></div><div id="boxes-empty" class="section-empty">Adicione amostras para visualizar as faixas de transporte.</div></section>

<section class="shipment-summary"><div class="summary-copy"><span class="eyebrow">Resumo da remessa</span></div><div id="component-summary" class="component-summary" aria-live="polite"></div><div class="summary-indicators"><div class="summary-pill"><strong id="sample-count">0</strong><span>amostra(s)</span></div><div class="summary-pill"><strong id="box-count">0</strong><span>caixa(s)</span></div></div></section>
<footer class="shipment-actions"><p><?= $sent?'As alterações serão aplicadas à remessa já enviada.':'Você pode continuar depois salvando como rascunho.' ?></p><div><?php if(!$sent): ?><button class="button button-secondary" type="submit">Salvar rascunho</button><button class="button button-primary" type="submit" formaction="/samples/shipments/send">Finalizar e enviar</button><?php else: ?><button class="button button-primary" type="submit">Salvar alterações</button><?php endif; ?></div></footer>
</form></section>
<dialog class="shipment-cancel-dialog" id="no-box-dialog"><div class="dialog-heading"><h3>Remessa sem caixa térmica</h3></div><p>Nenhuma caixa térmica foi registrada para esta remessa.<br>Sem o registro de uma caixa, não haverá campos para controle de temperatura durante o transporte.</p><div class="dialog-actions"><button class="button button-secondary" type="button" data-no-box-back>Voltar</button><button class="button" type="button" data-no-box-send>Enviar sem caixa térmica</button></div></dialog>
<script>
(()=>{const seed=<?= json_encode($samples,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG) ?>,boxSeed=<?= json_encode($boxes,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG) ?>,components=<?= json_encode(array_column($components,null,'id'),JSON_UNESCAPED_UNICODE|JSON_HEX_TAG) ?>,list=document.querySelector('#samples-list'),groupsElement=document.querySelector('#thermal-groups');let nextBox=0,initialBoxes=boxSeed,initializing=true;
function rangeKey(component){return component?.transport_temperature_min===null||component?.transport_temperature_max===null||component?.transport_temperature_min===undefined||component?.transport_temperature_max===undefined?`missing:${component?.id}`:`${Number(component.transport_temperature_min).toFixed(2)}|${Number(component.transport_temperature_max).toFixed(2)}`}
function currentBoxes(){return [...groupsElement.querySelectorAll('.box-entry')].map(entry=>({code:entry.querySelector('[data-box-code]').value,component_ids:[...entry.querySelectorAll('[data-component-id]')].map(x=>Number(x.value)),transport_min:entry.dataset.min||null,transport_max:entry.dataset.max||null}))}
function refresh(rebuild=true){const counts={};let sampleTotal=0;[...list.children].forEach((card,i)=>{const number=String(i+1).padStart(2,'0'),title=card.querySelector('[data-sample-title]');title.textContent=number;title.setAttribute('aria-label',`Amostra ${number}`);card.querySelectorAll('[data-field]').forEach(el=>el.name=`samples[${i}][${el.dataset.field}]`);const componentId=card.querySelector('[data-field="blood_component_id"]').value,isFilled=[...card.querySelectorAll('[data-field]:not([type="hidden"])')].some(el=>el.value.trim()!=='');if(isFilled)sampleTotal++;if(componentId)counts[componentId]=(counts[componentId]||0)+1});document.querySelector('#sample-count').textContent=sampleTotal;const summary=document.querySelector('#component-summary');summary.replaceChildren();Object.entries(counts).sort((a,b)=>(components[a[0]]?.code||'').localeCompare(components[b[0]]?.code||'')).forEach(([id,total])=>{const component=components[id];if(!component)return;const badge=document.createElement('span');badge.className='component-pill';badge.innerHTML=`<strong>${escapeHtml(component.code)}</strong><span>${escapeHtml(component.name)}</span><b>${total}</b>`;summary.append(badge)});summary.hidden=!summary.children.length;if(rebuild)renderGroups(counts);document.querySelector('#box-count').textContent=groupsElement.querySelectorAll('.box-entry').length}
function escapeHtml(value){const element=document.createElement('span');element.textContent=value??'';return element.innerHTML}
function addSample(data={},focus=false){const card=document.querySelector('#sample-row').content.firstElementChild.cloneNode(true);card.querySelectorAll('[data-field]').forEach(e=>e.value=data[e.dataset.field]??'');card.querySelector('.remove-row').onclick=()=>{card.remove();refresh()};card.querySelectorAll('select').forEach(field=>field.addEventListener('change',()=>refresh(true)));card.querySelectorAll('input').forEach(field=>field.addEventListener('change',()=>refresh(false)));card.querySelector('[data-field="donation_number"]').addEventListener('input',()=>refresh(false));card.querySelector('[data-field="donation_number"]').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addSample({blood_component_id:card.querySelector('[data-field="blood_component_id"]').value,production_date:card.querySelector('[data-field="production_date"]').value,bag_brand_id:card.querySelector('[data-field="bag_brand_id"]').value},true)}};list.append(card);if(!initializing)refresh();document.dispatchEvent(new CustomEvent('shipment-samples-changed'));if(focus)card.querySelector('[data-field="donation_number"]').focus()}
function addBox(container,group,data={}){const index=nextBox++,item=document.createElement('div');item.className='box-entry';item.dataset.min=group.min??'';item.dataset.max=group.max??'';item.innerHTML=`<label><span class="box-code-label">Nº da caixa <small>(opcional)</small></span><input data-box-code aria-label="Número da caixa" name="boxes[${index}][code]" maxlength="5" pattern="[A-Za-z]{3}[0-9]{2}" placeholder="ABC01"></label>${group.ids.map(id=>`<input data-component-id type="hidden" name="boxes[${index}][component_ids][]" value="${id}">`).join('')}<input type="hidden" name="boxes[${index}][transport_min]" value="${escapeHtml(group.min??'')}"><input type="hidden" name="boxes[${index}][transport_max]" value="${escapeHtml(group.max??'')}"><button type="button" class="remove-button" aria-label="Remover caixa"><span aria-hidden="true">×</span> Remover</button>`;item.querySelector('[data-box-code]').value=data.code??'';item.querySelector('[data-box-code]').oninput=e=>e.target.value=e.target.value.toUpperCase();item.querySelector('button').onclick=()=>{item.remove();refresh(false)};container.append(item)}
function renderGroups(counts){const saved=initialBoxes.length?initialBoxes:currentBoxes();initialBoxes=[];groupsElement.replaceChildren();const grouped={};Object.keys(counts).forEach(id=>{const c=components[id],key=rangeKey(c);if(!grouped[key])grouped[key]={key,min:c?.transport_temperature_min,max:c?.transport_temperature_max,ids:[],labels:[]};grouped[key].ids.push(Number(id));grouped[key].labels.push(c?.code||id)});Object.values(grouped).forEach(group=>{const card=document.createElement('article');card.className='thermal-group';const missing=group.key.startsWith('missing:');card.innerHTML=`<div class="thermal-group-heading"><strong>${missing?'Faixa não configurada':`${Number(group.min).toFixed(1).replace('.',',')} °C a ${Number(group.max).toFixed(1).replace('.',',')} °C`}</strong><div class="thermal-component-chips">${group.labels.map(label=>`<span>${escapeHtml(label)}</span>`).join('')}</div></div><div class="box-list"></div><button type="button" class="button button-secondary button-compact thermal-add-box"><span aria-hidden="true">+</span> Adicionar caixa</button>`;const boxList=card.querySelector('.box-list');saved.filter(box=>box.component_ids.some(id=>group.ids.includes(Number(id)))||(box.transport_min!==null&&Number(box.transport_min)===Number(group.min)&&Number(box.transport_max)===Number(group.max))).forEach(box=>addBox(boxList,group,box));card.querySelector('.thermal-add-box').onclick=()=>{addBox(boxList,group);refresh(false)};groupsElement.append(card)});document.querySelector('#boxes-empty').hidden=Object.keys(grouped).length>0}
document.querySelector('#add-sample').onclick=()=>addSample({},true);seed.forEach(x=>addSample(x));if(!seed.length)addSample();initializing=false;refresh(true)})();
</script>
<script>
(()=>{const form=document.getElementById('shipment-form'),timers=new WeakMap();
function message(card){let node=card.querySelector('[data-duplicate-message]');if(!node){node=document.createElement('small');node.className='field-error';node.dataset.duplicateMessage='';node.setAttribute('aria-live','polite');card.querySelector('[data-field="donation_number"]').closest('label').append(node);}return node}
function localDuplicate(card){const donation=card.querySelector('[data-field="donation_number"]').value.trim().toLocaleLowerCase('pt-BR'),component=card.querySelector('[data-field="blood_component_id"]').value;if(!donation||!component)return false;return [...document.querySelectorAll('.sample-card')].some(other=>other!==card&&other.querySelector('[data-field="donation_number"]')?.value.trim().toLocaleLowerCase('pt-BR')===donation&&other.querySelector('[data-field="blood_component_id"]')?.value===component)}
async function check(card){const donation=card.querySelector('[data-field="donation_number"]'),component=card.querySelector('[data-field="blood_component_id"]'),sample=card.querySelector('[data-field="id"]'),feedback=message(card);feedback.textContent='';card.dataset.duplicate='0';donation.setCustomValidity('');if(!donation.value.trim()||!component.value)return;if(localDuplicate(card)){feedback.textContent='O mesmo número de doação e hemocomponente foi informado mais de uma vez nesta remessa.';donation.setCustomValidity(feedback.textContent);card.dataset.duplicate='1';return}try{const params=new URLSearchParams({donation_number:donation.value.trim(),blood_component_id:component.value,sample_id:sample.value||'0'}),response=await fetch('/samples/check-duplicate?'+params,{headers:{Accept:'application/json'}}),data=await response.json();if(!data.available){feedback.textContent=data.message;donation.setCustomValidity(data.message);card.dataset.duplicate='1';}}catch(error){feedback.textContent='Não foi possível verificar a disponibilidade agora. A validação será repetida ao salvar.';}}
function schedule(card){clearTimeout(timers.get(card));timers.set(card,setTimeout(()=>check(card),350))}
document.addEventListener('input',event=>{const card=event.target.closest?.('.sample-card');if(card&&event.target.matches('[data-field="donation_number"]'))schedule(card)});document.addEventListener('change',event=>{const card=event.target.closest?.('.sample-card');if(card&&event.target.matches('[data-field="blood_component_id"]'))schedule(card)});form.addEventListener('submit',event=>{document.querySelectorAll('.sample-card').forEach(card=>{if(localDuplicate(card)){const field=card.querySelector('[data-field="donation_number"]');field.setCustomValidity('O mesmo número de doação e hemocomponente foi informado mais de uma vez nesta remessa.');message(card).textContent=field.validationMessage;card.dataset.duplicate='1';}});if(form.querySelector('[data-duplicate="1"]')){event.preventDefault();form.reportValidity();}});document.querySelectorAll('.sample-card').forEach(check);
})();
</script>
<script>
(()=>{const purpose=document.querySelector('[name="purpose"]'),origin=document.querySelector('[name="origin_unit_id"]'),pv=document.querySelector('[name="validation_id"]'),phase=document.querySelector('[name="validation_phase_id"]'),pvWrap=document.querySelector('[data-validation-fields]'),phaseWrap=document.querySelector('[data-phase-field]'),message=document.querySelector('[data-validation-message]'),selectedPv=<?= json_encode((string)($shipment['validation_id']??'')) ?>,selectedPhase=<?= json_encode((string)($shipment['validation_phase_id']??'')) ?>;let validations=[];
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o}function filterComponents(){const validation=validations.find(v=>String(v.id)===pv.value),chosen=validation?.phases.find(p=>String(p.id)===phase.value),allowed=(chosen?.component_ids||[]).map(String),active=purpose.value==='validation';document.querySelectorAll('[data-field="blood_component_id"] option').forEach(o=>o.hidden=active&&!!o.value&&!allowed.includes(o.value));document.querySelectorAll('[data-field="blood_component_id"]').forEach(s=>{if(active&&s.value&&!allowed.includes(s.value))s.value=''})}
function phases(){phase.replaceChildren(option('','Selecione'));const validation=validations.find(v=>String(v.id)===pv.value),rows=validation?.phases||[];rows.forEach(p=>phase.append(option(p.id,p.name)));phaseWrap.hidden=!validation||rows.length<2;phase.required=purpose.value==='validation';if(rows.length===1)phase.value=String(rows[0].id);else if(rows.some(p=>String(p.id)===selectedPhase))phase.value=selectedPhase;message.textContent=validation&&!validation.plan_configured?'Este PV ainda não possui plano de testes. Configure o plano antes de finalizar a remessa.':'';filterComponents()}
async function load(){const active=purpose.value==='validation';pvWrap.hidden=!active;pv.required=active;phase.required=active;if(!active){phaseWrap.hidden=true;validations=[];filterComponents();return}pv.replaceChildren(option('','Carregando...'));phase.replaceChildren(option('','Selecione'));message.textContent='';if(!origin.value){pv.replaceChildren(option('','Selecione a unidade primeiro'));message.textContent='Selecione a unidade de origem para carregar os PVs.';return}try{const response=await fetch('/validations/options?unit_id='+encodeURIComponent(origin.value),{headers:{Accept:'application/json'}}),data=await response.json();validations=data.validations||[];pv.replaceChildren(option('','Selecione'));validations.forEach(v=>pv.append(option(v.id,v.label)));message.textContent=data.message||'';if(validations.some(v=>String(v.id)===selectedPv))pv.value=selectedPv;phases()}catch(e){pv.replaceChildren(option('','Indisponível'));message.textContent='Não foi possível carregar as validações desta unidade.'}}
purpose.addEventListener('change',load);origin.addEventListener('change',load);pv.addEventListener('change',phases);phase.addEventListener('change',filterComponents);document.addEventListener('shipment-samples-changed',filterComponents);load()})();
</script>
<script>
(()=>{const form=document.querySelector('#shipment-form'),purpose=form.querySelector('[name="purpose"]'),wrap=form.querySelector('[data-patient-field]'),patient=form.querySelector('[name="patient_name"]'),dialog=document.querySelector('#no-box-dialog');function patientState(){const active=purpose.value==='transfusion_reaction';wrap.hidden=!active;patient.required=active;if(!active)patient.setCustomValidity('')}purpose.addEventListener('change',patientState);patientState();form.addEventListener('submit',event=>{const submitter=event.submitter;if(submitter?.formAction.endsWith('/samples/shipments/send')&&!form.querySelector('.box-entry')&&submitter.dataset.confirmedNoBox!=='1'){event.preventDefault();if(form.reportValidity())dialog.showModal()}});dialog.querySelector('[data-no-box-back]').onclick=()=>dialog.close();dialog.querySelector('[data-no-box-send]').onclick=()=>{dialog.close();const button=form.querySelector('[formaction="/samples/shipments/send"]');button.dataset.confirmedNoBox='1';form.requestSubmit(button)}})();
</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
