<?php require dirname(__DIR__).'/layouts/admin_start.php'; ?>
<?php $canCancel=$mutable&&\BloodHub\Core\Permission::can('shipments.cancel'); $isDraft=$shipment['status']==='draft'; ?>
<section class="content-card">
    <div class="section-heading">
        <div><span class="status status-<?= htmlspecialchars($shipment['status'],ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars(\BloodHub\Core\StatusLabel::label($shipment['status']),ENT_QUOTES,'UTF-8') ?></span></div>
        <div class="table-actions shipment-header-actions">
            <a class="button button-secondary" href="/samples">Voltar</a>
            <?php if($mutable): ?><a class="button" href="/samples/shipments/edit?id=<?= (int)$shipment['id'] ?>">Editar remessa</a><?php endif; ?>
            <?php if($canCancel): ?><button class="button button-danger button-danger-outline" type="button" id="open-cancel-shipment"><?= $isDraft?'Excluir rascunho':'Cancelar remessa' ?></button><?php endif; ?>
            <?php if($shipment['sent_at']&&\BloodHub\Core\Permission::can('shipments.print')): ?><a class="button button-secondary" href="/samples/shipments/report?id=<?= (int)$shipment['id'] ?>" target="_blank">Imprimir relatório</a><?php endif; ?>
        </div>
    </div>
    <?php if($shipment['status']==='awaiting_receipt'): ?><div class="shipment-notice">Esta remessa ainda não foi recebida pelo LCQH e pode ser alterada.</div><?php endif; ?>
    <dl class="detail-grid"><div><dt>Origem</dt><dd><?= htmlspecialchars($shipment['origin_name']) ?></dd></div><div><dt>Destino</dt><dd><?= htmlspecialchars($shipment['destination_name']) ?></dd></div><div><dt>Cliente</dt><dd><?= htmlspecialchars($shipment['client_name']??'—') ?></dd></div><div><dt>Responsável</dt><dd><?= htmlspecialchars($shipment['responsible_name']) ?></dd></div><div><dt>Conferido por</dt><dd><?= htmlspecialchars($shipment['checked_by']) ?></dd></div><div><dt>Finalidade</dt><dd><?= htmlspecialchars(\BloodHub\Core\SamplePurpose::label($shipment['purpose']??'quality_control')) ?></dd></div><div><dt>Enviada em</dt><dd><?= $shipment['sent_at']?date('d/m/Y H:i',strtotime($shipment['sent_at'])):'—' ?></dd></div><div><dt>Observações</dt><dd><?= nl2br(htmlspecialchars($shipment['notes']??'—')) ?></dd></div></dl>
    <?php if($shipment['status']==='cancelled'): ?><div class="shipment-notice trace-alert"><strong>Cancelada</strong><br>Motivo: <?= htmlspecialchars($shipment['cancellation_reason']??'—',ENT_QUOTES,'UTF-8') ?><br><?= $shipment['cancelled_at']?date('d/m/Y H:i',strtotime($shipment['cancelled_at'])):'—' ?> por <?= htmlspecialchars($shipment['cancelled_by_name']??'—',ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
    <h3>Amostras (<?= count($samples) ?>)</h3><div class="table-wrap"><table><thead><tr><th>Nº da Doação</th><th>Hemocomponente</th><th>Produção</th><th>Marca da bolsa</th><th>Status / detalhes</th></tr></thead><tbody><?php foreach($samples as $s): ?><tr><td><?= htmlspecialchars($s['donation_number']) ?></td><td><?= htmlspecialchars(($s['component_code']??'').' - '.($s['component_name']??'')) ?></td><td><?= $s['production_date']?date('d/m/Y',strtotime($s['production_date'])):'—' ?></td><td><?= htmlspecialchars($s['bag_brand_name']??'—') ?></td><td><span class="status status-<?= htmlspecialchars($s['status'],ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars(\BloodHub\Core\StatusLabel::label($s['status']),ENT_QUOTES,'UTF-8') ?></span><?php if($s['status']==='received'): ?><small class="cell-subtitle"><?= $s['received_at']?date('d/m/Y H:i',strtotime($s['received_at'])):'—' ?><br>por <?= htmlspecialchars($s['received_by_name']??'—') ?></small><?php elseif($s['status']==='rejected'): ?><small class="cell-subtitle"><strong>Motivo:</strong> <?= htmlspecialchars($s['rejection_reason']??'—') ?><br><?= $s['rejected_at']?date('d/m/Y H:i',strtotime($s['rejected_at'])):'—' ?> por <?= htmlspecialchars($s['rejected_by_name']??'—') ?></small><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
    <?php if($receptionHistory): ?><h3>Histórico do recebimento</h3><div class="reception-history"><?php foreach($receptionHistory as $event): ?><div><time><?= date('d/m/Y H:i',strtotime($event['at'])) ?></time><strong><?= htmlspecialchars($event['user']??'—') ?></strong><span><?= (int)$event['count'] ?> amostra<?= $event['count']===1?'':'s' ?> <?= $event['action']==='received'?'recebida'.($event['count']===1?'':'s'):'recusada'.($event['count']===1?'':'s') ?></span></div><?php endforeach; ?></div><?php endif; ?>
    <h3>Caixas térmicas</h3><?php if($receptionBoxes): ?><div class="table-wrap"><table><thead><tr><th>Código</th><th>Faixa no envio</th><th>Hemocomponentes</th><th>Temp. envio</th><th>Temp. recebimento</th><th>Recebida em</th><th>Recebida por</th></tr></thead><tbody><?php foreach($receptionBoxes as $box): ?><tr><td><strong><?= htmlspecialchars($box['box_code'],ENT_QUOTES,'UTF-8') ?></strong></td><td><?= $box['transport_temp_min_snapshot']!==null&&$box['transport_temp_max_snapshot']!==null?number_format((float)$box['transport_temp_min_snapshot'],1,',','.').' °C a '.number_format((float)$box['transport_temp_max_snapshot'],1,',','.').' °C':'—' ?></td><td><?= $box['component_labels']?implode('<br>',array_map('htmlspecialchars',explode('||',$box['component_labels']))):'—' ?></td><td><?= $box['sent_temperature']!==null?number_format((float)$box['sent_temperature'],2,',','.').' °C':'—' ?></td><td><?= $box['received_temperature']!==null?number_format((float)$box['received_temperature'],2,',','.').' °C':'—' ?></td><td><?= $box['received_at']?date('d/m/Y H:i',strtotime($box['received_at'])):'—' ?></td><td><?= htmlspecialchars($box['received_by_name']??'—',ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>Nenhuma caixa informada.</p><?php endif; ?>
</section>
<?php if($canCancel): ?>
<dialog class="shipment-cancel-dialog" id="cancel-shipment-dialog">
    <form method="post" action="/samples/shipments/cancel" id="cancel-shipment-form">
        <div class="dialog-heading"><h3><?= $isDraft?'Excluir rascunho':'Cancelar remessa' ?></h3><button type="button" class="dialog-close" data-close-dialog aria-label="Fechar">×</button></div>
        <p>Esta ação cancelará <?= $isDraft?'este rascunho e ele':'esta remessa e ela' ?> não poderá mais ser editad<?= $isDraft?'o':'a' ?>. Informe o motivo <?= $isDraft?'da exclusão':'do cancelamento' ?> para manter a rastreabilidade.</p>
        <input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$shipment['id'] ?>">
        <label><span>Motivo / justificativa *</span><textarea name="reason" required maxlength="500" placeholder="<?= $isDraft?'Descreva o motivo da exclusão deste rascunho...':'Descreva o motivo do cancelamento desta remessa...' ?>"></textarea><small class="field-error" aria-live="polite"></small></label>
        <div class="dialog-actions"><button class="button button-secondary" type="button" data-close-dialog>Cancelar</button><button class="button button-danger" type="submit"><?= $isDraft?'Confirmar exclusão':'Confirmar cancelamento' ?></button></div>
    </form>
</dialog>
<script>
(() => {
    const dialog=document.getElementById('cancel-shipment-dialog'), form=document.getElementById('cancel-shipment-form'), reason=form.elements.reason, error=form.querySelector('.field-error');
    document.getElementById('open-cancel-shipment').addEventListener('click',()=>{reason.setCustomValidity('');error.textContent='';dialog.showModal();reason.focus();});
    dialog.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>dialog.close()));
    dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
    reason.addEventListener('input',()=>{if(reason.value.trim()){reason.setCustomValidity('');error.textContent='';}});
    form.addEventListener('submit',event=>{if(!reason.value.trim()){event.preventDefault();reason.setCustomValidity('Informe o motivo da exclusão.');error.textContent='Informe o motivo da exclusão.';reason.reportValidity();reason.focus();}});
})();
</script>
<?php endif; ?>
<?php if(array_filter($samples,static fn($s)=>!empty($s['expiration_date']))): ?><section class="content-card"><div class="section-heading"><div><h3>Validade das amostras</h3><p>Snapshot aplicado no fluxo da remessa.</p></div></div><div class="table-wrap"><table><thead><tr><th>Nº da doação</th><th>Produção</th><th>Preservante</th><th>Validade</th></tr></thead><tbody><?php foreach($samples as $s): if(empty($s['expiration_date']))continue; ?><tr><td><?= htmlspecialchars($s['donation_number']) ?></td><td><?= date('d/m/Y',strtotime($s['production_date'])) ?></td><td><?= htmlspecialchars($s['preservative_code']??$s['preservative_name']??'—') ?></td><td><?= date('d/m/Y',strtotime($s['expiration_date'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
