<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database};
use DomainException;
use PDO;

final class BacteriologyService
{
    public const TEST_CODE='BACTERIOLOGY';
    public const POOL_COMPONENT='CP';
    public const POOL_MAX_SIZE=4;

    public static function counts():array
    {
        $pdo=Database::connection();BacteriologyEligibility::syncOpenSamples();
        $individual=(int)$pdo->query("SELECT COUNT(*) FROM sample_tests st JOIN tests t ON t.id=st.test_id AND t.code='BACTERIOLOGY' JOIN samples s ON s.id=st.sample_id WHERE s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results') AND st.status IN ('pending','in_progress') AND NOT EXISTS(SELECT 1 FROM bacteriology_pool_members m JOIN bacteriology_pools p ON p.id=m.pool_id WHERE m.sample_id=s.id AND m.active=1 AND p.status='open') AND NOT EXISTS(SELECT 1 FROM bacteriology_retests r WHERE r.sample_id=s.id AND r.status='pending')")->fetchColumn();
        $pools=(int)$pdo->query("SELECT COUNT(*) FROM bacteriology_pools WHERE status='open'")->fetchColumn();
        $retests=(int)$pdo->query("SELECT COUNT(*) FROM bacteriology_retests r JOIN bacteriology_results ir ON ir.id=r.initial_result_id WHERE r.status='pending' AND ir.stage='individual_initial'")->fetchColumn();
        $positives=(int)$pdo->query("SELECT COUNT(*) FROM bacteriology_positive_samples ps JOIN samples s ON s.id=ps.sample_id WHERE s.purpose='quality_control' AND ps.status<>'completed'")->fetchColumn();
        return compact('individual','pools','retests','positives')+['badge'=>$individual+$retests];
    }

    public static function individualSamples(array $f=[],string $purpose='quality_control'):array
    {
        $w=['s.purpose=:purpose',"s.status IN ('received','in_analysis','partial_results')","t.code='BACTERIOLOGY'","t.status='active'","st.status IN ('pending','in_progress')","NOT EXISTS(SELECT 1 FROM bacteriology_retests rr WHERE rr.sample_id=s.id AND rr.status='pending')","NOT EXISTS(SELECT 1 FROM bacteriology_pool_members am JOIN bacteriology_pools ap ON ap.id=am.pool_id WHERE am.sample_id=s.id AND am.active=1 AND ap.status='open')"];$p=['purpose'=>$purpose];
        self::sampleFilters($w,$p,$f);
        $sql="SELECT s.id,s.patient_name,s.donation_number,s.lcqh_code,s.production_date,s.received_at,s.origin_unit_id,s.client_id,bc.id component_id,bc.code component_code,bc.name component_name,u.name origin_name,c.name client_name,st.status test_status,pr.pool_id source_pool_id,pp.code source_pool_code,lr.id current_result_id,lr.test_sequence current_test_sequence,lr.result saved_result,lr.identified_bacteria saved_bacteria,lr.notes saved_notes,lr.workflow_status,CASE WHEN pr.pool_id IS NOT NULL THEN 'post_pool_individual' ELSE 'individual_initial' END bacteriology_stage FROM sample_tests st JOIN tests t ON t.id=st.test_id JOIN samples s ON s.id=st.sample_id JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN clients c ON c.id=s.client_id LEFT JOIN bacteriology_results pr ON pr.id=(SELECT MAX(br.id) FROM bacteriology_results br WHERE br.sample_id=s.id AND br.stage='pool_screening' AND br.result='positive') LEFT JOIN bacteriology_pools pp ON pp.id=pr.pool_id LEFT JOIN bacteriology_results lr ON lr.id=(SELECT MAX(li.id) FROM bacteriology_results li WHERE li.sample_id=s.id AND li.source_type='individual') WHERE ".implode(' AND ',$w)." ORDER BY s.received_at,s.id";
        $q=Database::connection()->prepare($sql);$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function retests(array $f=[],string $purpose='quality_control'):array
    {
        $w=["r.status='pending'","ir.stage='individual_initial'",'s.purpose=:purpose'];$p=['purpose'=>$purpose];self::sampleFilters($w,$p,$f,'s');
        if(!empty($f['origin_type'])&&$f['origin_type']!=='individual_positive')$w[]='1=0';
        $q=Database::connection()->prepare("SELECT r.id retest_id,r.created_at retest_created_at,s.id,s.patient_name,s.donation_number,s.lcqh_code,s.production_date,s.received_at,bc.code component_code,bc.name component_name,u.name origin_name,c.name client_name,ir.result initial_result,ir.identified_bacteria identified_bacteria_initial,ir.notes initial_notes FROM bacteriology_retests r JOIN samples s ON s.id=r.sample_id JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN clients c ON c.id=s.client_id JOIN bacteriology_results ir ON ir.id=r.initial_result_id WHERE ".implode(' AND ',$w)." ORDER BY r.created_at,s.id");$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function pools(array $f=[]):array
    {
        $w=['1=1'];$p=[];foreach([['origin','p.origin_unit_id'],['client','p.client_id']] as[$k,$c])if(!empty($f[$k])){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}if(!empty($f['from'])){$w[]='p.end_date>=:from';$p['from']=$f['from'];}if(!empty($f['to'])){$w[]='p.start_date<=:to';$p['to']=$f['to'];}if(!empty($f['status'])){$w[]='p.status=:status';$p['status']=$f['status'];}if(!empty($f['code'])){$w[]='p.code LIKE :code';$p['code']='%'.$f['code'].'%';}
        $q=Database::connection()->prepare("SELECT p.*,bc.code component_code,u.name origin_name,c.name client_name,COUNT(m.id) member_count,GROUP_CONCAT(CONCAT(COALESCE(s.donation_number,s.sample_code),'|',COALESCE(s.lcqh_code,'')) ORDER BY m.position SEPARATOR ';;') member_labels FROM bacteriology_pools p JOIN blood_components bc ON bc.id=p.component_id JOIN units u ON u.id=p.origin_unit_id LEFT JOIN clients c ON c.id=p.client_id JOIN bacteriology_pool_members m ON m.pool_id=p.id JOIN samples s ON s.id=m.sample_id WHERE ".implode(' AND ',$w).' GROUP BY p.id ORDER BY p.created_at DESC,p.id DESC');$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function generatePools(array $f):array
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$rows=self::eligiblePoolSamples($f,true);if(!$rows)throw new DomainException('Nenhuma CP elegível foi encontrada no período.');$groups=[];foreach($rows as$r)$groups[$r['blood_component_id'].'|'.$r['origin_unit_id'].'|'.($r['client_id']??'null')][]=$r;$codes=[];
            foreach($groups as$items)foreach(array_chunk($items,self::POOL_MAX_SIZE)as$chunk){$first=$chunk[0];$code=self::nextCode($pdo);$pdo->prepare("INSERT INTO bacteriology_pools(code,component_id,origin_unit_id,client_id,start_date,end_date,created_by) VALUES(:code,:component,:origin,:client,:start,:end,:user)")->execute(['code'=>$code,'component'=>$first['blood_component_id'],'origin'=>$first['origin_unit_id'],'client'=>$first['client_id'],'start'=>$f['from'],'end'=>$f['to'],'user'=>self::user()]);$pool=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO bacteriology_pool_members(pool_id,sample_id,position) VALUES(:pool,:sample,:position)');foreach($chunk as$i=>$s)$ins->execute(['pool'=>$pool,'sample'=>$s['id'],'position'=>$i+1]);Auth::registerAudit('bacteriology_pool.created','bacteriology_pools',$pool,null,['code'=>$code,'sample_ids'=>array_map(fn($x)=>(int)$x['id'],$chunk),'origin_unit_id'=>(int)$first['origin_unit_id'],'client_id'=>$first['client_id']]);$codes[]=$code;}
            $pdo->commit();return$codes;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public static function saveIndividual(int $sampleId,string $raw,?string $bacteria,?string $notes,bool $complete,string $purpose='quality_control'):string
    {
        $result=self::result($raw);$bacteria=self::bacteria($bacteria);if($complete&&$result==='positive'&&$bacteria===null)throw new DomainException('Informe a bactéria identificada.');$pdo=Database::connection();$pdo->beginTransaction();try{$sample=self::lockEligibleSample($sampleId);$stage=self::positivePoolId($sampleId);$stageName=$stage?'post_pool_individual':'individual_initial';$workflow=$result==='positive'&&$bacteria===null?'identification_pending':($result==='positive'&&!$stage?'retest_pending':'registered');$id=self::insertResult($sampleId,$stageName,'individual',$stage,$result,$complete&&$result==='negative',$notes,$bacteria,$workflow);self::markInProgress($sampleId);
            if(!$complete){Auth::registerAudit('bacteriology.individual_saved','bacteriology_results',$id,null,['sample_id'=>$sampleId,'result'=>$result,'stage'=>$stageName]);$pdo->commit();return'saved';}
            if($result==='negative'){self::finalize($sampleId,$result,$id);Auth::registerAudit('bacteriology.completed','samples',$sampleId,null,['result'=>$result,'source'=>$stage?'post_pool_individual':'individual']);$message='completed';}
            elseif($stage){
                self::finalize($sampleId,'positive',$id);
                $positiveId=PositiveBacteriologySampleService::createFromConfirmedResult($sampleId,$id);
                $pool=$pdo->prepare('SELECT code,result FROM bacteriology_pools WHERE id=:id');$pool->execute(['id'=>$stage]);$poolData=$pool->fetch(PDO::FETCH_ASSOC)?:[];
                Auth::registerAudit('bacteriology.positive_confirmed_after_pool','bacteriology_positive_samples',$positiveId,null,['message'=>'Positivo confirmado após abertura de pool positivo','sample_id'=>$sampleId,'result_id'=>$id,'pool_id'=>$stage,'pool_code'=>$poolData['code']??null,'pool_result'=>$poolData['result']??'positive','individual_result'=>'positive','confirmed_by'=>self::user(),'confirmed_at'=>date('Y-m-d H:i:s')]);
                Auth::registerAudit('bacteriology.completed','samples',$sampleId,null,['result'=>'positive','source'=>'post_pool_individual','pool_id'=>$stage]);$message='confirmed_pool';
            }else{$pdo->prepare("UPDATE bacteriology_results SET is_final=0,bacteriological_conformity='pending',workflow_status='retest_pending' WHERE id=:id")->execute(['id'=>$id]);$pdo->prepare("INSERT INTO bacteriology_retests(sample_id,initial_result_id,created_by) VALUES(:sample,:initial,:user)")->execute(['sample'=>$sampleId,'initial'=>$id,'user'=>self::user()]);self::markInProgress($sampleId);Auth::registerAudit('bacteriology.retest_opened','bacteriology_retests',(int)$pdo->lastInsertId(),null,['sample_id'=>$sampleId,'initial_result_id'=>$id,'identified_bacteria_initial'=>$bacteria]);$message='retest';}
            Auth::registerAudit('bacteriology.individual_result','bacteriology_results',$id,null,['sample_id'=>$sampleId,'result'=>$result,'stage'=>$stageName,'is_final'=>$message==='completed']);$pdo->commit();QcNotificationService::deliverPendingForSample($sampleId);return$message;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public static function individualTestHistory(int $sampleId,string $purpose):array
    {
        $q=Database::connection()->prepare("SELECT br.id,br.test_sequence,br.test_kind,br.result,br.identified_bacteria,br.notes,br.workflow_status,br.is_final,br.performed_at,u.name performed_by_name FROM bacteriology_results br JOIN samples s ON s.id=br.sample_id LEFT JOIN users u ON u.id=br.performed_by WHERE br.sample_id=:sample AND s.purpose=:purpose AND br.source_type='individual' ORDER BY br.test_sequence,br.id");
        $q->execute(['sample'=>$sampleId,'purpose'=>$purpose]);return$q->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function addIndividualTest(int $sampleId,string $purpose):int
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$sample=self::lockEligibleSample($sampleId);if($sample['purpose']!==$purpose)throw new DomainException('Amostra indisponível neste contexto.');
            $pending=$pdo->prepare("SELECT id FROM bacteriology_results WHERE sample_id=:sample AND source_type='individual' AND result IS NULL ORDER BY id DESC LIMIT 1 FOR UPDATE");$pending->execute(['sample'=>$sampleId]);if($pending->fetchColumn())throw new DomainException('Preencha o teste em aberto antes de adicionar outro.');
            $sequence=$pdo->prepare("SELECT COALESCE(MAX(test_sequence),0)+1 FROM bacteriology_results WHERE sample_id=:sample AND source_type='individual' FOR UPDATE");$sequence->execute(['sample'=>$sampleId]);$number=max(2,(int)$sequence->fetchColumn());
            $pdo->prepare("INSERT INTO bacteriology_results(sample_id,test_sequence,test_kind,stage,source_type,result,is_final,bacteriological_conformity,workflow_status,performed_by,performed_at) VALUES(:sample,:sequence,'additional','individual_initial','individual',NULL,0,'pending','registered',:user,NOW())")->execute(['sample'=>$sampleId,'sequence'=>$number,'user'=>self::user()]);$id=(int)$pdo->lastInsertId();self::markInProgress($sampleId);Auth::registerAudit('TRANSFUSION_REACTION_TEST_ADDED','bacteriology_results',$id,null,['sample_id'=>$sampleId,'test_sequence'=>$number]);$pdo->commit();return$id;
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public static function saveTransfusionTest(int $sampleId,int $resultId,string $raw,?string $bacteria,?string $notes,bool $complete):string
    {
        $result=self::result($raw);$bacteria=$result==='positive'?self::bacteria($bacteria):null;$notes=self::notes($notes);if($complete&&$result==='positive'&&$bacteria===null)throw new DomainException('Informe a bactéria identificada.');
        $pdo=Database::connection();$pdo->beginTransaction();try{$sample=self::lockEligibleSample($sampleId);if($sample['purpose']!=='transfusion_reaction')throw new DomainException('Amostra indisponível neste contexto.');
            if($resultId){$q=$pdo->prepare("SELECT * FROM bacteriology_results WHERE id=:id AND sample_id=:sample AND source_type='individual' FOR UPDATE");$q->execute(['id'=>$resultId,'sample'=>$sampleId]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new DomainException('Teste individual não encontrado.');$id=(int)$row['id'];$sequence=(int)$row['test_sequence'];$pdo->prepare("UPDATE bacteriology_results SET result=:result,identified_bacteria=:bacteria,notes=:notes,performed_by=:user,performed_at=NOW(),workflow_status=:workflow WHERE id=:id")->execute(['result'=>$result,'bacteria'=>$bacteria,'notes'=>$notes,'user'=>self::user(),'workflow'=>$result==='positive'?'registered':'registered','id'=>$id]);}
            else{$sequence=1;$id=self::insertResult($sampleId,'individual_initial','individual',null,$result,false,$notes,$bacteria,'registered');}
            self::markInProgress($sampleId);if(!$complete){Auth::registerAudit('TRANSFUSION_REACTION_BACTERIOLOGY_SAVED','bacteriology_results',$id,null,['sample_id'=>$sampleId,'test_sequence'=>$sequence,'result'=>$result]);$pdo->commit();return'saved';}
            if($result==='negative'){self::finalize($sampleId,'negative',$id);$state='completed';}
            else{$pdo->prepare("UPDATE bacteriology_results SET is_final=0,bacteriological_conformity='pending',workflow_status='retest_pending' WHERE id=:id")->execute(['id'=>$id]);$exists=$pdo->prepare("SELECT id FROM bacteriology_retests WHERE initial_result_id=:id AND status='pending'");$exists->execute(['id'=>$id]);if(!$exists->fetchColumn())$pdo->prepare("INSERT INTO bacteriology_retests(sample_id,initial_result_id,created_by) VALUES(:sample,:initial,:user)")->execute(['sample'=>$sampleId,'initial'=>$id,'user'=>self::user()]);$state='retest';}
            Auth::registerAudit('TRANSFUSION_REACTION_TEST_COMPLETED','bacteriology_results',$id,null,['sample_id'=>$sampleId,'test_sequence'=>$sequence,'result'=>$result,'state'=>$state]);$pdo->commit();return$state;
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public static function bulkCompleteTransfusionNegatives(array $submittedIds):array
    {
        $ids=array_values(array_unique(array_filter(array_map('intval',$submittedIds),static fn($id)=>$id>0)));if(!$ids)throw new DomainException('Selecione pelo menos uma amostra.');$pdo=Database::connection();$pdo->beginTransaction();try{$locked=[];
            foreach($ids as$id){$sample=self::lockEligibleSample($id);if($sample['purpose']!=='transfusion_reaction')throw new DomainException("Amostra #{$id} fora do contexto de reação transfusional.");$q=$pdo->prepare("SELECT id,result,workflow_status FROM bacteriology_results WHERE sample_id=:id AND source_type='individual' ORDER BY id DESC LIMIT 1 FOR UPDATE");$q->execute(['id'=>$id]);$latest=$q->fetch(PDO::FETCH_ASSOC)?:null;if(self::hasFinal($id)||($latest&&$latest['result']==='positive'))throw new DomainException("Amostra #{$id} não é mais elegível para conclusão negativa.");$q=$pdo->prepare("SELECT COUNT(*) FROM bacteriology_retests WHERE sample_id=:id AND status='pending'");$q->execute(['id'=>$id]);if((int)$q->fetchColumn()>0)throw new DomainException("Amostra #{$id} possui reteste pendente.");$locked[$id]=$latest;}
            foreach($locked as$id=>$latest){if($latest){$resultId=(int)$latest['id'];$pdo->prepare("UPDATE bacteriology_results SET result='negative',identified_bacteria=NULL,notes=NULL,performed_by=:user,performed_at=NOW(),workflow_status='registered' WHERE id=:id")->execute(['user'=>self::user(),'id'=>$resultId]);}else{$resultId=self::insertResult((int)$id,'individual_initial','individual',null,'negative',false,null,null,'registered');}self::finalize((int)$id,'negative',$resultId);Auth::registerAudit('TRANSFUSION_REACTION_TEST_COMPLETED','bacteriology_results',$resultId,null,['sample_id'=>(int)$id,'result'=>'negative','state'=>'completed','bulk'=>true]);}
            Auth::registerAudit('TRANSFUSION_REACTION_BACTERIOLOGY_COMPLETED','samples',null,null,['sample_ids'=>$ids,'bulk'=>true,'completed_count'=>count($ids)]);$pdo->commit();return$ids;
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }

    public static function bulkCompleteIndividuals(array $submitted):array
    {
        $pdo=Database::connection();$items=[];
        foreach($submitted as$rawId=>$values){$id=filter_var($rawId,FILTER_VALIDATE_INT);if($id&&is_array($values))$items[(int)$id]=$values;}
        if(!$items)throw new DomainException('Nenhuma amostra foi enviada para conclusão.');
        $completed=[];$skipped=[];
        foreach($items as$sampleId=>$values){
            $pdo->beginTransaction();
            try{
                $eligible=$pdo->prepare("SELECT s.id FROM sample_tests st JOIN tests t ON t.id=st.test_id AND t.code='BACTERIOLOGY' AND t.status='active' JOIN samples s ON s.id=st.sample_id WHERE s.id=:id AND s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results') AND st.status IN ('pending','in_progress') AND NOT EXISTS(SELECT 1 FROM bacteriology_retests rr WHERE rr.sample_id=s.id AND rr.status='pending') AND NOT EXISTS(SELECT 1 FROM bacteriology_pool_members m JOIN bacteriology_pools p ON p.id=m.pool_id WHERE m.sample_id=s.id AND m.active=1 AND p.status='open') FOR UPDATE");
                $eligible->execute(['id'=>$sampleId]);if(!$eligible->fetchColumn()||self::hasFinal($sampleId))throw new DomainException('Amostra indisponível para conclusão em lote.');
                $latest=$pdo->prepare("SELECT id,result FROM bacteriology_results WHERE sample_id=:id AND source_type='individual' ORDER BY id DESC LIMIT 1 FOR UPDATE");$latest->execute(['id'=>$sampleId]);$persisted=$latest->fetch(PDO::FETCH_ASSOC)?:null;
                $submittedResult=self::result((string)($values['result']??''));$result=($persisted&&$persisted['result']==='positive')||$submittedResult==='positive'?'positive':'negative';
                if($result==='positive'){
                    if(!$persisted||$persisted['result']!=='positive'){$stage=self::positivePoolId($sampleId);$bacteria=self::bacteria($values['identified_bacteria']??null);$resultId=self::insertResult($sampleId,$stage?'post_pool_individual':'individual_initial','individual',$stage,'positive',false,$values['notes']??null,$bacteria,$bacteria===null?'identification_pending':'registered');self::markInProgress($sampleId);Auth::registerAudit('bacteriology.bulk_positive_preserved','bacteriology_results',$resultId,null,['sample_id'=>$sampleId,'result'=>'positive','completed'=>false]);}
                    $skipped[]=$sampleId;$pdo->commit();continue;
                }
                $stage=self::positivePoolId($sampleId);$resultId=$persisted?(int)$persisted['id']:self::insertResult($sampleId,$stage?'post_pool_individual':'individual_initial','individual',$stage,'negative',false,$values['notes']??null,null,'registered');
                self::finalize($sampleId,'negative',$resultId);$completed[]=$sampleId;Auth::registerAudit('bacteriology.bulk_item_completed','samples',$sampleId,null,['result_id'=>$resultId,'result'=>'negative']);$pdo->commit();QcNotificationService::deliverPendingForSample($sampleId);
            }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$skipped[]=$sampleId;}
        }
        $skipped=array_values(array_unique($skipped));Auth::registerAudit('bacteriology.bulk_completed','samples',null,null,['sample_ids'=>$completed,'completed_count'=>count($completed),'pending_ids'=>$skipped,'pending_count'=>count($items)-count($completed)]);
        return['completed'=>count($completed),'pending'=>count($items)-count($completed),'ids'=>$completed];
    }

    public static function completeRetest(int $retestId,string $raw,?string $bacteria,?string $notes):void
    {$result=self::result($raw);$bacteria=self::bacteria($bacteria);if($result==='positive'&&$bacteria===null)throw new DomainException('Informe a bactéria identificada do reteste positivo.');$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM bacteriology_retests WHERE id=:id AND status='pending' FOR UPDATE");$q->execute(['id'=>$retestId]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Reteste indisponível.');self::lockEligibleSample((int)$r['sample_id']);$id=self::insertResult((int)$r['sample_id'],'retest','retest',null,$result,true,$notes,$bacteria,'completed');$pdo->prepare("UPDATE bacteriology_retests SET status='completed',result=:result,result_id=:result_id,completed_by=:user,completed_at=NOW(),notes=:notes WHERE id=:id")->execute(['result'=>$result,'result_id'=>$id,'user'=>self::user(),'notes'=>self::notes($notes),'id'=>$retestId]);self::finalize((int)$r['sample_id'],$result,$id);if($result==='positive')PositiveBacteriologySampleService::createFromConfirmedResult((int)$r['sample_id'],$id);Auth::registerAudit('bacteriology.retest_result','bacteriology_retests',$retestId,['status'=>'pending'],['status'=>'completed','result'=>$result,'result_id'=>$id,'positive_confirmed'=>$result==='positive','identified_bacteria_retest'=>$bacteria]);Auth::registerAudit('bacteriology.completed','samples',(int)$r['sample_id'],null,['result'=>$result,'source'=>'retest']);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function retestForm(int$id):array
    {$q=Database::connection()->prepare("SELECT r.id retest_id,r.created_at,s.donation_number,s.lcqh_code,s.production_date,s.collection_date,s.received_at,bc.name component_name,bc.code component_code,u.name origin_name,c.name client_name FROM bacteriology_retests r JOIN samples s ON s.id=r.sample_id JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN clients c ON c.id=s.client_id WHERE r.id=:id");$q->execute(['id'=>$id]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)throw new DomainException('Reteste não encontrado.');return$row;}

    public static function savePoolResult(int $poolId,string $raw,?string $notes,bool $complete):string
    {$result=self::result($raw);$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM bacteriology_pools WHERE id=:id AND status='open' FOR UPDATE");$q->execute(['id'=>$poolId]);$pool=$q->fetch(PDO::FETCH_ASSOC);if(!$pool)throw new DomainException('Somente pools abertos podem receber resultado.');$pdo->prepare('UPDATE bacteriology_pools SET result=:result,resulted_by=:user,resulted_at=NOW(),notes=:notes WHERE id=:id')->execute(['result'=>$result,'user'=>self::user(),'notes'=>self::notes($notes),'id'=>$poolId]);Auth::registerAudit('bacteriology_pool.result_saved','bacteriology_pools',$poolId,['result'=>$pool['result']],['result'=>$result]);if(!$complete){$pdo->commit();return'saved';}$members=self::members($poolId,true);$status=$result==='negative'?'completed_negative':'completed_positive';$pdo->prepare('UPDATE bacteriology_pools SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$poolId]);$pdo->prepare('UPDATE bacteriology_pool_members SET active=0,released_at=NOW() WHERE pool_id=:id')->execute(['id'=>$poolId]);foreach($members as$m){$sid=(int)$m['id'];$rid=self::insertResult($sid,'pool_screening','pool',$poolId,$result,$result==='negative',null);if($result==='negative'){self::finalize($sid,'negative',$rid);Auth::registerAudit('bacteriology_pool.negative_propagated','samples',$sid,null,['pool_id'=>$poolId,'pool_code'=>$pool['code'],'result'=>'negative']);}else{self::markInProgress($sid);Auth::registerAudit('bacteriology_pool.individual_opened','samples',$sid,null,['pool_id'=>$poolId,'pool_code'=>$pool['code']]);}}
            Auth::registerAudit('bacteriology_pool.completed','bacteriology_pools',$poolId,['status'=>'open'],['status'=>$status,'result'=>$result]);$pdo->commit();return$result;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function cancelPool(int $poolId,string $reason):void
    {$reason=trim($reason);if($reason===''||mb_strlen($reason)>500)throw new DomainException('Informe um motivo de até 500 caracteres.');$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM bacteriology_pools WHERE id=:id AND status='open' FOR UPDATE");$q->execute(['id'=>$poolId]);$pool=$q->fetch(PDO::FETCH_ASSOC);if(!$pool)throw new DomainException('Somente pools abertos podem ser cancelados.');if($pool['result']!==null)throw new DomainException('Pool com resultado salvo não pode ser cancelado.');$pdo->prepare("UPDATE bacteriology_pools SET status='cancelled',cancelled_by=:user,cancelled_at=NOW(),cancellation_reason=:reason WHERE id=:id")->execute(['user'=>self::user(),'reason'=>$reason,'id'=>$poolId]);$pdo->prepare('UPDATE bacteriology_pool_members SET active=0,released_at=NOW() WHERE pool_id=:id')->execute(['id'=>$poolId]);Auth::registerAudit('bacteriology_pool.cancelled','bacteriology_pools',$poolId,['status'=>'open'],['status'=>'cancelled','reason'=>$reason]);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function members(int $poolId,bool $lock=false):array{$q=Database::connection()->prepare("SELECT s.id,s.donation_number,s.sample_code,s.lcqh_code,m.position FROM bacteriology_pool_members m JOIN samples s ON s.id=m.sample_id WHERE m.pool_id=:id ORDER BY m.position".($lock?' FOR UPDATE':''));$q->execute(['id'=>$poolId]);return$q->fetchAll(PDO::FETCH_ASSOC);}
    public static function poolMap(array $ids=[]):array{$where=$ids?'p.id IN ('.implode(',',array_map('intval',$ids)).')':"p.status<>'cancelled'";$rows=Database::connection()->query("SELECT p.*,bc.name component_name,u.name origin_name,c.name client_name,cu.name created_by_name FROM bacteriology_pools p JOIN blood_components bc ON bc.id=p.component_id JOIN units u ON u.id=p.origin_unit_id LEFT JOIN clients c ON c.id=p.client_id LEFT JOIN users cu ON cu.id=p.created_by WHERE $where ORDER BY p.created_at,p.id")->fetchAll(PDO::FETCH_ASSOC);foreach($rows as&$r)$r['members']=self::members((int)$r['id']);return$rows;}

    private static function eligiblePoolSamples(array$f,bool$lock):array{$w=["s.purpose='quality_control'","s.status IN ('received','in_analysis','partial_results')","s.received_at IS NOT NULL","bc.code='".BacteriologyEligibility::AUTOMATIC_POOL_COMPONENT_CODE."'","s.origin_unit_id IS NOT NULL","EXISTS(SELECT 1 FROM test_blood_components x JOIN tests t ON t.id=x.test_id AND t.code='BACTERIOLOGY' AND t.status='active' WHERE x.blood_component_id=s.blood_component_id)","EXISTS(SELECT 1 FROM sample_tests st JOIN tests bt ON bt.id=st.test_id AND bt.code='BACTERIOLOGY' WHERE st.sample_id=s.id AND st.status IN ('pending','in_progress'))","NOT EXISTS(SELECT 1 FROM bacteriology_results r WHERE r.sample_id=s.id AND r.is_final=1)","NOT EXISTS(SELECT 1 FROM bacteriology_pool_members m WHERE m.sample_id=s.id AND m.active=1)","NOT EXISTS(SELECT 1 FROM bacteriology_retests r WHERE r.sample_id=s.id AND r.status='pending')"];$p=[];if(empty($f['from'])||empty($f['to']))throw new DomainException('Informe data inicial e final.');$w[]='DATE(s.received_at) BETWEEN :from AND :to';$p=['from'=>$f['from'],'to'=>$f['to']];foreach([['origin','s.origin_unit_id'],['client','s.client_id']]as[$k,$c])if(!empty($f[$k])){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}$q=Database::connection()->prepare("SELECT s.id,s.blood_component_id,s.origin_unit_id,s.client_id,s.received_at FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id WHERE ".implode(' AND ',$w).' ORDER BY s.received_at,s.id'.($lock?' FOR UPDATE':''));$q->execute($p);return$q->fetchAll(PDO::FETCH_ASSOC);}
    private static function sampleFilters(array&$w,array&$p,array$f,string$alias='s'):void{foreach([['origin',"$alias.origin_unit_id"],['component',"$alias.blood_component_id"]]as[$k,$c])if(!empty($f[$k])){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}if(!empty($f['received_date'])){$w[]="DATE($alias.received_at)=:received_date";$p['received_date']=$f['received_date'];}foreach([['patient',"$alias.patient_name"],['donation',"$alias.donation_number"],['lcqh',"$alias.lcqh_code"]]as[$k,$c])if(!empty($f[$k])){$w[]="$c LIKE :$k";$p[$k]='%'.$f[$k].'%';}}
    private static function lockEligibleSample(int$id):array{$q=Database::connection()->prepare("SELECT s.* FROM samples s JOIN sample_tests st ON st.sample_id=s.id JOIN tests t ON t.id=st.test_id AND t.code='BACTERIOLOGY' AND t.status='active' WHERE s.id=:id AND s.purpose IN ('quality_control','transfusion_reaction') AND s.status IN ('received','in_analysis','partial_results') FOR UPDATE");$q->execute(['id'=>$id]);$s=$q->fetch(PDO::FETCH_ASSOC);if(!$s||self::hasFinal($id))throw new DomainException('Amostra indisponível para resultado bacteriológico.');return$s;}
    private static function positivePoolId(int$s):?int{$q=Database::connection()->prepare("SELECT pool_id FROM bacteriology_results WHERE sample_id=:s AND stage='pool_screening' AND result='positive' ORDER BY id DESC LIMIT 1");$q->execute(['s'=>$s]);$v=$q->fetchColumn();return$v===false?null:(int)$v;}
    private static function insertResult(int$s,string$stage,string$source,?int$pool,string$result,bool$final,?string$notes,?string$bacteria=null,string$workflow='registered'):int{Database::connection()->prepare("INSERT INTO bacteriology_results(sample_id,stage,source_type,pool_id,result,identified_bacteria,is_final,bacteriological_conformity,workflow_status,performed_by,performed_at,notes) VALUES(:sample,:stage,:source,:pool,:result,:bacteria,:final,:conformity,:workflow,:user,NOW(),:notes)")->execute(['sample'=>$s,'stage'=>$stage,'source'=>$source,'pool'=>$pool,'result'=>$result,'bacteria'=>$bacteria,'final'=>$final?1:0,'conformity'=>$final?($result==='negative'?'conforming':'nonconforming'):'pending','workflow'=>$final?'completed':$workflow,'user'=>self::user(),'notes'=>self::notes($notes)]);return(int)Database::connection()->lastInsertId();}
    private static function finalize(int$s,string$result,int$resultId):void{$pdo=Database::connection();$test=TestResultService::configuredTest($s,self::TEST_CODE);if(!$test)throw new DomainException('Teste bacteriológico não configurado.');$q=$pdo->prepare('SELECT id FROM sample_tests WHERE sample_id=:s AND test_id=:t FOR UPDATE');$q->execute(['s'=>$s,'t'=>$test['id']]);$st=(int)$q->fetchColumn();if(!$st){$pdo->prepare("INSERT INTO sample_tests(sample_id,test_id,status,started_at) VALUES(:s,:t,'in_progress',NOW())")->execute(['s'=>$s,'t'=>$test['id']]);$st=(int)$pdo->lastInsertId();}$old=$pdo->prepare('SELECT id FROM test_results WHERE sample_test_id=:id ORDER BY id DESC LIMIT 1');$old->execute(['id'=>$st]);$tr=(int)$old->fetchColumn();$text=$result==='negative'?'Negativo':'Positivo';if($tr)$pdo->prepare('UPDATE test_results SET result_value_text=:v,result_value_numeric=NULL,recorded_by=:u,recorded_at=NOW() WHERE id=:id')->execute(['v'=>$text,'u'=>self::user(),'id'=>$tr]);else{$pdo->prepare('INSERT INTO test_results(sample_test_id,result_value_text,recorded_by) VALUES(:st,:v,:u)')->execute(['st'=>$st,'v'=>$text,'u'=>self::user()]);$tr=(int)$pdo->lastInsertId();}$pdo->prepare("UPDATE sample_tests SET status='completed',started_at=COALESCE(started_at,NOW()),completed_at=NOW(),executed_by=:u WHERE id=:id")->execute(['u'=>self::user(),'id'=>$st]);$pdo->prepare("UPDATE bacteriology_results SET is_final=(id=:rid),workflow_status=CASE WHEN id=:rid2 THEN 'completed' ELSE workflow_status END,bacteriological_conformity=CASE WHEN id=:rid3 THEN :c ELSE bacteriological_conformity END WHERE sample_id=:s")->execute(['rid'=>$resultId,'rid2'=>$resultId,'rid3'=>$resultId,'c'=>$result==='negative'?'conforming':'nonconforming','s'=>$s]);SpecificationEvaluator::persistForResult($tr);QcNotificationService::createForResult($tr);TestResultService::refreshSampleStatus($s);}
    private static function markInProgress(int$s):void{$test=TestResultService::configuredTest($s,self::TEST_CODE);if(!$test)throw new DomainException('Teste bacteriológico não configurado.');Database::connection()->prepare("UPDATE sample_tests SET status='in_progress',started_at=COALESCE(started_at,NOW()),completed_at=NULL WHERE sample_id=:s AND test_id=:t")->execute(['s'=>$s,'t'=>$test['id']]);}
    private static function nextCode(PDO$pdo):string{$prefix='BACT-CP-'.date('Ym').'-';$q=$pdo->prepare('SELECT code FROM bacteriology_pools WHERE code LIKE :p ORDER BY code DESC LIMIT 1 FOR UPDATE');$q->execute(['p'=>$prefix.'%']);$last=(string)$q->fetchColumn();return$prefix.str_pad((string)($last?(int)substr($last,-4)+1:1),4,'0',STR_PAD_LEFT);}
    private static function result(string$r):string{$r=mb_strtolower(trim($r));$map=['negativo'=>'negative','negative'=>'negative','positivo'=>'positive','positive'=>'positive'];if(!isset($map[$r]))throw new DomainException('Selecione Negativo ou Positivo.');return$map[$r];}
    private static function notes(?string$n):?string{$n=trim((string)$n);if(mb_strlen($n)>2000)throw new DomainException('A observação deve ter no máximo 2000 caracteres.');return$n===''?null:$n;}
    private static function bacteria(?string$value):?string{$value=trim((string)$value);if(mb_strlen($value)>255)throw new DomainException('A bactéria identificada deve ter no máximo 255 caracteres.');return$value===''?null:$value;}
    private static function hasFinal(int$s):bool{$q=Database::connection()->prepare('SELECT EXISTS(SELECT 1 FROM bacteriology_results WHERE sample_id=:s AND is_final=1)');$q->execute(['s'=>$s]);return(bool)$q->fetchColumn();}
    private static function user():?int{return isset(Auth::user()['id'])?(int)Auth::user()['id']:null;}
}
