<?php
declare(strict_types=1);
namespace BloodHub\Services;
use BloodHub\Core\{Auth,Database};
use PDO;
use RuntimeException;

final class BillingService
{
 public const VIEW='billing.view',MANUAL='billing.manual.manage',CONFIG='billing.config.manage',CLOSE='billing.close',REOPEN='billing.reopen';
 public static function catalogs():array{$pdo=Database::connection();return['centers'=>$pdo->query("SELECT b.*,u.name unit_name,COALESCE(b.client_id,u.client_id) resolved_client_id,c.name client_name,c.client_type FROM billing_cost_centers b LEFT JOIN units u ON u.id=b.unit_id LEFT JOIN clients c ON c.id=COALESCE(b.client_id,u.client_id) ORDER BY b.display_order,b.name")->fetchAll(PDO::FETCH_ASSOC),'services'=>$pdo->query("SELECT * FROM billing_services ORDER BY display_order,name")->fetchAll(PDO::FETCH_ASSOC),'tests'=>FinalResultCatalog::all(),'components'=>$pdo->query("SELECT id,code,name FROM blood_components WHERE status='active' ORDER BY code")->fetchAll(PDO::FETCH_ASSOC),'units'=>$pdo->query("SELECT u.id,u.code,u.name,u.client_id,c.name client_name,c.client_type FROM units u LEFT JOIN clients c ON c.id=u.client_id WHERE u.status='active' ORDER BY u.name")->fetchAll(PDO::FETCH_ASSOC),'clients'=>ClientScopeService::getVisibleClientsForUser(true)];}
 public static function getFinalBillableResults(int$year,int$month):array
 {
  [$from,$to]=self::range($year,$month);$pdo=Database::connection();
  $sql="SELECT DISTINCT s.id sample_id,s.donation_number,s.sample_code,s.lcqh_code,s.purpose context_scope,s.origin_unit_id,s.blood_component_id,bc.code component_code,bc.name component_name,t.id test_id,t.code test_code,t.name test_name,st.completed_at completed_at,u.name responsible_name,'automatic' origin,m.billing_service_id,cc.id billing_cost_center_id,ou.name unit_name
  FROM sample_tests st JOIN samples s ON s.id=st.sample_id AND s.status<>'cancelled' JOIN tests t ON t.id=st.test_id AND t.status='active' AND t.is_final_result=1
  JOIN test_results tr ON tr.id=(SELECT MAX(x.id) FROM test_results x WHERE x.sample_test_id=st.id)
  JOIN billing_service_mappings m ON m.test_id=t.id AND m.active=1 AND (m.blood_component_id IS NULL OR m.blood_component_id=s.blood_component_id) AND FIND_IN_SET(s.purpose,m.context_scope)>0
  LEFT JOIN billing_cost_centers cc ON cc.unit_id=s.origin_unit_id AND cc.active=1 LEFT JOIN units ou ON ou.id=s.origin_unit_id LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN users u ON u.id=st.executed_by
  WHERE st.status='completed' AND t.code<>'BACTERIOLOGY' AND st.completed_at>=:from AND st.completed_at<:to";
  $q=$pdo->prepare($sql);$q->execute(['from'=>$from,'to'=>$to]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
  $b="SELECT DISTINCT s.id sample_id,s.donation_number,s.sample_code,s.lcqh_code,s.purpose context_scope,s.origin_unit_id,s.blood_component_id,bc.code component_code,bc.name component_name,t.id test_id,t.code test_code,t.name test_name,br.performed_at completed_at,u.name responsible_name,'automatic' origin,m.billing_service_id,cc.id billing_cost_center_id,ou.name unit_name FROM samples s JOIN tests t ON t.code='BACTERIOLOGY' AND t.status='active' AND t.is_final_result=1 JOIN bacteriology_results br ON br.id=(SELECT br2.id FROM bacteriology_results br2 WHERE br2.sample_id=s.id AND br2.is_final=1 ORDER BY br2.performed_at DESC,br2.id DESC LIMIT 1) JOIN billing_service_mappings m ON m.test_id=t.id AND m.active=1 AND (m.blood_component_id IS NULL OR m.blood_component_id=s.blood_component_id) AND FIND_IN_SET(s.purpose,m.context_scope)>0 LEFT JOIN billing_cost_centers cc ON cc.unit_id=s.origin_unit_id AND cc.active=1 LEFT JOIN units ou ON ou.id=s.origin_unit_id LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN users u ON u.id=br.performed_by WHERE s.status<>'cancelled' AND br.performed_at>=:from AND br.performed_at<:to";
  $q=$pdo->prepare($b);$q->execute(['from'=>$from,'to'=>$to]);$rows=array_merge($rows,$q->fetchAll(PDO::FETCH_ASSOC));
  $related="SELECT CONCAT('related:',record.id) sample_id,record.donation_number,CONCAT('RT-',record.id) sample_code,parent_sample.lcqh_code,parent_sample.purpose context_scope,COALESCE(record.storage_unit_id,parent_sample.origin_unit_id) origin_unit_id,record.blood_component_id,COALESCE(component.code,'—') component_code,COALESCE(component.name,record.hemocomponent) component_name,final_test.id test_id,final_test.code test_code,final_test.name test_name,record_test.tested_at completed_at,responsible.name responsible_name,'automatic' origin,mapping.billing_service_id,cost_center.id billing_cost_center_id,COALESCE(unit.name,'—') unit_name
  FROM bacteriology_positive_record_tests record_test
  JOIN bacteriology_positive_sample_records record ON record.id=record_test.positive_record_id AND record.position>1 AND record.perform_bacteriology=1
  JOIN bacteriology_positive_samples investigation ON investigation.id=record.positive_sample_id
  JOIN samples parent_sample ON parent_sample.id=investigation.sample_id AND parent_sample.purpose='transfusion_reaction' AND parent_sample.status<>'cancelled'
  JOIN tests final_test ON final_test.code='BACTERIOLOGY' AND final_test.status='active' AND final_test.is_final_result=1
  JOIN billing_service_mappings mapping ON mapping.test_id=final_test.id AND mapping.active=1 AND (mapping.blood_component_id IS NULL OR mapping.blood_component_id=record.blood_component_id) AND FIND_IN_SET('transfusion_reaction',mapping.context_scope)>0
  LEFT JOIN billing_cost_centers cost_center ON cost_center.unit_id=COALESCE(record.storage_unit_id,parent_sample.origin_unit_id) AND cost_center.active=1
  LEFT JOIN units unit ON unit.id=COALESCE(record.storage_unit_id,parent_sample.origin_unit_id)
  LEFT JOIN blood_components component ON component.id=record.blood_component_id
  LEFT JOIN users responsible ON responsible.id=record_test.performed_by
  WHERE record_test.status='completed' AND record_test.tested_at>=:from AND record_test.tested_at<:to
   AND record_test.id=(SELECT latest.id FROM bacteriology_positive_record_tests latest WHERE latest.positive_record_id=record.id AND latest.status='completed' ORDER BY latest.sequence DESC,latest.id DESC LIMIT 1)
   AND NOT EXISTS(SELECT 1 FROM bacteriology_positive_record_tests pending WHERE pending.positive_record_id=record.id AND pending.status='pending')";
  $q=$pdo->prepare($related);$q->execute(['from'=>$from,'to'=>$to]);$rows=array_merge($rows,$q->fetchAll(PDO::FETCH_ASSOC));
  $unique=[];foreach($rows as$r)$unique[$r['sample_id'].'|'.$r['test_id'].'|'.$r['billing_service_id']]=$r;return array_values($unique);
 }
 public static function aggregateByCostCenterAndService(int$year,int$month):array{$out=[];foreach(self::getFinalBillableResults($year,$month)as$r)if($r['billing_cost_center_id'])$out[(int)$r['billing_cost_center_id']][(int)$r['billing_service_id']]=($out[(int)$r['billing_cost_center_id']][(int)$r['billing_service_id']]??0)+1;foreach(self::getManualEntries($year,$month)as$r)$out[(int)$r['billing_cost_center_id']][(int)$r['billing_service_id']]=($out[(int)$r['billing_cost_center_id']][(int)$r['billing_service_id']]??0)+(int)$r['quantity'];return$out;}
 public static function getUnmappedFinalResults(int$year,int$month):array{[$from,$to]=self::range($year,$month);$pdo=Database::connection();$q=$pdo->prepare("SELECT t.id test_id,t.code,t.name,bc.code component_code,s.purpose context_scope,COUNT(DISTINCT s.id) quantity FROM sample_tests st JOIN samples s ON s.id=st.sample_id AND s.status<>'cancelled' JOIN tests t ON t.id=st.test_id AND t.status='active' AND t.is_final_result=1 LEFT JOIN blood_components bc ON bc.id=s.blood_component_id WHERE st.status='completed' AND t.code<>'BACTERIOLOGY' AND st.completed_at>=:from AND st.completed_at<:to AND NOT EXISTS(SELECT 1 FROM billing_service_mappings m WHERE m.test_id=t.id AND m.active=1 AND (m.blood_component_id IS NULL OR m.blood_component_id=s.blood_component_id) AND FIND_IN_SET(s.purpose,m.context_scope)>0) GROUP BY t.id,t.code,t.name,bc.code,s.purpose ORDER BY t.name");$q->execute(['from'=>$from,'to'=>$to]);$out=$q->fetchAll(PDO::FETCH_ASSOC);$b=$pdo->prepare("SELECT t.id test_id,t.code,t.name,bc.code component_code,s.purpose context_scope,COUNT(DISTINCT s.id) quantity FROM samples s JOIN tests t ON t.code='BACTERIOLOGY' AND t.status='active' AND t.is_final_result=1 JOIN bacteriology_results br ON br.id=(SELECT br2.id FROM bacteriology_results br2 WHERE br2.sample_id=s.id AND br2.is_final=1 ORDER BY br2.performed_at DESC,br2.id DESC LIMIT 1) LEFT JOIN blood_components bc ON bc.id=s.blood_component_id WHERE s.status<>'cancelled' AND br.performed_at>=:from AND br.performed_at<:to AND NOT EXISTS(SELECT 1 FROM billing_service_mappings m WHERE m.test_id=t.id AND m.active=1 AND (m.blood_component_id IS NULL OR m.blood_component_id=s.blood_component_id) AND FIND_IN_SET(s.purpose,m.context_scope)>0) GROUP BY t.id,t.code,t.name,bc.code,s.purpose");$b->execute(['from'=>$from,'to'=>$to]);return array_merge($out,$b->fetchAll(PDO::FETCH_ASSOC));}
 public static function buildMatrix(int$year,int$month,bool$snapshot=true,?array$scope=null):array{$scope??=ClientScopeService::resolve();$pdo=Database::connection();$p=self::period($year,$month);if($snapshot&&$p&&$p['status']==='CLOSED'&&!empty($p['snapshot_json']))return self::filterMatrix(json_decode($p['snapshot_json'],true),$scope);$centers=$pdo->query("SELECT b.*,COALESCE(b.client_id,u.client_id) resolved_client_id,c.name client_name,c.client_type FROM billing_cost_centers b LEFT JOIN units u ON u.id=b.unit_id LEFT JOIN clients c ON c.id=COALESCE(b.client_id,u.client_id) WHERE b.active=1 ORDER BY b.display_order,b.name")->fetchAll(PDO::FETCH_ASSOC);$services=$pdo->query("SELECT * FROM billing_services WHERE active=1 ORDER BY display_order,name")->fetchAll(PDO::FETCH_ASSOC);$agg=self::aggregateByCostCenterAndService($year,$month);$rows=[];$totals=[];foreach($services as$s)$totals[(int)$s['id']]=0;foreach($centers as$c){if(!ClientScopeService::matches($scope,$c['resolved_client_id']!==null?(int)$c['resolved_client_id']:null,$c['client_type']??null))continue;$values=[];foreach($services as$s){$v=(int)($agg[(int)$c['id']][(int)$s['id']]??0);$values[(int)$s['id']]=$v;$totals[(int)$s['id']]+=$v;}$rows[]=['center'=>$c,'values'=>$values];}$centers=array_column($rows,'center');$unmapped=$scope['type']==='all'&&!$scope['client_id']?self::getUnmappedFinalResults($year,$month):[];$missingCenters=[];$total=array_sum($totals);return compact('year','month','centers','services','rows','totals','total','unmapped','missingCenters')+['period'=>$p?:['status'=>'OPEN','snapshot_version'=>0],'scope'=>$scope];}
 public static function getManualEntries(int$year,int$month):array{$q=Database::connection()->prepare("SELECT e.*,c.cost_center_code,c.name center_name,s.service_code,s.name service_name,u.name created_by_name FROM billing_manual_entries e JOIN billing_cost_centers c ON c.id=e.billing_cost_center_id JOIN billing_services s ON s.id=e.billing_service_id LEFT JOIN users u ON u.id=e.created_by WHERE e.year=:year AND e.month=:month ORDER BY e.created_at DESC");$q->execute(compact('year','month'));return$q->fetchAll(PDO::FETCH_ASSOC);}
 public static function saveManual(array$d,int$user):int
 {
  self::assertOpen((int)$d['year'],(int)$d['month']);$qty=(int)$d['quantity'];if($qty<1)throw new RuntimeException('A quantidade deve ser maior que zero.');$pdo=Database::connection();
  $source=$pdo->prepare('SELECT 1 FROM billing_service_mappings WHERE billing_service_id=:service AND active=1 LIMIT 1');$source->execute(['service'=>(int)$d['service']]);if($source->fetchColumn())throw new RuntimeException('Este serviço possui fonte automática e não aceita lançamento complementar.');
  $id=(int)($d['id']??0);if($id){$q=$pdo->prepare('SELECT * FROM billing_manual_entries WHERE id=:id');$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Lançamento não encontrado.');$pdo->prepare('UPDATE billing_manual_entries SET billing_cost_center_id=:center,billing_service_id=:service,quantity=:quantity,notes=:notes,updated_by=:user WHERE id=:id')->execute(['center'=>$d['center'],'service'=>$d['service'],'quantity'=>$qty,'notes'=>$d['notes']?:null,'user'=>$user,'id'=>$id]);Auth::registerAudit('BILLING_MANUAL_ENTRY_UPDATED','billing_manual_entries',$id,$old,$d);return$id;}
  $pdo->prepare('INSERT INTO billing_manual_entries(year,month,billing_cost_center_id,billing_service_id,quantity,notes,created_by,updated_by) VALUES(:year,:month,:center,:service,:quantity,:notes,:user,:user2)')->execute(['year'=>$d['year'],'month'=>$d['month'],'center'=>$d['center'],'service'=>$d['service'],'quantity'=>$qty,'notes'=>$d['notes']?:null,'user'=>$user,'user2'=>$user]);$id=(int)$pdo->lastInsertId();Auth::registerAudit('BILLING_MANUAL_ENTRY_CREATED','billing_manual_entries',$id,null,$d);return$id;
 }
 public static function removeManual(int$id,int$user):void{$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM billing_manual_entries WHERE id=:id');$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Lançamento não encontrado.');self::assertOpen((int)$old['year'],(int)$old['month']);$pdo->prepare('DELETE FROM billing_manual_entries WHERE id=:id')->execute(compact('id'));Auth::registerAudit('BILLING_MANUAL_ENTRY_REMOVED','billing_manual_entries',$id,$old,['removed_by'=>$user]);}
 public static function saveMapping(array$d):int{if(!FinalResultCatalog::isFinal((int)$d['test_id']))throw new RuntimeException('Somente resultados finais ativos podem ser associados.');$contexts=array_values(array_intersect(['quality_control','validation','single_assessment','transfusion_reaction'],(array)$d['contexts']));if(!$contexts)throw new RuntimeException('Selecione ao menos um contexto.');$pdo=Database::connection();$id=(int)($d['id']??0);$data=['service'=>(int)$d['service_id'],'test'=>(int)$d['test_id'],'component'=>!empty($d['component_id'])?(int)$d['component_id']:null,'scope'=>implode(',',$contexts),'active'=>!empty($d['active'])?1:0];if($data['active']){foreach($contexts as$context){$duplicate=$pdo->prepare('SELECT id FROM billing_service_mappings WHERE id<>:id AND billing_service_id=:service AND test_id=:test AND active=1 AND ((blood_component_id IS NULL AND :component IS NULL) OR blood_component_id=:component2) AND FIND_IN_SET(:context,context_scope)>0 LIMIT 1');$duplicate->execute(['id'=>$id,'service'=>$data['service'],'test'=>$data['test'],'component'=>$data['component'],'component2'=>$data['component'],'context'=>$context]);if($duplicate->fetchColumn())throw new RuntimeException('Já existe uma associação ativa para este resultado final, contexto e serviço.');}}$old=null;$pdo->beginTransaction();try{if($id){$q=$pdo->prepare('SELECT * FROM billing_service_mappings WHERE id=:id FOR UPDATE');$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Associação não encontrada.');if(self::mappingUsed($old)){$pdo->prepare('UPDATE billing_service_mappings SET active=0 WHERE id=:id')->execute(compact('id'));$version=(int)$old['version']+1;$pdo->prepare('INSERT INTO billing_service_mappings(billing_service_id,test_id,blood_component_id,context_scope,active,version,supersedes_id) VALUES(:service,:test,:component,:scope,:active,:version,:old)')->execute($data+['version'=>$version,'old'=>$id]);$id=(int)$pdo->lastInsertId();}else{$pdo->prepare('UPDATE billing_service_mappings SET billing_service_id=:service,test_id=:test,blood_component_id=:component,context_scope=:scope,active=:active WHERE id=:id')->execute($data+compact('id'));}}else{$pdo->prepare('INSERT INTO billing_service_mappings(billing_service_id,test_id,blood_component_id,context_scope,active) VALUES(:service,:test,:component,:scope,:active)')->execute($data);$id=(int)$pdo->lastInsertId();}Auth::registerAudit('BILLING_MAPPING_UPDATED','billing_service_mappings',$id,$old,$data);$pdo->commit();return$id;}catch(\Throwable$e){$pdo->rollBack();throw$e;}}
 public static function saveCatalog(string$type,array$d):void{if(!in_array($type,['center','service'],true))throw new RuntimeException('Tipo de cadastro inválido.');$table=$type==='center'?'billing_cost_centers':'billing_services';$id=(int)($d['id']??0);$pdo=Database::connection();$old=null;if($id){$q=$pdo->prepare("SELECT * FROM $table WHERE id=:id");$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Cadastro não encontrado.');}if($type==='center'){$data=['code'=>trim($d['code']),'name'=>trim($d['name']),'unit'=>$d['unit_id']!==''?(int)$d['unit_id']:null,'client'=>($d['client_id']??'')!==''?(int)$d['client_id']:null,'ord'=>(int)$d['display_order'],'active'=>!empty($d['active'])?1:0];$sql=$id?"UPDATE $table SET cost_center_code=:code,name=:name,unit_id=:unit,client_id=:client,display_order=:ord,active=:active WHERE id=:id":"INSERT INTO $table(cost_center_code,name,unit_id,client_id,display_order,active) VALUES(:code,:name,:unit,:client,:ord,:active)";}else{$data=['code'=>trim($d['code']),'name'=>trim($d['name']),'ord'=>(int)$d['display_order'],'active'=>!empty($d['active'])?1:0];$sql=$id?"UPDATE $table SET service_code=:code,name=:name,display_order=:ord,active=:active WHERE id=:id":"INSERT INTO $table(service_code,name,display_order,active) VALUES(:code,:name,:ord,:active)";}if(!$data['code']||!$data['name'])throw new RuntimeException('Código e nome são obrigatórios.');$pdo->prepare($sql)->execute($data+($id?compact('id'):[]));$newId=$id?: (int)$pdo->lastInsertId();Auth::registerAudit('BILLING_'.strtoupper($type).'_SAVED',$table,$newId,$old,$data);}
 public static function toggleConfig(string$type,int$id,bool$active):void{$table=self::configTable($type);$pdo=Database::connection();$q=$pdo->prepare("SELECT * FROM $table WHERE id=:id");$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Registro não encontrado.');if($type==='mapping'&&$active){$s=$pdo->prepare('SELECT active FROM billing_services WHERE id=:id');$s->execute(['id'=>$old['billing_service_id']]);if(!(int)$s->fetchColumn())throw new RuntimeException('Ative o serviço antes de reativar esta associação.');}$pdo->prepare("UPDATE $table SET active=:active WHERE id=:id")->execute(['active'=>$active?1:0,'id'=>$id]);if($type==='service'&&!$active)$pdo->prepare('UPDATE billing_service_mappings SET active=0 WHERE billing_service_id=:id')->execute(compact('id'));Auth::registerAudit('BILLING_'.strtoupper($type).'_'.($active?'ACTIVATED':'DEACTIVATED'),$table,$id,$old,['active'=>$active]);}
 public static function deleteConfig(string$type,int$id):void{$table=self::configTable($type);$pdo=Database::connection();$q=$pdo->prepare("SELECT * FROM $table WHERE id=:id");$q->execute(compact('id'));$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new RuntimeException('Registro não encontrado.');$used=match($type){'center'=>self::exists('SELECT 1 FROM billing_manual_entries WHERE billing_cost_center_id=:id LIMIT 1',$id)||self::snapshotMentions('centers',$id),'service'=>self::exists('SELECT 1 FROM billing_manual_entries WHERE billing_service_id=:id LIMIT 1',$id)||self::exists('SELECT 1 FROM billing_service_mappings WHERE billing_service_id=:id LIMIT 1',$id)||self::snapshotMentions('services',$id),'mapping'=>self::mappingUsed($old)};if($used)throw new RuntimeException('Este registro possui histórico de faturamento e não pode ser excluído. Inative-o para impedir novos usos.');try{$pdo->prepare("DELETE FROM $table WHERE id=:id")->execute(compact('id'));Auth::registerAudit('BILLING_'.strtoupper($type).'_DELETED',$table,$id,$old,null);}catch(\PDOException$e){throw new RuntimeException('Este registro possui vínculos e não pode ser excluído. Inative-o.');}}
 private static function configTable(string$type):string{return match($type){'center'=>'billing_cost_centers','service'=>'billing_services','mapping'=>'billing_service_mappings',default=>throw new RuntimeException('Tipo de cadastro inválido.')};}
 private static function exists(string$sql,int$id):bool{$q=Database::connection()->prepare($sql);$q->execute(compact('id'));return(bool)$q->fetchColumn();}
 private static function snapshotMentions(string$key,int$id):bool{$q=Database::connection()->prepare("SELECT snapshot_json FROM billing_periods WHERE status='CLOSED' AND snapshot_json IS NOT NULL");$q->execute();foreach($q->fetchAll(PDO::FETCH_COLUMN)as$json){$d=json_decode((string)$json,true);foreach(($d[$key]??[])as$r)if((int)($r['id']??0)===$id)return true;}return false;}
 private static function mappingUsed(array$m):bool{$contexts=explode(',',(string)$m['context_scope']);$marks=implode(',',array_fill(0,count($contexts),'?'));$sql="SELECT 1 FROM sample_tests st JOIN samples s ON s.id=st.sample_id WHERE st.test_id=? AND st.status='completed' AND (? IS NULL OR s.blood_component_id=?) AND s.purpose IN ($marks) LIMIT 1";$q=Database::connection()->prepare($sql);$q->execute(array_merge([(int)$m['test_id'],$m['blood_component_id'],$m['blood_component_id']],$contexts));return(bool)$q->fetchColumn();}
 public static function closePeriod(int$year,int$month,int$user):void{$period=self::period($year,$month);if(!$period||$period['status']!=='REVIEWED')throw new RuntimeException('Revise a competência antes de fechar.');$matrix=self::buildMatrix($year,$month,false);if($matrix['unmapped']||$matrix['missingCenters'])throw new RuntimeException('Resolva as pendências estruturais antes do fechamento.');$snapshot=json_encode($matrix,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$pdo=Database::connection();$pdo->prepare("INSERT INTO billing_periods(year,month,status,snapshot_json,snapshot_version,reviewed_by,reviewed_at,closed_by,closed_at) VALUES(:year,:month,'CLOSED',:snapshot,1,:user,NOW(),:user2,NOW()) ON DUPLICATE KEY UPDATE status='CLOSED',snapshot_json=VALUES(snapshot_json),snapshot_version=snapshot_version+1,reviewed_by=VALUES(reviewed_by),reviewed_at=NOW(),closed_by=VALUES(closed_by),closed_at=NOW()")->execute(['year'=>$year,'month'=>$month,'snapshot'=>$snapshot,'user'=>$user,'user2'=>$user]);Auth::registerAudit('BILLING_PERIOD_CLOSED','billing_periods',(int)$pdo->lastInsertId(),null,['year'=>$year,'month'=>$month]);}
 public static function reviewPeriod(int$year,int$month,int$user):void{$m=self::buildMatrix($year,$month,false);if($m['unmapped']||$m['missingCenters'])throw new RuntimeException('Resolva as pendências estruturais antes da revisão.');Database::connection()->prepare("INSERT INTO billing_periods(year,month,status,reviewed_by,reviewed_at) VALUES(:year,:month,'REVIEWED',:user,NOW()) ON DUPLICATE KEY UPDATE status='REVIEWED',reviewed_by=VALUES(reviewed_by),reviewed_at=NOW()")->execute(compact('year','month','user'));}
 public static function reopenPeriod(int$year,int$month,int$user,string$reason):void{if(trim($reason)==='')throw new RuntimeException('O motivo da reabertura é obrigatório.');$q=Database::connection()->prepare("UPDATE billing_periods SET status='REOPENED',reopened_by=:user,reopened_at=NOW(),reopen_reason=:reason WHERE year=:year AND month=:month AND status='CLOSED'");$q->execute(compact('user','reason','year','month'));if(!$q->rowCount())throw new RuntimeException('A competência não está fechada.');Auth::registerAudit('BILLING_PERIOD_REOPENED','billing_periods',null,null,compact('year','month','reason'));}
 public static function createSnapshot(int$year,int$month):array{return self::buildMatrix($year,$month,false);}
 public static function exportPdlab005(int$year,int$month):string{$m=self::buildMatrix($year,$month);$xml='<?xml version="1.0" encoding="UTF-8"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="PDLAB005"><Table>';$row=function(array$c)use(&$xml){$xml.='<Row>';foreach($c as[$v,$type])$xml.='<Cell><Data ss:Type="'.$type.'">'.htmlspecialchars((string)$v,ENT_XML1,'UTF-8').'</Data></Cell>';$xml.='</Row>';};$row([['PDLAB005 - QUANTIDADE DE TESTES DO LAB. DE CONTROLE DE QUALIDADE REALIZADOS','String']]);$row([['Rev.14','String'],[sprintf('%02d/%04d',$month,$year),'String']]);$head=[['CENTRO DE CUSTO','String'],['SERVIÇO','String']];foreach($m['services']as$s)$head[]=[$s['service_code'].' - '.$s['name'],'String'];$row($head);foreach($m['rows']as$r){$cells=[[$r['center']['cost_center_code'],'String'],[$r['center']['name'],'String']];foreach($m['services']as$s)$cells[]=[(int)$r['values'][(int)$s['id']],'Number'];$row($cells);}$cells=[['','String'],['TOTAL','String']];foreach($m['services']as$s)$cells[]=[(int)$m['totals'][(int)$s['id']],'Number'];$row($cells);return$xml.'</Table></Worksheet></Workbook>';}
 public static function detail(int$year,int$month,int$center,int$service):array{$rows=array_values(array_filter(self::getFinalBillableResults($year,$month),fn($r)=>(int)$r['billing_cost_center_id']===$center&&(int)$r['billing_service_id']===$service));foreach(self::getManualEntries($year,$month)as$r)if((int)$r['billing_cost_center_id']===$center&&(int)$r['billing_service_id']===$service)$rows[]=['completed_at'=>$r['created_at'],'donation_number'=>'—','sample_code'=>'Complementar','component_name'=>'—','context_scope'=>'manual','test_name'=>$r['service_name'],'unit_name'=>$r['center_name'],'lcqh_code'=>'—','origin'=>'manual ('.$r['quantity'].')','responsible_name'=>$r['created_by_name']];return$rows;}
 public static function exportCsv(int$year,int$month,array$scope=['type'=>'all','client_id'=>null,'client'=>null,'restricted'=>false]):string{$m=self::buildMatrix($year,$month,true,$scope);$stream=fopen('php://temp','r+');fwrite($stream,"\xEF\xBB\xBF");$write=static function($stream,array$row):void{fputcsv($stream,$row,';',chr(34),'\\');};$write($stream,['Competência',sprintf('%02d/%04d',$month,$year)]);$write($stream,['Tipo de cliente',$scope['type']==='all'?'Todos':($scope['type']==='internal'?'Internos':'Externos')]);$write($stream,['Cliente',$scope['client']['name']??'Todos os clientes']);$write($stream,[]);$header=['Código','Centro de custo','Tipo de cliente','Cliente'];foreach($m['services']as$s)$header[]=$s['service_code'].' — '.$s['name'];$write($stream,$header);foreach($m['rows']as$r){$row=[$r['center']['cost_center_code'],$r['center']['name'],$r['center']['client_type']??'Não classificado',$r['center']['client_name']??'Sem cliente associado'];foreach($m['services']as$s)$row[]=(int)$r['values'][(int)$s['id']];$write($stream,$row);}$total=['','TOTAL','',''];foreach($m['services']as$s)$total[]=(int)$m['totals'][(int)$s['id']];$write($stream,$total);rewind($stream);$csv=stream_get_contents($stream);fclose($stream);return$csv;}
 private static function missingCenters(int$year,int$month):array{$missing=[];foreach(self::getFinalBillableResults($year,$month)as$r){if($r['billing_cost_center_id'])continue;$unit=(int)$r['origin_unit_id'];$key=$unit?:0;if(!isset($missing[$key]))$missing[$key]=['id'=>$unit,'code'=>'','name'=>$unit?'Unidade #'.$unit:'Unidade não informada','quantity'=>0];$missing[$key]['quantity']++;}$ids=array_values(array_filter(array_keys($missing)));if($ids){$pdo=Database::connection();$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT id,code,name FROM units WHERE id IN ($marks)");$q->execute($ids);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$unit)$missing[(int)$unit['id']]=array_merge($missing[(int)$unit['id']],$unit);}return array_values($missing);}
 public static function clientlessCenters():array{return Database::connection()->query("SELECT b.id,b.cost_center_code code,b.name,0 quantity FROM billing_cost_centers b LEFT JOIN units u ON u.id=b.unit_id WHERE b.active=1 AND COALESCE(b.client_id,u.client_id) IS NULL ORDER BY b.display_order,b.name")->fetchAll(PDO::FETCH_ASSOC);}
 private static function filterMatrix(array$m,array$scope):array
 {if($scope['type']==='all'&&!$scope['client_id'])return$m;$ids=array_map(fn($r)=>(int)$r['center']['id'],$m['rows']??[]);$meta=[];if($ids){$marks=implode(',',array_fill(0,count($ids),'?'));$q=Database::connection()->prepare("SELECT b.id,COALESCE(b.client_id,u.client_id) client_id,c.client_type FROM billing_cost_centers b LEFT JOIN units u ON u.id=b.unit_id LEFT JOIN clients c ON c.id=COALESCE(b.client_id,u.client_id) WHERE b.id IN ($marks)");$q->execute($ids);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r)$meta[(int)$r['id']]=$r;}$m['rows']=array_values(array_filter($m['rows']??[],function($r)use($scope,$meta){$x=$meta[(int)$r['center']['id']]??[];return ClientScopeService::matches($scope,isset($x['client_id'])?(int)$x['client_id']:null,$x['client_type']??null);}));$m['centers']=array_column($m['rows'],'center');$m['totals']=array_fill_keys(array_map(fn($s)=>(int)$s['id'],$m['services']??[]),0);foreach($m['rows']as$r)foreach($m['totals']as$id=>$_)$m['totals'][$id]+=(int)($r['values'][$id]??0);$m['total']=array_sum($m['totals']);$m['unmapped']=[];$m['missingCenters']=[];$m['scope']=$scope;return$m;}
 private static function period(int$year,int$month):?array{$q=Database::connection()->prepare('SELECT * FROM billing_periods WHERE year=:year AND month=:month');$q->execute(compact('year','month'));return$q->fetch(PDO::FETCH_ASSOC)?:null;}
 private static function assertOpen(int$year,int$month):void{$p=self::period($year,$month);if($p&&$p['status']==='CLOSED')throw new RuntimeException('Competência fechada; reabra antes de alterar.');}
 private static function range(int$year,int$month):array{$from=sprintf('%04d-%02d-01',$year,$month);return[$from,date('Y-m-d',strtotime($from.' +1 month'))];}
}
