<?php
declare(strict_types=1);
namespace BloodHub\Services;
use BloodHub\Core\{Auth,Database};
use PDO;
final class CalculatedTestService
{
    public static function recalculateHemolysis(int $sampleId):?float
    {
        if(!TestResultService::configuredTest($sampleId,TestResultService::CODES['hemolysis']))return null;$pdo=Database::connection();$h=$pdo->prepare('SELECT hemolysis_hematocrit_test_id FROM blood_components bc JOIN samples s ON s.blood_component_id=bc.id WHERE s.id=:id');$h->execute(['id'=>$sampleId]);$hct=(int)$h->fetchColumn();
        $q=$pdo->prepare("SELECT t.id,t.code,tr.result_value_numeric FROM sample_tests st JOIN tests t ON t.id=st.test_id JOIN test_results tr ON tr.sample_test_id=st.id WHERE st.sample_id=:id AND (t.code IN ('FREE_HEMOGLOBIN','HEMOGLOBIN') OR t.id=:hct) ORDER BY tr.id");$q->execute(['id'=>$sampleId,'hct'=>$hct?:-1]);$v=[];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $r)$v[(int)$r['id']===$hct?'HEMATOCRIT':$r['code']]=$r['result_value_numeric'];if(!isset($v['FREE_HEMOGLOBIN'],$v['HEMOGLOBIN'],$v['HEMATOCRIT'])||(float)$v['HEMOGLOBIN']==0)return null;
        $value=((float)$v['FREE_HEMOGLOBIN']/(float)$v['HEMOGLOBIN'])*(100-(float)$v['HEMATOCRIT']);$test=TestResultService::configuredTest($sampleId,TestResultService::CODES['hemolysis']);$st=$pdo->prepare('SELECT id,status FROM sample_tests WHERE sample_id=:sample AND test_id=:test FOR UPDATE');$st->execute(['sample'=>$sampleId,'test'=>$test['id']]);$sampleTest=$st->fetch(PDO::FETCH_ASSOC);if(!$sampleTest){$pdo->prepare("INSERT INTO sample_tests(sample_id,test_id,status,started_at,executed_by) VALUES(:sample,:test,'in_progress',NOW(),:user)")->execute(['sample'=>$sampleId,'test'=>$test['id'],'user'=>Auth::user()['id']??null]);$sampleTest=['id'=>(int)$pdo->lastInsertId(),'status'=>'in_progress'];}$stId=(int)$sampleTest['id'];
        $old=$pdo->prepare('SELECT id,result_value_numeric FROM test_results WHERE sample_test_id=:id ORDER BY id DESC LIMIT 1');$old->execute(['id'=>$stId]);$before=$old->fetch(PDO::FETCH_ASSOC);$changed=!$before||$before['result_value_numeric']===null||abs((float)$before['result_value_numeric']-$value)>1e-12;if($before){if($changed)$pdo->prepare('UPDATE test_results SET result_value_numeric=:value,recorded_by=:user,recorded_at=NOW() WHERE id=:id')->execute(['value'=>$value,'user'=>Auth::user()['id']??null,'id'=>$before['id']]);$rid=(int)$before['id'];}else{$pdo->prepare('INSERT INTO test_results(sample_test_id,result_value_numeric,recorded_by) VALUES(:st,:value,:user)')->execute(['st'=>$stId,'value'=>$value,'user'=>Auth::user()['id']??null]);$rid=(int)$pdo->lastInsertId();}$pdo->prepare("UPDATE sample_tests SET status='completed',started_at=COALESCE(started_at,NOW()),completed_at=COALESCE(completed_at,NOW()),executed_by=:user WHERE id=:id")->execute(['user'=>Auth::user()['id']??null,'id'=>$stId]);if($changed||$sampleTest['status']!=='completed')Auth::registerAudit('HEMOLYSIS_RESULT_UPDATE','test_results',$rid,$before?:null,['sample_id'=>$sampleId,'hemolysis_degree'=>$value,'status'=>'completed']);return $value;
    }
    public static function hemolysisState(int $sampleId):array
    {
        if(!TestResultService::configuredTest($sampleId,TestResultService::CODES['hemolysis']))return ['applicable'=>false,'ready'=>false,'value'=>null,'values'=>[],'missing'=>[],'message'=>''];$pdo=Database::connection();$h=$pdo->prepare('SELECT hemolysis_hematocrit_test_id FROM blood_components bc JOIN samples s ON s.blood_component_id=bc.id WHERE s.id=:id');$h->execute(['id'=>$sampleId]);$hct=(int)$h->fetchColumn();$s=$pdo->prepare("SELECT t.id,t.code,tr.result_value_numeric FROM sample_tests st JOIN tests t ON t.id=st.test_id JOIN test_results tr ON tr.sample_test_id=st.id WHERE st.sample_id=:id AND (t.code IN ('FREE_HEMOGLOBIN','HEMOGLOBIN','HEMOLYSIS_DEGREE') OR t.id=:hct) ORDER BY tr.id");$s->execute(['id'=>$sampleId,'hct'=>$hct?:-1]);$values=[];foreach($s->fetchAll(PDO::FETCH_ASSOC) as $row)$values[(int)$row['id']===$hct?'HEMATOCRIT':$row['code']]=$row['result_value_numeric'];$labels=['FREE_HEMOGLOBIN'=>'Hemoglobina Livre','HEMATOCRIT'=>'Hematócrito','HEMOGLOBIN'=>'Hemoglobina'];$missing=[];foreach($labels as $code=>$label)if(!isset($values[$code]))$missing[]=$label;$result=$values['HEMOLYSIS_DEGREE']??null;$ready=$result!==null;return ['applicable'=>true,'ready'=>$ready,'value'=>$result,'values'=>$values,'missing'=>$missing,'message'=>$ready?'Resultado calculado disponível':($missing?'Pendente — aguardando '.self::joinLabels($missing):'Pronto para cálculo')];
    }
    private static function joinLabels(array $labels):string{if(count($labels)<2)return $labels[0]??'';$last=array_pop($labels);return implode(', ',$labels).' e '.$last;}
}
