<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database};
use DomainException;
use PDO;

final class FactorViiiPoolService
{
    public const FVIII_POOL_MAX_SIZE=4;
    public const TEST_CODE='FACTOR_VIII';
    public const COMPONENT_CODES=['PFC','PFC24'];

    public static function preview(array $filters):array
    {
        $rows=self::getEligibleSamples($filters,false);$groups=[];
        foreach($rows as $row)$groups[$row['blood_component_id'].'|'.$row['origin_unit_id']][]=$row;
        $pools=[];foreach($groups as $items)foreach(array_chunk($items,self::FVIII_POOL_MAX_SIZE) as $chunk)$pools[]=['blood_component_id'=>(int)$chunk[0]['blood_component_id'],'component_code'=>$chunk[0]['component_code'],'component_name'=>$chunk[0]['component_name'],'origin_unit_id'=>(int)$chunk[0]['origin_unit_id'],'origin_name'=>$chunk[0]['origin_name'],'samples'=>$chunk];
        return $pools;
    }
    public static function eligibleCount(array $filters=[]):int{return count(self::getEligibleSamples($filters,false));}

    public static function create(array $filters):array
    {
        $pdo=Database::connection();$pdo->beginTransaction();try{$rows=self::eligible($filters,true);if(!$rows)throw new DomainException('Nenhuma unidade elegível foi encontrada.');$groups=[];foreach($rows as $r)$groups[$r['blood_component_id'].'|'.$r['origin_unit_id']][]=$r;$created=[];
            foreach($groups as $items)foreach(array_chunk($items,self::FVIII_POOL_MAX_SIZE) as $chunk){self::assertCompatible($chunk);$code=self::nextCode($pdo,$chunk[0]['component_code']);$pdo->prepare("INSERT INTO factor_viii_pools(code,blood_component_id,origin_unit_id,created_by) VALUES(:code,:component,:origin,:user)")->execute(['code'=>$code,'component'=>$chunk[0]['blood_component_id'],'origin'=>$chunk[0]['origin_unit_id'],'user'=>Auth::user()['id']??null]);$poolId=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO factor_viii_pool_samples(pool_id,sample_id,position) VALUES(:pool,:sample,:position)');foreach($chunk as $i=>$sample){$ins->execute(['pool'=>$poolId,'sample'=>$sample['id'],'position'=>$i+1]);$pdo->prepare("INSERT INTO factor_viii_sample_results(sample_id,current_pool_id,analysis_mode) VALUES(:sample,:pool,'pool') ON DUPLICATE KEY UPDATE current_pool_id=VALUES(current_pool_id),analysis_mode='pool',individual_required=0")->execute(['sample'=>$sample['id'],'pool'=>$poolId]);}$created[]=$code;Auth::registerAudit('factor_viii_pool.created','factor_viii_pools',$poolId,null,['code'=>$code,'component'=>$chunk[0]['component_code'],'origin_unit_id'=>(int)$chunk[0]['origin_unit_id'],'sample_ids'=>array_map(fn($x)=>(int)$x['id'],$chunk)]);}
            $pdo->commit();return $created;
        }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public static function saveResult(int $poolId,mixed $raw,bool $complete):void
    {
        $value=self::decimal($raw);$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT p.*,bc.code component_code FROM factor_viii_pools p JOIN blood_components bc ON bc.id=p.blood_component_id WHERE p.id=:id FOR UPDATE");$q->execute(['id'=>$poolId]);$pool=$q->fetch(PDO::FETCH_ASSOC);if(!$pool||$pool['status']!=='open')throw new DomainException('Somente pools abertos podem receber resultado.');
            $pdo->prepare('UPDATE factor_viii_pools SET result=:result,result_saved_by=:user,result_saved_at=NOW() WHERE id=:id')->execute(['result'=>$value,'user'=>Auth::user()['id']??null,'id'=>$poolId]);Auth::registerAudit('factor_viii_pool.result_saved','factor_viii_pools',$poolId,['result'=>$pool['result']],['result'=>$value,'unit'=>'UI/mL']);if(!$complete){$pdo->commit();return;}
            $members=self::members($poolId,true);if(!$members)throw new DomainException('O pool não possui unidades.');$test=self::factorTest();$evaluation=SpecificationEvaluator::evaluate((int)$members[0]['id'],(int)$test['id'],$value,date('Y-m-d'));if(!in_array($evaluation['status'],['CONFORMING','NONCONFORMING'],true))throw new DomainException($evaluation['reason']??'Não foi possível determinar a especificação vigente.');$conforming=$evaluation['status']==='CONFORMING';$spec=$evaluation['specification'];$snapshot=self::snapshot($evaluation);
            $pdo->prepare("UPDATE factor_viii_pools SET status=:status,result=:result,specification_id=:spec,specification_snapshot=:snapshot,is_conforming=:conforming,finalized_by=:user,finalized_at=NOW() WHERE id=:id")->execute(['status'=>$conforming?'completed_conforming':'completed_nonconforming','result'=>$value,'spec'=>$spec['id']??null,'snapshot'=>$snapshot,'conforming'=>$conforming?1:0,'user'=>Auth::user()['id']??null,'id'=>$poolId]);
            foreach($members as $member){$sampleId=(int)$member['id'];$pdo->prepare("INSERT INTO factor_viii_sample_results(sample_id,current_pool_id,analysis_mode,pool_result,pool_result_at,pool_result_by,pool_specification_id,pool_specification_snapshot,individual_required,effective_result,effective_source) VALUES(:sample,:pool,'pool',:result,NOW(),:user,:spec,:snapshot,:required,:effective,:source) ON DUPLICATE KEY UPDATE current_pool_id=VALUES(current_pool_id),pool_result=VALUES(pool_result),pool_result_at=VALUES(pool_result_at),pool_result_by=VALUES(pool_result_by),pool_specification_id=VALUES(pool_specification_id),pool_specification_snapshot=VALUES(pool_specification_snapshot),individual_required=VALUES(individual_required),effective_result=VALUES(effective_result),effective_source=VALUES(effective_source)")->execute(['sample'=>$sampleId,'pool'=>$poolId,'result'=>$value,'user'=>Auth::user()['id']??null,'spec'=>$spec['id']??null,'snapshot'=>$snapshot,'required'=>$conforming?0:1,'effective'=>$conforming?$value:null,'source'=>$conforming?'pool':null]);if($conforming)self::materialize($sampleId,$value,'pool',$poolId);else self::markPending($sampleId);Auth::registerAudit($conforming?'factor_viii_pool.propagated':'factor_viii_pool.individual_retest_required','samples',$sampleId,null,['pool_id'=>$poolId,'pool_result'=>$value]);}
            Auth::registerAudit('factor_viii_pool.completed','factor_viii_pools',$poolId,['status'=>'open'],['status'=>$conforming?'completed_conforming':'completed_nonconforming','result'=>$value,'specification_id'=>$spec['id']??null]);$pdo->commit();
        }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public static function chooseIndividual(int $sampleId):void
    {$pdo=Database::connection();$pdo->beginTransaction();try{$sample=self::lockSample($sampleId);self::assertPlasma($sample);$q=$pdo->prepare("SELECT p.status FROM factor_viii_pool_samples m JOIN factor_viii_pools p ON p.id=m.pool_id WHERE m.sample_id=:sample AND p.status='open' FOR UPDATE");$q->execute(['sample'=>$sampleId]);if($q->fetchColumn())throw new DomainException('Cancele o pool aberto antes de selecionar análise individual.');$pdo->prepare("INSERT INTO factor_viii_sample_results(sample_id,analysis_mode,individual_required) VALUES(:sample,'individual',1) ON DUPLICATE KEY UPDATE analysis_mode='individual',individual_required=1")->execute(['sample'=>$sampleId]);Auth::registerAudit('factor_viii.individual_selected','samples',$sampleId,null,['analysis_mode'=>'individual']);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function saveIndividual(int $sampleId,mixed $raw):void
    {$value=self::decimal($raw);$pdo=Database::connection();$pdo->beginTransaction();try{$sample=self::lockSample($sampleId);self::assertPlasma($sample);$state=self::state($sampleId);if(!$state['individual_required']&&$state['analysis_mode']!=='individual')throw new DomainException('A amostra não está liberada para análise individual.');$result=self::materialize($sampleId,$value,'individual',null);$evaluation=SpecificationEvaluator::persistForResult((int)$result['id']);$snapshot=self::snapshot($evaluation);$spec=$evaluation['specification']??[];$pdo->prepare("INSERT INTO factor_viii_sample_results(sample_id,analysis_mode,individual_required,individual_result,individual_result_at,individual_result_by,individual_specification_id,individual_specification_snapshot,effective_result,effective_source,test_result_id) VALUES(:sample,'individual',0,:result,NOW(),:user,:spec,:snapshot,:result2,'individual',:test_result) ON DUPLICATE KEY UPDATE analysis_mode='individual',individual_required=0,individual_result=VALUES(individual_result),individual_result_at=VALUES(individual_result_at),individual_result_by=VALUES(individual_result_by),individual_specification_id=VALUES(individual_specification_id),individual_specification_snapshot=VALUES(individual_specification_snapshot),effective_result=VALUES(effective_result),effective_source='individual',test_result_id=VALUES(test_result_id)")->execute(['sample'=>$sampleId,'result'=>$value,'user'=>Auth::user()['id']??null,'spec'=>$spec['id']??null,'snapshot'=>$snapshot,'result2'=>$value,'test_result'=>$result['id']]);Auth::registerAudit('factor_viii.individual_result','samples',$sampleId,null,['individual_result'=>$value,'effective_result'=>$value,'specification_id'=>$spec['id']??null]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function cancel(int $poolId,string $reason):void
    {$reason=trim($reason);if($reason==='')throw new DomainException('Informe o motivo do cancelamento.');if(mb_strlen($reason)>500)throw new DomainException('O motivo deve ter no máximo 500 caracteres.');$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM factor_viii_pools WHERE id=:id FOR UPDATE");$q->execute(['id'=>$poolId]);$pool=$q->fetch(PDO::FETCH_ASSOC);if(!$pool||$pool['status']!=='open')throw new DomainException('Somente pools abertos podem ser cancelados.');$pdo->prepare("UPDATE factor_viii_pools SET status='cancelled',cancellation_reason=:reason,cancelled_by=:user,cancelled_at=NOW() WHERE id=:id")->execute(['reason'=>$reason,'user'=>Auth::user()['id']??null,'id'=>$poolId]);$pdo->prepare("UPDATE factor_viii_sample_results r JOIN factor_viii_pool_samples m ON m.sample_id=r.sample_id SET r.current_pool_id=NULL WHERE m.pool_id=:pool AND r.current_pool_id=:pool2 AND r.effective_result IS NULL")->execute(['pool'=>$poolId,'pool2'=>$poolId]);Auth::registerAudit('factor_viii_pool.cancelled','factor_viii_pools',$poolId,['status'=>'open'],['status'=>'cancelled','reason'=>$reason]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}

    public static function state(int $sampleId):array
    {$q=Database::connection()->prepare("SELECT r.*,p.code pool_code,p.status pool_status,p.result current_pool_result,p.finalized_at,p.result_saved_by,u.name pool_result_user FROM factor_viii_sample_results r LEFT JOIN factor_viii_pools p ON p.id=r.current_pool_id LEFT JOIN users u ON u.id=p.result_saved_by WHERE r.sample_id=:id");$q->execute(['id'=>$sampleId]);return $q->fetch(PDO::FETCH_ASSOC)?:['analysis_mode'=>'pool','individual_required'=>0,'effective_result'=>null,'effective_source'=>null,'pool_code'=>null,'pool_status'=>null,'pool_result'=>null,'individual_result'=>null];}
    public static function members(int $poolId,bool $lock=false):array{$sql="SELECT s.id,s.donation_number,s.lcqh_code,s.received_at,s.blood_component_id,s.origin_unit_id,m.position FROM factor_viii_pool_samples m JOIN samples s ON s.id=m.sample_id WHERE m.pool_id=:id ORDER BY m.position".($lock?' FOR UPDATE':'');$q=Database::connection()->prepare($sql);$q->execute(['id'=>$poolId]);return$q->fetchAll(PDO::FETCH_ASSOC);}

    public static function getEligibleSamples(array $f=[],bool $lock=false):array
    {
        $where=["s.purpose='quality_control'","s.status IN ('received','in_analysis','partial_results')","s.received_at IS NOT NULL","bc.code IN ('PFC','PFC24')","s.origin_unit_id IS NOT NULL","EXISTS(SELECT 1 FROM test_blood_components configured JOIN tests configured_test ON configured_test.id=configured.test_id AND configured_test.code='FACTOR_VIII' AND configured_test.status='active' WHERE configured.blood_component_id=s.blood_component_id)","NOT EXISTS(SELECT 1 FROM factor_viii_pool_samples mx JOIN factor_viii_pools px ON px.id=mx.pool_id WHERE mx.sample_id=s.id AND px.status IN ('open','completed_conforming','completed_nonconforming'))","NOT EXISTS(SELECT 1 FROM factor_viii_sample_results fr WHERE fr.sample_id=s.id AND (fr.effective_result IS NOT NULL OR fr.individual_result IS NOT NULL OR fr.analysis_mode='individual' OR fr.individual_required=1))","NOT EXISTS(SELECT 1 FROM sample_tests completed_st JOIN tests completed_t ON completed_t.id=completed_st.test_id AND completed_t.code='FACTOR_VIII' JOIN test_results completed_tr ON completed_tr.sample_test_id=completed_st.id WHERE completed_st.sample_id=s.id AND completed_st.status='completed' AND (completed_tr.result_value_numeric IS NOT NULL OR NULLIF(TRIM(completed_tr.result_value_text),'') IS NOT NULL))"];
        $p=[];foreach([['component','s.blood_component_id'],['origin','s.origin_unit_id']] as [$k,$col])if(!empty($f[$k])){$where[]="$col=:$k";$p[$k]=(int)$f[$k];}
        if(!empty($f['from'])){$where[]='DATE(s.received_at)>=:from';$p['from']=$f['from'];}if(!empty($f['to'])){$where[]='DATE(s.received_at)<=:to';$p['to']=$f['to'];}
        $sql="SELECT s.id,s.donation_number,s.sample_code,s.lcqh_code,s.status,s.purpose,s.received_at,s.sample_shipment_id shipment_id,s.blood_component_id,s.origin_unit_id,bc.code component_code,bc.name component_name,u.name origin_name FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id JOIN units u ON u.id=s.origin_unit_id WHERE ".implode(' AND ',$where).' ORDER BY s.blood_component_id,s.origin_unit_id,s.received_at,s.id'.($lock?' FOR UPDATE':'');
        $q=Database::connection()->prepare($sql);$q->execute($p);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
        if($lock)foreach($rows as $row)self::ensureFactorSampleTest((int)$row['id']);
        return $rows;
    }
    private static function eligible(array $filters,bool $lock):array{return self::getEligibleSamples($filters,$lock);}
    private static function ensureFactorSampleTest(int $sampleId):void{$test=self::factorTest();$q=Database::connection()->prepare('SELECT id FROM sample_tests WHERE sample_id=:sample AND test_id=:test ORDER BY id LIMIT 1 FOR UPDATE');$q->execute(['sample'=>$sampleId,'test'=>$test['id']]);if(!$q->fetchColumn())Database::connection()->prepare("INSERT INTO sample_tests(sample_id,test_id,status) VALUES(:sample,:test,'pending')")->execute(['sample'=>$sampleId,'test'=>$test['id']]);}
    private static function materialize(int $sampleId,float $value,string $source,?int $poolId):array{$result=TestResultService::saveNumeric($sampleId,self::TEST_CODE,$value);Database::connection()->prepare('UPDATE factor_viii_sample_results SET test_result_id=:result,effective_result=:value,effective_source=:source,current_pool_id=COALESCE(:pool,current_pool_id) WHERE sample_id=:sample')->execute(['result'=>$result['id'],'value'=>$value,'source'=>$source,'pool'=>$poolId,'sample'=>$sampleId]);return$result;}
    private static function markPending(int $sampleId):void{$test=self::factorTest();$q=Database::connection()->prepare('SELECT id FROM sample_tests WHERE sample_id=:sample AND test_id=:test FOR UPDATE');$q->execute(['sample'=>$sampleId,'test'=>$test['id']]);$id=(int)$q->fetchColumn();if($id)$pdo=Database::connection()->prepare("UPDATE sample_tests SET status='in_progress',completed_at=NULL WHERE id=:id");else{$pdo=Database::connection()->prepare("INSERT INTO sample_tests(sample_id,test_id,status,started_at) VALUES(:sample,:test,'in_progress',NOW())");$pdo->execute(['sample'=>$sampleId,'test'=>$test['id']]);return;}$pdo->execute(['id'=>$id]);}
    private static function factorTest():array{$q=Database::connection()->query("SELECT * FROM tests WHERE code='FACTOR_VIII' AND status='active' LIMIT 1");$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Teste Fator VIII não configurado.');return$r;}
    private static function nextCode(PDO $pdo,string $component):string{$prefix='FVIII-'.$component.'-'.date('Ym').'-';$q=$pdo->prepare('SELECT code FROM factor_viii_pools WHERE code LIKE :prefix ORDER BY code DESC LIMIT 1 FOR UPDATE');$q->execute(['prefix'=>$prefix.'%']);$last=(string)$q->fetchColumn();$seq=$last?(int)substr($last,-4)+1:1;return$prefix.str_pad((string)$seq,4,'0',STR_PAD_LEFT);}
    private static function decimal(mixed $raw):float{$raw=str_replace(',','.',trim((string)$raw));if($raw===''||!is_numeric($raw)||(float)$raw<0)throw new DomainException('Informe um resultado numérico válido em UI/mL.');return(float)$raw;}
    private static function snapshot(array $e):string{return json_encode(['status'=>$e['status']??null,'actual_value'=>$e['actual_value']??null,'text'=>$e['snapshot']??($e['reason']??null),'specification'=>$e['specification']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
    private static function assertCompatible(array $rows):void{$c=array_unique(array_column($rows,'blood_component_id'));$o=array_unique(array_column($rows,'origin_unit_id'));if(count($rows)>self::FVIII_POOL_MAX_SIZE||count($c)!==1||count($o)!==1)throw new DomainException('Um pool não pode misturar hemocomponentes ou origens e deve ter no máximo '.self::FVIII_POOL_MAX_SIZE.' unidades.');}
    private static function lockSample(int $id):array{$q=Database::connection()->prepare("SELECT s.*,bc.code component_code FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id WHERE s.id=:id AND s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results') FOR UPDATE");$q->execute(['id'=>$id]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Amostra indisponível.');return$r;}
    private static function assertPlasma(array $sample):void{if(!in_array($sample['component_code'],self::COMPONENT_CODES,true))throw new DomainException('Fator VIII por pool é exclusivo de PFC/PFC24.');}
}
