<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database,Permission};
use BloodHub\Services\Indicators\{IndicatorCalculator,PlateletMeanConcentrationIndicatorCalculator,WithinSpecificationIndicatorCalculator};
use DomainException;
use PDO;

final class IndicatorService
{
    public const VIEW='indicators.view';
    public static function all(bool $includeInactive=false):array
    {$sql='SELECT i.* FROM indicators i'.($includeInactive?'':' WHERE i.active=1').' ORDER BY i.name';$items=Database::connection()->query($sql)->fetchAll(PDO::FETCH_ASSOC);foreach($items as &$i)$i['target']=self::getTargetForPeriod((int)$i['id'],(int)date('Y'),(int)date('n'));return$items;}
    public static function getIndicator(string|int $key):?array
    {$field=is_int($key)||ctype_digit((string)$key)?'i.id':'i.slug';$q=Database::connection()->prepare("SELECT i.*,t.code configured_test_code,t.name configured_test_name FROM indicators i LEFT JOIN tests t ON t.id=i.configured_test_id WHERE $field=:key LIMIT 1");$q->execute(['key'=>$key]);$row=$q->fetch(PDO::FETCH_ASSOC);if(!$row)return null;$row['responsibles']=self::responsibles((int)$row['id']);return$row;}
    public static function dashboard(array $indicator,int $year,int $month,array $scope=['type'=>'all','client_id'=>null,'client'=>null,'restricted'=>false]):array
    {$calculated=self::calculator($indicator)->calculate($year,$month,$scope);$targets=[];foreach(range(1,12)as$m)$targets[$m]=self::getTargetForPeriod((int)$indicator['id'],$year,$m);foreach($calculated['months']as$m=>&$data){if($year>(int)date('Y')||($year===(int)date('Y')&&$m>(int)date('n'))){$data['value']=null;$data['quantity']=0;$data['rows']=[];if(isset($data['inside']))$data['inside']=0;if(isset($data['outside']))$data['outside']=0;}$data['target']=$targets[$m];$data['status']=self::targetStatus($data['value'],$targets[$m]);}unset($data);$calculated['month']=$calculated['months'][$month];return$calculated+['analysis'=>self::getAnalysis((int)$indicator['id'],$year,$month,$scope),'pending'=>self::getPendingActions((int)$indicator['id'],$year,$month,$scope),'can_manage'=>self::canManageAnalysis((int)$indicator['id'])];}
    public static function getTargetForPeriod(int $indicatorId,int $year,int $month):?array
    {$date=sprintf('%04d-%02d-01',$year,$month);$q=Database::connection()->prepare("SELECT it.*,u.name created_by_name FROM indicator_targets it LEFT JOIN users u ON u.id=it.created_by WHERE it.indicator_id=:id AND it.active=1 AND it.deleted_at IS NULL AND it.effective_from<=:period AND (it.effective_to IS NULL OR it.effective_to>=:period2) ORDER BY it.effective_from DESC,it.id DESC LIMIT 1");$q->execute(['id'=>$indicatorId,'period'=>$date,'period2'=>$date]);return$q->fetch(PDO::FETCH_ASSOC)?:null;}
    public static function getAnalysis(int $indicatorId,int $year,int $month,array $scope):?array
    {$q=Database::connection()->prepare('SELECT ia.*,cu.name created_by_name,uu.name updated_by_name FROM indicator_analyses ia LEFT JOIN users cu ON cu.id=ia.created_by LEFT JOIN users uu ON uu.id=ia.updated_by WHERE ia.indicator_id=:id AND ia.year=:year AND ia.month=:month AND ia.client_scope_type=:scope AND ((ia.client_id IS NULL AND :client IS NULL) OR ia.client_id=:client2)');$q->execute(['id'=>$indicatorId,'year'=>$year,'month'=>$month,'scope'=>$scope['type'],'client'=>$scope['client_id'],'client2'=>$scope['client_id']]);$a=$q->fetch(PDO::FETCH_ASSOC);if(!$a)return null;$a['actions']=self::actions((int)$a['id']);return$a;}
    public static function getPendingActions(int $indicatorId,int $year,int $month,array $scope):array
    {$period=$year*100+$month;$q=Database::connection()->prepare("SELECT a.*,ia.year,ia.month,COALESCE(u.name,a.who_text,'—') responsible_name FROM indicator_actions a JOIN indicator_analyses ia ON ia.id=a.indicator_analysis_id LEFT JOIN users u ON u.id=a.responsible_user_id WHERE ia.indicator_id=:id AND (ia.year*100+ia.month)<:period AND ia.client_scope_type=:scope AND ((ia.client_id IS NULL AND :client IS NULL) OR ia.client_id=:client2) AND a.status IN ('planned','in_progress') ORDER BY ia.year DESC,ia.month DESC,a.due_date,a.id");$q->execute(['id'=>$indicatorId,'period'=>$period,'scope'=>$scope['type'],'client'=>$scope['client_id'],'client2'=>$scope['client_id']]);$groups=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){$k=sprintf('%04d-%02d',$r['year'],$r['month']);$groups[$k]??=['year'=>(int)$r['year'],'month'=>(int)$r['month'],'actions'=>[]];$groups[$k]['actions'][]=$r;}return array_values($groups);}
    public static function canManageAnalysis(int $indicatorId):bool
    {if(Auth::isAdministrator())return true;if(!Permission::can('indicators.analysis.manage'))return false;$q=Database::connection()->prepare('SELECT 1 FROM indicator_responsibles WHERE indicator_id=:indicator AND user_id=:user AND active=1');$q->execute(['indicator'=>$indicatorId,'user'=>Auth::user()['id']??0]);return(bool)$q->fetchColumn();}
    public static function compare(?float $value,array $target):bool
    {$t=(float)$target['target_value'];return match($target['target_operator']){'GT'=>$value>$t,'GTE'=>$value>=$t,'LT'=>$value<$t,'LTE'=>$value<=$t,'EQ'=>abs($value-$t)<0.00000001,default=>false};}
    public static function saveAnalysis(int $indicatorId,int $year,int $month,string $text,array $actions,array $scope):void
    {
        if(!self::canManageAnalysis($indicatorId))throw new DomainException('Somente responsáveis pelo indicador podem editar esta análise.');if($month<1||$month>12||$year<2000||$year>2100)throw new DomainException('Período inválido.');$pdo=Database::connection();$user=(int)(Auth::user()['id']??0);$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM indicator_analyses WHERE indicator_id=:indicator AND year=:year AND month=:month AND client_scope_type=:scope AND ((client_id IS NULL AND :client IS NULL) OR client_id=:client2) FOR UPDATE');$q->execute(['indicator'=>$indicatorId,'year'=>$year,'month'=>$month,'scope'=>$scope['type'],'client'=>$scope['client_id'],'client2'=>$scope['client_id']]);$before=$q->fetch(PDO::FETCH_ASSOC)?:null;if($before){$pdo->prepare('UPDATE indicator_analyses SET analysis_text=:text,updated_by=:user WHERE id=:id')->execute(['text'=>$text?:null,'user'=>$user,'id'=>$before['id']]);$analysisId=(int)$before['id'];Auth::registerAudit('INDICATOR_ANALYSIS_UPDATED','indicator_analyses',$analysisId,$before,['analysis_text'=>$text]);}else{$pdo->prepare('INSERT INTO indicator_analyses(indicator_id,year,month,client_scope_type,client_id,analysis_text,created_by,updated_by) VALUES(:indicator,:year,:month,:scope,:client,:text,:user,:user2)')->execute(['indicator'=>$indicatorId,'year'=>$year,'month'=>$month,'scope'=>$scope['type'],'client'=>$scope['client_id'],'text'=>$text?:null,'user'=>$user,'user2'=>$user]);$analysisId=(int)$pdo->lastInsertId();Auth::registerAudit('INDICATOR_ANALYSIS_CREATED','indicator_analyses',$analysisId,null,['indicator_id'=>$indicatorId,'year'=>$year,'month'=>$month,'client_scope_type'=>$scope['type'],'client_id'=>$scope['client_id'],'analysis_text'=>$text]);}
            foreach($actions as$a){if(!self::hasActionContent($a))continue;$id=(int)($a['id']??0);$status=in_array(($a['status']??''),['planned','in_progress','completed','cancelled'],true)?$a['status']:'planned';$completion=self::date($a['completion_date']??'');if($status==='completed'&&!$completion)$completion=date('Y-m-d');$values=['cause'=>self::clean($a['cause']??''),'what'=>self::clean($a['what']??''),'why'=>self::clean($a['why']??''),'how'=>self::clean($a['how']??''),'who'=>self::clean($a['who_text']??''),'responsible'=>(int)($a['responsible_user_id']??0)?:null,'when'=>self::clean($a['when_text']??''),'due'=>self::date($a['due_date']??''),'status'=>$status,'completion'=>$completion,'user'=>$user];if($id){$old=self::actionForAnalysis($id,$analysisId);if(!$old)throw new DomainException('Ação inválida para esta análise.');$values+=['id'=>$id];$pdo->prepare('UPDATE indicator_actions SET cause=:cause,what_text=:what,why_text=:why,how_text=:how,who_text=:who,responsible_user_id=:responsible,when_text=:when,due_date=:due,status=:status,completion_date=:completion,updated_by=:user WHERE id=:id')->execute($values);Auth::registerAudit($status==='completed'&&$old['status']!=='completed'?'INDICATOR_ACTION_COMPLETED':'INDICATOR_ACTION_UPDATED','indicator_actions',$id,$old,$values);}else{$values+=['analysis'=>$analysisId,'creator'=>$user];$pdo->prepare('INSERT INTO indicator_actions(indicator_analysis_id,cause,what_text,why_text,how_text,who_text,responsible_user_id,when_text,due_date,status,completion_date,created_by,updated_by) VALUES(:analysis,:cause,:what,:why,:how,:who,:responsible,:when,:due,:status,:completion,:creator,:user)')->execute($values);Auth::registerAudit('INDICATOR_ACTION_CREATED','indicator_actions',(int)$pdo->lastInsertId(),null,$values);}}
            $pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }
    public static function responsibles(int $indicatorId):array{$q=Database::connection()->prepare('SELECT ir.*,u.name,u.email FROM indicator_responsibles ir JOIN users u ON u.id=ir.user_id WHERE ir.indicator_id=:id AND ir.active=1 ORDER BY u.name');$q->execute(['id'=>$indicatorId]);return$q->fetchAll(PDO::FETCH_ASSOC);}
    public static function targetStatus(?float$value,?array$target):string{if($value===null)return'no_data';if(!$target)return'no_target';return self::compare($value,$target)?'met':'below';}
    private static function calculator(array$i):IndicatorCalculator{return match($i['code']){'HEMOCOMPONENTS_WITHIN_SPECIFICATIONS'=>new WithinSpecificationIndicatorCalculator(),'PLATELET_MEAN_CONCENTRATION'=>new PlateletMeanConcentrationIndicatorCalculator((int)($i['configured_test_id']??0)),default=>throw new DomainException('Calculador não configurado para este indicador.')};}
    private static function actions(int$id):array{$q=Database::connection()->prepare("SELECT a.*,COALESCE(u.name,a.who_text,'—') responsible_name FROM indicator_actions a LEFT JOIN users u ON u.id=a.responsible_user_id WHERE a.indicator_analysis_id=:id ORDER BY a.id");$q->execute(['id'=>$id]);return$q->fetchAll(PDO::FETCH_ASSOC);}
    private static function actionForAnalysis(int$id,int$analysis):?array{$q=Database::connection()->prepare('SELECT * FROM indicator_actions WHERE id=:id AND indicator_analysis_id=:analysis');$q->execute(compact('id','analysis'));return$q->fetch(PDO::FETCH_ASSOC)?:null;}
    private static function hasActionContent(array$a):bool{foreach(['id','cause','what','why','how','who_text','responsible_user_id','when_text','due_date','completion_date']as$k)if(!empty($a[$k]))return true;return false;}
    private static function clean(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
    private static function date(mixed$v):?string{$v=trim((string)$v);return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)&&strtotime($v)!==false?$v:null;}
}
