<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database,Permission};
use DomainException;
use PDO;

final class LaboratoryReportService
{
    public const VIEW='reports.release.view',MANAGE='reports.release.manage',REVISE='reports.release.revise',CANCEL='reports.release.cancel';
    public const LABELS=['PENDING_RELEASE'=>'Aguardando liberação','RELEASED'=>'Liberado','REVISED'=>'Retificado','CANCELLED'=>'Cancelado'];

    public static function catalogs():array{return['clients'=>ClientScopeService::getVisibleClientsForUser(),'units'=>ClientScopeService::getVisibleUnitsForUser(),'components'=>Database::connection()->query("SELECT id,code,name FROM blood_components WHERE status='active' ORDER BY code")->fetchAll(PDO::FETCH_ASSOC)];}
    private const ELIGIBILITY_KEYS=[
        'external_quality_control'=>'report_eligibility_external_quality_control',
        'external_transfusion_reaction'=>'report_eligibility_external_transfusion_reaction',
        'internal_quality_control'=>'report_eligibility_internal_quality_control',
        'internal_transfusion_reaction'=>'report_eligibility_internal_transfusion_reaction',
    ];
    public static function eligibilitySettings():array{$settings=[];foreach(self::ELIGIBILITY_KEYS as$name=>$key)$settings[$name]=self::setting($key)==='1';return$settings;}
    public static function setEligibilitySettings(array$enabled):void
    {
        $pdo=Database::connection();$query=$pdo->prepare('INSERT INTO system_settings(setting_key,setting_value,updated_by) VALUES(:key,:value,:user) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)');
        $pdo->beginTransaction();try{foreach(self::ELIGIBILITY_KEYS as$name=>$key)$query->execute(['key'=>$key,'value'=>!empty($enabled[$name])?'1':'0','user'=>Auth::user()['id']??null]);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }
    public static function search(array$f):array
    {
        $scope=ClientScopeService::resolve($f['client_type']??null,$f['client_id']??null);[$scopeSql,$scopeP]=ClientScopeService::applyClientScope('s.client_id',$scope,'report');[$unitScopeSql,$unitScopeP]=UnitAccessService::sqlScope('s.origin_unit_id','report_unit');
        $where=["s.purpose IN ('quality_control','transfusion_reaction')","(s.purpose='transfusion_reaction' OR s.status='completed')","s.client_id IS NOT NULL",$scopeSql,$unitScopeSql];$p=$scopeP+$unitScopeP;
        $map=['unit_id'=>'s.origin_unit_id','component_id'=>'s.blood_component_id'];foreach($map as$k=>$col)if(($v=filter_var($f[$k]??null,FILTER_VALIDATE_INT))){$where[]="$col=:$k";$p[$k]=$v;}
        foreach(['donation'=>'s.donation_number','lcqh'=>'s.lcqh_code']as$k=>$col)if(trim((string)($f[$k]??''))!==''){$where[]="$col LIKE :$k";$p[$k]='%'.trim($f[$k]).'%';}
        if(preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($f['from']??''))){$where[]='DATE(s.received_at)>=:from';$p['from']=$f['from'];}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($f['to']??''))){$where[]='DATE(s.received_at)<=:to';$p['to']=$f['to'];}
        $restricted=$scope['restricted'];$status=trim((string)($f['status']??''));if($restricted)$where[]="lr.status IN ('RELEASED','REVISED')";elseif(isset(self::LABELS[$status])){$where[]='COALESCE(lr.status,\'PENDING_RELEASE\')=:status';$p['status']=$status;}
        $sql="SELECT s.id sample_id,s.received_at,s.donation_number,s.lcqh_code,s.client_id,s.origin_unit_id,s.blood_component_id,c.name client_name,c.client_type,u.name unit_name,bc.code component_code,bc.name component_name,lr.id report_id,lr.status report_status,lr.version,lr.released_at,lr.source_fingerprint FROM samples s JOIN clients c ON c.id=s.client_id LEFT JOIN units u ON u.id=s.origin_unit_id JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN laboratory_reports lr ON lr.id=(SELECT r.id FROM laboratory_reports r WHERE r.sample_id=s.id ORDER BY r.version DESC,r.id DESC LIMIT 1) WHERE ".implode(' AND ',$where).' ORDER BY s.received_at DESC,s.id DESC';
        $q=Database::connection()->prepare($sql);$q->execute($p);$rows=array_values(array_filter($q->fetchAll(PDO::FETCH_ASSOC),static fn($r)=>!empty($r['report_id'])||self::isSampleEligibleForReport((int)$r['sample_id'])));foreach($rows as&$r){$r['status']=$r['report_status']?:'PENDING_RELEASE';$r['needs_revision']=$r['report_id']&&$r['status']!=='CANCELLED'&&!hash_equals((string)$r['source_fingerprint'],self::fingerprint((int)$r['sample_id']));}return$rows;
    }
    public static function kpis(array$rows):array{$o=['PENDING_RELEASE'=>0,'RELEASED'=>0,'REVISED'=>0,'CANCELLED'=>0];foreach($rows as$r)$o[$r['status']]++;return$o;}

    public static function preview(int$sampleId):array
    {
        if(ClientScopeService::resolve()['restricted'])throw new DomainException('Laudo não encontrado.');
        $sample=self::sample($sampleId);self::authorizeClient((int)$sample['client_id']);UnitAccessService::authorize($sample['origin_unit_id']?(int)$sample['origin_unit_id']:null,'Laudo não encontrado.');if(!self::isSampleEligibleForReport($sampleId))throw new DomainException('Esta amostra não está elegível para emissão de laudo. Verifique a configuração do contexto e os resultados finais.');
        return self::snapshot($sample);
    }
    public static function release(int$sampleId,string$notes='',?int$previousId=null,string$reason=''):int
    {
        if(!Permission::can($previousId?self::REVISE:self::MANAGE))throw new DomainException('Você não possui permissão para esta operação.');
        $user=self::releaseUser();if(trim((string)($user['professional_name']??''))===''||trim((string)($user['professional_council']??''))===''||trim((string)($user['professional_registration']??''))==='')throw new DomainException('Preencha o nome para liberação, conselho profissional e número de registro antes de liberar o laudo.');
        $snapshot=self::preview($sampleId);$pdo=Database::connection();$pdo->beginTransaction();try{$previous=null;$version=1;$group=self::uuid();$status='RELEASED';if($previousId){$q=$pdo->prepare('SELECT * FROM laboratory_reports WHERE id=:id AND sample_id=:sample FOR UPDATE');$q->execute(['id'=>$previousId,'sample'=>$sampleId]);$previous=$q->fetch(PDO::FETCH_ASSOC);if(!$previous)throw new DomainException('Versão anterior não encontrada.');if(trim($reason)==='')throw new DomainException('Informe o motivo da retificação.');$version=(int)$previous['version']+1;$group=$previous['report_group_id'];$status='REVISED';}
            $released=date('Y-m-d H:i:s');$professional=trim(($user['professional_council']??'').' '.($user['professional_registration']??''));$fingerprint=self::fingerprint($sampleId);
            $q=$pdo->prepare('INSERT INTO laboratory_reports(report_group_id,previous_report_id,sample_id,client_id,unit_id,status,version,released_by,released_at,release_user_name_snapshot,professional_registration_snapshot,recipient_snapshot_json,sample_snapshot_json,results_snapshot_json,notes_snapshot,source_fingerprint,revision_reason) VALUES(:group_id,:previous,:sample,:client,:unit,:status,:version,:user,:released,:name,:professional,:recipient,:sample_json,:results,:notes,:fingerprint,:reason)');
            $q->execute(['group_id'=>$group,'previous'=>$previousId,'sample'=>$sampleId,'client'=>$snapshot['sample']['client_id'],'unit'=>$snapshot['sample']['unit_id'],'status'=>$status,'version'=>$version,'user'=>$user['id'],'released'=>$released,'name'=>trim((string)($user['professional_name']?:$user['name'])),'professional'=>$professional,'recipient'=>json_encode($snapshot['recipient'],JSON_UNESCAPED_UNICODE),'sample_json'=>json_encode($snapshot['sample'],JSON_UNESCAPED_UNICODE),'results'=>json_encode($snapshot['results'],JSON_UNESCAPED_UNICODE),'notes'=>$notes?:null,'fingerprint'=>$fingerprint,'reason'=>$reason?:null]);$id=(int)$pdo->lastInsertId();
            $record=self::findRaw($id);$pdf=self::generatePdf($record);$dir=dirname(__DIR__,2).'/storage/reports/'.date('Y/m',strtotime($released));if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new DomainException('Não foi possível preparar o armazenamento seguro.');$filename=self::filename($snapshot['sample'],$version);$path=$dir.'/'.$filename;if(file_put_contents($path,$pdf,LOCK_EX)===false)throw new DomainException('Não foi possível armazenar o PDF.');$relative=substr($path,strlen(dirname(__DIR__,2))+1);$pdo->prepare('UPDATE laboratory_reports SET pdf_path=:path WHERE id=:id')->execute(['path'=>str_replace('\\','/',$relative),'id'=>$id]);Auth::registerAudit($previousId?'REPORT_REVISED':'REPORT_RELEASED','laboratory_reports',$id,null,['sample_id'=>$sampleId,'version'=>$version]);$pdo->commit();return$id;
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }
    public static function cancel(int$id,string$reason):void{if(!Permission::can(self::CANCEL))throw new DomainException('Você não possui permissão para cancelar laudos.');if(trim($reason)==='')throw new DomainException('Informe o motivo do cancelamento.');$r=self::find($id);Database::connection()->prepare("UPDATE laboratory_reports SET status='CANCELLED',cancelled_by=:user,cancelled_at=NOW(),cancellation_reason=:reason WHERE id=:id")->execute(['user'=>Auth::user()['id'],'reason'=>trim($reason),'id'=>$id]);Auth::registerAudit('REPORT_CANCELLED','laboratory_reports',$id,['status'=>$r['status']],['status'=>'CANCELLED','reason'=>$reason]);}
    public static function versions(int$id):array{$r=self::find($id);$q=Database::connection()->prepare('SELECT id,version,status,released_at,release_user_name_snapshot,revision_reason,cancellation_reason FROM laboratory_reports WHERE report_group_id=:g ORDER BY version DESC');$q->execute(['g'=>$r['report_group_id']]);return$q->fetchAll(PDO::FETCH_ASSOC);}
    public static function find(int$id):array{$r=self::findRaw($id);if(!$r)throw new DomainException('Laudo não encontrado.');self::authorizeClient((int)$r['client_id']);UnitAccessService::authorize($r['unit_id']?(int)$r['unit_id']:null,'Laudo não encontrado.');$restricted=ClientScopeService::resolve()['restricted'];if($restricted&&!in_array($r['status'],['RELEASED','REVISED'],true))throw new DomainException('Laudo não encontrado.');return$r;}
    private static function findRaw(int$id):?array{$q=Database::connection()->prepare('SELECT * FROM laboratory_reports WHERE id=:id');$q->execute(['id'=>$id]);return$q->fetch(PDO::FETCH_ASSOC)?:null;}
    public static function pdfPath(array$r):string{$path=dirname(__DIR__,2).'/'.ltrim((string)$r['pdf_path'],'/');$root=realpath(dirname(__DIR__,2).'/storage/reports');$real=realpath($path);if(!$root||!$real||!str_starts_with($real,$root.DIRECTORY_SEPARATOR))throw new DomainException('Arquivo do laudo indisponível.');return$real;}
    private static function authorizeClient(int$id):void{if(!ClientScopeService::canAccessClient($id))throw new DomainException('Laudo não encontrado.');}
    private static function sample(int$id):array{$q=Database::connection()->prepare("SELECT s.*,c.name client_name,c.client_type,c.address client_address,c.district client_district,c.city client_city,c.state client_state,c.postal_code client_postal_code,c.contact_name client_contact,c.phone client_phone,c.phone_extension client_extension,u.name unit_name,u.address unit_address,u.district unit_district,u.city unit_city,u.state unit_state,u.postal_code unit_postal_code,u.contact_name unit_contact,u.phone unit_phone,u.phone_extension unit_extension,bc.code component_code,bc.name component_name FROM samples s JOIN clients c ON c.id=s.client_id LEFT JOIN units u ON u.id=s.origin_unit_id JOIN blood_components bc ON bc.id=s.blood_component_id WHERE s.id=:id AND s.purpose IN ('quality_control','transfusion_reaction') AND (s.purpose='transfusion_reaction' OR s.status='completed')");$q->execute(['id'=>$id]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new DomainException('Amostra concluída não encontrada.');return$r;}
    public static function isSampleEligibleForReport(int|array$sample):bool
    {
        $pdo=Database::connection();if(is_int($sample)){$q=$pdo->prepare('SELECT s.*,c.client_type FROM samples s JOIN clients c ON c.id=s.client_id WHERE s.id=:id');$q->execute(['id'=>$sample]);$sample=$q->fetch(PDO::FETCH_ASSOC)?:[];}
        if(!$sample)return false;
        $purpose=(string)($sample['purpose']??'');$clientType=(string)($sample['client_type']??'');
        if(!in_array($purpose,['quality_control','transfusion_reaction'],true)||!in_array($clientType,['internal','external'],true))return false;
        $context=$clientType.'_'.$purpose;$settings=self::eligibilitySettings();if(empty($settings[$context]))return false;
        return self::isSampleAnalyticallyComplete($sample);
    }
    private static function isSampleAnalyticallyComplete(array $sample):bool
    {
        return ($sample['purpose']??'')==='transfusion_reaction'?self::isTransfusionReactionComplete((int)$sample['id']):self::isQualityControlComplete($sample);
    }
    private static function isTransfusionReactionComplete(int $sampleId):bool
    {
        $q=Database::connection()->prepare("SELECT result,identified_bacteria,workflow_status FROM bacteriology_results WHERE sample_id=:id AND is_final=1 ORDER BY performed_at DESC,id DESC LIMIT 1");$q->execute(['id'=>$sampleId]);$result=$q->fetch(PDO::FETCH_ASSOC);if(!$result||$result['workflow_status']!=='completed'||!in_array($result['result'],['negative','positive'],true))return false;if($result['result']==='positive'&&trim((string)$result['identified_bacteria'])==='')return false;
        $q=Database::connection()->prepare("SELECT COUNT(*) FROM bacteriology_retests WHERE sample_id=:id AND status='pending'");$q->execute(['id'=>$sampleId]);return(int)$q->fetchColumn()===0;
    }
    private static function isQualityControlComplete(array $sample):bool
    {
        if(($sample['status']??'')!=='completed')return false;$pdo=Database::connection();if(TestResultService::pendingRequirements((int)$sample['id']))return false;
        $q=$pdo->prepare("SELECT COUNT(*) FROM test_blood_components tbc JOIN tests t ON t.id=tbc.test_id AND t.status='active' AND t.is_final_result=1 LEFT JOIN sample_tests st ON st.sample_id=:sample AND st.test_id=t.id LEFT JOIN test_results tr ON tr.id=(SELECT MAX(x.id) FROM test_results x WHERE x.sample_test_id=st.id) WHERE tbc.blood_component_id=:component AND tbc.is_required=1 AND (st.status IS NULL OR st.status<>'completed' OR tr.id IS NULL OR (tr.result_value_numeric IS NULL AND NULLIF(TRIM(tr.result_value_text),'') IS NULL))");$q->execute(['sample'=>$sample['id'],'component'=>$sample['blood_component_id']]);if((int)$q->fetchColumn()>0)return false;
        $q=$pdo->prepare("SELECT COUNT(*) FROM test_result_spec_evaluations e JOIN test_results tr ON tr.id=e.test_result_id JOIN sample_tests st ON st.id=tr.sample_test_id JOIN tests t ON t.id=st.test_id AND t.is_final_result=1 WHERE st.sample_id=:id AND e.conformity_status='NOT_EVALUATED'");$q->execute(['id'=>$sample['id']]);return(int)$q->fetchColumn()===0;
    }
    public static function releaseUser():array{$id=(int)(Auth::user()['id']??0);$q=Database::connection()->prepare('SELECT id,name,professional_name,professional_council,professional_registration FROM users WHERE id=:id AND status=\'active\'');$q->execute(['id'=>$id]);return$q->fetch(PDO::FETCH_ASSOC)?:[];}
    private static function snapshot(array$s):array
    {
        $prefer=fn(string$u,string$c)=>trim((string)($s[$u]??''))?:trim((string)($s[$c]??''));$recipient=['client'=>$s['client_name'],'unit'=>$s['unit_name'],'address'=>$prefer('unit_address','client_address'),'district'=>$prefer('unit_district','client_district'),'city'=>$prefer('unit_city','client_city'),'state'=>$prefer('unit_state','client_state'),'postal_code'=>$prefer('unit_postal_code','client_postal_code'),'contact'=>$prefer('unit_contact','client_contact'),'phone'=>$prefer('unit_phone','client_phone'),'extension'=>$prefer('unit_extension','client_extension')];
        $sample=['id'=>(int)$s['id'],'client_id'=>(int)$s['client_id'],'unit_id'=>$s['origin_unit_id']?(int)$s['origin_unit_id']:null,'component'=>$s['component_name'],'component_code'=>$s['component_code'],'donation'=>$s['donation_number'],'lcqh_code'=>$s['lcqh_code'],'production_date'=>$s['production_date']?:$s['collection_date'],'received_at'=>$s['received_at']];
        return['recipient'=>$recipient,'sample'=>$sample,'results'=>self::results((int)$s['id'],(string)$s['purpose'])];
    }
    private static function results(int$id,?string$purpose=null):array
    {
        if($purpose===null){$q=Database::connection()->prepare('SELECT purpose FROM samples WHERE id=:id');$q->execute(['id'=>$id]);$purpose=(string)$q->fetchColumn();}if($purpose==='transfusion_reaction')return self::transfusionReactionResults($id);
        $q=Database::connection()->prepare("SELECT tr.id,t.code,t.name,t.unit,t.method_name,tr.result_value_numeric,tr.result_value_text,e.specification_snapshot_text,e.rule_type,e.expected_min,e.expected_max,e.expected_text,e.unit specification_unit,e.conformity_status,re.method_snapshot,re.equipment_name_snapshot,re.manufacturer_snapshot,re.model_snapshot,re.serial_snapshot FROM sample_tests st JOIN tests t ON t.id=st.test_id AND t.is_final_result=1 AND t.code<>'BACTERIOLOGY' JOIN test_results tr ON tr.id=(SELECT MAX(x.id) FROM test_results x WHERE x.sample_test_id=st.id) LEFT JOIN test_result_spec_evaluations e ON e.test_result_id=tr.id LEFT JOIN test_result_equipment re ON re.test_result_id=tr.id WHERE st.sample_id=:id AND st.status='completed' ORDER BY t.name");$q->execute(['id'=>$id]);$out=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){$v=$r['result_value_numeric']!==null?$r['result_value_numeric']:$r['result_value_text'];$equipment=trim(implode(' ',array_filter([$r['manufacturer_snapshot'],$r['model_snapshot'],$r['serial_snapshot']])));$method=trim((string)($r['method_snapshot']?:$r['method_name']));$reference=in_array($r['conformity_status']??null,['CONFORMING','NONCONFORMING'],true)?MeasurementFormatter::formatSpecification((string)$r['code'],['rule_type'=>$r['rule_type'],'expected_min'=>$r['expected_min'],'expected_max'=>$r['expected_max'],'expected_text'=>$r['expected_text'],'unit'=>$r['specification_unit'],'specification_snapshot_text'=>$r['specification_snapshot_text']]):'Não se aplica';$out[]=['result_id'=>(int)$r['id'],'parameter'=>$r['name'],'result'=>is_numeric($v)?MeasurementFormatter::formatResult((string)$r['code'],$v,$r['unit']):trim((string)$v.' '.(string)$r['unit']),'reference'=>$reference,'method_equipment'=>implode(' - ',array_filter([$method,$equipment]))?:'Não se aplica'];}
        $b=Database::connection()->prepare("SELECT br.id,br.result,t.name,t.method_name FROM bacteriology_results br JOIN tests t ON t.code='BACTERIOLOGY' AND t.is_final_result=1 WHERE br.sample_id=:id AND br.is_final=1 ORDER BY br.performed_at DESC,br.id DESC LIMIT 1");$b->execute(['id'=>$id]);if($r=$b->fetch(PDO::FETCH_ASSOC))$out[]=['result_id'=>'b'.$r['id'],'parameter'=>$r['name'],'result'=>$r['result']==='negative'?'Negativo':'Positivo confirmado','reference'=>'Resultado bacteriológico final','method_equipment'=>$r['method_name']?:'Método configurável'];return$out;
    }
    private static function transfusionReactionResults(int$id):array
    {
        $q=Database::connection()->prepare("SELECT br.id,br.result,br.identified_bacteria,t.name,t.method_name FROM bacteriology_results br JOIN tests t ON t.code='BACTERIOLOGY' AND t.is_final_result=1 WHERE br.sample_id=:id AND br.is_final=1 AND br.workflow_status='completed' ORDER BY br.performed_at DESC,br.id DESC LIMIT 1");$q->execute(['id'=>$id]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)return[];$method=$r['method_name']?:'Método configurável';return[
            ['result_id'=>'b'.$r['id'],'parameter'=>$r['name'],'result'=>$r['result']==='negative'?'Negativo':'Positivo confirmado','reference'=>'Resultado bacteriológico final','method_equipment'=>$method],
            ['result_id'=>'bi'.$r['id'],'parameter'=>'Identificação bacteriana','result'=>$r['result']==='negative'?'Não se aplica':trim((string)$r['identified_bacteria']),'reference'=>'Não se aplica','method_equipment'=>$method]
        ];
    }
    public static function fingerprint(int$id):string{return hash('sha256',json_encode(self::results($id),JSON_UNESCAPED_UNICODE));}
    private static function generatePdf(array$r):string{$recipient=json_decode($r['recipient_snapshot_json'],true);$sample=json_decode($r['sample_snapshot_json'],true);$results=json_decode($r['results_snapshot_json'],true);$pdf=new SimplePdf('Laudo de Hemocomponente');$pdf->heading('LAUDO DE HEMOCOMPONENTE - VERSÃO '.$r['version']);$pdf->row('Recebimento',self::dateTime($sample['received_at']));$pdf->row('Emissão',self::dateTime($r['released_at']));$pdf->heading('DADOS DO DESTINATÁRIO');foreach(['Cliente'=>'client','Unidade'=>'unit','Endereço'=>'address','Bairro'=>'district','Cidade / UF'=>'city','CEP'=>'postal_code','Contato'=>'contact','Telefone / Ramal'=>'phone']as$l=>$k){$v=$recipient[$k]??'';if($k==='city')$v=trim($v.(!empty($recipient['state'])?' / '.$recipient['state']:''));if($k==='phone'&&!empty($recipient['extension']))$v.=' / '.$recipient['extension'];$pdf->row($l,$v?:'Não informado');}$pdf->heading('INFORMAÇÕES DO HEMOCOMPONENTE');$pdf->row('Hemocomponente',$sample['component']);$pdf->row('Nº da bolsa / doação',$sample['donation']?:'Não informado');$pdf->row('Data de coleta / produção',self::dateOnly($sample['production_date']));$pdf->row('Código LCQH',$sample['lcqh_code']?:'Não informado');$pdf->heading('RESULTADOS FINAIS');$pdf->results($results);$pdf->heading('OBSERVAÇÕES');$pdf->paragraph($r['notes_snapshot']?:'Sem observações.');$reg=self::setting('report_footer_regulatory_text');if($reg){$pdf->heading('REFERÊNCIA INSTITUCIONAL');$pdf->paragraph($reg);}$pdf->heading('RESPONSÁVEL PELA LIBERAÇÃO');$pdf->row('Liberado eletronicamente por',$r['release_user_name_snapshot']);$pdf->row('Registro profissional',$r['professional_registration_snapshot']);$pdf->row('Em',self::dateTime($r['released_at']));$footer=self::setting('report_institutional_footer');if($footer)$pdf->paragraph($footer);return$pdf->output();}
    private static function setting(string$key):string{$q=Database::connection()->prepare('SELECT setting_value FROM system_settings WHERE setting_key=:k');$q->execute(['k'=>$key]);return trim((string)$q->fetchColumn());}
    private static function filename(array$s,int$v):string{$base=preg_replace('/[^A-Za-z0-9_-]+/','_',($s['donation']?:$s['lcqh_code']?:'Amostra_'.$s['id']).'_'.$s['component_code']);return'Laudo_'.trim($base,'_').'_v'.$v.'.pdf';}
    private static function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
    private static function dateTime(?string$d):string{return$d?date('d/m/Y H:i',strtotime($d)):'Não informado';}private static function dateOnly(?string$d):string{return$d?date('d/m/Y',strtotime($d)):'Não informado';}
}
