<?php
declare(strict_types=1);
namespace BloodHub\Services;
use BloodHub\Core\{Auth,Database};
use DomainException;
use PDO;
final class NotificationActionService
{
 public const STATUSES=['PLANNED'=>'Planejada','IN_PROGRESS'=>'Em andamento','COMPLETED'=>'Concluída','CANCELLED'=>'Cancelada'];
 public static function save(?int$id,int$analysisId,array$data):int
 {NotificationWorkflowService::requirePermission('notifications.action_plan');$pdo=Database::connection();$pdo->beginTransaction();try{$a=NotificationAnalysisService::accessible($pdo,$analysisId,true);if($a['status']==='COMPLETED')throw new DomainException('Análises encerradas são somente leitura.');$description=trim((string)($data['action_description']??''));if($description==='')throw new DomainException('Informe a descrição da ação.');$status=(string)($data['status']??'PLANNED');if(!isset(self::STATUSES[$status]))throw new DomainException('Status da ação inválido.');$responsible=(int)($data['responsible_user_id']??0)?:null;if($responsible){$q=$pdo->prepare("SELECT 1 FROM users u LEFT JOIN user_units uu ON uu.user_id=u.id WHERE u.id=:user AND u.status='active' AND (u.primary_unit_id=:unit OR uu.unit_id=:unit2) LIMIT 1");$q->execute(['user'=>$responsible,'unit'=>$a['unit_id'],'unit2'=>$a['unit_id']]);if(!$q->fetchColumn())throw new DomainException('O responsável selecionado não pertence à unidade da análise.');}$uid=(int)(Auth::user()['id']??0);$completed=$status==='COMPLETED';
 if($id){$q=$pdo->prepare('SELECT * FROM qc_notification_actions WHERE id=:id AND analysis_id=:analysis FOR UPDATE');$q->execute(['id'=>$id,'analysis'=>$analysisId]);$old=$q->fetch(PDO::FETCH_ASSOC);if(!$old)throw new DomainException('Ação não encontrada.');$pdo->prepare('UPDATE qc_notification_actions SET action_description=:description,responsible_user_id=:responsible,responsible_name=:name,due_date=:due,status=:status,completed_at=CASE WHEN :done=1 AND completed_at IS NULL THEN NOW() WHEN :notdone=1 THEN NULL ELSE completed_at END,completion_notes=:notes,updated_by=:user WHERE id=:id')->execute(['description'=>$description,'responsible'=>$responsible,'name'=>trim((string)($data['responsible_name']??''))?:null,'due'=>$data['due_date']?:null,'status'=>$status,'done'=>$completed?1:0,'notdone'=>$completed?0:1,'notes'=>trim((string)($data['completion_notes']??''))?:null,'user'=>$uid,'id'=>$id]);$event=$completed&&$old['status']!=='COMPLETED'?'ACTION_COMPLETED':'ACTION_UPDATED';}
 else{$pdo->prepare('INSERT INTO qc_notification_actions(analysis_id,action_description,responsible_user_id,responsible_name,due_date,status,completed_at,completion_notes,created_by,updated_by) VALUES(:analysis,:description,:responsible,:name,:due,:status,CASE WHEN :done=1 THEN NOW() ELSE NULL END,:notes,:user,:user2)')->execute(['analysis'=>$analysisId,'description'=>$description,'responsible'=>$responsible,'name'=>trim((string)($data['responsible_name']??''))?:null,'due'=>$data['due_date']?:null,'status'=>$status,'done'=>$completed?1:0,'notes'=>trim((string)($data['completion_notes']??''))?:null,'user'=>$uid,'user2'=>$uid]);$id=(int)$pdo->lastInsertId();$event='ACTION_CREATED';}NotificationWorkflowService::analysisEvent($pdo,$analysisId,$event,$event==='ACTION_COMPLETED'?'Ação concluída':($event==='ACTION_CREATED'?'Ação adicionada':'Ação alterada'),$uid,['action_id'=>$id]);Auth::registerAudit($event,'qc_notification_actions',$id,null,['analysis_id'=>$analysisId,'status'=>$status]);$pdo->commit();return$id;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
}
