<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database,Permission};
use DomainException;
use PDO;

final class NotificationAnalysisService
{
    public const CAUSES=['PROCESS'=>'Processo produtivo','EQUIPMENT'=>'Equipamento','SUPPLY'=>'Insumo','METHOD'=>'Método','RAW_MATERIAL'=>'Matéria-prima','TRAINING'=>'Treinamento','OPERATIONAL_FAILURE'=>'Falha operacional','STORAGE'=>'Condição de armazenamento','TRANSPORT'=>'Transporte','OTHER'=>'Outro','UNDETERMINED'=>'Não determinada'];
    public static function create(array $ids):int
    {
        NotificationWorkflowService::requirePermission('notifications.analyze');$ids=array_values(array_unique(array_filter(array_map('intval',$ids))));if(!$ids)throw new DomainException('Selecione ao menos uma notificação.');$pdo=Database::connection();$uid=(int)(Auth::user()['id']??0);[$scope,$scopeParams]=QcNotificationService::scopeSql('n');$pdo->beginTransaction();
        try{$idParams=[];foreach($ids as$index=>$value)$idParams['selected_'.$index]=$value;$marks=implode(',',array_map(fn($key)=>':'.$key,array_keys($idParams)));$q=$pdo->prepare("SELECT n.* FROM qc_notifications n WHERE n.id IN ($marks) AND {$scope} ORDER BY n.id FOR UPDATE");$q->execute($idParams+$scopeParams);$rows=$q->fetchAll(PDO::FETCH_ASSOC);if(count($rows)!==count($ids))throw new DomainException('Uma ou mais notificações não estão disponíveis no seu escopo.');$first=$rows[0];
            self::assertCompatible($rows,$first);foreach($rows as$row){if($row['status']!==NotificationWorkflowService::ACKNOWLEDGED)throw new DomainException('Use somente notificações com ciência registrada e aguardando análise.');$busy=$pdo->prepare("SELECT 1 FROM qc_notification_analysis_items i JOIN qc_notification_analyses a ON a.id=i.analysis_id WHERE i.notification_id=:id AND i.removed_at IS NULL AND a.status<>'COMPLETED' LIMIT 1");$busy->execute(['id'=>$row['id']]);if($busy->fetchColumn())throw new DomainException('Uma ocorrência selecionada já participa de outra análise ativa.');}
            $testIds=array_unique(array_map(fn($row)=>(int)$row['test_id'],$rows));$analysisTestId=count($testIds)===1?$first['test_id']:null;$dates=array_column($rows,'occurred_at');sort($dates);$pdo->prepare('INSERT INTO qc_notification_analyses(unit_id,client_id,blood_component_id,test_id,period_start,period_end,created_by,updated_by) VALUES(:unit,:client,:component,:test,:start,:end,:user,:user2)')->execute(['unit'=>$first['origin_unit_id'],'client'=>$first['client_id'],'component'=>$first['blood_component_id'],'test'=>$analysisTestId,'start'=>substr($dates[0],0,10),'end'=>substr(end($dates),0,10),'user'=>$uid,'user2'=>$uid]);$analysisId=(int)$pdo->lastInsertId();$code='ANL-'.date('Ym').'-'.str_pad((string)$analysisId,5,'0',STR_PAD_LEFT);$pdo->prepare('UPDATE qc_notification_analyses SET analysis_code=:code WHERE id=:id')->execute(['code'=>$code,'id'=>$analysisId]);$item=$pdo->prepare('INSERT INTO qc_notification_analysis_items(analysis_id,notification_id,added_by) VALUES(:analysis,:notification,:user)');
            foreach($rows as$row){$item->execute(['analysis'=>$analysisId,'notification'=>$row['id'],'user'=>$uid]);$pdo->prepare('UPDATE qc_notifications SET status=:status WHERE id=:id')->execute(['status'=>NotificationWorkflowService::IN_ANALYSIS,'id'=>$row['id']]);self::notificationItemEvent($pdo,(int)$row['id'],$analysisId,$code,$uid);}
            NotificationWorkflowService::analysisEvent($pdo,$analysisId,'NOTIFICATION_ANALYSIS_CREATED','Análise criada com '.count($rows).' ocorrência(s)',$uid);Auth::registerAudit('NOTIFICATION_ANALYSIS_CREATED','qc_notification_analyses',$analysisId,null,['analysis_code'=>$code,'notifications'=>$ids]);$pdo->commit();return$analysisId;
        }catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
    }
    private static function notificationItemEvent(PDO $pdo,int $notificationId,int $analysisId,string $code,int $uid):void{NotificationWorkflowService::notificationEvent($pdo,$notificationId,'NOTIFICATION_ADDED_TO_ANALYSIS','Incluída na análise '.$code,$uid,['analysis_id'=>$analysisId,'analysis_code'=>$code]);Auth::registerAudit('NOTIFICATION_ADDED_TO_ANALYSIS','qc_notifications',$notificationId,['status'=>NotificationWorkflowService::ACKNOWLEDGED],['status'=>NotificationWorkflowService::IN_ANALYSIS,'analysis_id'=>$analysisId]);}
    public static function save(int $id,array $data):void
    {NotificationWorkflowService::requirePermission('notifications.analyze');$pdo=Database::connection();$a=self::accessible($pdo,$id,true);if($a['status']!=='IN_ANALYSIS')throw new DomainException('Somente análises em elaboração podem ser editadas.');$cause=(string)($data['cause_classification']??'');if($cause!==''&&!isset(self::CAUSES[$cause]))throw new DomainException('Classificação da causa inválida.');$noAction=!empty($data['no_action_required']);$justification=trim((string)($data['no_action_justification']??''));if($noAction&&$justification==='')throw new DomainException('Informe a justificativa para não criar um plano de ação.');$uid=(int)(Auth::user()['id']??0);$pdo->prepare('UPDATE qc_notification_analyses SET analysis_text=:text,cause_classification=:cause,cause_other=:other,no_action_required=:no_action,no_action_justification=:justification,updated_by=:user WHERE id=:id')->execute(['text'=>trim((string)($data['analysis_text']??''))?:null,'cause'=>$cause?:null,'other'=>trim((string)($data['cause_other']??''))?:null,'no_action'=>$noAction?1:0,'justification'=>$justification?:null,'user'=>$uid,'id'=>$id]);NotificationWorkflowService::analysisEvent($pdo,$id,'ANALYSIS_UPDATED','Análise salva como rascunho',$uid);Auth::registerAudit('ANALYSIS_UPDATED','qc_notification_analyses',$id,null,['status'=>'IN_ANALYSIS']);}
    public static function startFollowUp(int $id):void
    {NotificationWorkflowService::requirePermission('notifications.analyze');$pdo=Database::connection();$pdo->beginTransaction();try{$a=self::accessible($pdo,$id,true);if($a['status']!=='IN_ANALYSIS')throw new DomainException('A análise não está em elaboração.');if(trim((string)$a['analysis_text'])==='')throw new DomainException('Preencha e salve a análise da ocorrência.');$q=$pdo->prepare("SELECT COUNT(*) FROM qc_notification_actions WHERE analysis_id=:id AND status<>'CANCELLED'");$q->execute(['id'=>$id]);if(!$a['no_action_required']&&!(int)$q->fetchColumn())throw new DomainException('Adicione ao menos uma ação ou marque que o caso não requer plano de ação.');$uid=(int)(Auth::user()['id']??0);$pdo->prepare("UPDATE qc_notification_analyses SET status='IN_FOLLOW_UP',updated_by=:user WHERE id=:id")->execute(['user'=>$uid,'id'=>$id]);$pdo->prepare("UPDATE qc_notifications n JOIN qc_notification_analysis_items i ON i.notification_id=n.id AND i.analysis_id=:id AND i.removed_at IS NULL SET n.status='IN_FOLLOW_UP'")->execute(['id'=>$id]);self::eventsForItems($pdo,$id,'ACTION_PLAN_DEFINED','Plano de ação definido; acompanhamento iniciado',$uid);NotificationWorkflowService::analysisEvent($pdo,$id,'ACTION_PLAN_DEFINED','Análise finalizada e acompanhamento iniciado',$uid);Auth::registerAudit('ANALYSIS_UPDATED','qc_notification_analyses',$id,['status'=>'IN_ANALYSIS'],['status'=>'IN_FOLLOW_UP']);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public static function complete(int $id,string $conclusion):void
    {NotificationWorkflowService::requirePermission('notifications.close');$conclusion=trim($conclusion);if($conclusion==='')throw new DomainException('Informe a conclusão da análise.');$pdo=Database::connection();$pdo->beginTransaction();try{$a=self::accessible($pdo,$id,true);$direct=$a['status']==='IN_ANALYSIS'&&!empty($a['no_action_required']);if($a['status']!=='IN_FOLLOW_UP'&&!$direct)throw new DomainException('A análise precisa estar em acompanhamento ou dispensar plano de ação.');if($direct&&(trim((string)$a['analysis_text'])===''||trim((string)$a['no_action_justification'])===''))throw new DomainException('Preencha a análise e a justificativa antes de concluir.');$q=$pdo->prepare("SELECT COUNT(*) FROM qc_notification_actions WHERE analysis_id=:id AND status NOT IN ('COMPLETED','CANCELLED')");$q->execute(['id'=>$id]);if((int)$q->fetchColumn())throw new DomainException('Conclua ou cancele todas as ações antes de encerrar.');$q=$pdo->prepare("SELECT COUNT(*) FROM qc_notification_actions WHERE analysis_id=:id AND status<>'CANCELLED'");$q->execute(['id'=>$id]);if(!(int)$q->fetchColumn()&&!$a['no_action_required'])throw new DomainException('A análise não possui plano de ação nem justificativa de dispensa.');$uid=(int)(Auth::user()['id']??0);$pdo->prepare("UPDATE qc_notification_analyses SET status='COMPLETED',conclusion_text=:text,completed_by=:user,completed_at=NOW(),updated_by=:user2 WHERE id=:id")->execute(['text'=>$conclusion,'user'=>$uid,'user2'=>$uid,'id'=>$id]);$pdo->prepare("UPDATE qc_notifications n JOIN qc_notification_analysis_items i ON i.notification_id=n.id AND i.analysis_id=:id AND i.removed_at IS NULL SET n.status='COMPLETED'")->execute(['id'=>$id]);self::eventsForItems($pdo,$id,'ANALYSIS_COMPLETED','Análise encerrada',$uid);NotificationWorkflowService::analysisEvent($pdo,$id,'ANALYSIS_COMPLETED','Análise encerrada',$uid);Auth::registerAudit('ANALYSIS_COMPLETED','qc_notification_analyses',$id,['status'=>$a['status']],['status'=>'COMPLETED','conclusion_text'=>$conclusion]);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public static function removeItem(int $analysisId,int $notificationId):void
    {NotificationWorkflowService::requirePermission('notifications.analyze');$pdo=Database::connection();$pdo->beginTransaction();try{$a=self::accessible($pdo,$analysisId,true);if($a['status']!=='IN_ANALYSIS'&&!Permission::can('notifications.manage'))throw new DomainException('Ocorrências só podem ser removidas durante a elaboração.');$uid=(int)(Auth::user()['id']??0);$q=$pdo->prepare('UPDATE qc_notification_analysis_items SET removed_at=NOW(),removed_by=:user WHERE analysis_id=:analysis AND notification_id=:notification AND removed_at IS NULL');$q->execute(['user'=>$uid,'analysis'=>$analysisId,'notification'=>$notificationId]);if(!$q->rowCount())throw new DomainException('Ocorrência não encontrada nesta análise.');$pdo->prepare("UPDATE qc_notifications SET status='ACKNOWLEDGED' WHERE id=:id")->execute(['id'=>$notificationId]);NotificationWorkflowService::notificationEvent($pdo,$notificationId,'NOTIFICATION_REMOVED_FROM_ANALYSIS','Removida da análise '.$a['analysis_code'],$uid);NotificationWorkflowService::analysisEvent($pdo,$analysisId,'NOTIFICATION_REMOVED_FROM_ANALYSIS','Uma ocorrência foi removida',$uid,['notification_id'=>$notificationId]);Auth::registerAudit('NOTIFICATION_REMOVED_FROM_ANALYSIS','qc_notifications',$notificationId,['analysis_id'=>$analysisId],null);$pdo->commit();}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public static function addItems(int $analysisId,array $ids):int
    {NotificationWorkflowService::requirePermission('notifications.analyze');$ids=array_values(array_unique(array_filter(array_map('intval',$ids))));if(!$ids)throw new DomainException('Selecione ao menos uma ocorrência.');$pdo=Database::connection();$pdo->beginTransaction();try{$a=self::accessible($pdo,$analysisId,true);if($a['status']!=='IN_ANALYSIS')throw new DomainException('Ocorrências só podem ser adicionadas durante a elaboração.');[$scope,$params]=QcNotificationService::scopeSql('n');$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT n.* FROM qc_notifications n WHERE n.id IN ($marks) AND {$scope} ORDER BY n.id FOR UPDATE");$q->execute(array_merge($ids,array_values($params)));$rows=$q->fetchAll(PDO::FETCH_ASSOC);if(count($rows)!==count($ids))throw new DomainException('Uma ou mais ocorrências não estão disponíveis.');self::assertCompatible($rows,['origin_unit_id'=>$a['unit_id'],'blood_component_id'=>$a['blood_component_id']]);$uid=(int)(Auth::user()['id']??0);$insert=$pdo->prepare('INSERT INTO qc_notification_analysis_items(analysis_id,notification_id,added_by) VALUES(:analysis,:notification,:user)');foreach($rows as$row){if($row['status']!=='ACKNOWLEDGED')throw new DomainException('Use somente ocorrências com ciência registrada e aguardando análise.');$busy=$pdo->prepare("SELECT 1 FROM qc_notification_analysis_items i JOIN qc_notification_analyses x ON x.id=i.analysis_id WHERE i.notification_id=:id AND i.removed_at IS NULL AND x.status<>'COMPLETED' LIMIT 1");$busy->execute(['id'=>$row['id']]);if($busy->fetchColumn())throw new DomainException('Uma ocorrência já participa de outra análise ativa.');$insert->execute(['analysis'=>$analysisId,'notification'=>$row['id'],'user'=>$uid]);$pdo->prepare("UPDATE qc_notifications SET status='IN_ANALYSIS' WHERE id=:id")->execute(['id'=>$row['id']]);self::notificationItemEvent($pdo,(int)$row['id'],$analysisId,$a['analysis_code'],$uid);}$pdo->prepare('UPDATE qc_notification_analyses SET test_id=NULL,updated_by=:user WHERE id=:id AND test_id IS NOT NULL AND EXISTS (SELECT 1 FROM qc_notification_analysis_items i JOIN qc_notifications n ON n.id=i.notification_id WHERE i.analysis_id=:analysis AND i.removed_at IS NULL AND n.test_id<>qc_notification_analyses.test_id)')->execute(['user'=>$uid,'id'=>$analysisId,'analysis'=>$analysisId]);NotificationWorkflowService::analysisEvent($pdo,$analysisId,'NOTIFICATIONS_ADDED','Foram adicionadas '.count($rows).' ocorrência(s)',$uid);$pdo->commit();return count($rows);}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    private static function assertCompatible(array $rows,array $reference):void
    { $differentOrigin=false;$differentComponent=false;foreach($rows as$row){$differentOrigin=$differentOrigin||(int)$row['origin_unit_id']!==(int)$reference['origin_unit_id'];$differentComponent=$differentComponent||(int)$row['blood_component_id']!==(int)$reference['blood_component_id'];}if($differentOrigin&&$differentComponent)throw new DomainException('As ocorrências selecionadas devem pertencer à mesma origem/processamento e ao mesmo hemocomponente.');if($differentOrigin)throw new DomainException('As ocorrências selecionadas devem pertencer à mesma origem/processamento.');if($differentComponent)throw new DomainException('As ocorrências selecionadas devem pertencer ao mesmo hemocomponente.');}
    public static function accessible(PDO $pdo,int $id,bool $lock=false):array{[$scope,$params]=QcNotificationService::analysisScopeSql('a');$q=$pdo->prepare("SELECT a.*,(SELECT u.name FROM users u WHERE u.id=a.completed_by) completed_by_name FROM qc_notification_analyses a WHERE a.id=:id AND {$scope}".($lock?' FOR UPDATE':''));$q->execute(['id'=>$id]+$params);$a=$q->fetch(PDO::FETCH_ASSOC);if(!$a)throw new DomainException('Análise não encontrada ou fora do seu escopo.');return$a;}
    private static function eventsForItems(PDO $pdo,int$id,string$type,string$description,int$uid):void{$q=$pdo->prepare('SELECT notification_id FROM qc_notification_analysis_items WHERE analysis_id=:id AND removed_at IS NULL');$q->execute(['id'=>$id]);foreach($q->fetchAll(PDO::FETCH_COLUMN)as$n)NotificationWorkflowService::notificationEvent($pdo,(int)$n,$type,$description,$uid,['analysis_id'=>$id]);}
}
