<?php
declare(strict_types=1);
namespace BloodHub\Services;

use BloodHub\Core\{Auth,Database};
use DomainException;
use PDO;

final class PlateletResultService
{
    public const COMPONENT_CODES=['CP','CPAF'];

    public static function supports(string $componentCode):bool
    {
        return in_array($componentCode,self::COMPONENT_CODES,true);
    }

    public static function save(int $sampleId,array $input):array
    {
        $sample=self::sample($sampleId);if(!$sample||!self::supports((string)$sample['component_code']))throw new DomainException('Os resultados informados não pertencem a uma amostra de concentrado de plaquetas.');
        $gross=PlateletResultCalculator::decimal($input['gross_weight']??null);$existing=self::weight($sampleId);
        if($gross!==null){if(!$sample['bag_brand_id'])throw new DomainException('A amostra não possui referência de bolsa para resolver a tara.');$tare=BagTareResolver::resolve((int)$sample['bag_brand_id'],(int)$sample['blood_component_id']);$calc=PlateletResultCalculator::calculate(['gross_weight'=>$gross,'tare_weight'=>$tare['tare_weight']??null,'density'=>$sample['density']]);self::saveWeight($sample,$gross,$tare,$calc['volume_ml']);$existing=self::weight($sampleId);TestResultService::saveNumeric($sampleId,TestResultService::CODES['volume'],$calc['volume_ml']);}
        $pm=trim((string)($input['platelet_method']??''));$lm=trim((string)($input['leukocyte_method']??''));if($pm!==''&&!in_array($pm,PlateletResultCalculator::PLATELET_METHODS,true))throw new DomainException('Método de plaquetas inválido ou sem fórmula configurada.');if($lm!==''&&!in_array($lm,PlateletResultCalculator::LEUKOCYTE_METHODS,true))throw new DomainException('Método de leucócitos inválido.');
        $pr=PlateletResultCalculator::decimal($input['platelet_count']??null);$lr=PlateletResultCalculator::decimal($input['leukocyte_count']??null);$calc=PlateletResultCalculator::calculate(['volume_ml'=>$existing['volume_ml']??null,'platelet_method'=>$pm,'platelet_count'=>$pr,'leukocyte_method'=>$lm,'leukocyte_count'=>$lr]);
        if($pr!==null){$r=TestResultService::saveNumeric($sampleId,TestResultService::CODES['platelet_count'],$pr);self::saveMethod((int)$r['id'],'PLATELET_METHOD','Método Plaquetas',$pm);TestResultService::saveNumeric($sampleId,TestResultService::CODES['platelets_per_unit'],$calc['platelet_count_per_unit']);}elseif($pm!=='')self::savePendingMethod($sampleId,TestResultService::CODES['platelet_count'],'PLATELET_METHOD','Método Plaquetas',$pm);
        if($lr!==null){$r=TestResultService::saveNumeric($sampleId,TestResultService::CODES['leukocyte_count'],$lr);self::saveMethod((int)$r['id'],'LEUKOCYTE_METHOD','Método Leucócitos',$lm);TestResultService::saveNumeric($sampleId,TestResultService::CODES['leukocytes_per_unit'],$calc['leukocyte_count_per_unit']);}elseif($lm!=='')self::savePendingMethod($sampleId,TestResultService::CODES['leukocyte_count'],'LEUKOCYTE_METHOD','Método Leucócitos',$lm);
        $ph=PlateletResultCalculator::decimal($input['ph']??null);if($ph!==null)TestResultService::saveNumeric($sampleId,TestResultService::CODES['ph'],$ph);$sw=trim((string)($input['swirling']??''));if($sw!==''){if(!in_array($sw,['Presente','Ausente'],true))throw new DomainException('Selecione um valor válido para Swirling.');TestResultService::saveText($sampleId,TestResultService::CODES['swirling'],$sw);}
        $classification=$sample['component_code']==='CPAF'?CpafYieldClassificationService::recalculate($sampleId):null;
        Auth::registerAudit('quality_platelet_results.save','samples',$sampleId,null,['gross_weight'=>$gross,'tare_weight_used'=>$existing['tare_weight_used']??null,'density_used'=>$existing['density_used']??null,'volume_ml'=>$existing['volume_ml']??null,'platelet_method'=>$pm?:null,'platelet_count'=>$pr,'platelets_per_unit'=>$calc['platelet_count_per_unit'],'classification'=>$classification,'leukocyte_method'=>$lm?:null,'leukocyte_count'=>$lr,'leukocytes_per_unit'=>$calc['leukocyte_count_per_unit'],'ph'=>$ph,'swirling'=>$sw?:null]);return $calc+['classification'=>$classification];
    }

    public static function state(int $sampleId):array
    {
        $q=Database::connection()->prepare("SELECT t.code,tr.id result_id,tr.result_value_numeric,tr.result_value_text FROM sample_tests st JOIN tests t ON t.id=st.test_id LEFT JOIN test_results tr ON tr.sample_test_id=st.id WHERE st.sample_id=:id AND t.code IN ('VOLUME','PLATELET_COUNT','PLATELETS_PER_UNIT','LEUKOCYTE_COUNT','LEUKOCYTES_PER_UNIT','PH','SWIRLING')");$q->execute(['id'=>$sampleId]);$state=['platelet_method'=>null,'platelet_count'=>null,'platelets_per_unit'=>null,'leukocyte_method'=>null,'leukocyte_count'=>null,'leukocytes_per_unit'=>null,'ph'=>null,'swirling'=>null];
        foreach($q->fetchAll(PDO::FETCH_ASSOC) as $row){$key=match($row['code']){'PLATELET_COUNT'=>'platelet_count','PLATELETS_PER_UNIT'=>'platelets_per_unit','LEUKOCYTE_COUNT'=>'leukocyte_count','LEUKOCYTES_PER_UNIT'=>'leukocytes_per_unit','PH'=>'ph','SWIRLING'=>'swirling',default=>null};if($key)$state[$key]=$row['code']==='SWIRLING'?$row['result_value_text']:$row['result_value_numeric'];if($row['result_id']){$p=Database::connection()->prepare("SELECT parameter_code,text_value FROM test_result_parameters WHERE test_result_id=:id AND parameter_code IN ('PLATELET_METHOD','LEUKOCYTE_METHOD')");$p->execute(['id'=>$row['result_id']]);foreach($p->fetchAll(PDO::FETCH_ASSOC) as $v)$state[$v['parameter_code']==='PLATELET_METHOD'?'platelet_method':'leukocyte_method']=$v['text_value'];}}return $state;
    }

    public static function recalculate(int $sampleId):void
    {$sample=self::sample($sampleId);if(!$sample||!self::supports((string)$sample['component_code']))return;$s=self::state($sampleId);$w=self::weight($sampleId);if(!$w)return;$c=PlateletResultCalculator::calculate(['volume_ml'=>$w['volume_ml'],'platelet_method'=>$s['platelet_method'],'platelet_count'=>$s['platelet_count'],'leukocyte_method'=>$s['leukocyte_method'],'leukocyte_count'=>$s['leukocyte_count']]);TestResultService::saveNumeric($sampleId,TestResultService::CODES['volume'],$w['volume_ml']);if($c['platelet_count_per_unit']!==null)TestResultService::saveNumeric($sampleId,TestResultService::CODES['platelets_per_unit'],$c['platelet_count_per_unit']);if($c['leukocyte_count_per_unit']!==null)TestResultService::saveNumeric($sampleId,TestResultService::CODES['leukocytes_per_unit'],$c['leukocyte_count_per_unit']);if($sample['component_code']==='CPAF')CpafYieldClassificationService::recalculate($sampleId);}
    private static function sample(int $id):?array{$q=Database::connection()->prepare('SELECT s.*,bc.code component_code,bc.density FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id WHERE s.id=:id');$q->execute(['id'=>$id]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
    private static function weight(int $id):?array{$q=Database::connection()->prepare('SELECT * FROM sample_weight_results WHERE sample_id=:id');$q->execute(['id'=>$id]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
    private static function saveWeight(array $sample,float $gross,?array $tare,float $volume):void
    {if(!$tare)throw new DomainException(BagTareResolver::NOT_CONFIGURED);$pdo=Database::connection();$before=self::weight((int)$sample['id']);$net=$gross-(float)$tare['tare_weight'];$after=['gross_weight'=>$gross,'bag_brand_tare_id'=>$tare['tare_id'],'tare_weight_used'=>$tare['tare_weight'],'net_weight'=>$net,'density_used'=>$sample['density'],'volume_ml'=>$volume];$pdo->prepare('INSERT INTO sample_weight_results(sample_id,gross_weight,bag_brand_tare_id,tare_weight_used,net_weight,density_used,volume_ml,recorded_by) VALUES(:sample,:gross,:tare_id,:tare,:net,:density,:volume,:user) ON DUPLICATE KEY UPDATE gross_weight=VALUES(gross_weight),bag_brand_tare_id=VALUES(bag_brand_tare_id),tare_weight_used=VALUES(tare_weight_used),net_weight=VALUES(net_weight),density_used=VALUES(density_used),volume_ml=VALUES(volume_ml),recorded_by=VALUES(recorded_by),recorded_at=NOW()')->execute(['sample'=>$sample['id'],'gross'=>$gross,'tare_id'=>$tare['tare_id'],'tare'=>$tare['tare_weight'],'net'=>$net,'density'=>$sample['density'],'volume'=>$volume,'user'=>Auth::user()['id']??null]);$pdo->prepare('UPDATE bag_brand_tares SET locked_at=COALESCE(locked_at,NOW()) WHERE id=:id')->execute(['id'=>$tare['tare_id']]);Auth::registerAudit('quality_weight.save','samples',(int)$sample['id'],$before?:null,$after);}
    private static function savePendingMethod(int $sampleId,string $testCode,string $pc,string $pn,string $method):void
    {$test=TestResultService::configuredTest($sampleId,$testCode);if(!$test)return;$pdo=Database::connection();$q=$pdo->prepare('SELECT id FROM sample_tests WHERE sample_id=:sample AND test_id=:test');$q->execute(['sample'=>$sampleId,'test'=>$test['id']]);$st=(int)$q->fetchColumn();if(!$st){$pdo->prepare("INSERT INTO sample_tests(sample_id,test_id,status,started_at,executed_by) VALUES(:sample,:test,'in_progress',NOW(),:user)")->execute(['sample'=>$sampleId,'test'=>$test['id'],'user'=>Auth::user()['id']??null]);$st=(int)$pdo->lastInsertId();}$q=$pdo->prepare('SELECT id FROM test_results WHERE sample_test_id=:id ORDER BY id DESC LIMIT 1');$q->execute(['id'=>$st]);$r=(int)$q->fetchColumn();if(!$r){$pdo->prepare('INSERT INTO test_results(sample_test_id,recorded_by) VALUES(:id,:user)')->execute(['id'=>$st,'user'=>Auth::user()['id']??null]);$r=(int)$pdo->lastInsertId();}self::saveMethod($r,$pc,$pn,$method);TestResultService::refreshSampleStatus($sampleId);}
    private static function saveMethod(int $resultId,string $code,string $name,string $method):void{Database::connection()->prepare('INSERT INTO test_result_parameters(test_result_id,parameter_code,parameter_name,text_value) VALUES(:result,:code,:name,:value) ON DUPLICATE KEY UPDATE parameter_name=VALUES(parameter_name),text_value=VALUES(text_value),numeric_value=NULL')->execute(['result'=>$resultId,'code'=>$code,'name'=>$name,'value'=>$method]);}
}
