<?php
declare(strict_types=1);
namespace BloodHub\Services;
use BloodHub\Core\{Auth,Database};
use PDO;
final class ValidationResultService
{
 public static function saveBatch(int $validationId,array $rows):array{$saved=0;$errors=[];$pdo=Database::connection();foreach($rows as$id=>$values){$sample=self::sample((int)$id,$validationId);if(!$sample){$errors[]='Amostra #'.(int)$id.' indisponível.';continue;}if($sample['status']==='completed')continue;try{$pdo->beginTransaction();LaboratoryResultService::save($sample,(array)$values,'validation');$pdo->commit();$saved++;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$errors[]=($sample['donation_number']?:('#'.$id)).' — '.$e->getMessage();}}Auth::registerAudit('VALIDATION_RESULTS_BATCH_SAVE','validations',$validationId,null,['saved'=>$saved,'failed'=>count($errors)]);return[$saved,$errors];}
 public static function completeEligible(int $validationId,array $ids,bool $ack):array{$done=0;$pending=[];$errors=[];$pdo=Database::connection();foreach(array_unique(array_map('intval',$ids))as$id){$sample=self::sample($id,$validationId);if(!$sample||$sample['status']==='completed')continue;try{$pdo->beginTransaction();HemolysisResultService::synchronizeStage($id);CalculatedTestService::recalculateHemolysis($id);SpecificationEvaluator::evaluateSampleResults($id);$outside=self::nonconforming($id,$validationId);if($outside&&!$ack){$pdo->commit();$pending[]=['sample'=>$sample['donation_number']?:('#'.$id),'missing'=>['Ciência dos resultados fora da especificação']];continue;}$missing=self::missing($sample);if($missing){$pdo->commit();$pending[]=['sample'=>$sample['donation_number']?:('#'.$id),'missing'=>$missing];continue;}$pdo->prepare("UPDATE samples SET status='completed' WHERE id=:id AND purpose='validation'")->execute(['id'=>$id]);if($outside)SpecificationEvaluator::acknowledge($id,(int)(Auth::user()['id']??0));Auth::registerAudit('VALIDATION_SAMPLE_COMPLETED','samples',$id,null,['status'=>'completed','nonconforming_count'=>count($outside)]);$pdo->commit();$done++;}catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$errors[]=($sample['donation_number']?:('#'.$id)).' — '.$e->getMessage();}}return[$done,$pending,$errors];}
 public static function missing(array $sample):array{$pdo=Database::connection();$q=$pdo->prepare("SELECT t.code,t.name FROM validation_tests vt JOIN tests t ON t.id=vt.test_id LEFT JOIN sample_tests st ON st.sample_id=:sample AND st.test_id=t.id LEFT JOIN test_results tr ON tr.sample_test_id=st.id WHERE vt.validation_id=:validation AND vt.blood_component_id=:component AND vt.is_required=1 AND vt.status='active' AND (vt.phase_id=:phase OR vt.phase_id IS NULL) AND (tr.id IS NULL OR (tr.result_value_numeric IS NULL AND NULLIF(TRIM(tr.result_value_text),'') IS NULL)) ORDER BY t.name");$q->execute(['sample'=>$sample['id'],'validation'=>$sample['validation_id'],'component'=>$sample['blood_component_id'],'phase'=>$sample['validation_phase_id']]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);$missing=array_column($rows,'name');$deps=LaboratoryDependencyResolver::resolve(array_column($rows,'code'));$state=self::state((int)$sample['id']);$labels=['gross_weight'=>'Peso bruto','hemoglobin'=>'Hemoglobina','hematocrit'=>'Hematócrito','platelet_count'=>'Nº Plaquetas','platelet_method'=>'Método Plaquetas','leukocyte_count'=>'Nº Leucócitos','leukocyte_method'=>'Método Leucócitos','red_cell_count'=>'Nº Hemácias','red_cell_method'=>'Método Hemácias','dilution'=>'Diluição','fibrinogen_mg_dl'=>'Fibrinogênio (mg/dL)','abs_370'=>'Abs 370','abs_415'=>'Abs 415','abs_510'=>'Abs 510','abs_577'=>'Abs 577','abs_600'=>'Abs 600'];foreach($deps as$field)if(isset($labels[$field])&&($state[$field]??null)===null)$missing[]=$labels[$field];return array_values(array_unique($missing));}
 public static function nonconforming(int$id,int$validationId):array{$q=Database::connection()->prepare("SELECT e.*,t.name test_name,COALESCE(CAST(tr.result_value_numeric AS CHAR),tr.result_value_text) result_display,e.specification_snapshot_text reference_display FROM test_result_spec_evaluations e JOIN test_results tr ON tr.id=e.test_result_id JOIN sample_tests st ON st.id=tr.sample_test_id JOIN validation_tests vt ON vt.test_id=st.test_id AND vt.validation_id=:validation AND vt.status='active' JOIN tests t ON t.id=st.test_id WHERE st.sample_id=:sample AND e.conformity_status='NONCONFORMING'");$q->execute(['sample'=>$id,'validation'=>$validationId]);return$q->fetchAll(PDO::FETCH_ASSOC);}
 public static function state(int$id):array{$pdo=Database::connection();$q=$pdo->prepare("SELECT bc.code component_code,wr.*,MAX(CASE WHEN t.code='HEMATOCRIT' THEN tr.result_value_numeric END) hematocrit,MAX(CASE WHEN t.code='HEMOGLOBIN' THEN tr.result_value_numeric END) hemoglobin,MAX(CASE WHEN t.code='HEMOGLOBIN_PER_UNIT' THEN tr.result_value_numeric END) hemoglobin_per_unit,MAX(CASE WHEN t.code='HEMOLYSIS_DEGREE' THEN tr.result_value_numeric END) hemolysis_degree,MAX(CASE WHEN t.code='BACTERIOLOGY' THEN tr.result_value_text END) bacteriology,MAX(CASE WHEN t.code='FACTOR_VIII' THEN tr.result_value_numeric END) factor_viii FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN sample_weight_results wr ON wr.sample_id=s.id LEFT JOIN sample_tests st ON st.sample_id=s.id LEFT JOIN tests t ON t.id=st.test_id LEFT JOIN test_results tr ON tr.sample_test_id=st.id WHERE s.id=:id GROUP BY s.id");$q->execute(['id'=>$id]);$state=$q->fetch(PDO::FETCH_ASSOC)?:[];$code=$state['component_code']??'';if(PlateletResultService::supports($code))$state=array_replace($state,PlateletResultService::state($id));if(in_array($code,['PF','PF24'],true))$state=array_replace($state,FreshPlasmaResultService::state($id));if($code==='CRIO')$state=array_replace($state,CryoprecipitateResultService::state($id));if(WashedRedCellResultService::supports($code))$state=array_replace($state,WashedRedCellResultService::state($id));$hem=HemolysisResultService::state($id);$state['free_hemoglobin']=$hem['free_hemoglobin_g_dl'];foreach($hem['parameters']as$k=>$v)$state[$k]=$v;return$state;}
 private static function sample(int$id,int$v):?array{$q=Database::connection()->prepare("SELECT s.*,bc.code component_code,bc.name component_name FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id JOIN validations v ON v.id=s.validation_id WHERE s.id=:id AND s.validation_id=:validation AND s.purpose='validation' AND s.status IN('received','in_analysis','partial_results','completed') AND v.status NOT IN('completed','cancelled')");$q->execute(['id'=>$id,'validation'=>$v]);return$q->fetch(PDO::FETCH_ASSOC)?:null;}
}
