<?php require dirname(__DIR__,2).'/layouts/admin_start.php'; $editing=!empty($user['id']); $h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<section class="content-card form-card"><div class="section-heading"><div><h2><?=$editing?'Editar usuário':'Cadastrar usuário'?></h2><p>Campos marcados com * são obrigatórios.</p></div><a class="button button-secondary" href="/admin/users">Voltar</a></div>
<?php if($errors):?><div class="alert alert-error"><ul><?php foreach($errors as$error):?><li><?=$h($error)?></li><?php endforeach?></ul></div><?php endif?>
<form class="admin-form" method="post" action="<?=$editing?'/admin/users/edit?id='.(int)$user['id']:'/admin/users/create'?>"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><div class="form-grid">
<label><span>Nome *</span><input name="name" required value="<?=$h($user['name']??'')?>"></label><label><span>E-mail *</span><input type="email" name="email" required value="<?=$h($user['email']??'')?>"></label>
<label><span>Nome para assinatura/liberação</span><input name="professional_name" placeholder="Ex.: Cristiano B. Costa" value="<?=$h($user['professional_name']??'')?>"><small class="field-help">Nome que será registrado no laudo no momento da liberação.</small></label><label><span>Conselho profissional</span><input name="professional_council" placeholder="Ex.: CRBio" value="<?=$h($user['professional_council']??'')?>"></label><label><span>Número do registro</span><input name="professional_registration" value="<?=$h($user['professional_registration']??'')?>"></label>
<label><span>Perfil *</span><select name="role_id" required><option value="">Selecione</option><?php foreach($roles as$role):?><option value="<?=(int)$role['id']?>" <?=(string)($user['role_id']??'')===(string)$role['id']?'selected':''?>><?=$h($role['name'])?></option><?php endforeach?></select></label><label><span>Status *</span><select name="status"><?php foreach(['active'=>'Ativo','inactive'=>'Inativo','blocked'=>'Bloqueado']as$value=>$label):?><option value="<?=$value?>" <?=($user['status']??'active')===$value?'selected':''?>><?=$label?></option><?php endforeach?></select></label>
<label><span>Cliente</span><select name="client_id"><option value="">Sem cliente</option><?php foreach($clients as$client):?><option value="<?=(int)$client['id']?>" <?=(string)($user['client_id']??'')===(string)$client['id']?'selected':''?>><?=$h($client['name'])?></option><?php endforeach?></select></label><label><span>Unidade principal</span><select name="primary_unit_id"><option value="">Sem unidade</option><?php foreach($units as$unit):?><option value="<?=(int)$unit['id']?>" <?=(string)($user['primary_unit_id']??'')===(string)$unit['id']?'selected':''?>><?=$h($unit['name'])?></option><?php endforeach?></select></label>
<label class="span-2"><span>Unidades autorizadas</span><select name="unit_ids[]" multiple size="7"><?php foreach($units as$unit):?><option value="<?=(int)$unit['id']?>" <?=in_array((int)$unit['id'],$selectedUnitIds,true)?'selected':''?>><?=$h($unit['name'])?></option><?php endforeach?></select><small class="field-help">Use Ctrl/Cmd para selecionar mais de uma. A unidade principal também será autorizada automaticamente.</small></label>
<label class="span-2"><span>Senha <?=$editing?'(deixe em branco para manter)':'*'?></span><input type="password" name="password" <?=$editing?'':'required'?> minlength="8" autocomplete="new-password"></label></div><div class="form-actions"><button class="button" type="submit">Salvar Usuário</button></div></form></section><?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
