<?php require dirname(__DIR__).'/layouts/admin_start.php';$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$csrf=\BloodHub\Core\Csrf::token();$query=$_GET; ?><link rel="stylesheet" href="/assets/css/notifications.css">
<nav class="nc-module-nav"><a class="active" href="/notifications">Notificações</a><a href="/notifications/analyses">Análises</a></nav>
<section class="notification-metrics">
 <?php foreach([['status'=>'PENDING_ACKNOWLEDGEMENT','value'=>$counts['PENDING_ACKNOWLEDGEMENT'],'label'=>'Pendentes de ciência'],['status'=>'AWAITING_ANALYSIS','value'=>$counts['AWAITING_ANALYSIS'],'label'=>'Aguardando análise'],['status'=>'IN_FOLLOW_UP','value'=>$counts['IN_FOLLOW_UP'],'label'=>'Em acompanhamento'],['status'=>'COMPLETED','value'=>$counts['COMPLETED']+$counts['CLOSED'],'label'=>'Concluídas']]as$m):$query['status']=$m['status'];$query['tab']='all';?><a href="?<?= $h(http_build_query($query)) ?>"><strong><?= $m['value'] ?></strong><span><?= $m['label'] ?></span></a><?php endforeach; ?>
</section>
<nav class="notification-tabs"><?php foreach(['pending'=>'Pendentes','tracking'=>'Em acompanhamento','closed'=>'Concluídas','all'=>'Todas']as$key=>$label):$q=$_GET;$q['tab']=$key;unset($q['status']);?><a class="<?= ($_GET['tab']??'pending')===$key?'active':'' ?>" href="?<?= $h(http_build_query($q)) ?>"><?= $label ?></a><?php endforeach;?></nav>
<form class="card notification-filters" method="get"><input type="hidden" name="tab" value="<?= $h($_GET['tab']??'pending') ?>"><label>De<input type="date" name="from" value="<?= $h($_GET['from']??'') ?>"></label><label>Até<input type="date" name="to" value="<?= $h($_GET['to']??'') ?>"></label><?php if($canViewAll):?><label>Origem<select name="unit"><option value="">Todas</option><?php foreach($units as$u):?><option value="<?= $u['id'] ?>" <?= (string)$u['id']===($_GET['unit']??'')?'selected':'' ?>><?= $h($u['name']) ?></option><?php endforeach;?></select></label><?php endif;?><label>Hemocomponente<select name="component"><option value="">Todos</option><?php foreach($components as$c):?><option value="<?= $c['id'] ?>" <?= (string)$c['id']===($_GET['component']??'')?'selected':'' ?>><?= $h($c['name']) ?></option><?php endforeach;?></select></label><label>Teste<select name="test"><option value="">Todos</option><?php foreach($tests as$t):?><option value="<?= $t['id'] ?>" <?= (string)$t['id']===($_GET['test']??'')?'selected':'' ?>><?= $h($t['name']) ?></option><?php endforeach;?></select></label><label>Doação<input name="donation" value="<?= $h($_GET['donation']??'') ?>"></label><label>Código LCQH<input name="lcqh" value="<?= $h($_GET['lcqh']??'') ?>"></label><label>Notificação<input name="code" value="<?= $h($_GET['code']??'') ?>"></label><label>Status<select name="status"><option value="">Todos</option><?php foreach($labels as$k=>$v):?><option value="<?= $h($k) ?>" <?= $k===($_GET['status']??'')?'selected':'' ?>><?= $h($v) ?></option><?php endforeach;?></select></label><button class="button button-primary">Filtrar</button><a class="button button-light" href="/notifications?tab=<?= $h($_GET['tab']??'pending') ?>">Limpar</a></form>
<form id="notification-selection" method="post"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>">
 <div class="notification-bulk"><label class="select-all"><input type="checkbox" id="select-all"> Selecionar todas da listagem atual</label><span id="selected-count">0 selecionadas</span><?php if($canAcknowledge):?><button class="button button-light" type="button" data-bulk-ack disabled>Registrar ciência nas selecionadas</button><?php endif;?><?php if($canAnalyze):?><button class="button button-primary" type="button" data-create-analysis disabled>Criar análise</button><?php endif;?></div>
 <section class="notification-list"><?php if(!$notifications):?><div class="card empty-state"><strong>Nenhuma ocorrência encontrada</strong><span>Ajuste os filtros ou consulte outra etapa do fluxo.</span></div><?php endif;?>
 <?php foreach($notifications as$n):$eligible=($canAcknowledge&&$n['status']==='PENDING_ACKNOWLEDGEMENT')||($canAnalyze&&$n['status']==='ACKNOWLEDGED');?>
 <article class="card notification-card" data-status="<?= $h($n['status']) ?>"><div class="notification-select"><?php if($eligible):?><input class="notification-checkbox" type="checkbox" name="ids[]" value="<?= $n['id'] ?>" data-status="<?= $h($n['status']) ?>" data-origin-id="<?= $h($n['origin_unit_id']) ?>" data-origin="<?= $h($n['origin_unit_name_snapshot']) ?>" data-component-id="<?= $h($n['blood_component_id']) ?>" data-component="<?= $h($n['component_name_snapshot']) ?>" data-test-id="<?= $h($n['test_id']) ?>" data-test="<?= $h($n['test_name_snapshot']) ?>" aria-label="Selecionar <?= $h($n['public_code']) ?>"><?php endif;?></div><header><div><strong><?= $h($n['public_code']) ?></strong><small><?= date('d/m/Y H:i',strtotime($n['occurred_at'])) ?> · <?= $h($n['origin_unit_name_snapshot']) ?></small></div><span class="notification-status status-<?= strtolower($h($n['status'])) ?>"><?= $h($labels[$n['status']]??$n['status']) ?></span></header>
 <div class="notification-grid"><span><small>Doação / LCQH</small><?= $h(($n['donation_number_snapshot']?:'—').' · '.($n['lcqh_code_snapshot']?:'—')) ?></span><span><small>Hemocomponente</small><?= $h($n['component_name_snapshot']) ?></span><span><small>Teste</small><?= $h($n['test_name_snapshot']) ?></span><span class="notification-result"><small>Resultado</small><?= $h($n['result_display_snapshot']) ?><em>Fora da especificação</em></span><span><small>Referência</small><?= $h($n['reference_display_snapshot']?:'—') ?></span></div>
 <details><summary>Ver detalhes</summary><div class="notification-details"><div class="detail-columns"><section><h4>Identificação</h4><p><b>Notificação:</b> <?= $h($n['public_code']) ?></p><p><b>Origem:</b> <?= $h($n['origin_unit_name_snapshot']) ?></p><p><b>Cliente:</b> <?= $h($n['client_name_snapshot']?:'—') ?></p><p><b>Doação / LCQH:</b> <?= $h(($n['donation_number_snapshot']?:'—').' / '.($n['lcqh_code_snapshot']?:'—')) ?></p><p><b>Conclusão:</b> <?= date('d/m/Y H:i',strtotime($n['occurred_at'])) ?></p></section><section><h4>Resultado e especificação</h4><p><b>Teste:</b> <?= $h($n['test_name_snapshot']) ?></p><p><b>Resultado:</b> <?= $h($n['result_display_snapshot']) ?></p><p><b>Regra:</b> <?= $h($n['rule_snapshot']?:'—') ?></p><p><b>Versão:</b> <?= $h($n['specification_version_snapshot']?:'—') ?> · <b>Vigência:</b> <?= $n['specification_effective_from_snapshot']?date('d/m/Y',strtotime($n['specification_effective_from_snapshot'])):'—' ?></p></section></div><?php if($n['analysis_id']):?><a class="analysis-link" href="/notifications/analyses/view?id=<?= $n['analysis_id'] ?>">Esta ocorrência faz parte da análise <strong><?= $h($n['analysis_code']) ?></strong> →</a><?php endif;?><ol class="timeline"><li><b>Resultado concluído</b><time><?= date('d/m/Y H:i',strtotime($n['occurred_at'])) ?></time></li><li><b>Notificação criada</b><time><?= date('d/m/Y H:i',strtotime($n['created_at'])) ?></time></li><li><b><?= $n['email_status']==='SENT'?'E-mail enviado':($n['email_status']==='FAILED'?'Falha no envio':'Envio pendente') ?></b></li><?php foreach($events[$n['id']]??[]as$e):?><li><b><?= $h($e['description']) ?></b><span><?= $h($e['user_name']?:'Sistema') ?></span><time><?= date('d/m/Y H:i',strtotime($e['created_at'])) ?></time></li><?php endforeach;?></ol><div class="detail-actions"><?php if($canAcknowledge&&$n['status']==='PENDING_ACKNOWLEDGEMENT'):?><button class="button button-primary" type="button" data-ack='<?= $h(json_encode(['id'=>$n['id'],'code'=>$n['public_code'],'donation'=>$n['donation_number_snapshot'],'component'=>$n['component_name_snapshot'],'test'=>$n['test_name_snapshot'],'result'=>$n['result_display_snapshot'],'reference'=>$n['reference_display_snapshot'],'date'=>date('d/m/Y H:i',strtotime($n['occurred_at'])),'origin'=>$n['origin_unit_name_snapshot']],JSON_UNESCAPED_UNICODE)) ?>'>Registrar ciência</button><?php endif;?><?php if($canAnalyze&&$n['status']==='ACKNOWLEDGED'):?><button class="button button-primary single-analysis" type="submit" formaction="/notifications/analyses/create" name="ids[]" value="<?= $n['id'] ?>">Iniciar análise</button><?php endif;?></div></div></details></article><?php endforeach;?></section>
</form>
<dialog id="ack-dialog" class="nc-dialog"><form method="dialog"><button class="dialog-close" aria-label="Fechar">×</button><h3>Registrar ciência</h3><p id="ack-question">Confirme que tomou ciência deste resultado fora da especificação.</p><dl id="ack-summary"></dl><div class="dialog-actions"><button class="button button-light">Cancelar</button><button class="button button-primary" id="ack-confirm" type="button">Registrar ciência</button></div></form></dialog>
<dialog id="create-analysis-dialog" class="nc-dialog analysis-confirm-dialog"><form method="dialog"><button class="dialog-close" aria-label="Fechar">×</button><h3>Criar análise</h3><p>As ocorrências selecionadas serão reunidas em uma única análise.</p><p id="analysis-compatibility-error" class="analysis-confirm-error" role="alert" hidden></p><div id="analysis-confirm-content"><dl class="analysis-confirm-summary"><div><dt>Origem</dt><dd id="analysis-origin"></dd></div><div><dt>Hemocomponente</dt><dd id="analysis-component"></dd></div><div><dt>Ocorrências selecionadas</dt><dd id="analysis-count"></dd></div></dl><div class="analysis-confirm-tests"><strong>Testes envolvidos</strong><div id="analysis-tests" class="analysis-test-chips"></div></div><p class="analysis-confirm-help">Você poderá analisar os resultados em conjunto e definir um único plano de ação para estas ocorrências.</p></div><div class="dialog-actions"><button class="button button-light">Cancelar</button><button class="button button-primary" id="create-analysis-confirm" type="button">Criar análise</button></div></form></dialog>
<script src="/assets/js/notifications.js"></script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
