<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><title>Mapa de Pools — Fator VIII:C</title>
<style>
@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#17212b;font:11px Arial,sans-serif}.report-header{display:flex;align-items:center;gap:14mm;border-bottom:3px solid #7f1d35;padding-bottom:8px;margin-bottom:12px}.report-logo{display:block;width:5.2cm;height:auto;object-fit:contain;flex:0 0 auto}h1{flex:1;font-size:17px;letter-spacing:.06em;text-align:center;margin:0;padding-right:5.2cm}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-bottom:12px}.meta div{border:1px solid #d5dce5;border-radius:5px;padding:7px}.meta b{display:block;font-size:9px;text-transform:uppercase;color:#697586;margin-bottom:3px}table{width:100%;border-collapse:collapse;table-layout:fixed}.lcqh-column{width:6cm}th,td{border:1px solid #8993a1;padding:7px;text-align:center;vertical-align:middle}thead{display:table-header-group}thead th{height:32px;background:#edf0f4;font-size:9px;text-transform:uppercase}tbody tr{height:5cm;break-inside:avoid;page-break-inside:avoid}tbody td{height:5cm}.pool{font-weight:700;color:#7f1d35}.unit small{display:block;color:#687386;margin-top:2px}.report-footer{display:flex;justify-content:space-between;margin-top:12px;padding-top:7px;border-top:1px solid #ccd3dc;color:#5d6878}.page-number{min-width:28mm;text-align:center}.print{position:fixed;right:12px;top:12px}.print-pages{display:none}
body.preparing-print .print-pages{display:block;position:absolute;left:-10000px;top:0;width:273mm;visibility:hidden}.print-page{height:186mm;display:flex;flex-direction:column;overflow:hidden}.print-page>*{flex-shrink:0}.print-page .report-footer{margin-top:auto}.print-page table{flex:0 0 auto}
@media print{.print{display:none}body.print-ready .report-source{display:none}body.print-ready .print-pages{display:block}.print-page{break-after:page;page-break-after:always}.print-page:last-child{break-after:auto;page-break-after:auto}}
</style></head><body><button class="print" onclick="print()">Imprimir</button>
<main class="report-source"><header class="report-header"><img class="report-logo" src="/assets/images/bloodhub-logo-horizontal.png" alt="BloodHub"><h1>MAPA DE POOLS — FATOR VIII:C</h1></header>
<?php $componentNames=array_unique(array_column($pools,'component_code'));$originNames=array_unique(array_column($pools,'origin_name'));$dates=array_filter(array_column($pools,'created_at')); ?>
<section class="meta"><div><b>Período</b><?=isset($dates[0])?date('d/m/Y',strtotime(min($dates))).' a '.date('d/m/Y',strtotime(max($dates))):'—'?></div><div><b>Hemocomponente</b><?=htmlspecialchars(implode(', ',$componentNames)?:'—')?></div><div><b>Processamento / origem</b><?=htmlspecialchars(implode(', ',$originNames)?:'—')?></div><div><b>Data de geração do mapa</b><?=date('d/m/Y H:i')?></div></section>
<table><colgroup><col><col class="lcqh-column"><col><col><col><col></colgroup><thead><tr><th>Pool</th><th>Código LCQH</th><th>Unidade 1</th><th>Unidade 2</th><th>Unidade 3</th><th>Unidade 4</th></tr></thead><tbody>
<?php foreach($pools as $pool):?><tr><td class="pool"><?=htmlspecialchars($pool['code'])?></td><td></td><?php for($i=0;$i<4;$i++):$m=$pool['members'][$i]??null;?><td class="unit"><?=$m?htmlspecialchars($m['donation_number']?:'—'):''?><?php if($m&&!empty($m['lcqh_code'])):?><small><?=htmlspecialchars($m['lcqh_code'])?></small><?php endif;?></td><?php endfor;?></tr><?php endforeach;?>
</tbody></table><footer class="report-footer"><span>Gerado por: <?=htmlspecialchars(\BloodHub\Core\Auth::user()['name']??'—')?></span><span>Impresso em: <?=date('d/m/Y H:i:s')?></span></footer></main><div class="print-pages" aria-hidden="true"></div>
<script>
(()=>{const body=document.body,source=document.querySelector('.report-source'),pages=document.querySelector('.print-pages');
const newPage=first=>{const page=document.createElement('section');page.className='print-page';page.append(source.querySelector('.report-header').cloneNode(true));if(first)page.append(source.querySelector('.meta').cloneNode(true));const table=document.createElement('table');table.append(source.querySelector('colgroup').cloneNode(true),source.querySelector('thead').cloneNode(true),document.createElement('tbody'));page.append(table);const footer=source.querySelector('.report-footer').cloneNode(true),number=document.createElement('span');number.className='page-number';footer.insertBefore(number,footer.lastElementChild);page.append(footer);pages.append(page);return page};
const overflows=page=>page.scrollHeight>page.clientHeight+1;
const paginate=()=>{pages.replaceChildren();body.classList.add('preparing-print');let page=newPage(true);for(const row of source.querySelectorAll('tbody tr')){const copy=row.cloneNode(true);page.querySelector('tbody').append(copy);if(overflows(page)){copy.remove();page=newPage(false);page.querySelector('tbody').append(copy)}}const all=[...pages.querySelectorAll('.print-page')],total=all.length;all.forEach((item,index)=>item.querySelector('.page-number').textContent=`Página ${index+1} de ${total}`);body.classList.remove('preparing-print');body.classList.add('print-ready')};
addEventListener('beforeprint',paginate);addEventListener('afterprint',()=>{body.classList.remove('print-ready');pages.replaceChildren()});
})();
</script></body></html>
