<?php require dirname(__DIR__).'/layouts/admin_start.php';$mode=($_GET['mode']??'manual')==='import'?'import':'manual';$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$fmt=fn($v,$d=4)=>$v===null?'':number_format((float)$v,$d,',',''); ?>
<nav class="qc-flow-tabs"><a href="/quality-control">Hemocomponentes</a><a class="active" href="/quality-control/hemolysis">Grau de Hemólise <b class="qc-tab-badge"><?= (int)$queueCounts['hemolysis'] ?></b></a><a href="/quality-control/bacteriology">Bacteriológico <b class="qc-tab-badge"><?= (int)$queueCounts['bacteriology'] ?></b></a><?php if(\BloodHub\Core\Permission::can('quality_control.factor_viii_pool.view')):?><a href="/quality-control/factor-viii-pools">Fator VIII — Pools</a><?php endif;?></nav>
<div class="hemolysis-mode"><a class="<?= $mode==='manual'?'active':'' ?>" href="/quality-control/hemolysis?mode=manual">Inserção manual</a><a class="<?= $mode==='import'?'active':'' ?>" href="/quality-control/hemolysis?mode=import">Importar arquivo</a></div>
<?php if($mode==='manual'): ?>
<section class="content-card qc-filter-card"><form class="qc-filters" method="get"><input type="hidden" name="mode" value="manual"><label><span>Origem / unidade</span><select name="origin"><option value="">Todas</option><?php foreach($origins as $o):?><option value="<?= (int)$o['id'] ?>" <?= $filters['origin']==$o['id']?'selected':'' ?>><?= $e($o['name']) ?></option><?php endforeach;?></select></label><label><span>Hemocomponente</span><select name="component"><option value="">Todos</option><?php foreach($components as $c):?><option value="<?= (int)$c['id'] ?>" <?= $filters['component']==$c['id']?'selected':'' ?>><?= $e($c['code'].' — '.$c['name']) ?></option><?php endforeach;?></select></label><label><span>Recebimento</span><input type="date" name="received_date" value="<?= $e($filters['received_date']) ?>"></label><label><span>Nº da doação</span><input name="donation" value="<?= $e($filters['donation']) ?>"></label><label><span>Código LCQH</span><input name="lcqh" value="<?= $e($filters['lcqh']) ?>"></label><label><span>Status</span><select name="status"><option value="">Todos</option><option value="pending" <?= $filters['status']==='pending'?'selected':'' ?>>Pendente</option><option value="in_progress" <?= $filters['status']==='in_progress'?'selected':'' ?>>Parcial</option></select></label><div class="qc-filter-actions"><button class="button button-compact">Filtrar</button><a class="button button-secondary button-compact" href="/quality-control/hemolysis">Limpar</a></div></form></section>
<form method="post" action="/quality-control/hemolysis/save"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><div class="hemolysis-table-wrap"><table class="hemolysis-table"><thead><tr><th>LCQH / Doação</th><th>Componente</th><?php foreach(['370','415','510','577','600'] as $n):?><th>Abs <?= $n ?></th><?php endforeach;?><th>Hb Livre</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($samples as $s):$p=$s['snapshot']['parameters'];?><tr data-hemolysis-row><td><strong><?= $e($s['lcqh_code']?:'Sem LCQH') ?></strong><small><?= $e($s['donation_number']?:'—') ?> · <?= $e($s['origin_name']?:'Origem não informada') ?><br><?= $e($s['received_at']?:'') ?></small></td><td><span class="qc-code"><?= $e($s['component_code']) ?></span></td><?php foreach(['370','415','510','577','600'] as $n):$key='abs_'.$n;?><td><input class="abs-input" inputmode="decimal" name="samples[<?= (int)$s['id'] ?>][<?= $key ?>]" value="<?= $fmt($p[$key]??null) ?>" <?= !$canEdit?'disabled':'' ?>></td><?php endforeach;?><td><output data-free-hb><?= $s['snapshot']['free_hemoglobin_g_dl']!==null?$fmt($s['snapshot']['free_hemoglobin_g_dl'],6):'—' ?></output></td><td><span class="qc-status status-<?= $e($s['test_status']) ?>"><?= $e($s['hemolysis']['message']) ?></span></td><td><div class="hemolysis-actions"><?php if($canEdit):?><button class="button button-compact" name="sample_id" value="<?= (int)$s['id'] ?>">Salvar</button><?php endif;?><?php if($canComplete):?><button class="button button-secondary button-compact" formaction="/quality-control/hemolysis/complete" name="sample_id" value="<?= (int)$s['id'] ?>">Concluir</button><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div><?php if($samples&&$canEdit):?><div class="hemolysis-save-all"><button class="button">Salvar todos</button></div><?php endif;?><?php if(!$samples):?><div class="content-card qc-empty">Nenhuma amostra pendente aplicável ao Grau de Hemólise.</div><?php endif;?></form>
<?php else: ?>
<section class="content-card hemolysis-upload"><div><strong>Importar resultados do espectrofotômetro</strong><p>O cabeçalho será localizado automaticamente e nada será gravado antes da confirmação.</p></div><form method="post" action="/quality-control/hemolysis/import/preview" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label class="file-picker"><input type="file" name="excel" accept=".xlsx,.xls" required><span>Selecionar arquivo .xlsx ou .xls (máx. 10 MB)</span></label><button class="button">Analisar arquivo</button></form></section>
<?php if($preview):?><section class="content-card import-summary"><header><div><strong>Resumo da importação</strong><small><?= $e($preview['filename']) ?></small></div><div class="summary-metrics"><span><b><?= (int)$preview['valid'] ?></b> válidos</span><span class="ok"><b><?= (int)$preview['matched'] ?></b> encontrados</span><span class="warn"><b><?= (int)$preview['unmatched'] ?></b> não encontrados</span><span><b><?= (int)$preview['duplicates'] ?></b> duplicados</span><span><b><?= (int)$preview['ignored'] ?></b> ignorados</span></div></header><?php if($preview['errors']):?><div class="import-errors"><?= $e(implode(' ',array_slice($preview['errors'],0,5))) ?></div><?php endif;?><div class="hemolysis-table-wrap"><table class="hemolysis-table"><thead><tr><th>Sample Name</th><th>370</th><th>415</th><th>510</th><th>577</th><th>600</th><th>Correspondência</th><th>Hb Livre</th></tr></thead><tbody><?php foreach($preview['rows'] as $r):?><tr><td><strong><?= $e($r['sample_name']) ?></strong></td><?php foreach(['370','415','510','577','600'] as $n):?><td><?= $fmt($r['abs_'.$n]) ?></td><?php endforeach;?><td><span class="import-state <?= $e($r['status']) ?>"><?= $r['status']==='found'?'Encontrada por '.$e($r['match_by']):($r['status']==='duplicate'?'Duplicada no arquivo':'Não encontrada') ?></span></td><td><?= $fmt($r['calculation']['free_hemoglobin_g_dl'],6) ?></td></tr><?php endforeach;?></tbody></table></div><form class="import-apply" method="post" action="/quality-control/hemolysis/import/apply"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="preview_hash" value="<?= $e($preview['hash']) ?>"><?php if($canReplace):?><label><input type="checkbox" name="replace_existing" value="1"> Confirmo substituir resultados existentes ainda não concluídos</label><?php endif;?><button class="button" <?= !$preview['matched']?'disabled':'' ?>>Aplicar resultados</button></form></section><?php endif;?>
<?php endif; ?>
<script src="/assets/js/hemolysis-calculator.js?v=<?=filemtime(dirname(__DIR__,3).'/public/assets/js/hemolysis-calculator.js')?>"></script>
<script>document.querySelectorAll('[data-hemolysis-row]').forEach(row=>{row.dataset.hemolysisCalculator='';row.querySelectorAll('.abs-input').forEach(input=>input.dataset.hemolysisAbs='')});window.BloodHubHemolysisCalculator.bindRealtime(document);</script>
<script>
document.querySelectorAll('.hemolysis-actions').forEach(actions=>{
  const save=actions.querySelector('button:not([formaction])');
  if(save)save.textContent='Concluir resultado';
  const legacy=actions.querySelector('button[formaction="/quality-control/hemolysis/complete"]');
  if(legacy)legacy.hidden=true;
});
const saveAll=document.querySelector('.hemolysis-save-all .button');if(saveAll)saveAll.textContent='Salvar todos como parcial';
</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
