<?php
require dirname(__DIR__).'/layouts/admin_start.php';
$statusLabels=['received'=>'Recebida','in_analysis'=>'Em análise','partial_results'=>'Resultados parciais','completed'=>'Concluída'];$filterLabels=['in_progress'=>'Em andamento','received'=>'Recebidas','in_analysis'=>'Em análise','partial_results'=>'Resultados parciais','completed'=>'Concluídas','all'=>'Todos'];$fmt=static fn($v,$d=1)=>$v===null||$v===''?'':number_format((float)$v,$d,'.','');$display=\BloodHub\Services\MeasurementFormatter::class;$returnTo=$_SERVER['REQUEST_URI']??'/quality-control';$componentUrl=static function(int $id)use($filters):string{$query=$filters;$query['component']=(string)$id;return '/quality-control?'.http_build_query($query);};
?>
<nav class="qc-flow-tabs" aria-label="Fluxos de Controle de Qualidade"><a class="active" href="/quality-control">Hemocomponentes</a><?php if(\BloodHub\Core\Permission::can('quality_results.hemolysis')):?><a href="/quality-control/hemolysis">Grau de Hemólise <b class="qc-tab-badge"><?= (int)$queueCounts['hemolysis'] ?></b></a><?php endif;?><a href="/quality-control/bacteriology">Bacteriológico <b class="qc-tab-badge"><?= (int)$queueCounts['bacteriology'] ?></b></a><?php if(\BloodHub\Core\Permission::can('quality_control.factor_viii_pool.view')):?><a href="/quality-control/factor-viii-pools">Fator VIII — Pools</a><?php endif;?></nav>
<section class="content-card qc-filter-card"><form class="qc-filters" method="get"><label><span>Origem / unidade</span><select name="origin"><option value="">Todas</option><?php foreach($origins as $o):?><option value="<?= (int)$o['id'] ?>" <?= $filters['origin']==$o['id']?'selected':'' ?>><?= htmlspecialchars($o['name']) ?></option><?php endforeach;?></select></label>
<label><span>Hemocomponente</span><select name="component"><option value="">Todos</option><?php foreach($components as $c):?><option value="<?= (int)$c['id'] ?>" <?= $filters['component']==$c['id']?'selected':'' ?>><?= htmlspecialchars($c['code'].' — '.$c['name']) ?></option><?php endforeach;?></select></label>
<label><span>Recebida em</span><input type="date" name="received_date" value="<?= htmlspecialchars($filters['received_date']) ?>"></label>
<label><span>Nº da doação</span><input name="donation" value="<?= htmlspecialchars($filters['donation']) ?>"></label>
<label><span>Código LCQH</span><input name="lcqh" value="<?= htmlspecialchars($filters['lcqh']) ?>"></label>
<label><span>Status analítico</span><select name="status"><?php foreach($filterLabels as $key=>$label):?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><div class="qc-filter-actions"><button class="button button-compact">Filtrar</button><a class="button button-secondary button-compact" href="/quality-control">Limpar filtros</a></div></form></section>
<?php if($components):?><div class="qc-component-tabs"><?php foreach($components as $c):?><a class="<?= $filters['component']==$c['id']?'active':'' ?>" href="<?= htmlspecialchars($componentUrl((int)$c['id'])) ?>"><strong><?= htmlspecialchars($c['code']) ?></strong><span><?= htmlspecialchars($c['name']) ?></span></a><?php endforeach;?></div><?php endif;?>
<form method="post" action="/quality-control/save-all" id="qc-batch-form"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="return_to" value="<?= htmlspecialchars($returnTo) ?>"><input type="hidden" name="visible_ids" value="<?= htmlspecialchars(implode(',',array_column(array_filter($samples,static fn($row)=>$row['status']!=='completed'),'id'))) ?>">
<?php if($samples&&($canEdit||$canComplete)):?><div class="qc-batch-actions"><?php if($canEdit):?><button class="button button-secondary button-compact">Salvar todas</button><?php endif;?><?php if($canComplete&&$filters['status']!=='completed'):?><button class="button button-compact" type="button" data-open-complete>Concluir todas</button><?php endif;?></div><?php endif;?>
<section class="qc-list"><?php foreach($samples as $s):$locked=$s['status']==='completed'||!$canEdit;$days=($s['production_date']&&$s['received_at'])?(new DateTimeImmutable(substr($s['production_date'],0,10)))->diff(new DateTimeImmutable(substr($s['received_at'],0,10)))->days:null;$tare=$s['bag_brand_tare_id']?['tare_id'=>$s['bag_brand_tare_id'],'tare_weight'=>$s['tare_weight_used']]:$s['resolved_tare'];$n='samples['.(int)$s['id'].']';$componentCode=$s['component_code']??'';$hasResidualLeukocytes=\BloodHub\Services\RedCellResidualLeukocyteService::supports($componentCode);$isCHL=$componentCode==='CHL';$isCP=\BloodHub\Services\PlateletResultService::supports($componentCode);$isFreshPlasma=in_array($componentCode,['PF','PF24'],true);$isPlasma=in_array($componentCode,['PFC','PFC24'],true);$isWholeBlood=$componentCode==='ST';$isReconstitutedWholeBlood=$componentCode==='STR';$isCryoprecipitate=$componentCode==='CRIO';$renderer=$isCryoprecipitate?'CRIO':($isWholeBlood?'WHOLE_BLOOD':($isReconstitutedWholeBlood?'RECONSTITUTED_WHOLE_BLOOD':($isCP?'CP':($isFreshPlasma?'FRESH_PLASMA':($isPlasma?'PLASMA':($isCHL?'CHL':($hasResidualLeukocytes?'RED_CELL_LEUKO':'CH')))))));$p=$s['platelet'];$rl=$s['residual_leukocytes'];$w=$s['washed_red_cell'];$fresh=$s['fresh_plasma'];$fv=$s['factor_viii'];?>
<article class="qc-sample-card"><header><div class="qc-identity"><span class="qc-code"><?= htmlspecialchars($s['component_code']??'—') ?></span><div><strong><?= htmlspecialchars($s['donation_number']??'—') ?></strong><small><?= htmlspecialchars($s['origin_name']??'Origem não informada') ?></small></div></div><div class="qc-summary"><span><small>Bolsa</small><?= htmlspecialchars(trim(($s['bag_brand_name']??'').' · '.($s['preservative_code']?:$s['preservative_name']??''),' ·'))?:'—' ?></span><span><small>Produção</small><?= $s['production_date']?date('d/m/Y',strtotime($s['production_date'])):'—' ?></span><span><small>Recebida em</small><?= $s['received_at']?date('d/m/Y H:i',strtotime($s['received_at'])):'—' ?></span><span><small>Em estoque</small><?= $days===null?'—':$days.' '.($days===1?'dia':'dias') ?></span></div><span class="qc-status status-<?= htmlspecialchars($s['status']) ?>"><?= htmlspecialchars($statusLabels[$s['status']]??$s['status']) ?></span></header>
<div class="qc-result-form" data-sample-form data-component="<?= $renderer ?>"><div class="qc-fields <?= $isCryoprecipitate?'qc-fields-crio':($isCP?'qc-fields-cp':($isFreshPlasma?'qc-fields-fresh-plasma':($isPlasma?'qc-fields-plasma':($hasResidualLeukocytes?'qc-fields-chf':'')))) ?>"><label><span>Código LCQH</span><input name="<?= $n ?>[lcqh_code]" maxlength="80" value="<?= htmlspecialchars($s['lcqh_code']??'') ?>" <?= $locked?'disabled':'' ?>></label>
<?php if($isWholeBlood):?><?php require __DIR__.'/partials/whole_blood_results.php';?>
<?php elseif($isReconstitutedWholeBlood):?><?php require __DIR__.'/partials/reconstituted_whole_blood_results.php';?>
<?php elseif($isCP):$plateletMethod=$p['platelet_method']?:'Sysmex';$leukocyteMethod=$p['leukocyte_method']?:'Sysmex';$swirling=$p['swirling']?:'Presente';?><label><span>Peso bruto (g)</span><input inputmode="decimal" name="<?= $n ?>[gross_weight]" value="<?= $fmt($s['gross_weight'],3) ?>" <?= $locked?'disabled':'' ?> data-gross></label>
<label class="qc-readonly"><span>Volume (mL)</span><input readonly value="<?= $display::formatDecimalMeasurement($s['volume_ml'],1) ?>" data-volume data-volume-raw="<?= htmlspecialchars((string)($s['volume_ml']??'')) ?>"></label>
<label><span>Método Plaquetas</span><select name="<?= $n ?>[platelet_method]" <?= $locked?'disabled':'' ?> data-platelet-method><option value="">Selecione</option><?php foreach(\BloodHub\Services\PlateletResultCalculator::PLATELET_METHODS as $m):?><option <?= $plateletMethod===$m?'selected':'' ?>><?= $m ?></option><?php endforeach;?></select></label>
<label><span>Nº Plaquetas</span><input inputmode="decimal" name="<?= $n ?>[platelet_count]" value="<?= $fmt($p['platelet_count'],4) ?>" <?= $locked?'disabled':'' ?> data-platelet-count></label>
<label class="qc-readonly"><span>Plaquetas/U</span><input readonly value="<?= $display::formatScientific($p['platelets_per_unit']) ?>" data-platelets-unit></label>
<label><span>Método Leucócitos</span><select name="<?= $n ?>[leukocyte_method]" <?= $locked?'disabled':'' ?> data-leukocyte-method><option value="">Selecione</option><?php foreach(\BloodHub\Services\PlateletResultCalculator::LEUKOCYTE_METHODS as $m):?><option <?= $leukocyteMethod===$m?'selected':'' ?>><?= $m ?></option><?php endforeach;?></select></label>
<label><span>Nº Leucócitos</span><input inputmode="decimal" name="<?= $n ?>[leukocyte_count]" value="<?= $fmt($p['leukocyte_count'],4) ?>" <?= $locked?'disabled':'' ?> data-leukocyte-count></label>
<label class="qc-readonly"><span>Leucócitos/U</span><input readonly value="<?= $display::formatScientific($p['leukocytes_per_unit']) ?>" data-leukocytes-unit></label>
<label><span>pH</span><input inputmode="decimal" name="<?= $n ?>[ph]" value="<?= $fmt($p['ph'],2) ?>" <?= $locked?'disabled':'' ?>></label>
<label><span>Swirling</span><select name="<?= $n ?>[swirling]" <?= $locked?'disabled':'' ?>><option value="">Selecione</option><?php foreach(['Presente','Ausente'] as $v):?><option <?= $swirling===$v?'selected':'' ?>><?= $v ?></option><?php endforeach;?></select></label>
<?php elseif($isPlasma):?><label><span>Peso bruto (g)</span><input type="number" step="0.001" min="0.001" name="<?= $n ?>[gross_weight]" value="<?= $fmt($s['gross_weight'],3) ?>" <?= $locked?'disabled':'' ?> data-gross></label>
<label class="qc-readonly"><span>Volume (mL)</span><input readonly value="<?= $display::formatDecimalMeasurement($s['volume_ml'],1) ?>" data-volume data-volume-raw="<?= htmlspecialchars((string)($s['volume_ml']??'')) ?>"></label><div class="qc-fviii-field"><span>Fator VIII (UI/mL)</span><div class="fviii-state-value"><?php if(($fv['pool_status']??null)==='open'):?><b>Pool <?= htmlspecialchars($fv['pool_code']) ?> — aguardando resultado</b><?php elseif(($fv['pool_status']??null)==='completed_conforming'):?><b><?= number_format((float)$fv['effective_result'],2,',','.') ?> UI/mL</b><small>Resultado do pool</small><?php elseif(!empty($fv['individual_required'])||($fv['analysis_mode']??'pool')==='individual'):?><?php if($fv['pool_result']!==null):?><small>Resultado do pool: <?= number_format((float)$fv['pool_result'],2,',','.') ?> UI/mL</small><?php endif;?><?php else:?><span>Aguardando definição do Fator VIII</span><?php if(!$locked):?><button form="fviii-select-<?= (int)$s['id'] ?>" class="button button-secondary button-compact">Analisar individualmente</button><?php endif;?><?php endif;?></div></div><?php if(!empty($fv['individual_required'])||($fv['analysis_mode']??'pool')==='individual'):?><label class="qc-fviii-individual"><span>Fator VIII individual (UI/mL) <small>Reteste</small></span><div><input form="fviii-save-<?= (int)$s['id'] ?>" inputmode="decimal" name="factor_viii" value="<?= $fv['individual_result']!==null?number_format((float)$fv['individual_result'],2,',',''):'' ?>" <?= $locked?'disabled':'' ?> required><?php if(!$locked):?><button form="fviii-save-<?= (int)$s['id'] ?>" class="button button-compact">Salvar</button><?php endif;?></div></label><?php endif;?>
<?php elseif($isFreshPlasma):?><?php require __DIR__.'/partials/fresh_plasma_results.php';?>
<?php elseif($componentCode==='CRIO'):?><?php require __DIR__.'/partials/cryoprecipitate_results.php';?>
<?php elseif($isCHL):?><label><span>Peso origem (g)</span><input inputmode="decimal" name="<?= $n ?>[initial_weight_g]" value="<?= $fmt($w['initial_weight_g'],3) ?>" <?= $locked?'disabled':'' ?> data-chl-initial-weight></label>
<label class="qc-readonly"><span>Vol. Origem (mL)</span><input readonly value="<?= $display::formatDecimalMeasurement($w['initial_volume_ml'],1) ?>" data-chl-initial-volume></label>
<label><span>Peso final (g)</span><input inputmode="decimal" name="<?= $n ?>[final_weight_g]" value="<?= $fmt($w['final_weight_g'],3) ?>" <?= $locked?'disabled':'' ?> data-chl-final-weight></label>
<label class="qc-readonly"><span>Vol. Final (mL)</span><input readonly value="<?= $display::formatDecimalMeasurement($w['final_volume_ml'],1) ?>" data-chl-final-volume></label>
<label><span>Ht inicial (%)</span><input inputmode="decimal" name="<?= $n ?>[initial_hematocrit_pct]" value="<?= $fmt($w['initial_hematocrit_pct'],2) ?>" <?= $locked?'disabled':'' ?> data-chl-initial-hct></label>
<label><span>Ht final (%)</span><input inputmode="decimal" name="<?= $n ?>[final_hematocrit_pct]" value="<?= $fmt($w['final_hematocrit_pct'],2) ?>" <?= $locked?'disabled':'' ?> data-chl-final-hct></label>
<label class="qc-readonly"><span>Recup. (%)</span><input readonly value="<?= $fmt($w['recovery_pct'],2) ?>" data-chl-recovery></label>
<label><span>Hb (g/dL)</span><input inputmode="decimal" name="<?= $n ?>[hemoglobin_g_dl]" value="<?= $fmt($w['hemoglobin_g_dl'],2) ?>" <?= $locked?'disabled':'' ?> data-chl-hb></label>
<label class="qc-readonly"><span>Hb (g/U)</span><input readonly value="<?= $fmt($w['hemoglobin_per_unit_g'],2) ?>" data-chl-hb-unit></label>
<label class="qc-readonly qc-hemolysis-field"><span>G° Hemólise (%)</span><input readonly value="<?= $s['hemolysis']['ready']?$fmt($s['hemolysis']['value'],2):'—' ?>"></label>
<label><span>Abs padrão</span><input inputmode="decimal" name="<?= $n ?>[standard_absorbance]" value="<?= $fmt($w['standard_absorbance'],4) ?>" <?= $locked?'disabled':'' ?> data-chl-standard></label>
<label><span>Abs proteína</span><input inputmode="decimal" name="<?= $n ?>[protein_absorbance]" value="<?= $fmt($w['protein_absorbance'],4) ?>" <?= $locked?'disabled':'' ?> data-chl-protein></label>
<label class="qc-readonly"><span>Proteína (g/U)</span><input readonly value="<?= $fmt($w['residual_protein_g_u'],4) ?>" data-chl-residual-protein></label>
<?php else:?><label class="qc-readonly"><span>Preservante</span><input class="<?= empty($s['resolved_preservative_id'])?'tare-warning':'' ?>" readonly value="<?= htmlspecialchars($s['preservative_code']?:($s['preservative_name']?:'Não configurado')) ?>"></label>
<label><span>Peso bruto (g)</span><input type="number" step="0.001" min="0.001" name="<?= $n ?>[gross_weight]" value="<?= $fmt($s['gross_weight'],3) ?>" <?= $locked?'disabled':'' ?> data-gross></label>
<label class="qc-readonly"><span>Volume (mL)</span><input readonly value="<?= $fmt($s['volume_ml'],2) ?>" data-volume data-volume-raw="<?= htmlspecialchars((string)($s['volume_ml']??'')) ?>"></label>
<label><span>Ht (%)</span><input type="number" step="0.01" name="<?= $n ?>[hematocrit]" value="<?= $fmt($s['hematocrit'],2) ?>" <?= $locked?'disabled':'' ?>></label>
<label><span>Hb (g/dL)</span><input type="number" step="0.01" name="<?= $n ?>[hemoglobin]" value="<?= $fmt($s['hemoglobin'],2) ?>" <?= $locked?'disabled':'' ?> data-hb></label>
<label class="qc-readonly"><span>Hb (g/U)</span><input readonly value="<?= $fmt($s['hemoglobin_per_unit'],2) ?>" data-hb-unit></label><?php if($hasResidualLeukocytes):$leukocyteMethod=$rl['leukocyte_method']?:'Nageotte';?><label><span>Método Leucócitos</span><select name="<?= $n ?>[leukocyte_method]" <?= $locked?'disabled':'' ?> data-leukocyte-method><option <?= $leukocyteMethod==='Nageotte'?'selected':'' ?>>Nageotte</option></select></label>
<label><span>Nº Leucócitos</span><input inputmode="decimal" name="<?= $n ?>[leukocyte_count]" value="<?= $fmt($rl['leukocyte_count'],4) ?>" <?= $locked?'disabled':'' ?> data-leukocyte-count></label>
<label class="qc-readonly"><span>Leucócitos/U</span><input readonly value="<?= $display::formatScientific($rl['leukocytes_per_unit']) ?>" data-leukocytes-unit></label><?php endif;?><label class="qc-readonly qc-hemolysis-field"><span>Grau de Hemólise (%)</span><input readonly value="<?= $s['hemolysis']['ready']?$fmt($s['hemolysis']['value'],2):'—' ?>"></label><?php endif;?></div>
<div class="qc-under-fields"><?php if(!$isFreshPlasma):?><?php $densityValid=$s['density']!==null&&(float)$s['density']>0;$calculationMessage=!$tare?($s['tare_error']?:\BloodHub\Services\BagTareResolver::NOT_CONFIGURED):($isCryoprecipitate&&!$densityValid?'Densidade não configurada para o hemocomponente CRIO.':'Tara aplicada: '.number_format((float)$tare['tare_weight'],3,',','.').' g');?><span class="<?= $tare&&(!$isCryoprecipitate||$densityValid)?'tare-ok':'tare-warning' ?>" data-tare data-weight="<?= $tare?htmlspecialchars((string)$tare['tare_weight']):'' ?>" data-density="<?= htmlspecialchars((string)($s['density']??'')) ?>"><?= htmlspecialchars($calculationMessage) ?></span><?php endif;?><?php if(!$isCP&&!$isPlasma&&!$isFreshPlasma&&!$isCryoprecipitate):?><span class="hemolysis-state"><?= htmlspecialchars($s['hemolysis']['message']) ?></span><?php endif;?></div><footer><?php if(!$locked):?><button class="button button-compact" type="submit" formaction="/quality-control/save" name="sample_id" value="<?= (int)$s['id'] ?>">Salvar</button><?php endif;?><?php if($canComplete&&$s['status']!=='completed'):?><button class="button button-secondary button-compact" type="submit" formaction="/quality-control/complete" name="sample_id" value="<?= (int)$s['id'] ?>">Concluir análise</button><?php endif;?></footer></div></article>
<?php endforeach;?><?php if(!$samples):?><div class="content-card qc-empty"><strong>Nenhuma amostra elegível encontrada.</strong><span>Altere os filtros para consultar outros estados analíticos.</span></div><?php endif;?></section></form>
<div class="qc-modal-backdrop" data-complete-modal hidden><div class="qc-modal" role="dialog" aria-modal="true"><h2>Resultados fora da especificação</h2><p>Foram identificados resultados fora dos valores de referência destes hemocomponentes.</p><p>A conclusão é permitida, mas estes resultados serão registrados como fora da especificação.</p><div data-batch-spec-summary></div><div><button class="button button-secondary button-compact" type="button" data-close-complete>Voltar e revisar</button><button class="button button-compact" type="submit" form="qc-batch-form" formaction="/quality-control/complete-all" name="specification_acknowledged" value="1">Estou ciente · Concluir todas</button></div></div></div>
<div class="qc-modal-backdrop" data-individual-modal hidden><form class="qc-modal" method="post" action="/quality-control/complete"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="sample_id" data-individual-id><input type="hidden" name="specification_acknowledged" value="1"><h2>Resultados fora da especificação</h2><p>Foram identificados resultados fora dos valores de referência deste hemocomponente.</p><p>A conclusão é permitida, mas estes resultados serão registrados como fora da especificação.</p><div data-individual-spec-summary></div><div><button class="button button-secondary button-compact" type="button" data-close-individual>Voltar e revisar</button><button class="button button-compact">Estou ciente · Concluir</button></div></form></div>
<?php foreach($samples as $ps):if(!in_array(($ps['component_code']??''),['PFC','PFC24'],true))continue;$factorState=$ps['factor_viii'];if(!empty($factorState['individual_required'])||($factorState['analysis_mode']??'pool')==='individual'):?><form hidden id="fviii-save-<?= (int)$ps['id'] ?>" method="post" action="/quality-control/factor-viii/individual/save"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="return_to" value="<?= htmlspecialchars($returnTo) ?>"><input type="hidden" name="sample_id" value="<?= (int)$ps['id'] ?>"></form><?php elseif(($factorState['pool_status']??null)!=='open'&&($factorState['pool_status']??null)!=='completed_conforming'):?><form hidden id="fviii-select-<?= (int)$ps['id'] ?>" method="post" action="/quality-control/factor-viii/individual/select"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="return_to" value="<?= htmlspecialchars($returnTo) ?>"><input type="hidden" name="sample_id" value="<?= (int)$ps['id'] ?>"></form><?php endif;endforeach;?>
<?php if(false):?>
<?php $plasmaSamples=array_values(array_filter($samples,static fn($row)=>in_array(($row['component_code']??''),['PFC','PFC24'],true)));if($plasmaSamples):?><section class="content-card fviii-main-summary"><h2>Fator VIII:C — PFC/PFC24</h2><?php foreach($plasmaSamples as $ps):$fv=$ps['factor_viii'];?><article><div><b><?=htmlspecialchars($ps['lcqh_code']?:($ps['donation_number']?:'—'))?></b><small><?=htmlspecialchars($ps['component_code'].' · '.$ps['origin_name'])?></small></div><span>Volume: <?=$ps['volume_ml']!==null?number_format((float)$ps['volume_ml'],1,',','.').' mL':'pendente'?></span><div class="fviii-state-value"><?php if(($fv['pool_status']??null)==='open'):?>Pool <?=htmlspecialchars($fv['pool_code'])?> — aguardando resultado<?php elseif(($fv['pool_status']??null)==='completed_conforming'):?><?=number_format((float)$fv['effective_result'],2,',','.')?> UI/mL <b>Resultado do pool</b><?php elseif(!empty($fv['individual_required'])||($fv['analysis_mode']??'pool')==='individual'):?><?php if($fv['pool_result']!==null):?><small>Pool: <?=number_format((float)$fv['pool_result'],2,',','.')?> UI/mL</small><?php endif;?><form method="post" action="/quality-control/factor-viii/individual/save"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_to" value="<?=htmlspecialchars($returnTo)?>"><input type="hidden" name="sample_id" value="<?=$ps['id']?>"><input inputmode="decimal" name="factor_viii" placeholder="Fator VIII individual" value="<?=$fv['individual_result']!==null?number_format((float)$fv['individual_result'],2,',',''):''?>" required><button class="button button-compact">Salvar</button></form><?php else:?>Aguardando pool<?php if($canEdit):?><form method="post" action="/quality-control/factor-viii/individual/select"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="return_to" value="<?=htmlspecialchars($returnTo)?>"><input type="hidden" name="sample_id" value="<?=$ps['id']?>"><button class="button button-secondary button-compact">Analisar individualmente</button></form><?php endif;?><?php endif;?></div></article><?php endforeach;?></section><?php endif;?>
<?php endif;?>
<script src="/assets/js/measurement-formatter.js?v=<?= filemtime(dirname(__DIR__,3).'/public/assets/js/measurement-formatter.js') ?>"></script><script src="/assets/js/fresh-plasma-calculator.js?v=<?= filemtime(dirname(__DIR__,3).'/public/assets/js/fresh-plasma-calculator.js') ?>"></script><script>
<?php $initialOutsideMap=array_column(array_map(static fn($s)=>['id'=>(int)$s['id'],'label'=>(string)($s['donation_number']??('#'.$s['id'])),'items'=>$s['nonconforming']??[]],$samples),null,'id'); ?>
<?php $cpafClassificationMap=[];foreach($samples as $sample){if(($sample['component_code']??'')!=='CPAF')continue;$saved=\BloodHub\Services\CpafYieldClassificationService::state((int)$sample['id']);$rule=$saved?:\BloodHub\Services\CpafYieldClassificationService::activeRule((int)$sample['blood_component_id']);if(!$rule)continue;$cpafClassificationMap[(int)$sample['id']]=['simple_min'=>(float)($rule['simple_min']??$rule['simple_min_platelets']),'double_min'=>(float)($rule['double_min']??$rule['double_min_platelets']),'label'=>$saved['label']??null,'code'=>$saved['code']??null,'version_number'=>(int)($rule['version_number']??1),'finalized'=>(bool)($saved['finalized']??false)];} ?>
const cpafClassificationMap=<?=json_encode($cpafClassificationMap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),specRows=row=>'<div class="qc-spec-list">'+row.items.map(x=>'<div class="qc-spec-row"><b>'+escapeHtml(x.test_name)+'</b><span><small>Resultado:</small> '+escapeHtml(x.result_display)+'</span><span><small>Referência:</small> '+escapeHtml(x.reference_display)+'</span><strong>Fora da especificação</strong></div>').join('')+'</div>';
const initialOutsideMap=<?=json_encode($initialOutsideMap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;Object.entries(initialOutsideMap).forEach(([id,row])=>{if(!row.items?.length)return;const button=document.querySelector('button[formaction="/quality-control/complete"][value="'+id+'"]'),card=button?.closest('.qc-sample-card');if(!card)return;card.classList.add('qc-nonconforming');const warning=document.createElement('div');warning.className='qc-spec-warning';warning.innerHTML='<strong>FORA DA ESPECIFICAÇÃO</strong>'+specRows(row);card.querySelector('.qc-result-form')?.prepend(warning)});
const batchForm=document.getElementById('qc-batch-form'),individual=document.querySelector('[data-individual-modal]'),completeModal=document.querySelector('[data-complete-modal]');let pendingIndividualButton=null;
const showQcError=message=>{let box=document.querySelector('[data-qc-preview-error]');if(!box){box=document.createElement('div');box.className='alert alert-error';box.dataset.qcPreviewError='1';batchForm.before(box);}box.textContent=message;box.scrollIntoView({behavior:'smooth',block:'center'});};
const previewSpecifications=async sampleId=>{const data=new FormData(batchForm);if(sampleId)data.set('sample_id',sampleId);const response=await fetch('/quality-control/specifications/preview',{method:'POST',body:data,headers:{'X-Requested-With':'XMLHttpRequest'}});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error((payload.errors||[payload.message||'Não foi possível avaliar os resultados.']).join(' | '));return payload;};
document.querySelectorAll('button[formaction="/quality-control/complete"]').forEach(b=>b.addEventListener('click',async e=>{if(b.dataset.previewed==='1'){delete b.dataset.previewed;return;}e.preventDefault();b.disabled=true;try{const payload=await previewSpecifications(b.value),row=payload.samples[0];if(!row?.items?.length){b.dataset.previewed='1';b.disabled=false;b.click();return;}pendingIndividualButton=b;individual.querySelector('[data-individual-id]').value=b.value;individual.querySelector('[data-individual-spec-summary]').innerHTML=specRows(row);individual.hidden=false;}catch(error){showQcError(error.message);}finally{b.disabled=false;}}));
individual.querySelector('form')?.addEventListener('submit',e=>{e.preventDefault();if(!pendingIndividualButton)return;let ack=batchForm.querySelector('input[name="specification_acknowledged"]');if(!ack){ack=document.createElement('input');ack.type='hidden';ack.name='specification_acknowledged';batchForm.append(ack);}ack.value='1';pendingIndividualButton.dataset.previewed='1';individual.hidden=true;batchForm.requestSubmit(pendingIndividualButton);});
document.querySelector('[data-close-individual]')?.addEventListener('click',()=>individual.hidden=true);individual?.addEventListener('click',e=>{if(e.target===individual)individual.hidden=true});
const number=v=>{v=String(v??'').trim();if(v.includes(','))v=v.replaceAll('.','').replace(',','.');return Number.parseFloat(v)},{formatScientificPtBr,formatDecimalMeasurementPtBr}=window.BloodHubMeasurementFormatter;
window.BloodHubFreshPlasmaCalculator.bindRealtime(document.getElementById('qc-batch-form'),formatScientificPtBr);
Object.entries(cpafClassificationMap).forEach(([id,config])=>{const input=document.querySelector('[name="samples['+id+'][platelet_count]"]'),card=input?.closest('[data-sample-form]');if(!card)return;const field=document.createElement('label');field.className='qc-readonly qc-cpaf-classification-field';field.innerHTML='<span>Classificação</span><output class="cpaf-classification-badge" data-cpaf-classification>—</output>';card.querySelector('.qc-fields')?.append(field);const badge=field.querySelector('[data-cpaf-classification]'),render=()=>{if(config.finalized&&config.label){badge.textContent=config.label.toLocaleUpperCase('pt-BR');badge.dataset.classification=config.code;return;}const gross=number(card.querySelector('[data-gross]')?.value),tare=number(card.querySelector('[data-tare]')?.dataset.weight),density=number(card.querySelector('[data-tare]')?.dataset.density),count=number(input.value),method=card.querySelector('[data-platelet-method]')?.value,volume=Number.isFinite(gross)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&gross>tare?(gross-tare)/density:number(card.querySelector('[data-volume]')?.dataset.volumeRaw);let value=NaN;if(Number.isFinite(volume)&&Number.isFinite(count))value=method==='Sysmex'?count*5*1e6*volume:method==='Neubauer'?count*5*10*200*1000*volume:NaN;const code=!Number.isFinite(value)?'':value<config.simple_min?'INSUFFICIENT_YIELD':value<config.double_min?'CPAF_SIMPLE':'CPAF_DOUBLE';badge.dataset.classification=code;badge.textContent=code==='INSUFFICIENT_YIELD'?'RENDIMENTO INSUFICIENTE':code==='CPAF_SIMPLE'?'CPAF SIMPLES':code==='CPAF_DOUBLE'?'CPAF DUPLA':'—';};card.querySelectorAll('[data-gross],[data-platelet-method],[data-platelet-count]').forEach(el=>el.addEventListener('input',render));render();});
document.querySelectorAll('[data-sample-form]').forEach(card=>{const gross=card.querySelector('[data-gross]'),volume=card.querySelector('[data-volume]'),tare=card.querySelector('[data-tare]'),hb=card.querySelector('[data-hb]'),hbUnit=card.querySelector('[data-hb-unit]');const calculate=()=>{const g=number(gross?.value),t=number(tare?.dataset.weight),d=number(tare?.dataset.density);let vol=number(volume?.dataset.volumeRaw);if(gross&&volume&&gross.value!==''){vol=Number.isFinite(g)&&Number.isFinite(t)&&Number.isFinite(d)&&d>0&&g>t?(g-t)/d:NaN;volume.value=['CP','CRIO'].includes(card.dataset.component)?formatDecimalMeasurementPtBr(vol,1):(Number.isFinite(vol)?vol.toFixed(2):'');volume.dataset.volumeRaw=Number.isFinite(vol)?String(vol):''}if(hbUnit){const h=number(hb?.value);hbUnit.value=Number.isFinite(vol)&&Number.isFinite(h)?(h/100*vol).toFixed(2):''}if(card.dataset.component==='RED_CELL_LEUKO'){const lr=number(card.querySelector('[data-leukocyte-count]')?.value),lu=Number.isFinite(vol)&&Number.isFinite(lr)?(lr*10*1000*vol)/50:NaN;card.querySelector('[data-leukocytes-unit]').value=formatScientificPtBr(lu)}if(card.dataset.component==='CP'){const pm=card.querySelector('[data-platelet-method]')?.value,pr=number(card.querySelector('[data-platelet-count]')?.value),lm=card.querySelector('[data-leukocyte-method]')?.value,lr=number(card.querySelector('[data-leukocyte-count]')?.value);let pu=NaN,lu=NaN;if(Number.isFinite(vol)&&Number.isFinite(pr))pu=pm==='Sysmex'?pr*5*1e6*vol:pm==='Neubauer'?pr*5*10*200*1000*vol:NaN;if(Number.isFinite(vol)&&Number.isFinite(lr))lu=lm==='Sysmex'?lr*1e6*vol:lm==='Neubauer'?(lr*10*20*1000*vol)/4:lm==='Nageotte'?(lr*10*1000*vol)/50:NaN;card.querySelector('[data-platelets-unit]').value=formatScientificPtBr(pu);card.querySelector('[data-leukocytes-unit]').value=formatScientificPtBr(lu)}};card.querySelectorAll('[data-gross],[data-hb],[data-platelet-method],[data-platelet-count],[data-leukocyte-method],[data-leukocyte-count]').forEach(el=>el.addEventListener('input',calculate));calculate()});
document.querySelectorAll('[data-sample-form][data-component="CRIO"]').forEach(card=>{const calculate=()=>{const grossField=card.querySelector('[data-gross]'),volumeField=card.querySelector('[data-volume]'),gross=number(grossField?.value),tare=number(card.querySelector('[data-tare]')?.dataset.weight),density=number(card.querySelector('[data-tare]')?.dataset.density),volume=grossField?.value!==''&&Number.isFinite(gross)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&gross>tare?(gross-tare)/density:NaN;if(volumeField){volumeField.value=Number.isFinite(volume)?formatDecimalMeasurementPtBr(volume,1):'';volumeField.dataset.volumeRaw=Number.isFinite(volume)?String(volume):''}const dilutionField=card.querySelector('[data-crio-dilution]'),mgDlField=card.querySelector('[data-crio-fibrinogen-mg-dl]'),dilution=number(dilutionField?.value),mgDl=number(mgDlField?.value),output=card.querySelector('[data-crio-fibrinogen-mg-u]'),result=dilutionField?.value!==''&&mgDlField?.value!==''&&Number.isFinite(volume)&&Number.isFinite(dilution)&&Number.isFinite(mgDl)?((mgDl*dilution)/100)*volume:NaN;if(output)output.value=Number.isFinite(result)?formatDecimalMeasurementPtBr(result,2):''};card.querySelectorAll('[data-gross],[data-crio-dilution],[data-crio-fibrinogen-mg-dl]').forEach(el=>el.addEventListener('input',calculate));calculate()});
document.querySelectorAll('[data-sample-form][data-component="PLASMA"]').forEach(card=>card.querySelector('[data-gross]')?.addEventListener('input',()=>{const gross=number(card.querySelector('[data-gross]').value),tare=number(card.querySelector('[data-tare]')?.dataset.weight),density=number(card.querySelector('[data-tare]')?.dataset.density),volume=card.querySelector('[data-volume]'),calculated=Number.isFinite(gross)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&gross>tare?(gross-tare)/density:NaN;volume.value=formatDecimalMeasurementPtBr(calculated,1);volume.dataset.volumeRaw=Number.isFinite(calculated)?String(calculated):''}));
document.querySelectorAll('[data-sample-form][data-component="WHOLE_BLOOD"],[data-sample-form][data-component="RECONSTITUTED_WHOLE_BLOOD"]').forEach(card=>card.querySelector('[data-gross]')?.addEventListener('input',()=>{const gross=number(card.querySelector('[data-gross]').value),tare=number(card.querySelector('[data-tare]')?.dataset.weight),density=number(card.querySelector('[data-tare]')?.dataset.density),volume=card.querySelector('[data-volume]'),calculated=Number.isFinite(gross)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&gross>tare?(gross-tare)/density:NaN;volume.value=formatDecimalMeasurementPtBr(calculated,1);volume.dataset.volumeRaw=Number.isFinite(calculated)?String(calculated):''}));
document.querySelector('[data-open-complete]')?.addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{const payload=await previewSpecifications(),rows=payload.samples.filter(row=>row.items?.length);if(!rows.length){batchForm.requestSubmit(completeModal.querySelector('button[formaction="/quality-control/complete-all"]'));return;}completeModal.querySelector('[data-batch-spec-summary]').innerHTML='<p><strong>'+rows.length+' amostra(s) possuem resultados fora da especificação.</strong></p>'+rows.map(row=>'<div><strong>Amostra '+escapeHtml(row.label)+'</strong>'+specRows(row)+'</div>').join('');completeModal.hidden=false;}catch(error){showQcError(error.message);}finally{button.disabled=false;}});document.querySelector('[data-close-complete]')?.addEventListener('click',()=>completeModal.hidden=true);completeModal?.addEventListener('click',e=>{if(e.target===completeModal)completeModal.hidden=true});
document.querySelectorAll('[data-sample-form][data-component="CHL"]').forEach(card=>{const get=s=>number(card.querySelector(s)?.value),out=(s,v,d=2)=>{card.querySelector(s).value=Number.isFinite(v)?v.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):''},calculate=()=>{const tare=number(card.querySelector('[data-tare]')?.dataset.weight),density=number(card.querySelector('[data-tare]')?.dataset.density),iw=get('[data-chl-initial-weight]'),fw=get('[data-chl-final-weight]'),ih=get('[data-chl-initial-hct]'),fh=get('[data-chl-final-hct]'),hb=get('[data-chl-hb]'),standard=get('[data-chl-standard]'),protein=get('[data-chl-protein]'),iv=Number.isFinite(iw)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&iw>tare?(iw-tare)/density:NaN,fv=Number.isFinite(fw)&&Number.isFinite(tare)&&Number.isFinite(density)&&density>0&&fw>tare?(fw-tare)/density:NaN;out('[data-chl-initial-volume]',iv,1);out('[data-chl-final-volume]',fv,1);out('[data-chl-recovery]',Number.isFinite(ih)&&ih!==0&&Number.isFinite(iv)&&iv!==0&&Number.isFinite(fh)&&Number.isFinite(fv)?(fh*fv)/(ih*iv)*100:NaN,2);out('[data-chl-hb-unit]',Number.isFinite(hb)&&Number.isFinite(fv)?hb/100*fv:NaN,2);out('[data-chl-residual-protein]',Number.isFinite(standard)&&standard!==0&&Number.isFinite(protein)&&Number.isFinite(fv)?protein/standard*50*0.00001*fv:NaN,4)};card.querySelectorAll('[data-chl-initial-weight],[data-chl-final-weight],[data-chl-initial-hct],[data-chl-final-hct],[data-chl-hb],[data-chl-standard],[data-chl-protein]').forEach(el=>el.addEventListener('input',calculate));calculate()});
</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
