<?php require dirname(__DIR__).'/layouts/admin_start.php';$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$names=[1=>'Segunda',2=>'Terça',3=>'Quarta',4=>'Quinta',5=>'Sexta',6=>'Sábado',0=>'Domingo'];$nowMonth=date('Y-m'); ?>
<section class="sampling-context card">
 <form method="get"><label>Unidade<select name="unit_id" <?=!$isAdmin?'disabled':''?>><?php foreach($units as$u):?><option value="<?=$u['id']?>" <?=(int)$u['id']===$unitId?'selected':''?>><?=$e($u['name'])?></option><?php endforeach?></select></label><?php if(!$isAdmin):?><input type="hidden" name="unit_id" value="<?=$unitId?>"><?php endif?><label>Mês<input type="month" name="month" max="<?=date('Y-m',strtotime('+1 month'))?>" value="<?=$e($month)?>"></label><input type="hidden" name="weekday" value="<?=$weekday?>"><button class="button button-primary">Consultar</button></form>
 <div><span>Unidade</span><strong><?=$e($unitName)?></strong><span>Regra geral</span><strong>1% da produção · mínimo configurável</strong><?php if($month<$nowMonth):?><b class="sampling-badge neutral">MÊS ENCERRADO</b><?php elseif($month>$nowMonth):?><b class="sampling-badge neutral">MÊS AINDA NÃO INICIADO</b><?php endif?></div>
</section>
<section class="sampling-kpis"><?php foreach(['produced'=>'Produção no mês','required'=>'Exigido para CQ','sent'=>'Já enviado','pending'=>'Pendente']as$k=>$label):?><article><span><?=$label?></span><strong><?=$totals[$k]?></strong></article><?php endforeach?></section>
<nav class="sampling-days" aria-label="Dias do cronograma"><?php foreach($names as$n=>$label):$query=http_build_query(['unit_id'=>$unitId,'month'=>$month,'weekday'=>$n]);?><a href="?<?=$query?>" class="<?=$weekday===$n?'active':''?>"><?=$label?><?php if((int)date('w')===$n):?><small>Hoje</small><?php endif?></a><?php endforeach?></nav>
<section class="sampling-grid">
<?php foreach($rows as$r):$s=$r['suggestion'];$red=(bool)preg_match('/^(CH|CHF|CHL|CHAF|ST|STR)$/',$r['code']);$status=match($s['status']){'closed'=>'HISTÓRICO','future'=>'MÊS NÃO INICIADO','no_production'=>'SEM PRODUÇÃO NO MÊS','complete'=>'ATENDIDO','not_scheduled'=>'NÃO PROGRAMADO PARA ESTE DIA','await_day'=>'AGUARDAR DIA','on_track'=>'META DO DIA ATENDIDA',default=>'FALTAM '.$r['pending'].' UNID.'};?>
 <article class="sampling-component <?=$s['status']==='no_production'||!$s['eligible']?'muted':''?>">
  <header><span class="blood-bag <?=$red?'red':'amber'?>" aria-hidden="true"></span><div><b><?=$e($r['code'])?></b><h2><?=$e($r['name'])?></h2></div><span class="sampling-badge status-<?=$e($s['status'])?>"><?=$status?></span></header>
  <dl><div><dt>Produzido</dt><dd><?=$r['produced']?></dd></div><div><dt>Exigido</dt><dd><?=$r['required']?></dd></div><div><dt>Enviado</dt><dd><?=$r['sent']?></dd></div><div><dt>Pendente</dt><dd><?=$r['pending']?></dd></div></dl>
  <footer><?php if($s['amount']>0):?><strong>ENVIAR <?=$s['amount']?> UNID.</strong><?php elseif($s['status']==='complete'):?><strong>ATENDIDO</strong><?php else:?><span><?=$status?></span><?php endif?><?php if($s['amount']>0&&\BloodHub\Core\Permission::can('shipments.create')):?><a href="/samples/shipments/create?origin_unit_id=<?=$unitId?>">Cadastrar amostra</a><?php endif?></footer>
 </article>
<?php endforeach?></section>
<?php if($endMonth):?><section class="card sampling-end"><header><div><span class="eyebrow">Últimos dias úteis</span><h2>Projeção de fim de mês</h2></div><p>Distribuição inteira e determinística do faltante projetado.</p></header><div class="table-wrap"><table><thead><tr><th>Hemocomponente</th><th>Produzido</th><th>Enviado</th><th>Exigido projetado</th><th>Faltante</th><?php for($i=0;$i<3;$i++):?><th>D<?=$i?></th><?php endfor?></tr></thead><tbody><?php foreach($endMonth['rows']as$r):?><tr><td><b><?=$e($r['code'])?></b> <?=$e($r['name'])?></td><td><?=$r['produced']?></td><td><?=$r['sent']?></td><td><?=$r['projected_required']?></td><td><?=$r['end_month_missing']?></td><?php foreach($r['daily_distribution']as$v):?><td><?=$v?></td><?php endforeach?></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
