<?php
require dirname(__DIR__).'/layouts/admin_start.php';
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$labels=['planned'=>'Planejada','in_progress'=>'Em andamento','completed'=>'Concluída','cancelled'=>'Cancelada'];
$phaseLabels=['active'=>'Em andamento','completed'=>'Concluída','cancelled'=>'Cancelada','inactive'=>'Planejada'];
$outcomes=['satisfactory'=>'Satisfatória','unsatisfactory'=>'Insatisfatória — requer nova etapa','inconclusive'=>'Inconclusiva — requer nova etapa'];
$readOnly=in_array($validation['status'],['completed','cancelled'],true);
$last=$phases?end($phases):null;
$canManage=!$readOnly&&\BloodHub\Core\Permission::can('validations.complete');
$canCreate=!$readOnly&&$last&&$last['status']==='completed'&&in_array($last['outcome'],['unsatisfactory','inconclusive'],true);
$nextSequence=$last?(int)$last['sequence_order']+1:1;
$date=static fn($v)=>$v?date('d/m/Y',strtotime($v)):'—';
?>
<div class="validation-detail">
 <section class="content-card validation-hero"><div><div class="validation-title-row"><h2><?=$e($validation['pv_number'].' — '.$validation['name'])?></h2><span class="status status-<?=$e($validation['status'])?>"><?=$e($labels[$validation['status']]??$validation['status'])?></span></div><p>Unidade: <strong><?=$e($validation['unit_name']??'Unidade não definida')?></strong></p></div><div class="validation-header-actions"><a class="button button-secondary" href="/validations">Voltar</a><?php if(!$readOnly&&\BloodHub\Core\Permission::can('validations.edit')):?><a class="button button-secondary" href="/validations/edit?id=<?=(int)$validation['id']?>">Editar</a><?php endif;?></div></section>
 <dl class="validation-date-grid"><div><dt>Início</dt><dd><?=$date($validation['start_date'])?></dd></div><div><dt>Previsão de término</dt><dd><?=$date($validation['expected_end_date'])?></dd></div><div><dt>Término efetivo</dt><dd><?=$date($validation['actual_end_date'])?></dd></div><div><dt>Unidade responsável</dt><dd><?=$e($validation['unit_name']??'Unidade não definida')?></dd></div></dl>
 <nav class="validation-tabs"><a class="active" href="/validations/view?id=<?=(int)$validation['id']?>">Visão geral</a><a href="/validations/dashboard?id=<?=(int)$validation['id']?>">Dashboard</a><a href="/validations/plan?id=<?=(int)$validation['id']?>">Plano de testes</a><a href="/validations/results?id=<?=(int)$validation['id']?>">Amostras e resultados</a></nav>
 <section class="validation-overview-kpis"><article><strong><?=(int)$stats['samples']?></strong><span>Amostras</span></article><article><strong><?=(int)$stats['completed']?></strong><span>Concluídas</span></article><article><strong><?=(int)$stats['pending']?></strong><span>Pendentes</span></article><article><strong><?=(int)$resultStats['filled'].' / '.(int)$resultStats['expected']?></strong><span>Resultados</span></article></section>
 <section class="content-card validation-overview">
  <div class="validation-section"><div class="validation-section-heading"><h3>Etapas</h3><?php if($canCreate):?><button class="button button-compact" type="button" data-open-new-phase>+ Criar próxima etapa</button><?php endif;?></div>
   <div class="validation-phase-list"><?php foreach($phases as$p):?>
    <article class="validation-phase-item"><header><div><small>ETAPA <?=(int)$p['sequence_order']?></small><strong><?=$e($p['name'])?></strong></div><span class="status status-<?=$e($p['status'])?>"><?=$e($phaseLabels[$p['status']]??$p['status'])?></span></header>
     <div class="validation-phase-dates"><span>Início: <?=$date($p['started_at'])?></span><?php if($p['completed_at']):?><span>Conclusão: <?=$date($p['completed_at'])?></span><?php endif;?></div>
     <div class="validation-phase-counts"><span><b><?=(int)$p['sample_count']?></b> amostras</span><span><b><?=(int)$p['completed_count']?></b> concluídas</span><span><b><?=(int)$p['filled_results'].' / '.(int)$p['expected_results']?></b> resultados</span></div>
     <?php if($p['outcome']):?><p class="validation-phase-outcome"><b>Resultado:</b> <?=$e($outcomes[$p['outcome']]??$p['outcome'])?></p><?php endif;?>
     <?php if($p['conclusion']):?><div class="validation-phase-conclusion"><b>Conclusão</b><p><?=nl2br($e($p['conclusion']))?></p></div><?php endif;?>
     <footer><a class="button button-secondary button-compact" href="/validations/results?id=<?=(int)$validation['id']?>&phase=<?=(int)$p['id']?>"><?=$p['status']==='active'?'Abrir resultados':'Ver resultados'?></a><?php if($canManage&&$p['status']==='active'):?><button class="button button-compact" type="button" data-open-complete-phase data-phase-id="<?=(int)$p['id']?>" data-phase-name="<?=$e($p['name'])?>">Concluir etapa</button><?php endif;?></footer>
    </article><?php endforeach;?></div>
  </div>
  <div class="validation-section"><h3>Plano de testes</h3><?php if($components):?><div class="validation-component-list"><?php foreach($components as$c):?><span><?=$e($c['code'].' — '.$c['name'])?></span><?php endforeach;?></div><?php else:?><div class="validation-empty"><p>Plano de testes ainda não configurado.</p><?php if(!$readOnly&&\BloodHub\Core\Permission::can('validations.configure_tests')):?><a class="button" href="/validations/plan?id=<?=(int)$validation['id']?>">Configurar plano de testes</a><?php endif;?></div><?php endif;?></div>
  <?php if($validation['status']==='completed'&&!empty($validation['final_conclusion'])):?><div class="validation-final-conclusion"><h3>Conclusão final da validação</h3><p><?=nl2br($e($validation['final_conclusion']))?></p></div><?php endif;?>
  <?php if(!$readOnly&&\BloodHub\Core\Permission::can('validations.complete')):?><div class="validation-complete-area"><div><strong>Concluir validação</strong><p><?=$e($completionBlocker?:'A última etapa foi satisfatória. Registre a conclusão final.')?></p></div><button class="button" type="button" data-open-complete-validation <?=$completionBlocker?'disabled':''?>>Concluir validação</button></div><?php endif;?>
 </section>
</div>

<div class="modal-backdrop" data-complete-phase-modal hidden><section class="modal-card"><h2 data-complete-phase-title>Concluir etapa</h2><p>Registre a avaliação desta rodada antes de encerrá-la.</p><form method="post" action="/validations/phases/complete"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id" value="<?=(int)$validation['id']?>"><input type="hidden" name="phase_id" data-phase-id-input><label><span>Resultado da etapa *</span><select name="outcome" required><option value="">Selecione</option><option value="satisfactory">Satisfatória</option><option value="unsatisfactory">Insatisfatória — requer nova etapa</option><option value="inconclusive">Inconclusiva — requer nova etapa</option></select></label><label><span>Conclusão da etapa *</span><textarea name="conclusion" required></textarea></label><div class="form-actions"><button class="button button-secondary" type="button" data-close-modal>Voltar</button><button class="button">Concluir etapa</button></div></form></section></div>
<div class="modal-backdrop" data-new-phase-modal hidden><section class="modal-card"><h2>Criar Etapa <?=$nextSequence?></h2><form method="post" action="/validations/phases/create"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id" value="<?=(int)$validation['id']?>"><label><span>Nome da etapa</span><input name="name" value="Etapa <?=$nextSequence?>" required></label><label><span>Data de início</span><input type="date" name="start_date" value="<?=date('Y-m-d')?>" required></label><label class="validation-check"><input type="checkbox" name="copy_plan" value="1" checked> Copiar plano de testes da etapa anterior</label><div class="form-actions"><button class="button button-secondary" type="button" data-close-modal>Cancelar</button><button class="button">Criar etapa</button></div></form></section></div>
<div class="modal-backdrop" data-complete-validation-modal hidden><section class="modal-card"><h2>Concluir validação</h2><dl class="validation-modal-summary"><div><dt>PV</dt><dd><?=$e($validation['pv_number'])?></dd></div><div><dt>Nome</dt><dd><?=$e($validation['name'])?></dd></div><div><dt>Unidade</dt><dd><?=$e($validation['unit_name']??'—')?></dd></div><div><dt>Etapas</dt><dd><?=count($phases)?></dd></div><div><dt>Período</dt><dd><?=$date($validation['start_date'])?> — <?=date('d/m/Y')?></dd></div></dl><form method="post" action="/validations/complete"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id" value="<?=(int)$validation['id']?>"><label><span>Conclusão final da validação *</span><textarea name="final_conclusion" required></textarea></label><div class="form-actions"><button class="button button-secondary" type="button" data-close-modal>Voltar</button><button class="button">Concluir validação</button></div></form></section></div>
<script>(()=>{const open=(selector)=>{const modal=document.querySelector(selector);if(modal)modal.hidden=false};document.querySelector('[data-open-new-phase]')?.addEventListener('click',()=>open('[data-new-phase-modal]'));document.querySelector('[data-open-complete-validation]')?.addEventListener('click',()=>open('[data-complete-validation-modal]'));document.querySelectorAll('[data-open-complete-phase]').forEach(button=>button.addEventListener('click',()=>{const modal=document.querySelector('[data-complete-phase-modal]');modal.querySelector('[data-phase-id-input]').value=button.dataset.phaseId;modal.querySelector('[data-complete-phase-title]').textContent='Concluir '+button.dataset.phaseName;modal.hidden=false}));document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',()=>button.closest('.modal-backdrop').hidden=true));})();</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
