<?php
declare(strict_types=1);
namespace BloodHub\Controllers\Admin;

use BloodHub\Core\{AdminGuard,Auth,Csrf,Database,Flash,SamplePurpose,StatusLabel};
use BloodHub\Services\AdministrativeCorrectionService;
use PDO;

final class CorrectionController
{
    private const PERMISSION='admin_corrections.manage';
    public static function index():void
    {
        self::guard();$pdo=Database::connection();$page=max(1,(int)($_GET['page']??1));$perPage=10;$where=['1=1'];$params=[];
        $filters=['donation'=>trim((string)($_GET['donation']??'')),'lcqh'=>trim((string)($_GET['lcqh']??'')),'component'=>(int)($_GET['component']??0),'origin'=>(int)($_GET['origin']??0),'purpose'=>trim((string)($_GET['purpose']??'')),'status'=>trim((string)($_GET['status']??'')),'received_from'=>trim((string)($_GET['received_from']??'')),'received_to'=>trim((string)($_GET['received_to']??'')),'corrected'=>trim((string)($_GET['corrected']??''))];
        foreach(['donation'=>'s.donation_number','lcqh'=>'s.lcqh_code'] as$key=>$column)if($filters[$key]!==''){$where[]="$column LIKE :$key";$params[$key]='%'.$filters[$key].'%';}
        foreach(['component'=>'s.blood_component_id','origin'=>'s.origin_unit_id'] as$key=>$column)if($filters[$key]){$where[]="$column=:$key";$params[$key]=$filters[$key];}
        foreach(['purpose'=>'s.purpose','status'=>'s.status'] as$key=>$column)if($filters[$key]!==''){$where[]="$column=:$key";$params[$key]=$filters[$key];}
        if($filters['received_from']!==''){$where[]='DATE(s.received_at)>=:received_from';$params['received_from']=$filters['received_from'];}if($filters['received_to']!==''){$where[]='DATE(s.received_at)<=:received_to';$params['received_to']=$filters['received_to'];}
        if($filters['corrected']==='yes')$where[]='EXISTS(SELECT 1 FROM administrative_corrections ac WHERE ac.sample_id=s.id)';elseif($filters['corrected']==='no')$where[]='NOT EXISTS(SELECT 1 FROM administrative_corrections ac WHERE ac.sample_id=s.id)';$sql=implode(' AND ',$where);
        $q=$pdo->prepare("SELECT COUNT(*) FROM samples s WHERE $sql");$q->execute($params);$total=(int)$q->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);$offset=($page-1)*$perPage;
        $q=$pdo->prepare("SELECT s.*,bc.name component_name,u.name origin_name,c.name client_name,(SELECT COUNT(*) FROM test_results tr JOIN sample_tests st ON st.id=tr.sample_test_id WHERE st.sample_id=s.id) result_count,EXISTS(SELECT 1 FROM administrative_corrections ac WHERE ac.sample_id=s.id) corrected FROM samples s LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN clients c ON c.id=s.client_id WHERE $sql ORDER BY s.registered_at DESC,s.id DESC LIMIT $perPage OFFSET $offset");$q->execute($params);$samples=$q->fetchAll(PDO::FETCH_ASSOC);foreach($samples as&$sample){$sample['purpose_label']=SamplePurpose::label((string)$sample['purpose']);$sample['status_label']=StatusLabel::sample((string)$sample['status']);}unset($sample);
        $metrics=['located'=>$total,'corrections'=>(int)$pdo->query("SELECT COUNT(*) FROM administrative_corrections WHERE corrected_at>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')")->fetchColumn(),'cancellations'=>(int)$pdo->query("SELECT COUNT(*) FROM administrative_corrections WHERE correction_type='SAMPLE_STATUS' AND corrected_at>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')")->fetchColumn(),'results'=>(int)$pdo->query("SELECT COUNT(*) FROM administrative_corrections WHERE correction_type IN('LAB_RESULT','BACTERIOLOGY_RESULT','POOL_RESULT') AND corrected_at>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')")->fetchColumn()];
        $components=$pdo->query("SELECT id,name FROM blood_components WHERE status='active' ORDER BY name")->fetchAll();$units=$pdo->query("SELECT id,name FROM units WHERE status='active' ORDER BY name")->fetchAll();$purposeOptions=SamplePurpose::OPTIONS;$pageTitle='Correções administrativas';$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__,2).'/Views/admin/corrections/index.php';
    }
    public static function show():void
    {
        self::guard();$id=(int)($_GET['id']??0);$pdo=Database::connection();$q=$pdo->prepare('SELECT s.*,bc.name component_name,bc.code component_code,u.name origin_name,c.name client_name,bb.name bag_brand_name,p.name preservative_name,v.pv_number validation_code,vp.name validation_phase FROM samples s LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN clients c ON c.id=s.client_id LEFT JOIN bag_brands bb ON bb.id=s.bag_brand_id LEFT JOIN preservatives p ON p.id=s.preservative_id LEFT JOIN validations v ON v.id=s.validation_id LEFT JOIN validation_phases vp ON vp.id=s.validation_phase_id WHERE s.id=:id');$q->execute(['id'=>$id]);$sample=$q->fetch(PDO::FETCH_ASSOC);if(!$sample){http_response_code(404);echo'Amostra não encontrada.';return;}
        $results=self::results($id);$bacteriology=self::bacteriology($id);$dependencies=AdministrativeCorrectionService::dependencies($id);$q=$pdo->prepare('SELECT ac.*,u.name user_name,u.email user_email FROM administrative_corrections ac LEFT JOIN users u ON u.id=ac.corrected_by WHERE ac.sample_id=:id ORDER BY ac.corrected_at DESC,ac.id DESC');$q->execute(['id'=>$id]);$history=$q->fetchAll(PDO::FETCH_ASSOC);$q=$pdo->prepare('SELECT al.*,u.name user_name FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id WHERE (al.entity_type=\'samples\' AND al.entity_id=:id) OR (al.entity_type=\'test_results\' AND al.entity_id IN(SELECT tr.id FROM test_results tr JOIN sample_tests st ON st.id=tr.sample_test_id WHERE st.sample_id=:id2)) ORDER BY al.created_at DESC LIMIT 100');$q->execute(['id'=>$id,'id2'=>$id]);$audits=$q->fetchAll(PDO::FETCH_ASSOC);
        $components=$pdo->query("SELECT id,name FROM blood_components WHERE status='active' ORDER BY name")->fetchAll();$units=$pdo->query("SELECT id,name FROM units WHERE status='active' ORDER BY name")->fetchAll();$pageTitle='Correções administrativas';$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__,2).'/Views/admin/corrections/show.php';
    }
    public static function identification():void{self::post();try{AdministrativeCorrectionService::correctIdentification((int)($_POST['sample_id']??0),$_POST,trim((string)($_POST['reason']??'')));Flash::set('success','Identificação corrigida e registrada no histórico.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back();}
    public static function cancel():void{self::post();try{AdministrativeCorrectionService::cancelSample((int)($_POST['sample_id']??0),trim((string)($_POST['reason']??'')));Flash::set('success','Amostra cancelada sem exclusão dos dados históricos.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back();}
    public static function result():void{self::post();try{AdministrativeCorrectionService::correctResult((int)($_POST['sample_id']??0),(int)($_POST['result_id']??0),$_POST['new_value']??null,trim((string)($_POST['reason']??'')));Flash::set('success','Resultado retificado e cadeia de dependências reavaliada.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back();}
    public static function bacteriologyResult():void{self::post();try{AdministrativeCorrectionService::correctBacteriology((int)($_POST['sample_id']??0),(int)($_POST['result_id']??0),(string)($_POST['new_value']??''),trim((string)($_POST['reason']??'')));Flash::set('success','Resultado bacteriológico retificado; o workflow anterior foi preservado.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back();}
    public static function parameter():void{self::post();try{AdministrativeCorrectionService::correctParameter((int)($_POST['sample_id']??0),(int)($_POST['parameter_id']??0),$_POST['new_value']??null,trim((string)($_POST['reason']??'')));Flash::set('success','Dado primário retificado e resultados dependentes recalculados.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back();}
    private static function post():void{self::guard();if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada. Tente novamente.');self::back();}}
    private static function guard():void{AdminGuard::enforce(self::PERMISSION);}
    private static function back():never{$id=(int)($_POST['sample_id']??0);header('Location: /admin/corrections/view?id='.$id);exit;}
    private static function results(int$id):array{$q=Database::connection()->prepare("SELECT tr.id,st.status,t.id test_id,t.code,t.name,t.unit,t.result_type,tr.result_value_numeric,tr.result_value_text,tr.recorded_at,u.name responsible,e.conformity_status,e.specification_snapshot_text,e.specification_id,CASE WHEN t.code IN('VOLUME','HEMOGLOBIN_PER_UNIT','HEMOLYSIS_DEGREE','FREE_HEMOGLOBIN','PLATELETS_PER_UNIT','LEUKOCYTES_PER_UNIT','PLATELETS_PER_ML','LEUKOCYTES_PER_ML','REDBLOODCELLS_PER_ML','RECOVERY','RESIDUAL_PROTEIN','FIBRINOGEN') THEN 1 ELSE 0 END calculated FROM test_results tr JOIN sample_tests st ON st.id=tr.sample_test_id JOIN tests t ON t.id=st.test_id LEFT JOIN users u ON u.id=tr.recorded_by LEFT JOIN test_result_spec_evaluations e ON e.test_result_id=tr.id WHERE st.sample_id=:id ORDER BY t.name,tr.id");$q->execute(['id'=>$id]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as&$r){$r['value']=$r['result_value_numeric']!==null?$r['result_value_numeric']:$r['result_value_text'];$p=Database::connection()->prepare("SELECT id,parameter_code,parameter_name,numeric_value FROM test_result_parameters WHERE test_result_id=:id AND parameter_code LIKE 'abs_%' ORDER BY parameter_code");$p->execute(['id'=>$r['id']]);$r['parameters']=$p->fetchAll(PDO::FETCH_ASSOC);}return$rows;}
    private static function bacteriology(int$id):array{$q=Database::connection()->prepare('SELECT br.*,u.name responsible,bp.code pool_code,(SELECT COUNT(*) FROM bacteriology_retests rt WHERE rt.initial_result_id=br.id) retest_count,(SELECT COUNT(*) FROM bacteriology_positive_samples ps WHERE ps.bacteriology_result_id=br.id) positive_count FROM bacteriology_results br LEFT JOIN users u ON u.id=br.performed_by LEFT JOIN bacteriology_pools bp ON bp.id=br.pool_id WHERE br.sample_id=:id ORDER BY br.performed_at DESC,br.id DESC');$q->execute(['id'=>$id]);return$q->fetchAll(PDO::FETCH_ASSOC);}
    public static function relatedInvestigation(int$id):array{$q=Database::connection()->prepare('SELECT r.id,r.donation_number,COALESCE(bc.name,r.hemocomponent) component_name,r.situation,COALESCE(u.name,r.storage_location) storage_location,r.perform_bacteriology,r.operational_notes,t.sequence,t.attempt_type,t.status test_status,t.result,t.identified_bacteria,t.tested_at FROM bacteriology_positive_samples ps JOIN bacteriology_positive_sample_records r ON r.positive_sample_id=ps.id LEFT JOIN blood_components bc ON bc.id=r.blood_component_id LEFT JOIN units u ON u.id=r.storage_unit_id LEFT JOIN bacteriology_positive_record_tests t ON t.positive_record_id=r.id WHERE ps.sample_id=:id ORDER BY r.position,t.sequence');$q->execute(['id'=>$id]);return$q->fetchAll(PDO::FETCH_ASSOC);}
}
