<?php
$situationLabels=['in_stock'=>'Em estoque','distributed'=>'Distribuído','discarded'=>'Descartado'];
$statusLabels=['no_test'=>'SEM TESTE','waiting'=>'AGUARDANDO RESULTADO','retest'=>'EM RETESTE','negative'=>'NEGATIVO','positive_confirmed'=>'POSITIVO CONFIRMADO'];
$sourceBacteria=$openPositive['source_bacteria_retest']?:$openPositive['source_bacteria_initial'];
?>
<dialog class="rt-related-dialog" aria-labelledby="rt-related-title">
 <div class="rt-related-shell">
  <header class="rt-related-title"><div><small>REAÇÃO TRANSFUSIONAL</small><h2 id="rt-related-title">Amostras Positivas / Componentes relacionados</h2><p>Investigação individual dos hemocomponentes produzidos a partir da mesma doação.</p></div><button type="button" class="button button-secondary button-compact" data-related-main-close>Fechar</button></header>
  <section class="rt-positive-summary">
   <div><small>Doação</small><strong><?=$e($openPositive['donation_number'])?></strong></div>
   <div><small>Paciente</small><strong><?=$e($openPositive['patient_name']?:'—')?></strong></div>
   <div><small>Amostra principal</small><strong><?=$e($openPositive['source_component']?:'—')?></strong></div>
   <div><small>Código LCQH</small><strong><?=$e($openPositive['lcqh_code']?:'—')?></strong></div>
   <div><small>Resultado</small><strong class="rt-badge positiva-confirmada">POSITIVO CONFIRMADO</strong></div>
   <div><small>Bactéria</small><strong><?=$e($sourceBacteria?:'—')?></strong></div>
  </section>
  <section class="rt-related-list"><header><div><h3>Componentes relacionados da mesma doação</h3><p>O número <?=$e($openPositive['donation_number'])?> é herdado e não pode ser alterado.</p></div><?php if($canEdit):?><button type="button" class="button" data-related-add>+ Adicionar componente relacionado</button><?php endif;?></header>
   <div class="table-responsive"><table><thead><tr><th>Hemocomponente</th><th>Situação</th><th>Local</th><th>Teste bacteriológico</th><th>Resultado</th><th>Bactéria</th><th>Status</th><th>Ações</th></tr></thead><tbody>
   <?php foreach($openPositive['records'] as$r):if((int)$r['blood_component_id']===(int)$openPositive['source_component_id']&&empty($r['situation']))continue;$tests=$r['tests']??[];$last=$tests?end($tests):null;$status=$r['investigation_status'];?><tr>
    <td><strong><?=$e(trim(($r['component_code']??'').' '.$r['hemocomponent']))?></strong></td><td><?=$e($situationLabels[$r['situation']]??$r['situation']??'—')?></td><td><?=$e($r['storage_location']?:'—')?></td><td><?=empty($r['perform_bacteriology'])?'Não':'Sim — individual'?></td><td><?=$last&&$last['result']?$e($last['result']==='positive'?'Positivo':'Negativo'):'—'?></td><td><?=$e($last['identified_bacteria']??'—')?></td><td><span class="rt-badge rt-related-status-<?=$e($status)?>"><?=$e($statusLabels[$status]??$status)?></span></td>
    <td><div class="rt-row-actions"><button type="button" class="button button-secondary button-compact" data-related-open="<?=$r['id']?>">Abrir</button><a class="button button-secondary button-compact" target="_blank" href="/transfusion-reactions/positive-samples/form?id=<?=$openPositive['id']?>&record=<?=$r['id']?>">Imprimir</a></div></td></tr>
    <tr hidden data-related-detail="<?=$r['id']?>"><td colspan="8"><div class="rt-related-detail">
     <form method="post" action="/transfusion-reactions/positive-samples/components/update" class="rt-operational-form"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="positive_sample_id" value="<?=$openPositive['id']?>"><input type="hidden" name="record_id" value="<?=$r['id']?>"><label><span>Situação *</span><select name="situation" required><?php foreach($situationLabels as$value=>$label):?><option value="<?=$value?>" <?=$r['situation']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label data-storage><span>Local de armazenamento</span><select name="storage_unit_id"><option value="">Selecione</option><?php foreach($positiveUnits as$u):?><option value="<?=$u['id']?>" <?=$r['storage_unit_id']==$u['id']?'selected':''?>><?=$e($u['name'])?></option><?php endforeach;?></select></label><label class="rt-related-notes"><span>Observação</span><textarea name="operational_notes" rows="2" maxlength="2000"><?=$e($r['operational_notes']??'')?></textarea></label><?php if($canEdit):?><button class="button button-secondary">Editar dados operacionais</button><?php endif;?></form>
     <?php if($tests):?><div class="rt-related-history"><h4>Histórico bacteriológico individual</h4><?php foreach($tests as$t):?><article><strong><?=$t['attempt_type']==='retest'?'Reteste':'Teste 1'?></strong><span><?=$t['tested_at']?date('d/m/Y H:i',strtotime($t['tested_at'])):'Aguardando resultado'?></span><span><?=$t['result']?($t['result']==='positive'?'Positivo':'Negativo'):'—'?></span><span><?=$e($t['identified_bacteria']?:'—')?></span><span><?=$e($t['notes']?:'')?></span></article><?php endforeach;?></div><?php endif;?>
     <?php if($last&&$last['status']==='pending'&&$canEdit):?><form method="post" action="<?=$last['attempt_type']==='retest'?'/transfusion-reactions/positive-samples/retests/save':'/transfusion-reactions/positive-samples/tests/save'?>" class="rt-related-test" data-related-result><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="positive_sample_id" value="<?=$openPositive['id']?>"><input type="hidden" name="test_id" value="<?=$last['id']?>"><h4><?=$last['attempt_type']==='retest'?'Registrar reteste':'Registrar teste bacteriológico'?></h4><label><span>Resultado *</span><select name="result" required><option value="">Selecione</option><option value="negative">Negativo</option><option value="positive">Positivo</option></select></label><label><span>Data do teste *</span><input type="datetime-local" name="tested_at" value="<?=date('Y-m-d\TH:i')?>" required></label><label data-related-bacteria hidden><span>Bactéria identificada *</span><input name="identified_bacteria" maxlength="255"></label><label class="rt-related-notes"><span>Observação</span><textarea name="notes" maxlength="2000" rows="2"></textarea></label><button class="button"><?=$last['attempt_type']==='retest'?'Concluir reteste':'Salvar resultado'?></button></form><?php elseif(empty($r['perform_bacteriology'])):?><p class="rt-no-test">Sem teste bacteriológico. Situação e local permanecem rastreáveis.</p><?php endif;?>
    </div></td></tr>
   <?php endforeach;?><?php if(!$openPositive['records']):?><tr><td colspan="8" class="qc-empty">Nenhum componente relacionado cadastrado.</td></tr><?php endif;?></tbody></table></div>
  </section>
 </div>
</dialog>
<dialog class="rt-add-related"><form method="post" action="/transfusion-reactions/positive-samples/components/add"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="positive_sample_id" value="<?=$openPositive['id']?>"><header><div><h3>Novo componente relacionado</h3><p>Doação <?=$e($openPositive['donation_number'])?> — vínculo imutável no backend.</p></div><button type="button" class="dialog-x" data-related-close>×</button></header><div class="rt-related-form-grid"><label><span>Hemocomponente *</span><select name="blood_component_id" required><option value="">Selecione</option><?php foreach($positiveComponents as$c):?><option value="<?=$c['id']?>"><?=$e($c['code'].' — '.$c['name'])?></option><?php endforeach;?></select></label><label><span>Situação *</span><select name="situation" required><option value="">Selecione</option><?php foreach($situationLabels as$value=>$label):?><option value="<?=$value?>"><?=$label?></option><?php endforeach;?></select></label><label data-storage hidden><span>Local de armazenamento *</span><select name="storage_unit_id"><option value="">Selecione</option><?php foreach($positiveUnits as$u):?><option value="<?=$u['id']?>"><?=$e($u['name'])?></option><?php endforeach;?></select></label><fieldset><legend>Realizar teste bacteriológico?</legend><label><input type="radio" name="perform_bacteriology" value="yes" required> Sim</label><label><input type="radio" name="perform_bacteriology" value="no" required> Não</label></fieldset><label class="rt-related-notes"><span>Observação</span><textarea name="operational_notes" maxlength="2000" rows="3"></textarea></label></div><footer><button type="button" class="button button-secondary" data-related-close>Cancelar</button><button class="button">Adicionar componente</button></footer></form></dialog>
<script>(()=>{const dialog=document.querySelector('.rt-related-dialog'),add=document.querySelector('.rt-add-related'),previousOverflow=document.body.style.overflow;const unlockBody=()=>{document.body.style.overflow=previousOverflow};const cleanUrl=()=>{const url=new URL(location.href);url.searchParams.delete('open_positive');history.replaceState(history.state,'',url.pathname+(url.searchParams.size?'?'+url.searchParams:'')+url.hash)};const closeMain=()=>{if(add?.open)add.close();if(dialog?.open)dialog.close()};if(dialog){document.body.style.overflow='hidden';dialog.showModal();dialog.querySelector('[data-related-main-close]')?.addEventListener('click',closeMain);dialog.addEventListener('close',()=>{unlockBody();cleanUrl()},{once:true});dialog.addEventListener('click',event=>{const rect=dialog.getBoundingClientRect(),outside=event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom;if(event.target===dialog&&outside)closeMain()});window.addEventListener('pagehide',unlockBody,{once:true})}document.querySelector('[data-related-add]')?.addEventListener('click',()=>{add.showModal();add.querySelector('select, input, textarea, button')?.focus()});add?.querySelectorAll('[data-related-close]').forEach(b=>b.addEventListener('click',()=>add.close()));const syncStorage=form=>{const situation=form.querySelector('[name="situation"]'),box=form.querySelector('[data-storage]'),select=box?.querySelector('select');if(!situation||!box)return;const sync=()=>{const needed=situation.value==='in_stock';box.hidden=!needed;if(select){select.required=needed;if(!needed)select.value=''}};situation.addEventListener('change',sync);sync()};document.querySelectorAll('.rt-add-related form,.rt-operational-form').forEach(syncStorage);document.querySelectorAll('[data-related-open]').forEach(b=>b.addEventListener('click',()=>{const row=document.querySelector(`[data-related-detail="${b.dataset.relatedOpen}"]`);row.hidden=!row.hidden;b.textContent=row.hidden?'Abrir':'Fechar'}));document.querySelectorAll('[data-related-result]').forEach(form=>{const select=form.querySelector('[name="result"]'),wrap=form.querySelector('[data-related-bacteria]'),input=wrap.querySelector('input');const sync=()=>{const show=select.value==='positive';wrap.hidden=!show;input.required=show;if(!show)input.value=''};select.addEventListener('change',sync);sync()})})();</script>
