<?php
use BloodHub\Core\SamplePurpose;
require dirname(__DIR__).'/layouts/admin_start.php';
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$tab=$_GET['tab']??'summary';
$status=$matrix['period']['status']??'OPEN';
$statusLabels=['OPEN'=>'Em aberto','REVIEWED'=>'Revisado','CLOSED'=>'Fechado','REOPENED'=>'Reaberto'];
$monthNames=[1=>'Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
$pendingCount=count($matrix['unmapped'])+count($matrix['missingCenters']);
?>
<section class="billing-toolbar card">
 <form method="get" class="billing-filters">
  <label>Mês<select name="month"><?php foreach($monthNames as$m=>$name):?><option value="<?=$m?>" <?=$m===$month?'selected':''?>><?=$name?></option><?php endforeach?></select></label>
  <label>Ano<input name="year" type="number" min="2000" max="2100" value="<?=$year?>"></label>
  <label>Tipo de cliente<select name="client_type" <?=$scope['restricted']?'disabled':''?>><option value="all" <?=$scope['type']==='all'?'selected':''?>>Todos</option><option value="internal" <?=$scope['type']==='internal'?'selected':''?>>Internos</option><option value="external" <?=$scope['type']==='external'?'selected':''?>>Externos</option></select></label>
  <label><?=$scope['type']==='external'?'Cliente externo':'Cliente'?><select name="client_id" <?=$scope['restricted']?'disabled':''?>><option value="">Todos os clientes</option><?php foreach($clients as$c):?><option value="<?=$c['id']?>" data-client-type="<?=$e($c['client_type'])?>" <?=$scope['client_id']==$c['id']?'selected':''?>><?=$e($c['name'])?><?=$c['status']==='inactive'?' (inativo)':''?></option><?php endforeach?></select></label>
  <?php if($scope['restricted']):?><input type="hidden" name="client_type" value="<?=$e($scope['type'])?>"><input type="hidden" name="client_id" value="<?=$scope['client_id']?>"><?php endif?>
  <button class="btn btn-primary billing-load" type="submit">Carregar faturamento</button>
 </form>
 <div class="billing-actions"><a class="billing-export" href="/billing/export?<?=http_build_query(['year'=>$year,'month'=>$month,'client_type'=>$scope['type'],'client_id'=>$scope['client_id']])?>">Exportar CSV</a><span class="status-pill status-<?=strtolower($status)?>"><?=$e($statusLabels[$status]??$status)?></span></div>
</section>
<nav class="billing-tabs" aria-label="Seções do faturamento"><a class="<?=$tab==='summary'?'active':''?>" href="?year=<?=$year?>&month=<?=$month?>&tab=summary">Resumo mensal</a><a class="<?=$tab==='manual'?'active':''?>" href="?year=<?=$year?>&month=<?=$month?>&tab=manual">Lançamentos complementares</a></nav>
<?php if($tab==='manual'): ?>
<section class="card billing-panel"><h2>Lançamentos complementares</h2><p>Use somente para serviços sem fonte automática no BloodHub.</p><?php if($canManual&&$status!=='CLOSED'):?><form method="post" action="/billing/manual/save" class="billing-form"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><label>Centro<select name="center" required><option value="">Selecione</option><?php foreach($catalogs['centers']as$c)if($c['active']):?><option value="<?=$c['id']?>"><?=$e($c['cost_center_code'].' — '.$c['name'])?></option><?php endif?></select></label><label>Serviço<select name="service" required><option value="">Selecione</option><?php foreach($catalogs['services']as$s)if($s['active']):?><option value="<?=$s['id']?>"><?=$e($s['service_code'].' — '.$s['name'])?></option><?php endif?></select></label><label>Quantidade<input type="number" name="quantity" min="1" required></label><label class="wide">Observação<input name="notes" maxlength="1000"></label><button class="billing-btn-primary">Adicionar lançamento</button></form><?php endif?><div class="table-wrap"><table><thead><tr><th>Centro</th><th>Serviço</th><th>Quantidade</th><th>Observação</th><th>Criado por</th><th></th></tr></thead><tbody><?php foreach($entries as$r):?><tr><td><?=$e($r['cost_center_code'].' — '.$r['center_name'])?></td><td><?=$e($r['service_code'].' — '.$r['service_name'])?></td><td><?=$r['quantity']?></td><td><?=$e($r['notes'])?></td><td><?=$e($r['created_by_name'])?></td><td><?php if($canManual&&$status!=='CLOSED'):?><form method="post" action="/billing/manual/remove"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="link-danger">Remover</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<?php else: ?>
<section class="billing-kpis"><article><span>Centros de custo</span><strong><?=count($matrix['centers'])?></strong></article><article><span>Resultados finais contabilizados</span><strong><?=$matrix['total']?></strong></article><article><span>Serviços com movimento</span><strong><?=count(array_filter($matrix['totals']))?></strong></article><article><span>Resultados sem serviço associado</span><strong><?=count($matrix['unmapped'])?></strong></article></section>
<?php if($pendingCount):?><section class="billing-pending card" aria-labelledby="pending-title"><header><span class="pending-icon" aria-hidden="true">!</span><div><h2 id="pending-title">Pendências para revisão</h2><p><?=$pendingCount?> <?=$pendingCount===1?'pendência identificada':'pendências identificadas'?></p></div><span class="pending-count"><?=$pendingCount?></span></header><div class="pending-list"><?php foreach($matrix['unmapped']as$p):?><article><strong>Resultado final sem serviço de faturamento associado</strong><span><?=$e(($p['component_code']?:'Sem componente').' — '.$p['name'])?></span><span>Não foi definido em qual serviço do faturamento este resultado deve ser contabilizado.</span><small>Contexto: <?=$e(SamplePurpose::label((string)$p['context_scope']))?> · Resultados encontrados: <?=$p['quantity']?></small></article><?php endforeach?><?php foreach($matrix['missingCenters']as$p):?><article><strong>Unidade sem centro de custo de faturamento associado</strong><span><?=$e($p['name'])?></span><span>Este resultado possui serviço de faturamento definido, mas a unidade ainda não está vinculada a um centro de custo.</span><small><?=$p['quantity']??0?> <?=($p['quantity']??0)==1?'resultado final':'resultados finais'?></small></article><?php endforeach?></div></section><?php endif?>
<section class="card billing-matrix"><header class="matrix-heading"><h2>Resumo por centro de custo</h2><p>Quantidades de resultados finais contabilizados por serviço.</p></header><div class="matrix-scroll"><table style="--service-count:<?=count($matrix['services'])?>"><thead><tr><th class="sticky c1">Código</th><th class="sticky c2">Centro de custo</th><?php foreach($matrix['services']as$s):?><th class="service-column" title="<?=$e($s['service_code'].' — '.$s['name'])?>"><span><?=$e($s['service_code'])?></span><small><?=$e($s['name'])?></small></th><?php endforeach?></tr></thead><tbody><?php foreach($matrix['rows']as$r):?><tr><td class="sticky c1"><?=$e($r['center']['cost_center_code'])?></td><td class="sticky c2"><?=$e($r['center']['name'])?></td><?php foreach($matrix['services']as$s):$v=$r['values'][(int)$s['id']];?><td><?php if($v):?><a href="/billing/detail?year=<?=$year?>&month=<?=$month?>&center=<?=$r['center']['id']?>&service=<?=$s['id']?>"><?=$v?></a><?php else:?>0<?php endif?></td><?php endforeach?></tr><?php endforeach?><tr class="total"><td class="sticky c1"></td><td class="sticky c2">TOTAL</td><?php foreach($matrix['services']as$s):?><td><?=$matrix['totals'][(int)$s['id']]?></td><?php endforeach?></tr></tbody></table></div></section>
<section class="billing-close card"><h2>Revisão e fechamento da competência</h2><?php if($status==='CLOSED'&&$canReopen):?><form method="post" action="/billing/reopen"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><label>Motivo da reabertura <input name="reason" required maxlength="1000"></label><button class="btn">Reabrir competência</button></form><?php elseif($canClose):?><?php $hasBillingPending=(bool)($matrix['unmapped']||$matrix['missingCenters']);$closeDisabled=$hasBillingPending||$status!=='REVIEWED';?><div class="billing-actions"><?php if($status!=='REVIEWED'):?><form method="post" action="/billing/review"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><button class="billing-btn-secondary" <?=$hasBillingPending?'disabled title="Resolva as pendências de faturamento antes de continuar."':''?>>Marcar como revisada</button></form><?php endif?><form method="post" action="/billing/close"><input type="hidden" name="_csrf" value="<?=$csrf?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><button class="billing-btn-primary" <?=$closeDisabled?'disabled':''?> <?=$hasBillingPending?'title="Resolva as pendências de faturamento antes de continuar."':''?>>Fechar competência</button></form></div><?php endif?></section>
<?php endif?>
<?php if($details):?><div class="billing-modal"><div><a class="modal-close" href="/billing?year=<?=$year?>&month=<?=$month?>">×</a><h2>Resultados que compõem este total</h2><div class="table-wrap"><table><thead><tr><th>Data da conclusão</th><th>Doação/amostra</th><th>Hemocomponente</th><th>Contexto</th><th>Resultado final</th><th>Unidade</th><th>Código LCQH</th><th>Responsável</th></tr></thead><tbody><?php foreach($details as$d):?><tr><td><?=$e($d['completed_at']??'')?></td><td><?=$e(($d['donation_number']??'')?:($d['sample_code']??''))?></td><td><?=$e($d['component_name']??'—')?></td><td><?=$e(SamplePurpose::label((string)($d['context_scope']??'')))?></td><td><?=$e($d['test_name']??'')?></td><td><?=$e($d['unit_name']??'—')?></td><td><?=$e($d['lcqh_code']??'—')?></td><td><?=$e($d['responsible_name']??'')?></td></tr><?php endforeach?></tbody></table></div></div></div><?php endif?>
<script>document.addEventListener('DOMContentLoaded',()=>{const t=document.querySelector('.billing-filters [name="client_type"]'),c=document.querySelector('.billing-filters [name="client_id"]');if(!t||!c||t.disabled)return;const sync=()=>{for(const o of c.options){if(!o.value)continue;o.hidden=t.value!=='all'&&o.dataset.clientType!==t.value;}if(c.selectedOptions[0]?.hidden)c.value='';};t.addEventListener('change',sync);sync();});</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
