<?php
declare(strict_types=1);

use BloodHub\Controllers\AuthController;
use BloodHub\Controllers\DashboardController;
use BloodHub\Controllers\ProfileController;
use BloodHub\Controllers\SettingsController;
use BloodHub\Controllers\ChatController;
use BloodHub\Controllers\SampleController;
use BloodHub\Controllers\ReceptionController;
use BloodHub\Controllers\ShipmentController;
use BloodHub\Controllers\QualityControlController;
use BloodHub\Controllers\FactorViiiPoolController;
use BloodHub\Controllers\BacteriologyController;
use BloodHub\Controllers\TransfusionReactionController;
use BloodHub\Controllers\TransfusionReactionConsultationController;
use BloodHub\Controllers\NotificationController;
use BloodHub\Controllers\ValidationController;
use BloodHub\Controllers\ProductionController;
use BloodHub\Controllers\SamplingScheduleController;
use BloodHub\Controllers\QualityControlReportController;
use BloodHub\Controllers\IndicatorController;
use BloodHub\Controllers\QcMonthlyClosureController;
use BloodHub\Controllers\BillingController;
use BloodHub\Controllers\LaboratoryReportController;
use BloodHub\Controllers\Admin\EquipmentController;
use BloodHub\Controllers\Admin\ReportConfigController;
use BloodHub\Controllers\Admin\SamplingScheduleController as AdminSamplingScheduleController;
use BloodHub\Controllers\Admin\UserController;
use BloodHub\Controllers\Admin\RoleController;
use BloodHub\Controllers\Admin\PermissionController;
use BloodHub\Controllers\Admin\ClientController;
use BloodHub\Controllers\Admin\UnitController;
use BloodHub\Controllers\Admin\BloodComponentController;
use BloodHub\Controllers\Admin\TestController;
use BloodHub\Controllers\Admin\SupplyController;
use BloodHub\Controllers\Admin\BagBrandController;
use BloodHub\Controllers\Admin\PreservativeController;
use BloodHub\Controllers\Admin\CorrectionController;
use BloodHub\Controllers\Admin\DashboardTargetController;
use BloodHub\Controllers\Admin\IndicatorConfigController;
use BloodHub\Controllers\Admin\BillingConfigController;
use BloodHub\Core\Router;

header('Content-Type: text/html; charset=UTF-8');

$sessionPath = getenv('SESSION_SAVE_PATH') ?: dirname(__DIR__) . '/storage/sessions';
if (!is_dir($sessionPath)) mkdir($sessionPath, 0770, true);
if (is_dir($sessionPath) && is_writable($sessionPath)) session_save_path($sessionPath);
session_start();

spl_autoload_register(function (string $class): void {
    $prefix = 'BloodHub\\';
    $baseDir = dirname(__DIR__) . '/src/';
    if (!str_starts_with($class, $prefix)) return;
    $relative = substr($class, strlen($prefix));
    $file = $baseDir . str_replace('\\', '/', $relative) . '.php';
    if (file_exists($file)) require $file;
});

$router = new Router();
$router->get('/', [DashboardController::class, 'index']);
$router->get('/dashboard-global/report', [DashboardController::class, 'report']);
$router->get('/reports/quality-control', [QualityControlReportController::class, 'index']);
$router->get('/reports/quality-control/detail', [QualityControlReportController::class, 'detail']);
$router->get('/reports/quality-control/csv', [QualityControlReportController::class, 'csv']);
$router->get('/reports/quality-control/pdf', [QualityControlReportController::class, 'pdf']);
$router->get('/indicators', [IndicatorController::class, 'index']);
$router->get('/monthly-closures', [QcMonthlyClosureController::class, 'index']);
$router->get('/monthly-closures/view', [QcMonthlyClosureController::class, 'show']);
$router->post('/monthly-closures/close', [QcMonthlyClosureController::class, 'close']);
$router->post('/monthly-closures/reopen', [QcMonthlyClosureController::class, 'reopen']);
$router->get('/monthly-closures/pdf', [QcMonthlyClosureController::class, 'pdf']);
$router->get('/billing', [BillingController::class, 'index']);
$router->get('/reports', [LaboratoryReportController::class, 'index']);
$router->get('/reports/preview', [LaboratoryReportController::class, 'preview']);
$router->get('/reports/view', [LaboratoryReportController::class, 'show']);
$router->get('/reports/download', [LaboratoryReportController::class, 'download']);
$router->post('/reports/release', [LaboratoryReportController::class, 'release']);
$router->post('/reports/revise', [LaboratoryReportController::class, 'revise']);
$router->post('/reports/cancel', [LaboratoryReportController::class, 'cancel']);
$router->get('/admin/equipment', [EquipmentController::class, 'index']);
$router->post('/admin/equipment/save', [EquipmentController::class, 'save']);
$router->post('/admin/equipment/assign', [EquipmentController::class, 'assign']);
$router->get('/admin/reports', [ReportConfigController::class, 'index']);
$router->post('/admin/reports', [ReportConfigController::class, 'save']);
$router->get('/billing/detail', [BillingController::class, 'detail']);
$router->get('/billing/export', [BillingController::class, 'export']);
$router->post('/billing/manual/save', [BillingController::class, 'manualSave']);
$router->post('/billing/manual/remove', [BillingController::class, 'manualRemove']);
$router->post('/billing/close', [BillingController::class, 'close']);
$router->post('/billing/review', [BillingController::class, 'review']);
$router->post('/billing/reopen', [BillingController::class, 'reopen']);
$router->get('/indicators/hemocomponents-within-specifications', [IndicatorController::class, 'withinSpecifications']);
$router->get('/indicators/platelet-mean-concentration', [IndicatorController::class, 'plateletMean']);
$router->post('/indicators/analysis/save', [IndicatorController::class, 'saveAnalysis']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/profile', [ProfileController::class, 'show']);
$router->post('/profile', [ProfileController::class, 'update']);
$router->get('/admin', [SettingsController::class, 'index']);
$router->get('/admin/dashboard-targets', [DashboardTargetController::class, 'index']);
$router->post('/admin/dashboard-targets', [DashboardTargetController::class, 'save']);
$router->get('/admin/indicators', [IndicatorConfigController::class, 'index']);
$router->post('/admin/indicators/metadata', [IndicatorConfigController::class, 'saveMetadata']);
$router->post('/admin/indicators/target', [IndicatorConfigController::class, 'saveTarget']);
$router->post('/admin/indicators/responsibles/add', [IndicatorConfigController::class, 'addResponsible']);
$router->post('/admin/indicators/responsibles/remove', [IndicatorConfigController::class, 'removeResponsible']);
$router->post('/admin/indicators/target/update', [IndicatorConfigController::class, 'updateTarget']);
$router->post('/admin/indicators/target/delete', [IndicatorConfigController::class, 'deleteTarget']);
$router->get('/admin/billing', [BillingConfigController::class, 'index']);
$router->post('/admin/billing/mapping', [BillingConfigController::class, 'mapping']);
$router->post('/admin/billing/catalog', [BillingConfigController::class, 'catalog']);
$router->get('/admin/corrections', [CorrectionController::class, 'index']);
$router->get('/admin/corrections/view', [CorrectionController::class, 'show']);
$router->post('/admin/corrections/identification', [CorrectionController::class, 'identification']);
$router->post('/admin/corrections/cancel', [CorrectionController::class, 'cancel']);
$router->post('/admin/corrections/result', [CorrectionController::class, 'result']);
$router->post('/admin/corrections/parameter', [CorrectionController::class, 'parameter']);
$router->post('/admin/corrections/bacteriology', [CorrectionController::class, 'bacteriologyResult']);
$router->get('/chat', [ChatController::class, 'index']);
$router->get('/chat/conversations', [ChatController::class, 'conversations']);
$router->get('/chat/users', [ChatController::class, 'users']);
$router->get('/chat/sectors', [ChatController::class, 'sectors']);
$router->get('/chat/participants', [ChatController::class, 'participants']);
$router->get('/chat/messages', [ChatController::class, 'messages']);
$router->get('/chat/unread', [ChatController::class, 'unread']);
$router->post('/chat/send', [ChatController::class, 'send']);
$router->post('/chat/read', [ChatController::class, 'read']);
$router->post('/chat/private', [ChatController::class, 'privateConversation']);
$router->post('/chat/group', [ChatController::class, 'groupConversation']);
$router->post('/chat/archive', [ChatController::class, 'archiveConversation']);
$router->get('/samples', [SampleController::class, 'index']);
$router->get('/samples/shipments/create', [ShipmentController::class, 'create']);
$router->get('/samples/check-duplicate', [ShipmentController::class, 'checkDuplicate']);
$router->post('/samples/shipments/create', [ShipmentController::class, 'store']);
$router->get('/samples/shipments/view', [ShipmentController::class, 'show']);
$router->get('/samples/shipments/edit', [ShipmentController::class, 'edit']);
$router->post('/samples/shipments/edit', [ShipmentController::class, 'update']);
$router->post('/samples/shipments/send', [ShipmentController::class, 'send']);
$router->post('/samples/shipments/cancel', [ShipmentController::class, 'cancel']);
$router->get('/samples/shipments/report', [ShipmentController::class, 'report']);
$router->get('/samples/view', [SampleController::class, 'show']);
$router->get('/reception', [ReceptionController::class, 'index']);
$router->get('/reception/view', [ReceptionController::class, 'show']);
$router->get('/production', [ProductionController::class, 'index']);
$router->post('/production/save', [ProductionController::class, 'save']);
$router->get('/sampling-schedule', [SamplingScheduleController::class, 'index']);
$router->get('/admin/sampling-schedule', [AdminSamplingScheduleController::class, 'index']);
$router->post('/admin/sampling-schedule', [AdminSamplingScheduleController::class, 'update']);
$router->post('/reception/receive', [ReceptionController::class, 'receive']);
$router->post('/reception/sample/edit', [ReceptionController::class, 'editSample']);
$router->get('/quality-control', [QualityControlController::class, 'index']);
  $router->get('/validations', [ValidationController::class, 'index']);
  $router->get('/validations/options', [ValidationController::class, 'options']);
$router->get('/validations/create', [ValidationController::class, 'create']);
$router->post('/validations/create', [ValidationController::class, 'storeWithPhaseCycle']);
$router->get('/validations/edit', [ValidationController::class, 'edit']);
$router->post('/validations/edit', [ValidationController::class, 'update']);
$router->get('/validations/view', [ValidationController::class, 'show']);
$router->get('/validations/plan', [ValidationController::class, 'plan']);
$router->post('/validations/plan/save', [ValidationController::class, 'savePhasePlan']);
$router->get('/validations/results', [ValidationController::class, 'results']);
$router->post('/validations/results/save', [ValidationController::class, 'saveResult']);
$router->post('/validations/results/complete', [ValidationController::class, 'completeSample']);
$router->post('/validations/phases/complete', [ValidationController::class, 'completePhase']);
$router->post('/validations/phases/create', [ValidationController::class, 'createPhase']);
$router->post('/validations/complete', [ValidationController::class, 'completeValidation']);
$router->get('/notifications', [NotificationController::class, 'index']);
$router->post('/notifications/acknowledge', [NotificationController::class, 'acknowledge']);
$router->post('/notifications/analyses/create', [NotificationController::class, 'createAnalysis']);
$router->get('/notifications/analyses', [NotificationController::class, 'analyses']);
$router->get('/notifications/analyses/view', [NotificationController::class, 'showAnalysis']);
$router->post('/notifications/analyses/save', [NotificationController::class, 'saveAnalysis']);
$router->post('/notifications/analyses/follow-up', [NotificationController::class, 'startFollowUp']);
$router->post('/notifications/analyses/complete', [NotificationController::class, 'completeAnalysis']);
$router->post('/notifications/analyses/actions/save', [NotificationController::class, 'saveAction']);
$router->post('/notifications/analyses/items/remove', [NotificationController::class, 'removeItem']);
$router->post('/notifications/analyses/items/add', [NotificationController::class, 'addItems']);
$router->post('/quality-control/save', [QualityControlController::class, 'save']);
$router->post('/quality-control/save-all', [QualityControlController::class, 'saveAll']);
$router->post('/quality-control/specifications/preview', [QualityControlController::class, 'previewSpecifications']);
$router->post('/quality-control/complete', [QualityControlController::class, 'complete']);
$router->post('/quality-control/complete-all', [QualityControlController::class, 'completeAll']);
$router->get('/quality-control/hemolysis', [QualityControlController::class, 'hemolysis']);
$router->post('/quality-control/hemolysis/save', [QualityControlController::class, 'saveHemolysis']);
$router->post('/quality-control/hemolysis/complete', [QualityControlController::class, 'completeHemolysis']);
$router->post('/quality-control/hemolysis/import/preview', [QualityControlController::class, 'previewHemolysisImport']);
$router->post('/quality-control/hemolysis/import/apply', [QualityControlController::class, 'applyHemolysisImport']);
$router->get('/quality-control/bacteriology', [BacteriologyController::class, 'index']);
$router->get('/transfusion-reactions', [TransfusionReactionController::class, 'index']);
$router->get('/transfusion-reaction-consultation', [TransfusionReactionConsultationController::class, 'index']);
$router->post('/transfusion-reactions/save', [TransfusionReactionController::class, 'save']);
$router->post('/transfusion-reactions/tests/add', [TransfusionReactionController::class, 'addTest']);
$router->post('/transfusion-reactions/retest', [TransfusionReactionController::class, 'retest']);
$router->post('/transfusion-reactions/bulk', [TransfusionReactionController::class, 'bulk']);
$router->get('/transfusion-reactions/form', [TransfusionReactionController::class, 'form']);
$router->post('/transfusion-reactions/positive-samples/save', [TransfusionReactionController::class, 'savePositiveSample']);
$router->post('/transfusion-reactions/positive-samples/components/add', [TransfusionReactionController::class, 'addRelatedComponent']);
$router->post('/transfusion-reactions/positive-samples/components/update', [TransfusionReactionController::class, 'updateRelatedComponent']);
$router->post('/transfusion-reactions/positive-samples/tests/save', [TransfusionReactionController::class, 'saveRelatedTest']);
$router->post('/transfusion-reactions/positive-samples/retests/save', [TransfusionReactionController::class, 'saveRelatedRetest']);
$router->get('/transfusion-reactions/positive-samples/form', [TransfusionReactionController::class, 'positiveSampleForm']);
$router->post('/quality-control/bacteriology/individual', [BacteriologyController::class, 'individual']);
$router->post('/quality-control/bacteriology/individual/bulk-complete', [BacteriologyController::class, 'bulkCompleteIndividuals']);
$router->post('/quality-control/bacteriology/retest', [BacteriologyController::class, 'retest']);
$router->get('/quality-control/bacteriology/retest/form', [BacteriologyController::class, 'retestForm']);
$router->post('/quality-control/bacteriology/positive-samples/save', [BacteriologyController::class, 'savePositiveSample']);
$router->get('/quality-control/bacteriology/positive-samples/form', [BacteriologyController::class, 'positiveSampleForm']);
$router->post('/quality-control/bacteriology/pools/generate', [BacteriologyController::class, 'generate']);
$router->post('/quality-control/bacteriology/pools/result', [BacteriologyController::class, 'poolResult']);
$router->post('/quality-control/bacteriology/pools/cancel', [BacteriologyController::class, 'cancel']);
$router->get('/quality-control/bacteriology/pools/map', [BacteriologyController::class, 'map']);
$router->get('/quality-control/factor-viii-pools', [FactorViiiPoolController::class, 'index']);
$router->post('/quality-control/factor-viii-pools/preview', [FactorViiiPoolController::class, 'preview']);
$router->post('/quality-control/factor-viii-pools/preview/discard', [FactorViiiPoolController::class, 'discardPreview']);
$router->post('/quality-control/factor-viii-pools/create', [FactorViiiPoolController::class, 'create']);
$router->post('/quality-control/factor-viii-pools/result', [FactorViiiPoolController::class, 'saveResult']);
$router->post('/quality-control/factor-viii-pools/save-all', [FactorViiiPoolController::class, 'saveAll']);
$router->post('/quality-control/factor-viii-pools/cancel', [FactorViiiPoolController::class, 'cancel']);
$router->get('/quality-control/factor-viii-pools/map', [FactorViiiPoolController::class, 'map']);
$router->post('/quality-control/factor-viii/individual/select', [FactorViiiPoolController::class, 'chooseIndividual']);
$router->post('/quality-control/factor-viii/individual/save', [FactorViiiPoolController::class, 'saveIndividual']);
$router->get('/admin/users', [UserController::class, 'index']);
$router->get('/admin/users/create', [UserController::class, 'create']);
$router->post('/admin/users/create', [UserController::class, 'store']);
$router->get('/admin/users/edit', [UserController::class, 'edit']);
$router->post('/admin/users/edit', [UserController::class, 'update']);
$router->get('/admin/roles', [RoleController::class, 'index']);
$router->get('/admin/roles/create', [RoleController::class, 'create']);
$router->post('/admin/roles/create', [RoleController::class, 'store']);
$router->get('/admin/roles/edit', [RoleController::class, 'edit']);
$router->post('/admin/roles/edit', [RoleController::class, 'update']);
$router->get('/admin/permissions', [PermissionController::class, 'index']);
$router->post('/admin/permissions', [PermissionController::class, 'update']);
$router->get('/admin/clients', [ClientController::class, 'index']);
$router->get('/admin/clients/create', [ClientController::class, 'create']);
$router->post('/admin/clients/create', [ClientController::class, 'store']);
$router->get('/admin/clients/edit', [ClientController::class, 'edit']);
$router->post('/admin/clients/edit', [ClientController::class, 'update']);
$router->get('/admin/units', [UnitController::class, 'index']);
$router->get('/admin/units/create', [UnitController::class, 'create']);
$router->post('/admin/units/create', [UnitController::class, 'store']);
$router->get('/admin/units/edit', [UnitController::class, 'edit']);
$router->post('/admin/units/edit', [UnitController::class, 'update']);
$router->get('/admin/blood-components', [BloodComponentController::class, 'index']);
$router->get('/admin/blood-components/create', [BloodComponentController::class, 'create']);
$router->post('/admin/blood-components/create', [BloodComponentController::class, 'store']);
$router->get('/admin/blood-components/edit', [BloodComponentController::class, 'edit']);
$router->post('/admin/blood-components/edit', [BloodComponentController::class, 'update']);
$router->post('/admin/blood-components/shelf-life', [BloodComponentController::class, 'saveShelfLife']);
$router->post('/admin/blood-components/specifications/save', [BloodComponentController::class, 'saveSpecification']);
$router->post('/admin/blood-components/specifications/toggle', [BloodComponentController::class, 'toggleSpecification']);
$router->post('/admin/blood-components/specifications/delete', [BloodComponentController::class, 'deleteSpecification']);
$router->post('/admin/blood-components/cpaf-yield-rule', [BloodComponentController::class, 'saveCpafYieldRule']);
$router->post('/admin/blood-components/cpaf-yield-rule/toggle', [BloodComponentController::class, 'toggleCpafYieldRule']);
$router->get('/admin/bag-brands', [BagBrandController::class, 'index']);
$router->get('/admin/bag-brands/create', [BagBrandController::class, 'create']);
$router->post('/admin/bag-brands/create', [BagBrandController::class, 'store']);
$router->get('/admin/bag-brands/edit', [BagBrandController::class, 'edit']);
$router->post('/admin/bag-brands/edit', [BagBrandController::class, 'update']);
$router->post('/admin/bag-brands/toggle-status', [BagBrandController::class, 'toggleStatus']);
$router->post('/admin/bag-brands/tares/create', [BagBrandController::class, 'storeTare']);
$router->post('/admin/bag-brands/tares/edit', [BagBrandController::class, 'updateTare']);
$router->post('/admin/bag-brands/tares/deactivate', [BagBrandController::class, 'deactivateTare']);
$router->get('/admin/preservatives', [PreservativeController::class, 'index']);
$router->post('/admin/preservatives', [PreservativeController::class, 'save']);
$router->get('/admin/tests', [TestController::class, 'index']);
$router->get('/admin/tests/create', [TestController::class, 'create']);
$router->post('/admin/tests/create', [TestController::class, 'store']);
$router->get('/admin/tests/edit', [TestController::class, 'edit']);
$router->post('/admin/tests/edit', [TestController::class, 'update']);
$router->post('/admin/tests/supplies/create', [TestController::class, 'createSupply']);
$router->post('/admin/tests/supplies/update', [TestController::class, 'updateSupply']);
$router->post('/admin/tests/supplies/delete', [TestController::class, 'deleteSupply']);
$router->get('/admin/supplies', [SupplyController::class, 'index']);
$router->get('/admin/supplies/create', [SupplyController::class, 'create']);
$router->post('/admin/supplies/create', [SupplyController::class, 'store']);
$router->get('/admin/supplies/edit', [SupplyController::class, 'edit']);
$router->post('/admin/supplies/edit', [SupplyController::class, 'update']);
$router->get('/admin/supplies/lots', [SupplyController::class, 'lots']);
$router->get('/admin/supplies/lots/create', [SupplyController::class, 'createLot']);
$router->post('/admin/supplies/lots/create', [SupplyController::class, 'storeLot']);
$router->get('/admin/supplies/lots/edit', [SupplyController::class, 'editLot']);
$router->post('/admin/supplies/lots/edit', [SupplyController::class, 'updateLot']);
$router->dispatch();
