<?php
use BloodHub\Core\SamplePurpose;
require dirname(__DIR__,2).'/layouts/admin_start.php';
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
?>
<section class="billing-config-grid">
 <article class="card billing-panel billing-catalog-panel">
  <div class="billing-panel-heading"><div><h2>Centros de custo</h2><p>Cadastre e classifique os centros usados no faturamento.</p></div></div>
  <form method="post" action="/admin/billing/catalog" class="billing-form billing-center-form">
   <input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="type" value="center"><input type="hidden" name="id">
   <label>Código<input name="code" required></label><label>Nome<input name="name" required></label>
   <label>Unidade<select name="unit_id"><option value="">Sem vínculo</option><?php foreach($catalogs['units']as$u):?><option value="<?=(int)$u['id']?>"><?=$e($u['code'].' — '.$u['name'])?></option><?php endforeach?></select></label>
   <label>Cliente associado<select name="client_id"><option value="">Herdar da unidade / pendente</option><?php foreach($catalogs['clients']as$c):?><option value="<?=(int)$c['id']?>"><?=$e($c['name'].' — '.($c['client_type']==='internal'?'Interno':'Externo'))?></option><?php endforeach?></select></label>
   <label>Ordem<input type="number" name="display_order" value="0"></label><label class="billing-check"><input type="checkbox" name="active" value="1" checked><span>Ativo</span></label><button class="billing-btn-primary" type="submit">Salvar centro</button>
  </form>
  <div class="compact-list billing-catalog-list"><?php foreach($catalogs['centers']as$c):?><div><span><b><?=$e($c['cost_center_code'])?></b> <?=$e($c['name'])?> <span class="status status-<?=$c['active']?'active':'inactive'?>"><?=$c['active']?'Ativo':'Inativo'?></span></span><small><?=$c['unit_name']?'Vínculo: '.$e($c['unit_name']):'Somente faturamento'?></small><div class="table-actions"><button type="button" class="table-action" data-edit-center='<?=$e(json_encode($c,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'>Editar</button><button type="button" class="table-action" data-config-action="toggle" data-type="center" data-id="<?=$c['id']?>" data-active="<?=$c['active']?0:1?>"><?=$c['active']?'Inativar':'Ativar'?></button><button type="button" class="table-action table-action-danger" data-config-action="delete" data-type="center" data-id="<?=$c['id']?>">Excluir</button></div></div><?php endforeach?></div>
 </article>
 <article class="card billing-panel billing-catalog-panel">
  <div class="billing-panel-heading"><div><h2>Serviços</h2><p>Organize os serviços disponíveis para associação.</p></div></div>
  <form method="post" action="/admin/billing/catalog" class="billing-form billing-service-form">
   <input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="type" value="service"><input type="hidden" name="id">
   <label>Código<input name="code" required></label><label>Nome<input name="name" required></label><label>Ordem<input type="number" name="display_order" value="0"></label><label class="billing-check"><input type="checkbox" name="active" value="1" checked><span>Ativo</span></label><button class="billing-btn-primary" type="submit">Salvar serviço</button>
  </form>
  <div class="compact-list billing-catalog-list"><?php foreach($catalogs['services']as$s):?><div><span><b><?=$e($s['service_code'])?></b> <?=$e($s['name'])?> <span class="status status-<?=$s['active']?'active':'inactive'?>"><?=$s['active']?'Ativo':'Inativo'?></span></span><div class="table-actions"><button type="button" class="table-action" data-edit-service='<?=$e(json_encode($s,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'>Editar</button><button type="button" class="table-action" data-config-action="toggle" data-type="service" data-id="<?=$s['id']?>" data-active="<?=$s['active']?0:1?>"><?=$s['active']?'Inativar':'Ativar'?></button><button type="button" class="table-action table-action-danger" data-config-action="delete" data-type="service" data-id="<?=$s['id']?>">Excluir</button></div></div><?php endforeach?></div>
 </article>
</section>
<section class="card billing-panel billing-mapping-panel">
 <div class="billing-panel-heading"><div><h2>Associações de serviços</h2><p>Associe cada resultado final ao serviço institucional em que ele deve ser contabilizado.</p></div></div>
 <form method="post" action="/admin/billing/mapping" class="billing-form billing-mapping-form">
  <input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id">
  <label>Serviço associado<select name="service_id" required><?php foreach($catalogs['services']as$s):if($s['active']):?><option value="<?=(int)$s['id']?>"><?=$e($s['service_code'].' — '.$s['name'])?></option><?php endif;endforeach?></select></label>
  <label>Resultado final<select name="test_id" required><?php foreach($catalogs['tests']as$t):?><option value="<?=(int)$t['id']?>"><?=$e(($t['code']?:'—').' — '.$t['name'])?></option><?php endforeach?></select></label>
  <label>Hemocomponente<select name="component_id"><option value="">Todos</option><?php foreach($catalogs['components']as$c):?><option value="<?=(int)$c['id']?>"><?=$e($c['code'].' — '.$c['name'])?></option><?php endforeach?></select></label>
  <fieldset class="billing-contexts"><legend>Contextos</legend><div><?php foreach(['quality_control'=>'Controle de Qualidade','validation'=>'Validação','single_assessment'=>'Avaliação','transfusion_reaction'=>'Reação Transfusional']as$k=>$v):?><label class="billing-check"><input type="checkbox" name="contexts[]" value="<?=$e($k)?>" <?=$k==='quality_control'?'checked':''?>><span><?=$e($v)?></span></label><?php endforeach?></div></fieldset>
  <label class="billing-check"><input type="checkbox" name="active" value="1" checked><span>Ativo</span></label><button class="billing-btn-primary" type="submit">Salvar associação</button>
 </form>
 <div class="table-wrap billing-table"><table><thead><tr><th>Serviço associado</th><th>Resultado final</th><th>Hemocomponente</th><th>Contexto</th><th>Versão</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($mappings as$m):?><tr><td><?=$e($m['service_code'].' — '.$m['service_name'])?></td><td><?=$e($m['test_code'].' — '.$m['test_name'])?></td><td><?=$e($m['component_code']?:'Todos')?></td><td><?=$e(implode(', ',array_map([SamplePurpose::class,'label'],explode(',',(string)$m['context_scope']))))?></td><td>v<?=(int)$m['version']?></td><td><span class="status <?=$m['active']?'status-active':'status-inactive'?>"><?=$m['active']?'Ativa':'Inativa'?></span></td><td><div class="table-actions"><button type="button" class="table-action" data-edit-mapping='<?=$e(json_encode($m,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'>Editar</button><button type="button" class="table-action" data-config-action="toggle" data-type="mapping" data-id="<?=$m['id']?>" data-active="<?=$m['active']?0:1?>"><?=$m['active']?'Inativar':'Ativar'?></button><button type="button" class="table-action table-action-danger" data-config-action="delete" data-type="mapping" data-id="<?=$m['id']?>">Excluir</button></div></td></tr><?php endforeach?></tbody></table></div>
</section>
<section class="card billing-panel">
 <div class="billing-panel-heading"><div><h2>Classificação dos centros</h2><p>Confira os vínculos usados para classificar corretamente o faturamento.</p></div></div>
 <div class="table-wrap billing-table"><table><thead><tr><th>Centro</th><th>Unidade</th><th>Cliente associado</th><th>Tipo</th></tr></thead><tbody><?php foreach($catalogs['centers']as$c):?><tr><td><?=$e($c['cost_center_code'].' — '.$c['name'])?></td><td><?=$e($c['unit_name']?:'Sem unidade operacional')?></td><td><?=$e($c['client_name']?:'Centro de custo sem cliente associado')?></td><td><?=$c['client_type']==='internal'?'Interno':($c['client_type']==='external'?'Externo':'Pendente')?></td></tr><?php endforeach?></tbody></table></div>
</section>
<dialog class="shipment-cancel-dialog" id="billing-confirm"><form method="post"><div class="dialog-heading"><h3>Confirmar ação</h3><button class="dialog-close" type="button" data-close>×</button></div><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="type"><input type="hidden" name="id"><input type="hidden" name="active"><p>A exclusão será definitiva somente se o registro nunca tiver sido utilizado. Caso exista histórico, a operação será bloqueada.</p><div class="dialog-actions"><button class="button button-secondary" type="button" data-close>Cancelar</button><button class="button button-danger">Confirmar</button></div></form></dialog>
<script>(()=>{const fill=(f,d,map={})=>Object.entries(d).forEach(([k,v])=>{const name=map[k]||k,el=f.elements[name];if(!el)return;if(el.type==='checkbox')el.checked=!!Number(v);else el.value=v??''});const cf=document.querySelector('.billing-center-form'),sf=document.querySelector('.billing-service-form'),mf=document.querySelector('.billing-mapping-form');document.querySelectorAll('[data-edit-center]').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.editCenter);fill(cf,d,{cost_center_code:'code'});cf.scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-edit-service]').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.editService);fill(sf,d,{service_code:'code'});sf.scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-edit-mapping]').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.editMapping);fill(mf,d,{billing_service_id:'service_id',blood_component_id:'component_id'});mf.querySelectorAll('[name="contexts[]"]').forEach(x=>x.checked=d.context_scope.split(',').includes(x.value));mf.scrollIntoView({behavior:'smooth'})});const dialog=document.querySelector('#billing-confirm'),form=dialog.querySelector('form');document.querySelectorAll('[data-config-action]').forEach(b=>b.onclick=()=>{form.action='/admin/billing/'+b.dataset.configAction;fill(form,b.dataset);dialog.showModal()});dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close())})();</script>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
