<?php
$userAuth=$user;$flash=[];$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$f=$filters;$d=$dashboard;$s=$d['summary'];
$base=['blood_component_id'=>$f['componentId'],'year'=>$f['year']?:'','month'=>$f['month']?:'','unit_id'=>$f['unitId']?:''];
$fmtInt=fn($v)=>$v===null?'—':number_format((int)$v,0,',','.');$fmtPct=fn($v)=>$v===null?'—':number_format((float)$v,1,',','.').'%';
require dirname(__DIR__).'/layouts/admin_start.php'; ?>
<section class="gd-actions"><p>O mês considera a data de produção do hemocomponente.</p><a class="button button-secondary" target="_blank" rel="noopener" href="/dashboard-global/report?<?=$h(http_build_query($base))?>">Gerar resumo PDF</a></section>
<form class="gd-filters content-card" method="get" action="/">
 <label><span>Hemocomponente</span><select name="blood_component_id" required><?php foreach($f['components']as$c):?><option value="<?=(int)$c['id']?>" <?=(int)$c['id']===$f['componentId']?'selected':''?>><?=$h($c['code'].' — '.$c['name'])?></option><?php endforeach;?></select></label>
 <label><span>Ano</span><select name="year"><option value="">Todos os anos</option><?php foreach($f['years']as$y):?><option value="<?=(int)$y?>" <?=(int)$y===$f['year']?'selected':''?>><?=(int)$y?></option><?php endforeach;?></select></label>
 <label><span>Mês</span><select name="month"><option value="">Todos os meses</option><?php foreach($f['months']as$n=>$name):?><option value="<?=$n?>" <?=$n===$f['month']?'selected':''?>><?=$h($name)?></option><?php endforeach;?></select></label>
 <label><span>Unidade / Processamento</span><select name="unit_id"><option value="">Todos os processamentos</option><?php foreach($f['units']as$u):?><option value="<?=(int)$u['id']?>" <?=(int)$u['id']===$f['unitId']?'selected':''?>><?=$h($u['name'])?></option><?php endforeach;?></select></label>
 <div class="gd-filter-actions"><button class="button">Aplicar filtros</button><a class="button button-secondary" href="/">Limpar filtros</a></div>
</form>
<?php if(!$d['hasData']):?><section class="gd-empty content-card"><strong>Não há dados para os filtros selecionados.</strong><p>O painel mantém os filtros disponíveis sem representar ausência de registros como resultados reais.</p></section><?php endif;?>
<section class="gd-kpis" aria-label="Indicadores principais">
 <article class="gd-kpi"><span title="Soma dos registros de produção, considerando a fonte configurada no cronograma.">Produzido ⓘ</span><strong><?=$fmtInt($s['produced'])?></strong><small><?=$s['produced']===null?'Produção não informada':'Unidades produzidas'?></small></article>
 <article class="gd-kpi"><span title="Amostras de CQ concluídas, contadas uma única vez pela data de produção.">Testado (CQ) ⓘ</span><strong><?=$fmtInt($s['tested'])?></strong><small><?=$s['in_progress']?> em análise</small></article>
 <article class="gd-kpi"><span title="Testado dividido por produzido. Não calculado sem produção ou com produção igual a zero.">Amostragem ⓘ</span><strong><?=$fmtPct($s['sampling_percent'])?></strong><small><?=$s['units_eligible']?$s['units_met'].'/'.$s['units_eligible'].' unidades/períodos atenderam':'Sem base para avaliação'?></small></article>
 <article class="gd-kpi"><span title="Quantidade exigida pela regra de amostragem vigente em cada mês.">Mínimo exigido ⓘ</span><strong><?=$fmtInt($s['minimum'])?></strong><small><?=$s['missing']?'Faltam '.$s['missing'].' amostras':($s['sampling_met']?'Amostragem atendida':'—')?></small></article>
 <article class="gd-kpi gd-kpi-primary"><span title="Amostras concluídas com todos os testes obrigatórios finais avaliáveis conformes.">Conformidade global ⓘ</span><strong><?=$fmtPct($s['global_percent'])?></strong><small><?=$d['globalConformity']['evaluated']?> amostras avaliadas</small></article>
</section>
<?php if($d['testConformity']):?><section class="gd-test-cards" aria-label="Conformidade por teste"><?php foreach($d['testConformity']as$t):$statusLabel=['met'=>'Meta atingida','below'=>'Abaixo da meta','no_target'=>'Meta não configurada','no_results'=>'Sem resultados avaliáveis'][$t['target_status']];$tip="Conformidade: ".($t['percent']===null?'—':number_format((float)$t['percent'],1,',','.').'%')."\nMeta: ".($t['target']===null?'não configurada':number_format((float)$t['target'],1,',','.').'%')."\nAvaliados: {$t['evaluated']}\nConformes: {$t['conforming']}\nStatus: {$statusLabel}";?><article class="gd-test-card status-<?=$h($t['target_status'])?>" title="<?=$h($tip)?>"><span>% Conformidade</span><strong><?=$fmtPct($t['percent'])?></strong><b><?=$h($t['name'])?></b><small><?=$t['evaluated']?> avaliados · <?=$t['conforming']?> conformes</small><em><?=$t['target']===null?'Meta não configurada':'Meta '.$fmtPct($t['target']).' · '.$statusLabel?></em></article><?php endforeach;?></section><?php endif;?>
<section class="gd-charts">
 <article class="content-card gd-chart-card"><header><div><h2>Amostragem no período</h2><p><?=$h($d['series']['mode'])?> · Testado / Produzido</p></div></header><canvas id="samplingChart" height="250" aria-label="Gráfico de amostragem"></canvas></article>
 <article class="content-card gd-chart-card"><header><div><h2>Conformidade por teste (%)</h2><p>Somente resultados finais avaliáveis</p></div></header><canvas id="conformityChart" height="250" aria-label="Gráfico de conformidade"></canvas></article>
</section>
<section class="gd-secondary">
 <?php if(!$f['unitId']):?><article class="content-card"><h2>Situação por processamento</h2><div class="gd-unit-list"><?php foreach($d['unitStatus']as$u):?><div><b><?=$h($u['unit_name'])?></b><?php if(!$u['total']):?><span class="badge badge-neutral">Sem base</span><?php elseif($u['met']===$u['total']):?><span class="badge badge-success">Amostragem atendida</span><?php else:?><span class="badge badge-warning">Pendente <?=$u['missing']?></span><?php endif;?></div><?php endforeach;?></div></article><?php endif;?>
 <article class="content-card"><h2>Pontos de atenção</h2><?php if($d['attention']):?><ul class="gd-attention"><?php foreach($d['attention']as$item):?><li class="<?=$h($item['type'])?>"><?=$h($item['text'])?></li><?php endforeach;?></ul><?php else:?><p class="gd-muted">Nenhum ponto objetivo de atenção para os filtros.</p><?php endif;?></article>
 <article class="content-card gd-donut-wrap"><h2>Conformidade global</h2><div class="gd-donut" style="--ok:<?=$d['globalConformity']['evaluated']?round($d['globalConformity']['conforming']/$d['globalConformity']['evaluated']*100,2):0?>"><span><?=$d['globalConformity']['evaluated']?$fmtPct($d['globalConformity']['conforming']/$d['globalConformity']['evaluated']*100):'—'?></span></div><p><i class="ok"></i> Conformes <?=$d['globalConformity']['conforming']?> · <i class="bad"></i> Não conformes <?=$d['globalConformity']['nonconforming']?></p></article>
</section>
<section class="content-card gd-table-card"><header><div><h2>Detalhamento por unidade e período</h2><p><?=$d['total']?> linha(s), 10 por página.</p></div></header><div class="table-wrap"><table><thead><tr><th>Ano</th><th>Mês</th><th>Processamento</th><th>Produzido</th><th>Testado</th><th>% Amostragem</th><th>Mínimo</th><th>Situação</th><?php foreach($d['testCatalog']as$t):?><th>% <?=$h($t['name'])?></th><?php endforeach;?><th>% Global</th></tr></thead><tbody><?php foreach($d['rows']as$r):$testMap=[];foreach($r['tests']as$t)$testMap[$t['id']]=$t;?><tr><td><?=$r['year']?></td><td><?=$h($r['month_name'])?></td><td><b><?=$h($r['unit_name'])?></b></td><td><?=$fmtInt($r['produced'])?><?php if($r['produced']===null):?><small class="cell-note">Pendente</small><?php endif;?></td><td><?=$r['tested']?></td><td><?=$fmtPct($r['sampling_percent'])?></td><td><?=$fmtInt($r['minimum'])?></td><td><?php if($r['minimum']===null):?><span class="badge badge-neutral">Sem produção</span><?php elseif($r['sampling_met']):?><span class="badge badge-success">Atendida</span><?php else:?><span class="badge badge-warning">Pendente <?=$r['missing']?></span><?php endif;?></td><?php foreach($d['testCatalog']as$t):?><td><?=$fmtPct($testMap[$t['id']]['percent']??null)?></td><?php endforeach;?><td><?=$fmtPct($r['global_percent'])?></td></tr><?php endforeach;?></tbody></table></div>
 <?php if($d['pages']>1):?><nav class="gd-pagination" aria-label="Paginação"><?php for($p=1;$p<=$d['pages'];$p++):?><a class="<?=$p===$d['page']?'active':''?>" href="/?<?=$h(http_build_query($base+['page'=>$p]))?>"><?=$p?></a><?php endfor;?></nav><?php endif;?>
</section>
<script>window.globalDashboardData=<?=json_encode(['sampling'=>$d['series'],'tests'=>array_map(fn($t)=>['name'=>$t['name'],'percent'=>$t['percent'],'conforming'=>$t['conforming'],'evaluated'=>$t['evaluated'],'target'=>$t['target'],'status'=>$t['target_status']],$d['testConformity'])],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<script src="/assets/js/global-dashboard.js"></script>
<?php require dirname(__DIR__).'/layouts/admin_end.php'; ?>
