<?php
$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$s=$dashboard['summary'];
$fmt=fn($v)=>$v===null?'—':number_format((float)$v,is_float($v)?1:0,',','.');
$pct=fn($v)=>$v===null?'—':number_format((float)$v,1,',','.').'%';
$selectedUnit='Todos os processamentos';foreach($filters['units']as$u)if((int)$u['id']===$filters['unitId'])$selectedUnit=$u['name'];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Resumo Dashboard Global — BloodHub</title><style>
@page{size:A4 landscape;margin:13mm 11mm 15mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1f3048;font-size:10px;margin:0}header{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #7b2031;padding-bottom:9px;margin-bottom:12px}header img{width:145px}h1{font-size:20px;margin:0;color:#17375e}h2{font-size:12px;color:#17375e;margin:15px 0 7px}.meta{text-align:right;color:#657084;line-height:1.55}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.kpi{border:1px solid #dce2e9;border-top:3px solid #7b2031;border-radius:6px;padding:8px}.kpi span{display:block;text-transform:uppercase;font-size:8px;color:#697487;font-weight:bold}.kpi b{display:block;font-size:17px;margin-top:5px}.tests{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.test{border:1px solid #e0e5eb;border-left:3px solid #17375e;padding:6px;border-radius:5px}.test.met{border-left-color:#2f8a62}.test.below{border-left-color:#bb3d49}.test.met b{color:#24704f}.test.below b{color:#a9303d}.test b{color:#17375e;font-size:13px}table{width:100%;border-collapse:collapse;font-size:8px}th{background:#17375e;color:#fff}th,td{padding:5px;border:1px solid #dce2e9;text-align:left}.status{font-weight:bold}.attention{margin:0;padding-left:16px}.attention li{margin:4px 0}.print{position:fixed;right:10px;top:10px}@media print{.print{display:none}footer{position:fixed;bottom:-10mm;left:0;right:0}}footer{border-top:1px solid #ccd4dd;padding-top:4px;margin-top:12px;color:#6c7788;display:flex;justify-content:space-between}
</style></head><body><button class="print" onclick="window.print()">Imprimir / salvar PDF</button>
<header><img src="/assets/images/bloodhub-logo-horizontal.png" alt="BloodHub"><div><h1>Dashboard Global — Resumo institucional</h1><b>Laboratório de Controle de Qualidade de Hemocomponentes</b></div><div class="meta">Hemocomponente: <b><?=$h($dashboard['component']['code'].' — '.$dashboard['component']['name'])?></b><br>Período: <?=$h($dashboard['period'])?><br>Unidade(s): <?=$h($selectedUnit)?><br>Gerado em: <?=date('d/m/Y H:i')?></div></header>
<section class="kpis"><?php foreach([['Produzido',$fmt($s['produced'])],['Testado (CQ)',$fmt($s['tested'])],['Amostragem',$pct($s['sampling_percent'])],['Mínimo exigido',$fmt($s['minimum'])],['Conformidade global',$pct($s['global_percent'])]]as[$l,$v]):?><div class="kpi"><span><?=$l?></span><b><?=$v?></b></div><?php endforeach;?></section>
<h2>Conformidade por teste</h2><section class="tests"><?php foreach($dashboard['testConformity']as$t):$label=['met'=>'Meta atingida','below'=>'Abaixo da meta','no_target'=>'Meta não configurada','no_results'=>'Sem resultados avaliáveis'][$t['target_status']];?><div class="test <?=$h($t['target_status'])?>"><span><?=$h($t['name'])?></span><br><b><?=$pct($t['percent'])?></b><br><?=$t['conforming']?> conformes / <?=$t['evaluated']?> avaliados<br>Meta: <?=$t['target']===null?'não configurada':$pct($t['target'])?> · <?=$h($label)?></div><?php endforeach;?></section>
<h2>Situação da amostragem</h2><p class="status"><?=$s['units_eligible']?$s['units_met'].' de '.$s['units_eligible'].' unidade(s)/período atenderam.':'Sem produção informada para avaliar.'?> <?=$s['missing']?'Faltam '.$s['missing'].' amostra(s).':''?></p>
<h2>Detalhamento por unidade e período</h2><table><thead><tr><th>Ano</th><th>Mês</th><th>Processamento</th><th>Produzido</th><th>Testado</th><th>% amostragem</th><th>Mínimo</th><th>Situação</th><?php foreach($dashboard['testCatalog']as$t):?><th>% <?=$h($t['name'])?></th><?php endforeach;?><th>% Global</th></tr></thead><tbody><?php foreach($dashboard['rows']as$r):$tm=[];foreach($r['tests']as$t)$tm[$t['id']]=$t;?><tr><td><?=$r['year']?></td><td><?=$h($r['month_name'])?></td><td><?=$h($r['unit_name'])?></td><td><?=$fmt($r['produced'])?></td><td><?=$r['tested']?></td><td><?=$pct($r['sampling_percent'])?></td><td><?=$fmt($r['minimum'])?></td><td><?=$r['minimum']===null?'Produção pendente':($r['sampling_met']?'Atendida':'Pendente '.$r['missing'])?></td><?php foreach($dashboard['testCatalog']as$t):?><td><?=$pct($tm[$t['id']]['percent']??null)?></td><?php endforeach;?><td><?=$pct($r['global_percent'])?></td></tr><?php endforeach;?></tbody></table>
<h2>Pontos de atenção</h2><?php if($dashboard['attention']):?><ul class="attention"><?php foreach($dashboard['attention']as$i):?><li><?=$h($i['text'])?></li><?php endforeach;?></ul><?php else:?><p>Nenhum ponto objetivo de atenção para os filtros.</p><?php endif;?><footer><span>BloodHub · Laboratório de Controle de Qualidade de Hemocomponentes</span><span><?=$h($dashboard['period'])?> · Gerado em <?=date('d/m/Y H:i')?></span></footer><script>if(location.search.includes('print=1'))addEventListener('load',()=>window.print())</script></body></html>
