<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$editing=!empty($test['id']); ?>
<section class="content-card form-card"><div class="section-heading"><div><h2><?= $editing?'Editar teste':'Cadastrar teste' ?></h2><p>Configure os dados principais e os hemocomponentes em que o ensaio se aplica.</p></div><a class="button button-secondary" href="/admin/tests">Voltar</a></div><?php if($errors): ?><div class="alert alert-error"><ul><?php foreach($errors as $error): ?><li><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $editing?'/admin/tests/edit':'/admin/tests/create' ?>"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><?php if($editing): ?><input type="hidden" name="id" value="<?= (int)$test['id'] ?>"><?php endif; ?><div class="form-grid">
<label><span>Código</span><input name="code" maxlength="80" placeholder="Ex.: HEM, LEU" value="<?= htmlspecialchars($test['code']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>Nome do teste *</span><input name="name" required maxlength="180" value="<?= htmlspecialchars($test['name']??'',ENT_QUOTES,'UTF-8') ?>"></label>
<label><span>Tipo de resultado *</span><select name="result_type" required><option value="">Selecione</option><?php foreach(['numeric'=>'Numérico','text'=>'Texto','select'=>'Lista de opções','boolean'=>'Sim / Não','positive_negative'=>'Positivo / Negativo'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($test['result_type']??'')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label><span>Unidade de medida</span><input name="unit" maxlength="80" placeholder="Ex.: g/dL, %, mL" value="<?= htmlspecialchars($test['unit']??'',ENT_QUOTES,'UTF-8') ?>"></label>
<label><span>Método</span><input name="method_name" maxlength="180" placeholder="Ex.: Microhematócrito" value="<?= htmlspecialchars($test['method_name']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>Equipamento obrigatório?</span><select name="equipment_required"><option value="0" <?=empty($test['equipment_required'])?'selected':''?>>Não / manual ou visual</option><option value="1" <?=!empty($test['equipment_required'])?'selected':''?>>Sim</option></select></label>
<label><span>Permitir uso como teste avulso? *</span><select name="allows_ad_hoc" required><option value="0" <?= (string)($test['allows_ad_hoc']??'0')==='0'?'selected':'' ?>>Não</option><option value="1" <?= (string)($test['allows_ad_hoc']??'0')==='1'?'selected':'' ?>>Sim</option></select><small class="field-help">Permite futura seleção manual em Validações e Reações Transfusionais.</small></label><label><span>Status *</span><select name="status" required><option value="active" <?= ($test['status']??'active')==='active'?'selected':'' ?>>Ativo</option><option value="inactive" <?= ($test['status']??'')==='inactive'?'selected':'' ?>>Inativo</option></select></label>
<label><span>Resultado final gerencial? *</span><select name="is_final_result" required><option value="1" <?= (string)($test['is_final_result']??'1')==='1'?'selected':'' ?>>Sim</option><option value="0" <?= (string)($test['is_final_result']??'1')==='0'?'selected':'' ?>>Não — dado auxiliar</option></select><small class="field-help">Controla apenas Dashboard e relatórios gerenciais; não remove o campo do laboratório.</small></label>
<fieldset class="span-2 component-picker"><legend>Hemocomponentes aplicáveis</legend><p>Selecione um ou mais hemocomponentes ativos. Este vínculo é opcional nesta etapa.</p><div class="component-grid"><?php foreach($bloodComponents as $component): ?><label class="component-option <?= $component['status']==='inactive'?'component-option-inactive':'' ?>"><input type="checkbox" name="blood_component_ids[]" value="<?= (int)$component['id'] ?>" <?= in_array((int)$component['id'],$selectedComponentIds,true)?'checked':'' ?>><span><strong><?= htmlspecialchars($component['code'],ENT_QUOTES,'UTF-8') ?><?php if($component['status']==='inactive'): ?> <small class="component-status">Inativo</small><?php endif; ?></strong><?= htmlspecialchars($component['name'],ENT_QUOTES,'UTF-8') ?></span></label><?php endforeach; ?><?php if(!$bloodComponents): ?><div class="empty component-empty">Nenhum hemocomponente ativo disponível.</div><?php endif; ?></div></fieldset>
</div><div class="form-actions"><button class="button" type="submit">Salvar Teste</button></div></form></section>
<?php if($editing): ?>
<section class="content-card test-supplies-card"><div class="section-heading"><div><h2>Insumos necessários</h2><p>Configure os materiais utilizados por execução e acompanhe a situação atual dos lotes.</p></div><button class="button" type="button" onclick="document.getElementById('add-supply-dialog').showModal()" <?= !$availableSupplies?'disabled':'' ?>>+ Adicionar Insumo</button></div>
<div class="table-wrap"><table><thead><tr><th>Insumo</th><th>Quantidade por teste</th><th>Obrigatório</th><th>Situação atual</th><th>Ações</th></tr></thead><tbody>
<?php foreach($testSupplies as $item): ?><tr><td><strong><?= htmlspecialchars($item['name'],ENT_QUOTES,'UTF-8') ?></strong></td><td><?= $item['quantity_required']!==null?htmlspecialchars(rtrim(rtrim(number_format((float)$item['quantity_required'],4,',','.'),'0'),','),ENT_QUOTES,'UTF-8').' '.htmlspecialchars($item['unit_of_measure']??'',ENT_QUOTES,'UTF-8'):'—' ?></td><td><?= (int)$item['is_required']===1?'Sim':'Não' ?></td><td><span class="validity validity-<?= htmlspecialchars($item['best_status']['key'],ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($item['best_status']['label'],ENT_QUOTES,'UTF-8') ?></span></td><td><div class="table-actions"><button class="table-action link-button" type="button" onclick="document.getElementById('edit-supply-<?= (int)$item['supply_id'] ?>').showModal()">Editar vínculo</button><form method="post" action="/admin/tests/supplies/delete" onsubmit="return confirm('Remover este insumo da configuração do teste?')"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="test_id" value="<?= (int)$test['id'] ?>"><input type="hidden" name="supply_id" value="<?= (int)$item['supply_id'] ?>"><button class="table-action link-button danger-link" type="submit">Remover vínculo</button></form></div></td></tr>
<dialog class="supply-dialog" id="edit-supply-<?= (int)$item['supply_id'] ?>"><form method="post" action="/admin/tests/supplies/update"><div class="dialog-heading"><h3>Editar vínculo</h3><button type="button" class="dialog-close" onclick="this.closest('dialog').close()" aria-label="Fechar">×</button></div><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="test_id" value="<?= (int)$test['id'] ?>"><input type="hidden" name="supply_id" value="<?= (int)$item['supply_id'] ?>"><p class="dialog-supply-name"><?= htmlspecialchars($item['name'],ENT_QUOTES,'UTF-8') ?></p><label><span>Quantidade necessária por execução</span><input type="number" name="quantity_required" min="0.0001" step="0.0001" value="<?= htmlspecialchars($item['quantity_required']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>Obrigatório</span><select name="is_required" required><option value="1" <?= (int)$item['is_required']===1?'selected':'' ?>>Sim</option><option value="0" <?= (int)$item['is_required']===0?'selected':'' ?>>Não</option></select></label><div class="dialog-actions"><button class="button button-secondary" type="button" onclick="this.closest('dialog').close()">Cancelar</button><button class="button" type="submit">Salvar</button></div></form></dialog><?php endforeach; ?>
<?php if(!$testSupplies): ?><tr><td class="empty" colspan="5">Nenhum insumo vinculado a este teste.</td></tr><?php endif; ?></tbody></table></div></section>
<dialog class="supply-dialog" id="add-supply-dialog"><form method="post" action="/admin/tests/supplies/create"><div class="dialog-heading"><h3>Adicionar insumo</h3><button type="button" class="dialog-close" onclick="this.closest('dialog').close()" aria-label="Fechar">×</button></div><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="test_id" value="<?= (int)$test['id'] ?>"><label><span>Insumo *</span><select name="supply_id" required><option value="">Selecione</option><?php foreach($availableSupplies as $supply): ?><option value="<?= (int)$supply['id'] ?>"><?= htmlspecialchars($supply['name'].($supply['unit_of_measure']?' ('.$supply['unit_of_measure'].')':''),ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label><label><span>Quantidade necessária por execução</span><input type="number" name="quantity_required" min="0.0001" step="0.0001" placeholder="Opcional"></label><label><span>Obrigatório *</span><select name="is_required" required><option value="1">Sim</option><option value="0">Não</option></select></label><div class="dialog-actions"><button class="button button-secondary" type="button" onclick="this.closest('dialog').close()">Cancelar</button><button class="button" type="submit">Vincular insumo</button></div></form></dialog>
<?php endif; ?>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
