<?php require dirname(__DIR__).'/layouts/admin_start.php';$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$query=function(array$replace=[])use($filters){return http_build_query(array_filter(array_merge($filters,$replace),static fn($v)=>$v!==''&&$v!==null));};$fmt=fn($v)=>$v?date('d/m/Y H:i',strtotime($v)):'—';?>
<?php if(!$global&&count($units)===1):?><section class="rtc-scope"><span>Unidade autorizada</span><strong><?=$h(trim(($units[0]['code']??'').' — '.$units[0]['name'],' —'))?></strong></section><?php endif;?>
<section class="content-card rtc-filters"><div class="section-heading"><div><h2>Filtros de pesquisa</h2><p>O escopo de unidades é aplicado pelo servidor.</p></div></div><form method="get">
<label><span>Data inicial</span><input type="date" name="from" value="<?=$h($filters['from'])?>"></label><label><span>Data final</span><input type="date" name="to" value="<?=$h($filters['to'])?>"></label>
<?php if($global):?><label><span>Tipo de cliente</span><select name="client_type"><option value="">Todos</option><option value="internal" <?=$filters['client_type']==='internal'?'selected':''?>>Interno</option><option value="external" <?=$filters['client_type']==='external'?'selected':''?>>Externo</option></select></label><label><span>Cliente</span><select name="client_id"><option value="">Todos</option><?php foreach($clients as$c):?><option value="<?=(int)$c['id']?>" <?=(string)$c['id']===$filters['client_id']?'selected':''?>><?=$h($c['name'])?></option><?php endforeach;?></select></label><?php endif;?>
<?php if($global||count($units)>1):?><label><span>Unidade</span><select name="unit_id"><option value="">Todas as autorizadas</option><?php foreach($units as$u):?><option value="<?=(int)$u['id']?>" <?=(string)$u['id']===$filters['unit_id']?'selected':''?>><?=$h(trim(($u['code']??'').' — '.$u['name'],' —'))?></option><?php endforeach;?></select></label><?php endif;?>
<label><span>Número da amostra</span><input name="sample" value="<?=$h($filters['sample'])?>" placeholder="Amostra, doação ou código LCQH"></label><label><span>Status</span><select name="status"><option value="">Todos</option><option value="in_progress" <?=$filters['status']==='in_progress'?'selected':''?>>Em andamento</option><option value="completed" <?=$filters['status']==='completed'?'selected':''?>>Concluídos</option></select></label><div class="rtc-filter-actions"><button class="button">Pesquisar</button><a class="button button-secondary" href="/transfusion-reaction-consultation">Limpar filtros</a></div></form></section>
<section class="rtc-kpis"><article><span>Total encontrado</span><strong><?=number_format($kpis['total'],0,',','.')?></strong></article><article class="is-progress"><span>Em andamento</span><strong><?=number_format($kpis['in_progress'],0,',','.')?></strong></article><article class="is-complete"><span>Concluídos</span><strong><?=number_format($kpis['completed'],0,',','.')?></strong></article></section>
<section class="rtc-results" aria-label="Resultados"><?php foreach($rows as$row):$identifier=$row['donation_number']?:$row['sample_code'];$positive=$row['final_result']==='positive';?><article class="content-card rtc-card"><header><div class="rtc-card-title"><span class="rtc-unit"><?=$h(trim(($row['unit_code']??'').' — '.$row['unit_name'],' —'))?></span><span class="rtc-heading-separator" aria-hidden="true">•</span><h2>Amostra <?=$h($identifier?:'—')?></h2><span class="rtc-heading-separator" aria-hidden="true">•</span><p><?=$h($row['component_name']?:$row['component_code']?:'Hemocomponente não informado')?></p></div><span class="rtc-badge status-<?=$h($row['consultation_status'])?>"><?=$h($row['status_label'])?></span></header><div class="rtc-grid"><div><span>Data de recebimento</span><strong><?=$fmt($row['received_at']?:$row['sent_at']?:$row['registered_at'])?></strong></div><div><span>Código LCQH</span><strong><?=$h($row['lcqh_code']?:'—')?></strong></div><div class="rtc-result <?=$positive?'is-positive':($row['final_result']==='negative'?'is-negative':'is-waiting')?>"><span>Bacteriológico</span><strong><?=$h($row['result_label'])?></strong></div><div><span>Identificação</span><strong><?=$h($row['identification_label'])?></strong></div><div><span>Conclusão</span><strong><?=$fmt($row['conclusion_at'])?></strong></div><div class="rtc-observation"><span>Observação</span><strong><?=$h($row['notes']?:'—')?></strong></div><div class="rtc-report"><span>Laudo</span><?php if($row['released_report']):?><div><a class="button button-secondary button-compact" href="/reports/view?id=<?=(int)$row['released_report']['id']?>">Visualizar laudo</a><a class="button button-compact" href="/reports/download?id=<?=(int)$row['released_report']['id']?>">Baixar laudo</a></div><?php elseif($row['consultation_status']==='completed'):?><strong class="muted">Laudo em preparação</strong><?php else:?><strong>—</strong><?php endif;?></div></div></article><?php endforeach;?>
<?php if(!$rows):?><article class="content-card rtc-empty">Nenhuma reação transfusional encontrada para os filtros selecionados.</article><?php endif;?></section>
<?php if($pages>1):?><nav class="rtc-pagination" aria-label="Paginação"><?php if($page>1):?><a class="button button-secondary" href="?<?=$h($query(['page'=>$page-1]))?>">Anterior</a><?php endif;?><span>Página <?=$page?> de <?=$pages?></span><?php if($page<$pages):?><a class="button button-secondary" href="?<?=$h($query(['page'=>$page+1]))?>">Próxima</a><?php endif;?></nav><?php endif;?>
<?php require dirname(__DIR__).'/layouts/admin_end.php';?>
