<?php
use BloodHub\Services\IndicatorValueFormatter as F;
$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$months=[1=>'JAN',2=>'FEV',3=>'MAR',4=>'ABR',5=>'MAI',6=>'JUN',7=>'JUL',8=>'AGO',9=>'SET',10=>'OUT',11=>'NOV',12=>'DEZ'];$m=$dashboard['month'];$analysis=$dashboard['analysis'];$actions=$analysis['actions']??[];$isWithin=$indicator['code']==='HEMOCOMPONENTS_WITHIN_SPECIFICATIONS';
require dirname(__DIR__).'/layouts/admin_start.php';?>
<section class="indicator-hero">
 <div class="indicator-hero-title"><span>INDICADOR</span><h2><?=$h($indicator['name'])?></h2><p><?=$h($indicator['objective']?:'Objetivo não configurado.')?></p></div>
 <dl class="indicator-meta"><div><dt>Setor</dt><dd><?=$h($indicator['sector']?:'—')?></dd></div><div><dt>Regional</dt><dd><?=$h($indicator['regional']?:'—')?></dd></div><div><dt>Categoria</dt><dd><?=$h($indicator['category']?:'—')?></dd></div><div><dt>Meta</dt><dd><?=F::target($indicator,$m['target'])?></dd></div><div><dt>Periodicidade</dt><dd><?=$h($indicator['periodicity'])?></dd></div><div><dt>Subcategoria</dt><dd><?=$h($indicator['subcategory']?:'—')?></dd></div></dl>
</section>
<?php if($calculationError):?><div class="alert alert-error"><?=$h($calculationError)?></div><?php endif;?>
<form class="indicator-filters content-card" method="get"><label class="indicator-filter-month"><span>Mês</span><select class="bh-field bh-select" name="month"><?php foreach($months as$n=>$label):?><option value="<?=$n?>" <?=$n===$month?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label class="indicator-filter-year"><span>Ano</span><input class="bh-field" type="number" name="year" value="<?=$year?>" min="2000" max="2100"></label><label><span>Tipo de cliente</span><select class="bh-field bh-select" name="client_type" <?=$scope['restricted']?'disabled':''?>><option value="all" <?=$scope['type']==='all'?'selected':''?>>Todos</option><option value="internal" <?=$scope['type']==='internal'?'selected':''?>>Internos</option><option value="external" <?=$scope['type']==='external'?'selected':''?>>Externos</option></select></label><label><span><?=$scope['type']==='external'?'Cliente externo':'Cliente'?></span><select class="bh-field bh-select" name="client_id" <?=$scope['restricted']?'disabled':''?>><option value="">Todos os clientes</option><?php foreach($clients as$c):?><option value="<?=$c['id']?>" data-client-type="<?=$h($c['client_type'])?>" <?=$scope['client_id']==$c['id']?'selected':''?>><?=$h($c['name'])?><?=$c['status']==='inactive'?' (inativo)':''?></option><?php endforeach;?></select></label><?php if($scope['restricted']):?><input type="hidden" name="client_type" value="<?=$h($scope['type'])?>"><input type="hidden" name="client_id" value="<?=$scope['client_id']?>"><?php endif;?><button class="button indicator-filter-submit">Aplicar</button></form>

<section class="content-card indicator-table"><header><div><h2><?=$isWithin?'Hemocomponentes Dentro das Especificações':'Concentração Média de Plaquetas por Processamento'?></h2><p>Período <?=$months[$month]?>/<?=$year?> · amostras de CQ concluídas pela data de produção</p></div></header><div class="table-wrap"><table><thead><tr><?php if($isWithin):?><th>Hemocomponente</th><th>Fora</th><th>Dentro</th><th>% Dentro</th><?php else:?><th>Processamento</th><th>Quantidade avaliada</th><th>Média (Plaquetas/U)</th><?php endif;?></tr></thead><tbody><?php if(!$m['rows']):?><tr><td colspan="4" class="indicator-empty">Sem dados no período.</td></tr><?php else:foreach($m['rows']as$r):?><tr><?php if($isWithin):?><td><b><?=$h($r['code'])?></b> · <?=$h($r['name'])?></td><td><?=$r['outside']?></td><td><?=$r['inside']?></td><td><?=F::value($indicator,$r['value'])?></td><?php else:?><td><b><?=$h($r['processing'])?></b></td><td><?=$r['quantity']?></td><td><?=F::value($indicator,$r['value'])?></td><?php endif;?></tr><?php endforeach;endif;?></tbody></table></div></section>

<section class="indicator-global status-<?=$h($m['status'])?>"><div><span>Resultado Global do Mês</span><strong><?=F::value($indicator,$m['value'])?></strong></div><dl><?php if($isWithin):?><div><dt>Fora</dt><dd><?=$m['outside']?></dd></div><div><dt>Dentro</dt><dd><?=$m['inside']?></dd></div><?php else:?><div><dt>Quantidade avaliada</dt><dd><?=$m['quantity']?></dd></div><?php endif;?></dl><span class="indicator-status"><?=['met'=>'META ATINGIDA','below'=>$isWithin?'ABAIXO DA META':'META NÃO ATINGIDA','no_target'=>'META NÃO CONFIGURADA','no_data'=>'SEM DADOS'][$m['status']]?></span></section>

<section class="content-card indicator-chart-card"><header><div><h2><?=$isWithin?'Global Anual — % Dentro das Especificações':'Global Anual — Média de Plaquetas/U'?></h2><p>Barras mensais e meta vigente em cada período.</p></div></header><div class="indicator-chart-area"><canvas id="indicatorAnnualChart" height="280" aria-label="Série anual do indicador"></canvas><p class="indicator-chart-empty" id="indicatorChartEmpty" hidden>Sem dados anuais disponíveis.</p><div class="indicator-chart-tooltip" id="indicatorChartTooltip" role="status" hidden></div></div></section>
<section class="content-card indicator-year-summary"><h2>Resumo Jan–Dez</h2><div class="table-wrap"><table><thead><tr><?php foreach($months as$label):?><th><?=$label?></th><?php endforeach;?></tr></thead><tbody><tr><?php foreach($dashboard['months']as$data):?><td><?=F::value($indicator,$data['value'])?></td><?php endforeach;?></tr></tbody></table></div></section>

<section class="content-card indicator-pending"><header><div><h2>Ações pendentes</h2><p>Planejadas / Em andamento de períodos anteriores.</p></div></header><?php if(!$dashboard['pending']):?><p class="indicator-muted">Nenhuma ação anterior em aberto.</p><?php else:?><div class="pending-chips"><?php foreach($dashboard['pending']as$g):?><button type="button" class="pending-chip" data-pending="<?=sprintf('%04d-%02d',$g['year'],$g['month'])?>"><b><?=$months[$g['month']]?>/<?=$g['year']?></b><span><?=count($g['actions'])?></span></button><?php endforeach;?></div><?php foreach($dashboard['pending']as$g):?><dialog class="indicator-dialog pending-dialog" id="pending-<?=sprintf('%04d-%02d',$g['year'],$g['month'])?>"><header><div><span>Ações pendentes</span><h3><?=$months[$g['month']]?>/<?=$g['year']?></h3></div><button type="button" data-close aria-label="Fechar">×</button></header><div class="dialog-scroll"><?php foreach($g['actions']as$a):?><article class="pending-action"><div><span>Causa</span><p><?=$h($a['cause']?:'—')?></p></div><div><span>Ação</span><p><?=$h($a['what_text']?:'—')?></p></div><div><span>Responsável</span><p><?=$h($a['responsible_name'])?></p></div><div><span>Prazo</span><p><?=$h($a['due_date']?date('d/m/Y',strtotime($a['due_date'])):($a['when_text']?:'—'))?></p></div><div><span>Status</span><p><?=$a['status']==='planned'?'Planejada':'Em andamento'?></p></div></article><?php endforeach;?></div></dialog><?php endforeach;endif;?></section>

<section class="content-card indicator-analysis"><header><div><h2>Análise do Indicador</h2><p><?=$months[$month]?>/<?=$year?></p></div><?php if($dashboard['can_manage']):?><button class="button" type="button" id="openAnalysis">Registrar / Editar Análise</button><?php else:?><button class="button" disabled title="Somente responsáveis pelo indicador podem editar.">Registrar / Editar Análise</button><?php endif;?></header><div class="analysis-copy"><span>Análise</span><p><?=$analysis&&trim((string)$analysis['analysis_text'])!==''?nl2br($h($analysis['analysis_text'])):'Nenhuma análise registrada para este período.'?></p></div><h3>Ações</h3><?php if(!$actions):?><p class="indicator-muted">Nenhum plano de ação registrado.</p><?php else:?><div class="action-read-grid"><?php foreach($actions as$a):?><article><div class="action-read-head"><b><?=$h($a['what_text']?:'Ação sem título')?></b><span class="action-status status-<?=$h($a['status'])?>"><?=['planned'=>'Planejada','in_progress'=>'Em andamento','completed'=>'Concluída','cancelled'=>'Cancelada'][$a['status']]?></span></div><dl><div><dt>Causa</dt><dd><?=$h($a['cause']?:'—')?></dd></div><div><dt>Por quê?</dt><dd><?=$h($a['why_text']?:'—')?></dd></div><div><dt>Como?</dt><dd><?=$h($a['how_text']?:'—')?></dd></div><div><dt>Quem?</dt><dd><?=$h($a['responsible_name'])?></dd></div><div><dt>Quando?</dt><dd><?=$h($a['due_date']?date('d/m/Y',strtotime($a['due_date'])):($a['when_text']?:'—'))?></dd></div><div><dt>Conclusão</dt><dd><?=$a['completion_date']?date('d/m/Y',strtotime($a['completion_date'])):'—'?></dd></div></dl></article><?php endforeach;?></div><?php endif;?></section>

<?php if($dashboard['can_manage']):?><dialog class="indicator-dialog analysis-dialog" id="analysisDialog"><form method="post" action="/indicators/analysis/save"><header><div><span><?=$months[$month]?>/<?=$year?></span><h3>Registrar / Editar Análise</h3></div><button type="button" data-close aria-label="Fechar">×</button></header><div class="dialog-scroll"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_slug" value="<?=$h($indicator['slug'])?>"><input type="hidden" name="year" value="<?=$year?>"><input type="hidden" name="month" value="<?=$month?>"><label class="analysis-text"><span>Análise</span><textarea class="bh-field bh-textarea" name="analysis_text" rows="6"><?=$h($analysis['analysis_text']??'')?></textarea></label><div class="action-editor-title"><h4>Plano de ação</h4><button type="button" class="button button-secondary" id="addAction">+ Adicionar ação</button></div><div id="actionEditors"><?php foreach($actions as$idx=>$a)require __DIR__.'/action_editor.php';?></div></div><footer><button type="button" class="button button-secondary" data-close>Cancelar</button><button class="button">Salvar análise e ações</button></footer></form></dialog><template id="actionTemplate"><?php $idx='__INDEX__';$a=[];require __DIR__.'/action_editor.php';?></template><?php endif;?>
<script>window.indicatorChartData=<?=json_encode(['labels'=>array_values($months),'monthNames'=>['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],'year'=>$year,'unit'=>$indicator['value_unit'],'months'=>array_values(array_map(fn($d)=>['value'=>$d['value']===null?null:(float)$d['value'],'target'=>$d['target']===null?null:(float)$d['target']['target_value'],'status'=>$d['status'],'quantity'=>$d['quantity']??0,'inside'=>$d['inside']??null,'outside'=>$d['outside']??null],$dashboard['months'])),'scientific'=>$indicator['value_type']==='scientific','isWithin'=>$isWithin],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="/assets/js/indicators.js"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{const t=document.querySelector('.indicator-filters [name="client_type"]'),c=document.querySelector('.indicator-filters [name="client_id"]');if(t&&c&&!t.disabled){const sync=()=>{for(const o of c.options){if(!o.value)continue;o.hidden=t.value!=='all'&&o.dataset.clientType!==t.value;}if(c.selectedOptions[0]?.hidden)c.value='';};t.addEventListener('change',sync);sync();}const f=document.querySelector('#analysisDialog form');if(!f)return;for(const [name,value] of Object.entries({client_type:<?=json_encode($scope['type'])?>,client_id:<?=json_encode($scope['client_id'])?>})){const i=document.createElement('input');i.type='hidden';i.name=name;i.value=value??'';f.appendChild(i);}});</script>
<?php require dirname(__DIR__).'/layouts/admin_end.php';?>
