<?php require dirname(__DIR__,2).'/layouts/admin_start.php'; $editing=!empty($client['id']); ?>
<section class="content-card form-card"><div class="section-heading"><div><h2><?= $editing?'Editar cliente':'Cadastrar cliente' ?></h2><p>Campos marcados com * são obrigatórios.</p></div><a class="button button-secondary" href="/admin/clients">Voltar</a></div>
<?php if($errors): ?><div class="alert alert-error"><ul><?php foreach($errors as $error): ?><li><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $editing?'/admin/clients/edit?id='.(int)$client['id']:'/admin/clients/create' ?>"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>"><div class="form-grid">
<label><span>Nome *</span><input name="name" required value="<?= htmlspecialchars($client['name']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>Tipo do cliente *</span><select name="client_type" required><option value="">Selecione</option><?php foreach(['internal'=>'Interno','external'=>'Externo'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($client['client_type']??'')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label><span>CNPJ</span><input name="document" value="<?= htmlspecialchars($client['document']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>E-mail</span><input type="email" name="email" value="<?= htmlspecialchars($client['email']??'',ENT_QUOTES,'UTF-8') ?>"></label>
<label><span>Telefone</span><input type="tel" name="phone" value="<?= htmlspecialchars($client['phone']??'',ENT_QUOTES,'UTF-8') ?>"></label><label><span>Status *</span><select name="status" required><?php foreach(['active'=>'Ativo','inactive'=>'Inativo'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($client['status']??'active')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label><span>Endereço</span><input name="address" value="<?=htmlspecialchars($client['address']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>Bairro</span><input name="district" value="<?=htmlspecialchars($client['district']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>Cidade</span><input name="city" value="<?=htmlspecialchars($client['city']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>UF</span><input name="state" maxlength="2" value="<?=htmlspecialchars($client['state']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>CEP</span><input name="postal_code" value="<?=htmlspecialchars($client['postal_code']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>Contato</span><input name="contact_name" value="<?=htmlspecialchars($client['contact_name']??'',ENT_QUOTES,'UTF-8')?>"></label><label><span>Ramal</span><input name="phone_extension" value="<?=htmlspecialchars($client['phone_extension']??'',ENT_QUOTES,'UTF-8')?>"></label>
</div><div class="form-actions"><button class="button" type="submit">Salvar Cliente</button></div></form></section><?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
