<?php
declare(strict_types=1);
namespace BloodHub\Controllers;

use BloodHub\Core\{AdminGuard,Auth,Csrf,Database,Flash,Permission};
use BloodHub\Services\{BacteriologyEligibility,BacteriologyService,PositiveBacteriologySampleService};
use DomainException;
use PDO;

final class BacteriologyController
{
    public static function index():void
    {
        AdminGuard::enforce('quality.bacteriology.view');BacteriologyEligibility::syncOpenSamples();$pdo=Database::connection();$tab=in_array($_GET['tab']??'individual',['individual','pools','retests','positives'],true)?$_GET['tab']:'individual';$f=self::filters();$openPositive=null;$relatedComponents=[];$positiveComponents=[];$positiveUnits=[];
        if($tab==='positives'&&!empty($_GET['open'])){try{$openPositive=PositiveBacteriologySampleService::find((int)$_GET['open']);$relatedComponents=PositiveBacteriologySampleService::relatedComponents((int)$_GET['open']);$positiveComponents=PositiveBacteriologySampleService::activeComponents();$positiveUnits=PositiveBacteriologySampleService::activeUnitsForClient((int)($openPositive['client_id']??0));}catch(\Throwable$e){self::error($e);}}
        self::view('bacteriology',['tab'=>$tab,'filters'=>$f,'individuals'=>BacteriologyService::individualSamples($f),'pools'=>BacteriologyService::pools($f),'retests'=>BacteriologyService::retests($f),'positiveSamples'=>PositiveBacteriologySampleService::all($f),'openPositive'=>$openPositive,'relatedComponents'=>$relatedComponents,'positiveComponents'=>$positiveComponents,'positiveUnits'=>$positiveUnits,'counts'=>BacteriologyService::counts(),'components'=>BacteriologyEligibility::eligibleComponents(),'origins'=>$pdo->query("SELECT id,name FROM units WHERE status='active' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC),'clients'=>$pdo->query("SELECT id,name FROM clients WHERE status='active' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC),'canEdit'=>Permission::can('quality.bacteriology.edit'),'canPool'=>Permission::can('quality.bacteriology.pool'),'pageTitle'=>'Bacteriológico','pageSubtitle'=>'Registre resultados individuais, acompanhe retestes, pools e positivos confirmados.']);
    }
    public static function individual():void{self::guard('quality.bacteriology.edit');try{$state=BacteriologyService::saveIndividual((int)($_POST['sample_id']??0),(string)($_POST['result']??''),$_POST['identified_bacteria']??null,$_POST['notes']??null,!empty($_POST['complete']));Flash::set('success',$state==='retest'?'Resultado inicial positivo registrado; identificação preservada e reteste obrigatório criado.':($state==='confirmed_pool'?'Positivo confirmado após abertura de pool, com identificação bacteriana registrada.':($state==='completed'?'Resultado bacteriológico concluído.':'Resultado registrado sem concluir.')));}catch(\Throwable$e){self::error($e);}self::back('individual');}
    public static function bulkCompleteIndividuals():void{self::guard('quality.bacteriology.edit');try{$result=BacteriologyService::bulkCompleteIndividuals((array)($_POST['samples']??[]));$done=$result['completed'];$pending=$result['pending'];Flash::set('success',$done.' '.($done===1?'amostra negativa concluída':'amostras negativas concluídas').'. '.$pending.' '.($pending===1?'amostra permaneceu pendente para análise individual.':'amostras permaneceram pendentes para análise individual.'));}catch(\Throwable$e){self::error($e);}self::back('individual');}
    public static function retest():void{self::guard('quality.bacteriology.edit');try{BacteriologyService::completeRetest((int)($_POST['retest_id']??0),(string)($_POST['result']??''),$_POST['identified_bacteria_retest']??null,$_POST['notes']??null);Flash::set('success','Reteste concluído e resultado final registrado.');}catch(\Throwable$e){self::error($e);}self::back('retests');}
    public static function retestForm():void{AdminGuard::enforce('quality.bacteriology.view');$retest=BacteriologyService::retestForm((int)($_GET['id']??0));Auth::registerAudit('bacteriology.retest_form_printed','bacteriology_retests',(int)$retest['retest_id']);require dirname(__DIR__).'/Views/quality_control/bacteriology_retest_form.php';}
    public static function savePositiveSample():void{self::guard('quality.bacteriology.edit');$id=(int)($_POST['positive_sample_id']??0);try{PositiveBacteriologySampleService::save($id,$_POST,!empty($_POST['complete']));Flash::set('success',!empty($_POST['complete'])?'Ocorrência positiva concluída.':'Cadastro salvo para continuar depois.');}catch(\Throwable$e){self::error($e);}header('Location: /quality-control/bacteriology?tab=positives&open='.$id);exit;}
    public static function positiveSampleForm():void{AdminGuard::enforce('quality.bacteriology.view');$positive=PositiveBacteriologySampleService::find((int)($_GET['id']??0));$recordId=(int)($_GET['record']??0);$selected=array_values(array_filter(array_map('intval',explode(',',(string)($_GET['records']??'')))));$positive['records']=array_values(array_filter($positive['records'],static function($r)use($recordId,$selected){if((int)$r['position']===1)return false;if($recordId)return(int)$r['id']===$recordId;return $selected?in_array((int)$r['id'],$selected,true):(int)$r['include_in_form']===1;}));if(!$positive['records'])throw new DomainException('Nenhum registro adicional selecionado para impressão.');Auth::registerAudit('bacteriology.positive_forms_printed','bacteriology_positive_samples',(int)$positive['id'],null,['record_ids'=>array_column($positive['records'],'id')]);require dirname(__DIR__).'/Views/quality_control/bacteriology_positive_form.php';}
    public static function generate():void{self::guard('quality.bacteriology.pool');try{$codes=BacteriologyService::generatePools(self::filters($_POST));Flash::set('success',count($codes).' pool(s) criado(s): '.implode(', ',$codes));}catch(\Throwable$e){self::error($e);}self::back('pools');}
    public static function poolResult():void{self::guard('quality.bacteriology.pool');try{$state=BacteriologyService::savePoolResult((int)($_POST['pool_id']??0),(string)($_POST['result']??''),$_POST['notes']??null,!empty($_POST['complete']));Flash::set('success',$state==='positive'?'Pool positivo. As unidades foram encaminhadas para análise bacteriológica individual.':($state==='negative'?'Pool negativo concluído e propagado aos membros.':'Resultado do pool salvo sem concluir.'));}catch(\Throwable$e){self::error($e);}self::back('pools');}
    public static function cancel():void{self::guard('quality.bacteriology.pool');try{BacteriologyService::cancelPool((int)($_POST['pool_id']??0),(string)($_POST['reason']??''));Flash::set('success','Pool cancelado; os membros foram liberados para novo agrupamento.');}catch(\Throwable$e){self::error($e);}self::back('pools');}
    public static function map():void{AdminGuard::enforce('quality.bacteriology.view');$ids=array_values(array_filter(array_map('intval',explode(',',(string)($_GET['ids']??'')))));$pools=BacteriologyService::poolMap($ids);Auth::registerAudit('bacteriology_pool.map_printed','bacteriology_pools',null,null,['pool_ids'=>array_column($pools,'id')]);require dirname(__DIR__).'/Views/quality_control/bacteriology_map.php';}
    private static function filters(?array$source=null):array{$s=$source??$_GET;return['origin'=>trim((string)($s['origin']??'')),'client'=>trim((string)($s['client']??'')),'component'=>trim((string)($s['component']??'')),'received_date'=>trim((string)($s['received_date']??'')),'donation'=>trim((string)($s['donation']??'')),'lcqh'=>trim((string)($s['lcqh']??'')),'status'=>trim((string)($s['status']??'')),'positive_status'=>trim((string)($s['positive_status']??'')),'code'=>trim((string)($s['code']??'')),'from'=>trim((string)($s['from']??date('Y-m-01'))),'to'=>trim((string)($s['to']??date('Y-m-d'))),'origin_type'=>trim((string)($s['origin_type']??''))];}
    private static function guard(string$p):void{AdminGuard::enforce($p);if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada.');self::back((string)($_POST['tab']??'individual'));}}
    private static function error(\Throwable$e):void{Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível processar a operação bacteriológica.');}
    private static function back(string$tab):never{header('Location: /quality-control/bacteriology?tab='.urlencode($tab));exit;}
    private static function view(string$name,array$vars):void{extract($vars);$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__).'/Views/quality_control/'.$name.'.php';}
}
