<?php
declare(strict_types=1);
namespace BloodHub\Controllers;
use BloodHub\Core\{AdminGuard,Auth,Csrf,Flash,Permission};
use BloodHub\Services\{BillingService as Billing,ClientScopeService};

final class BillingController
{
 public static function index():void{AdminGuard::enforce(Billing::VIEW);[$year,$month]=self::period($_GET);$scope=self::scope($_GET);$matrix=Billing::buildMatrix($year,$month,true,$scope);if($scope['type']==='all'&&!$scope['client_id'])$matrix['missingCenters']=array_merge($matrix['missingCenters'],Billing::clientlessCenters());$entries=Billing::getManualEntries($year,$month);$catalogs=Billing::catalogs();$clients=ClientScopeService::getVisibleClientsForUser(true);$details=[];self::view('index',compact('year','month','matrix','entries','catalogs','details','scope','clients')+['pageTitle'=>'Faturamento','pageSubtitle'=>'Consolide os resultados finais por cliente, centro de custo e competência.']);}
 public static function detail():void{AdminGuard::enforce(Billing::VIEW);[$year,$month]=self::period($_GET);$scope=self::scope($_GET);$matrix=Billing::buildMatrix($year,$month,true,$scope);$center=(int)($_GET['center']??0);if(!array_filter($matrix['rows'],fn($r)=>(int)$r['center']['id']===$center)){http_response_code(403);echo'Centro de custo fora do escopo autorizado.';return;}$entries=Billing::getManualEntries($year,$month);$catalogs=Billing::catalogs();$clients=ClientScopeService::getVisibleClientsForUser(true);$details=Billing::detail($year,$month,$center,(int)($_GET['service']??0));self::view('index',compact('year','month','matrix','entries','catalogs','details','scope','clients')+['pageTitle'=>'Faturamento','pageSubtitle'=>'Consolide os resultados finais por cliente, centro de custo e competência.']);}
 public static function manualSave():void{AdminGuard::enforce(Billing::MANUAL);self::csrf();[$year,$month]=self::period($_POST);try{Billing::saveManual(['id'=>(int)($_POST['id']??0),'year'=>$year,'month'=>$month,'center'=>(int)($_POST['center']??0),'service'=>(int)($_POST['service']??0),'quantity'=>(int)($_POST['quantity']??0),'notes'=>trim((string)($_POST['notes']??''))],(int)Auth::user()['id']);Flash::set('success','Lançamento complementar salvo.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::redirect($year,$month,'manual');}
 public static function manualRemove():void{AdminGuard::enforce(Billing::MANUAL);self::csrf();[$year,$month]=self::period($_POST);try{Billing::removeManual((int)($_POST['id']??0),(int)Auth::user()['id']);Flash::set('success','Lançamento complementar removido.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::redirect($year,$month,'manual');}
 public static function close():void{AdminGuard::enforce(Billing::CLOSE);self::csrf();[$year,$month]=self::period($_POST);try{Billing::closePeriod($year,$month,(int)Auth::user()['id']);Flash::set('success','Competência fechada e matriz completa preservada em snapshot.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::redirect($year,$month);}
 public static function review():void{AdminGuard::enforce(Billing::CLOSE);self::csrf();[$year,$month]=self::period($_POST);try{Billing::reviewPeriod($year,$month,(int)Auth::user()['id']);Flash::set('success','Competência revisada e pronta para fechamento.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::redirect($year,$month);}
 public static function reopen():void{AdminGuard::enforce(Billing::REOPEN);self::csrf();[$year,$month]=self::period($_POST);try{Billing::reopenPeriod($year,$month,(int)Auth::user()['id'],trim((string)($_POST['reason']??'')));Flash::set('success','Competência reaberta. O snapshot anterior foi preservado.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::redirect($year,$month);}
 public static function export():void{AdminGuard::enforce(Billing::VIEW);[$year,$month]=self::period($_GET);$scope=self::scope($_GET);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="faturamento-'.sprintf('%04d-%02d',$year,$month).'.csv"');echo Billing::exportCsv($year,$month,$scope);}
 private static function scope(array$i):array{try{return ClientScopeService::resolve($i['client_type']??'all',$i['client_id']??null);}catch(\Throwable$e){http_response_code(403);exit($e->getMessage());}}
 private static function period(array$i):array{$y=(int)($i['year']??date('Y'));$m=(int)($i['month']??date('n'));return[$y>=2000&&$y<=2100?$y:(int)date('Y'),$m>=1&&$m<=12?$m:(int)date('n')];}
 private static function csrf():void{if(!Csrf::validate($_POST['_csrf']??null))throw new \RuntimeException('Sessão expirada.');}
 private static function redirect(int$y,int$m,string$tab='summary'):never{header('Location: /billing?'.http_build_query(['year'=>$y,'month'=>$m,'tab'=>$tab]));exit;}
 private static function view(string$n,array$v):void{extract($v);$flash=Flash::pull();$csrf=Csrf::token();$canManual=Permission::can(Billing::MANUAL);$canClose=Permission::can(Billing::CLOSE);$canReopen=Permission::can(Billing::REOPEN);require dirname(__DIR__).'/Views/billing/'.$n.'.php';}
}
