<?php
declare(strict_types=1);
namespace BloodHub\Controllers;
use BloodHub\Core\{AdminGuard,Auth,Csrf,Database,Flash,Permission};
use BloodHub\Services\FactorViiiPoolService;
use DomainException;
use PDO;
final class FactorViiiPoolController
{
 public static function index():void{$pdo=Database::connection();AdminGuard::enforce('quality_control.factor_viii_pool.view');$f=self::filters();$w=['1=1'];$p=[];foreach([['component','p.blood_component_id'],['origin','p.origin_unit_id']] as [$k,$c])if($f[$k]!==''){$w[]="$c=:$k";$p[$k]=(int)$f[$k];}if($f['status']!==''){$w[]='p.status=:status';$p['status']=$f['status'];}if($f['code']!==''){$w[]='p.code LIKE :code';$p['code']='%'.$f['code'].'%';}if($f['from']!==''){$w[]='DATE(p.created_at)>=:from';$p['from']=$f['from'];}if($f['to']!==''){$w[]='DATE(p.created_at)<=:to';$p['to']=$f['to'];}$sql="SELECT p.*,bc.code component_code,bc.name component_name,u.name origin_name,cu.name created_by_name,COUNT(m.id) member_count,GROUP_CONCAT(CONCAT(COALESCE(s.donation_number,'-'),'|',COALESCE(s.lcqh_code,'')) ORDER BY m.position SEPARATOR ';;') member_labels FROM factor_viii_pools p JOIN blood_components bc ON bc.id=p.blood_component_id JOIN units u ON u.id=p.origin_unit_id LEFT JOIN users cu ON cu.id=p.created_by LEFT JOIN factor_viii_pool_samples m ON m.pool_id=p.id LEFT JOIN samples s ON s.id=m.sample_id WHERE ".implode(' AND ',$w)." GROUP BY p.id ORDER BY p.created_at DESC,p.id DESC";$q=$pdo->prepare($sql);$q->execute($p);$pools=$q->fetchAll(PDO::FETCH_ASSOC);$open=(int)$pdo->query("SELECT COUNT(*) FROM factor_viii_pools WHERE status='open'")->fetchColumn();$eligible=FactorViiiPoolService::eligibleCount();$individual=(int)$pdo->query('SELECT COUNT(*) FROM factor_viii_sample_results WHERE individual_required=1')->fetchColumn();self::view('factor_viii_pools',['pools'=>$pools,'preview'=>$_SESSION['fviii_preview']??null,'filters'=>$f,'components'=>$pdo->query("SELECT id,code,name FROM blood_components WHERE code IN ('PFC','PFC24') ORDER BY code")->fetchAll(),'origins'=>$pdo->query("SELECT id,name FROM units WHERE unit_type='processing' AND status='active' ORDER BY name")->fetchAll(),'counts'=>compact('open','eligible','individual')+['badge'=>$open+$eligible],'canCreate'=>Permission::can('quality_control.factor_viii_pool.create'),'canResult'=>Permission::can('quality_control.factor_viii_pool.result'),'canCancel'=>Permission::can('quality_control.factor_viii_pool.cancel'),'pageTitle'=>'Pools de Fator VIII','pageSubtitle'=>'Formação segregada, resultados, propagação e retestes de PFC/PFC24.']);}
 public static function preview():void{self::guard('quality_control.factor_viii_pool.create');try{$f=self::postFilters();$p=FactorViiiPoolService::preview($f);if(!$p)throw new DomainException('Nenhuma unidade elegível foi encontrada.');$_SESSION['fviii_preview']=['filters'=>$f,'pools'=>$p];Flash::set('success','Prévia gerada. Revise os grupos antes de confirmar.');}catch(\Throwable $e){unset($_SESSION['fviii_preview']);self::error($e);}self::back();}
 public static function create():void{self::guard('quality_control.factor_viii_pool.create');try{$v=$_SESSION['fviii_preview']??null;if(!$v)throw new DomainException('A prévia expirou. Gere novamente.');$codes=FactorViiiPoolService::create($v['filters']);unset($_SESSION['fviii_preview']);Flash::set('success',count($codes).' pool(s) criado(s): '.implode(', ',$codes));}catch(\Throwable $e){self::error($e);}self::back();}
 public static function discardPreview():void{self::guard('quality_control.factor_viii_pool.create');unset($_SESSION['fviii_preview']);self::back();}
 public static function saveResult():void{self::guard('quality_control.factor_viii_pool.result');$id=(int)($_POST['pool_id']??0);try{FactorViiiPoolService::saveResult($id,$_POST['result']??($_POST['pools'][$id]??''),!empty($_POST['complete']));Flash::set('success',empty($_POST['complete'])?'Resultado salvo.':'Pool concluído e unidades atualizadas.');}catch(\Throwable $e){self::error($e);}self::back();}
 public static function saveAll():void{self::guard('quality_control.factor_viii_pool.result');$ok=0;$errors=[];foreach((array)($_POST['pools']??[]) as $id=>$v){if(trim((string)$v)==='')continue;try{FactorViiiPoolService::saveResult((int)$id,$v,!empty($_POST['complete']));$ok++;}catch(\Throwable $e){$errors[]='#'.$id.': '.$e->getMessage();}}Flash::set($errors?'error':'success',"{$ok} pool(s) processado(s). ".implode(' | ',$errors));self::back();}
 public static function cancel():void{self::guard('quality_control.factor_viii_pool.cancel');try{FactorViiiPoolService::cancel((int)($_POST['pool_id']??0),(string)($_POST['reason']??''));Flash::set('success','Pool cancelado; as unidades voltaram à elegibilidade.');}catch(\Throwable $e){self::error($e);}self::back();}
 public static function chooseIndividual():void{self::guard('quality_results.edit','/quality-control');try{FactorViiiPoolService::chooseIndividual((int)($_POST['sample_id']??0));Flash::set('success','Análise individual selecionada.');}catch(\Throwable $e){self::error($e);}self::returnTo();}
 public static function saveIndividual():void{self::guard('quality_results.edit','/quality-control');try{FactorViiiPoolService::saveIndividual((int)($_POST['sample_id']??0),$_POST['factor_viii']??'');Flash::set('success','Resultado individual salvo.');}catch(\Throwable $e){self::error($e);}self::returnTo();}
 public static function map():void{AdminGuard::enforce('quality_control.factor_viii_pool.view');$ids=array_values(array_filter(array_map('intval',explode(',',(string)($_GET['ids']??'')))));$where=$ids?'p.id IN ('.implode(',',$ids).')':"p.status<>'cancelled'";$q=Database::connection()->query("SELECT p.*,bc.code component_code,bc.name component_name,u.name origin_name,cu.name created_by_name FROM factor_viii_pools p JOIN blood_components bc ON bc.id=p.blood_component_id JOIN units u ON u.id=p.origin_unit_id LEFT JOIN users cu ON cu.id=p.created_by WHERE {$where} ORDER BY bc.code,u.name,p.id");$pools=$q->fetchAll(PDO::FETCH_ASSOC);foreach($pools as &$pool)$pool['members']=FactorViiiPoolService::members((int)$pool['id']);unset($pool);Auth::registerAudit('factor_viii_pool.map_printed','factor_viii_pools',null,null,['pool_ids'=>array_column($pools,'id')]);require dirname(__DIR__).'/Views/quality_control/factor_viii_map.php';}
 private static function guard(string $permission,string $back='/quality-control/factor-viii-pools'):void{AdminGuard::enforce($permission);if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada.');header('Location: '.$back);exit;}}
 private static function filters():array{return ['component'=>trim((string)($_GET['component']??'')),'origin'=>trim((string)($_GET['origin']??'')),'from'=>trim((string)($_GET['from']??'')),'to'=>trim((string)($_GET['to']??'')),'status'=>trim((string)($_GET['status']??'')),'code'=>trim((string)($_GET['code']??''))];}
 private static function postFilters():array{return ['component'=>trim((string)($_POST['component']??'')),'origin'=>trim((string)($_POST['origin']??'')),'from'=>trim((string)($_POST['from']??'')),'to'=>trim((string)($_POST['to']??''))];}
 private static function error(\Throwable $e):void{Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível processar a operação.');}
 private static function back():never{header('Location: /quality-control/factor-viii-pools');exit;}
 private static function returnTo():never{$r=(string)($_POST['return_to']??'');header('Location: '.(str_starts_with($r,'/quality-control')&&!str_contains($r,"\n")&&!str_contains($r,"\r")?$r:'/quality-control'));exit;}
 private static function view(string $name,array $vars):void{extract($vars);$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__).'/Views/quality_control/'.$name.'.php';}
}
