<?php
declare(strict_types=1);
namespace BloodHub\Controllers;

use BloodHub\Core\{AdminGuard,Csrf,Database,Flash,Permission};
use BloodHub\Services\{MeasurementFormatter,NotificationActionService,NotificationAnalysisService,NotificationWorkflowService,QcNotificationService};
use PDO;

final class NotificationController
{
 public static function index():void
 {
  AdminGuard::enforce('notifications.view');$pdo=Database::connection();[$scope,$params]=QcNotificationService::scopeSql('n');$where=[$scope];$f=$_GET;
  foreach([['unit','n.origin_unit_id'],['component','n.blood_component_id'],['test','n.test_id']]as[$key,$column])if(!empty($f[$key])){$where[]="$column=:$key";$params[$key]=$f[$key];}
  if(!empty($f['status'])){$statuses=$f['status']==='AWAITING_ANALYSIS'?['ACKNOWLEDGED','IN_ANALYSIS']:[$f['status']];$statusMarks=[];foreach($statuses as$index=>$status){$key='status_'.$index;$statusMarks[]=':'.$key;$params[$key]=$status;}$where[]="(CASE WHEN a.status IN ('IN_ANALYSIS','IN_FOLLOW_UP','COMPLETED') THEN a.status ELSE n.status END) IN (".implode(',',$statusMarks).')';}
  if(!empty($f['from'])){$where[]='DATE(n.occurred_at)>=:from';$params['from']=$f['from'];}if(!empty($f['to'])){$where[]='DATE(n.occurred_at)<=:to';$params['to']=$f['to'];}
  foreach([['donation','n.donation_number_snapshot'],['lcqh','n.lcqh_code_snapshot'],['code','n.public_code']]as[$key,$column])if(!empty($f[$key])){$where[]="$column LIKE :$key";$params[$key]='%'.trim((string)$f[$key]).'%';}
  $effectiveListStatus="CASE WHEN a.status IN ('IN_ANALYSIS','IN_FOLLOW_UP','COMPLETED') THEN a.status ELSE n.status END";$tab=(string)($f['tab']??'pending');if($tab==='pending')$where[]="$effectiveListStatus IN ('PENDING_ACKNOWLEDGEMENT','ACKNOWLEDGED')";elseif($tab==='tracking')$where[]="$effectiveListStatus IN ('IN_ANALYSIS','ANALYZED','IN_FOLLOW_UP')";elseif($tab==='closed')$where[]="$effectiveListStatus IN ('COMPLETED','CLOSED','CANCELLED')";
  $sql="SELECT n.*,ack.name acknowledged_by_name,(SELECT el.status FROM qc_notification_email_logs el WHERE el.notification_id=n.id ORDER BY el.id DESC LIMIT 1) email_status,ai.analysis_id,a.analysis_code FROM qc_notifications n LEFT JOIN users ack ON ack.id=n.acknowledged_by LEFT JOIN qc_notification_analysis_items ai ON ai.notification_id=n.id AND ai.removed_at IS NULL LEFT JOIN qc_notification_analyses a ON a.id=ai.analysis_id WHERE ".implode(' AND ',$where).' ORDER BY n.occurred_at DESC,n.id DESC';$q=$pdo->prepare($sql);$q->execute($params);$notifications=$q->fetchAll(PDO::FETCH_ASSOC);
  [$countScope,$countParams]=QcNotificationService::scopeSql('n');$effectiveStatus="CASE WHEN a.status IN ('IN_ANALYSIS','IN_FOLLOW_UP','COMPLETED') THEN a.status ELSE n.status END";$q=$pdo->prepare("SELECT {$effectiveStatus} status,COUNT(DISTINCT n.id) total FROM qc_notifications n LEFT JOIN qc_notification_analysis_items ai ON ai.notification_id=n.id AND ai.removed_at IS NULL LEFT JOIN qc_notification_analyses a ON a.id=ai.analysis_id WHERE {$countScope} GROUP BY {$effectiveStatus}");$q->execute($countParams);$counts=array_fill_keys(['PENDING_ACKNOWLEDGEMENT','ACKNOWLEDGED','IN_ANALYSIS','IN_FOLLOW_UP','COMPLETED','CLOSED'],0);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$row)$counts[$row['status']]=(int)$row['total'];$counts['AWAITING_ANALYSIS']=$counts['ACKNOWLEDGED']+$counts['IN_ANALYSIS'];
  $events=[];if($notifications){$ids=array_column($notifications,'id');$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT e.*,u.name user_name FROM qc_notification_events e LEFT JOIN users u ON u.id=e.user_id WHERE e.notification_id IN ($marks) ORDER BY e.created_at,e.id");$q->execute($ids);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$e)$events[$e['notification_id']][]=$e;}
  $units=$pdo->query("SELECT id,name FROM units WHERE status='active' AND unit_type='processing' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);$components=$pdo->query('SELECT id,name FROM blood_components ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$tests=$pdo->query('SELECT id,name FROM tests ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);
  $canAcknowledge=Permission::can('notifications.acknowledge');$canAnalyze=Permission::can('notifications.analyze');$canViewAll=Permission::can('notifications.view_all');$labels=NotificationWorkflowService::labels();$pageTitle='Notificações';$pageSubtitle='Gestão de resultados de Controle de Qualidade fora da especificação.';$flash=Flash::pull();require dirname(__DIR__).'/Views/notifications/index.php';
 }
 public static function acknowledge():void{self::postGuard('notifications.acknowledge');try{$ids=isset($_POST['ids'])?(array)$_POST['ids']:[($_POST['id']??0)];$count=NotificationWorkflowService::acknowledge($ids);Flash::set('success',$count.' '.($count===1?'ciência registrada.':'ciências registradas.'));}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications');}
 public static function createAnalysis():void{self::postGuard('notifications.analyze');try{$id=NotificationAnalysisService::create((array)($_POST['ids']??[]));Flash::set('success','Análise criada com sucesso.');self::back('/notifications/analyses/view?id='.$id);}catch(\Throwable$e){Flash::set('error',$e->getMessage());self::back('/notifications?tab=pending');}}
 public static function analyses():void
 {AdminGuard::enforce('notifications.view');$pdo=Database::connection();[$scope,$params]=QcNotificationService::analysisScopeSql('a');$where=[$scope];$f=$_GET;foreach([['unit','a.unit_id'],['component','a.blood_component_id'],['status','a.status']]as[$key,$column])if(!empty($f[$key])){$where[]="$column=:$key";$params[$key]=$f[$key];}if(!empty($f['test'])){$where[]='EXISTS (SELECT 1 FROM qc_notification_analysis_items filter_i JOIN qc_notifications filter_n ON filter_n.id=filter_i.notification_id WHERE filter_i.analysis_id=a.id AND filter_i.removed_at IS NULL AND filter_n.test_id=:test)';$params['test']=$f['test'];}if(!empty($f['from'])){$where[]='a.period_end>=:from';$params['from']=$f['from'];}if(!empty($f['to'])){$where[]='a.period_start<=:to';$params['to']=$f['to'];}if(!empty($f['code'])){$where[]='a.analysis_code LIKE :code';$params['code']='%'.trim((string)$f['code']).'%';}
  $q=$pdo->prepare("SELECT a.*,u.name unit_name,bc.name component_name,t.name test_name,(SELECT GROUP_CONCAT(DISTINCT n.test_name_snapshot ORDER BY n.test_name_snapshot SEPARATOR '||') FROM qc_notification_analysis_items ti JOIN qc_notifications n ON n.id=ti.notification_id WHERE ti.analysis_id=a.id AND ti.removed_at IS NULL) test_names,(SELECT COUNT(*) FROM qc_notification_analysis_items i WHERE i.analysis_id=a.id AND i.removed_at IS NULL) occurrence_count,(SELECT COUNT(*) FROM qc_notification_actions ac WHERE ac.analysis_id=a.id) action_count FROM qc_notification_analyses a JOIN units u ON u.id=a.unit_id LEFT JOIN blood_components bc ON bc.id=a.blood_component_id LEFT JOIN tests t ON t.id=a.test_id WHERE ".implode(' AND ',$where).' ORDER BY a.updated_at DESC');$q->execute($params);$analyses=$q->fetchAll(PDO::FETCH_ASSOC);
  [$cs,$cp]=QcNotificationService::analysisScopeSql('a');$q=$pdo->prepare("SELECT status,COUNT(*) total FROM qc_notification_analyses a WHERE {$cs} GROUP BY status");$q->execute($cp);$counts=array_fill_keys(['IN_ANALYSIS','IN_FOLLOW_UP','COMPLETED'],0);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r)$counts[$r['status']]=(int)$r['total'];$units=$pdo->query("SELECT id,name FROM units WHERE status='active' AND unit_type='processing' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);$components=$pdo->query('SELECT id,name FROM blood_components ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$tests=$pdo->query('SELECT id,name FROM tests ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);$canViewAll=Permission::can('notifications.view_all');$pageTitle='Análises';$pageSubtitle='Análise de não conformidades e acompanhamento dos planos de ação.';$flash=Flash::pull();require dirname(__DIR__).'/Views/notifications/analyses.php';}
 public static function showAnalysis():void
 {AdminGuard::enforce('notifications.view');$pdo=Database::connection();try{$analysis=NotificationAnalysisService::accessible($pdo,(int)($_GET['id']??0));}catch(\Throwable$e){Flash::set('error',$e->getMessage());self::back('/notifications/analyses');}$q=$pdo->prepare("SELECT n.*,i.id item_id FROM qc_notification_analysis_items i JOIN qc_notifications n ON n.id=i.notification_id WHERE i.analysis_id=:id AND i.removed_at IS NULL ORDER BY n.occurred_at");$q->execute(['id'=>$analysis['id']]);$items=$q->fetchAll(PDO::FETCH_ASSOC);foreach($items as&$item){$item['analysis_result_display']=MeasurementFormatter::formatResult((string)$item['test_code_snapshot'],$item['result_value_snapshot'],$item['result_unit_snapshot']);$item['analysis_reference_display']=MeasurementFormatter::formatSpecification((string)$item['test_code_snapshot'],['rule_type'=>$item['rule_snapshot'],'expected_min'=>$item['min_value_snapshot'],'expected_max'=>$item['max_value_snapshot'],'expected_text'=>$item['expected_text_snapshot'],'unit'=>$item['specification_unit_snapshot']?:$item['result_unit_snapshot'],'specification_snapshot_text'=>$item['reference_display_snapshot']]);}unset($item);$q=$pdo->prepare('SELECT ac.*,u.name responsible_user_name FROM qc_notification_actions ac LEFT JOIN users u ON u.id=ac.responsible_user_id WHERE ac.analysis_id=:id ORDER BY ac.created_at');$q->execute(['id'=>$analysis['id']]);$actions=$q->fetchAll(PDO::FETCH_ASSOC);$actionProgress=['total'=>0,'completed'=>0,'pending'=>0];foreach($actions as$action){if($action['status']!=='CANCELLED'){$actionProgress['total']++;if($action['status']==='COMPLETED')$actionProgress['completed']++;else$actionProgress['pending']++;}}$q=$pdo->prepare('SELECT e.*,u.name user_name FROM qc_notification_analysis_events e LEFT JOIN users u ON u.id=e.user_id WHERE e.analysis_id=:id ORDER BY e.created_at,e.id');$q->execute(['id'=>$analysis['id']]);$events=$q->fetchAll(PDO::FETCH_ASSOC);$q=$pdo->prepare("SELECT DISTINCT u.id,u.name FROM users u LEFT JOIN user_units uu ON uu.user_id=u.id WHERE u.status='active' AND (u.primary_unit_id=:unit OR uu.unit_id=:unit2) ORDER BY u.name");$q->execute(['unit'=>$analysis['unit_id'],'unit2'=>$analysis['unit_id']]);$responsibles=$q->fetchAll(PDO::FETCH_ASSOC);
  $candidateQuery=$pdo->prepare("SELECT id,public_code,donation_number_snapshot,lcqh_code_snapshot,occurred_at,result_display_snapshot,test_id,test_name_snapshot FROM qc_notifications WHERE status='ACKNOWLEDGED' AND origin_unit_id=:unit AND blood_component_id <=> :component AND DATE(occurred_at) BETWEEN :start AND :end ORDER BY occurred_at");$candidateQuery->execute(['unit'=>$analysis['unit_id'],'component'=>$analysis['blood_component_id'],'start'=>$analysis['period_start'],'end'=>$analysis['period_end']]);$candidates=$candidateQuery->fetchAll(PDO::FETCH_ASSOC);
  $testNames=[];$statGroups=[];foreach($items as$i){$testNames[(int)$i['test_id']]=$i['test_name_snapshot'];$key=(int)$i['test_id'];if(!isset($statGroups[$key]))$statGroups[$key]=['name'=>$i['test_name_snapshot'],'code'=>$i['test_code_snapshot'],'values'=>[],'units'=>[],'total'=>0];$statGroups[$key]['total']++;if(is_numeric($i['result_value_snapshot'])){$statGroups[$key]['values'][]=(float)$i['result_value_snapshot'];$statGroups[$key]['units'][(string)$i['result_unit_snapshot']]=true;}}$stats=[];foreach($statGroups as$group){if(count($group['values'])===$group['total']&&count($group['units'])<=1&&$group['values']){$unit=array_key_first($group['units']);$stats[]=['name'=>$group['name'],'count'=>$group['total'],'min'=>MeasurementFormatter::formatResult((string)$group['code'],min($group['values']),$unit),'max'=>MeasurementFormatter::formatResult((string)$group['code'],max($group['values']),$unit),'avg'=>MeasurementFormatter::formatResult((string)$group['code'],array_sum($group['values'])/count($group['values']),$unit)];}}$canAnalyze=Permission::can('notifications.analyze');$canAction=Permission::can('notifications.action_plan');$canClose=Permission::can('notifications.close');$causes=NotificationAnalysisService::CAUSES;$actionStatuses=NotificationActionService::STATUSES;$pageTitle='Análise '.$analysis['analysis_code'];$pageSubtitle='Gestão da não conformidade e do plano de ação.';$flash=Flash::pull();require dirname(__DIR__).'/Views/notifications/analysis_show.php';}
 public static function saveAnalysis():void{self::postGuard('notifications.analyze');$id=(int)($_POST['analysis_id']??0);try{NotificationAnalysisService::save($id,$_POST);Flash::set('success','Rascunho salvo.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$id);}
 public static function startFollowUp():void{self::postGuard('notifications.analyze');$id=(int)($_POST['analysis_id']??0);try{if(array_key_exists('analysis_text',$_POST))NotificationAnalysisService::save($id,$_POST);NotificationAnalysisService::startFollowUp($id);Flash::set('success','Acompanhamento iniciado.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$id);}
 public static function completeAnalysis():void{self::postGuard('notifications.close');$id=(int)($_POST['analysis_id']??0);try{if(array_key_exists('analysis_text',$_POST))NotificationAnalysisService::save($id,$_POST);NotificationAnalysisService::complete($id,(string)($_POST['conclusion_text']??''));Flash::set('success','Análise encerrada.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$id);}
 public static function saveAction():void{self::postGuard('notifications.action_plan');$analysisId=(int)($_POST['analysis_id']??0);try{if(array_key_exists('analysis_text',$_POST))NotificationAnalysisService::save($analysisId,$_POST);NotificationActionService::save(((int)($_POST['action_id']??0))?:null,$analysisId,$_POST);Flash::set('success','Ação salva.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$analysisId.'#actions');}
 public static function addItems():void{self::postGuard('notifications.analyze');$analysisId=(int)($_POST['analysis_id']??0);try{$count=NotificationAnalysisService::addItems($analysisId,(array)($_POST['ids']??[]));Flash::set('success',$count.' ocorrência(s) adicionada(s).');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$analysisId);}
 public static function removeItem():void{self::postGuard('notifications.analyze');$analysisId=(int)($_POST['analysis_id']??0);try{NotificationAnalysisService::removeItem($analysisId,(int)($_POST['notification_id']??0));Flash::set('success','Ocorrência removida da análise.');}catch(\Throwable$e){Flash::set('error',$e->getMessage());}self::back('/notifications/analyses/view?id='.$analysisId);}
 private static function postGuard(string$permission):void{AdminGuard::enforce($permission);if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada. Tente novamente.');self::back('/notifications');}}
 private static function back(string$url):never{header('Location: '.$url);exit;}
}
