<?php
declare(strict_types=1);
namespace BloodHub\Controllers;

use BloodHub\Core\{AdminGuard,Auth,Csrf,Database,Flash,Permission};
use BloodHub\Services\{BagTareResolver,CalculatedTestService,CryoprecipitateResultService,FactorViiiPoolService,FreshPlasmaResultService,HemolysisCalculator,HemolysisResultService,HemolysisSpreadsheetReader,PlateletResultService,QcMonthlyClosureService,QcNotificationService,RedCellResidualLeukocyteService,SampleTestSynchronizer,SpecificationEvaluator,TestResultService,WashedRedCellResultService,WeightVolumeService};
use DomainException;
use PDO;

final class QualityControlController
{
    public static function index():void
    {
        AdminGuard::enforce('quality_results.view');$filters=self::filters('in_progress');$pdo=Database::connection();SampleTestSynchronizer::syncOpenSamples();
        $components=$pdo->query("SELECT DISTINCT bc.id,bc.code,bc.name FROM blood_components bc JOIN test_blood_components tbc ON tbc.blood_component_id=bc.id JOIN tests t ON t.id=tbc.test_id AND t.status='active' WHERE bc.status='active' ORDER BY bc.code")->fetchAll(PDO::FETCH_ASSOC);
        if(!$filters['component']&&$components)$filters['component']=(string)$components[0]['id'];
        $where=["s.purpose='quality_control'","s.status IN ('received','in_analysis','partial_results','completed')"];$params=[];
        foreach([['origin','s.origin_unit_id'],['component','s.blood_component_id']] as [$key,$column])if($filters[$key]!==''){$where[]="$column=:$key";$params[$key]=$filters[$key];}
        if($filters['status']==='in_progress')$where[]="s.status IN ('received','in_analysis','partial_results')";
        elseif($filters['status']!=='all'){$where[]='s.status=:status';$params['status']=$filters['status'];}
        if($filters['received_date']!==''){$where[]='DATE(s.received_at)=:received_date';$params['received_date']=$filters['received_date'];}
        foreach([['donation','s.donation_number'],['lcqh','s.lcqh_code']] as [$key,$column])if($filters[$key]!==''){$where[]="$column LIKE :$key";$params[$key]='%'.$filters[$key].'%';}
        $sql="SELECT s.*,u.name origin_name,bc.code component_code,bc.name component_name,bc.density,b.name bag_brand_name,b.reference_number,CASE WHEN s.status='completed' THEN s.preservative_id ELSE b.preservative_id END resolved_preservative_id,p.code preservative_code,p.name preservative_name,wr.gross_weight,wr.tare_weight_used,wr.net_weight,wr.density_used,wr.volume_ml,wr.bag_brand_tare_id,
            MAX(CASE WHEN t.code='HEMATOCRIT' THEN tr.result_value_numeric END) hematocrit,
            MAX(CASE WHEN t.code='HEMOGLOBIN' THEN tr.result_value_numeric END) hemoglobin,
            MAX(CASE WHEN t.code='HEMOGLOBIN_PER_UNIT' THEN tr.result_value_numeric END) hemoglobin_per_unit,
            MAX(CASE WHEN t.code='VOLUME' THEN tr.result_value_numeric END) manual_volume,
            MAX(CASE WHEN t.code='FIBRINOGEN' THEN tr.result_value_numeric END) fibrinogen,
            cr.dilution crio_dilution,cr.fibrinogen_mg_dl crio_fibrinogen_mg_dl,cr.fibrinogen_mg_u crio_fibrinogen_mg_u,cr.gross_weight crio_gross_weight
            FROM samples s LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN bag_brands b ON b.id=s.bag_brand_id LEFT JOIN preservatives p ON p.id=CASE WHEN s.status='completed' THEN s.preservative_id ELSE b.preservative_id END LEFT JOIN sample_weight_results wr ON wr.sample_id=s.id LEFT JOIN cryoprecipitate_results cr ON cr.sample_id=s.id LEFT JOIN sample_tests st ON st.sample_id=s.id LEFT JOIN tests t ON t.id=st.test_id LEFT JOIN test_results tr ON tr.sample_test_id=st.id WHERE ".implode(' AND ',$where).' GROUP BY s.id ORDER BY s.received_at DESC,s.id DESC';
        $q=$pdo->prepare($sql);$q->execute($params);$samples=$q->fetchAll(PDO::FETCH_ASSOC);
        foreach($samples as &$sample){$sample['hemolysis']=CalculatedTestService::hemolysisState((int)$sample['id']);$sample['washed_red_cell']=WashedRedCellResultService::state((int)$sample['id']);$sample['platelet']=PlateletResultService::state((int)$sample['id']);$sample['residual_leukocytes']=RedCellResidualLeukocyteService::state((int)$sample['id']);$sample['fresh_plasma']=FreshPlasmaResultService::state((int)$sample['id']);$sample['factor_viii']=FactorViiiPoolService::state((int)$sample['id']);$sample['nonconforming']=SpecificationEvaluator::nonconforming((int)$sample['id']);$sample['missing_requirements']=TestResultService::missingRequired((int)$sample['id']);try{$sample['resolved_tare']=($sample['bag_brand_id']&&$sample['blood_component_id'])?BagTareResolver::resolve((int)$sample['bag_brand_id'],(int)$sample['blood_component_id']):null;$sample['tare_error']=null;}catch(DomainException $e){$sample['resolved_tare']=null;$sample['tare_error']=$e->getMessage();}}unset($sample);
        self::view('index',['samples'=>$samples,'components'=>$components,'origins'=>$pdo->query("SELECT DISTINCT u.id,u.name FROM units u JOIN samples s ON s.origin_unit_id=u.id WHERE s.purpose='quality_control' ORDER BY u.name")->fetchAll(PDO::FETCH_ASSOC),'filters'=>$filters,'canEdit'=>Permission::can('quality_results.edit'),'canComplete'=>Permission::can('quality_results.complete'),'queueCounts'=>self::queueCounts(),'pageTitle'=>'Controle de Qualidade','pageSubtitle'=>'Registre, acompanhe e conclua os resultados das amostras recebidas pelo LCQH.']);
    }

    public static function save():void
    {
        $postedId=self::id($_POST['sample_id']??null);if($postedId&&isset($_POST['samples'][$postedId])&&is_array($_POST['samples'][$postedId]))$_POST=array_merge($_POST,$_POST['samples'][$postedId]);
        AdminGuard::enforce('quality_results.edit');if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada. Tente novamente.');self::redirect('/quality-control');}
        $id=self::id($_POST['sample_id']??null);$sample=self::eligible($id,false);if(!$sample){Flash::set('error','Amostra não encontrada ou indisponível para edição.');self::redirect('/quality-control');}
        $componentCode=self::componentCode((int)$sample['blood_component_id']);
        if(PlateletResultService::supports($componentCode))self::savePlateletRequest($sample,$_POST);
        if(in_array($componentCode,['PF','PF24'],true))self::saveFreshPlasmaRequest($sample,$_POST);
        if(in_array($componentCode,['PFC','PFC24'],true))self::savePlasmaRequest($sample,$_POST);
        if($componentCode==='CRIO')self::saveCryoprecipitateRequest($sample,$_POST);
        $lcqh=trim((string)($_POST['lcqh_code']??''));$gross=trim((string)($_POST['gross_weight']??''));$ht=trim((string)($_POST['hematocrit']??''));$hb=trim((string)($_POST['hemoglobin']??''));
        if(mb_strlen($lcqh)>80){Flash::set('error','Código LCQH deve ter no máximo 80 caracteres.');self::redirect('/quality-control');}
        $pdo=Database::connection();try{$pdo->beginTransaction();
            self::resolvePreservative($sample,false);
            $pdo->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh?:null,'id'=>$id]);
            if(($sample['lcqh_code']??null)!==($lcqh?:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']],['lcqh_code'=>$lcqh?:null]);
            if(WashedRedCellResultService::supports($componentCode)){WashedRedCellResultService::save($sample,$_POST);SpecificationEvaluator::evaluateSampleResults($id);$pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));}
            if($gross!=='')self::saveVolume($sample,$gross);
            if($ht!=='')TestResultService::saveNumeric($id,TestResultService::CODES['hematocrit'],$ht);
            if($hb!=='')TestResultService::saveNumeric($id,TestResultService::CODES['hemoglobin'],$hb);
            TestResultService::recalculateHemoglobinPerUnit($id);
            if(RedCellResidualLeukocyteService::supports($componentCode))RedCellResidualLeukocyteService::save($id,$_POST);
            CalculatedTestService::recalculateHemolysis($id);
            SpecificationEvaluator::evaluateSampleResults($id);
            $pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');
        }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível salvar os resultados.');}
        self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));
    }

    public static function saveAll():void
    {
        AdminGuard::enforce('quality_results.edit');self::csrf(self::returnUrl('/quality-control'));
        [$saved,$errors]=self::processBatch(false);
        Auth::registerAudit('QUALITY_RESULTS_BATCH_SAVE','samples',null,null,['processed'=>$saved+count($errors),'saved'=>$saved,'failed'=>count($errors)]);
        $message=$saved.' '.($saved===1?'amostra salva':'amostras salvas').'.';
        if($errors)$message.=' '.count($errors).' '.(count($errors)===1?'não pôde ser salva: ':'não puderam ser salvas: ').implode(' | ',$errors);
        Flash::set($errors?'error':'success',$message);self::redirect(self::returnUrl('/quality-control'));
    }

    public static function completeAll():void
    {
        AdminGuard::enforce('quality_results.complete');self::csrf(self::returnUrl('/quality-control'));
        if(empty($_POST['specification_acknowledged'])){foreach(array_keys((array)($_POST['samples']??[])) as $sid)if(SpecificationEvaluator::nonconforming((int)$sid)){Flash::set('error','Existem resultados fora da especificação. Confirme explicitamente a ciência para concluir.');self::redirect(self::returnUrl('/quality-control'));}}[$completed,$pending,$errors]=self::processBatch(true);
        Auth::registerAudit('QUALITY_RESULTS_BATCH_COMPLETE','samples',null,null,['processed'=>$completed+count($pending)+count($errors),'completed'=>$completed,'pending'=>count($pending),'failed'=>count($errors)]);
        $message=$completed.' '.($completed===1?'análise concluída':'análises concluídas').'. ';
        $message.=count($pending).' '.(count($pending)===1?'permanece pendente.':'permanecem pendentes.');
        if($pending)$message.=' '.implode(' | ',$pending);if($errors)$message.=' Falhas: '.implode(' | ',$errors);
        Flash::set(($pending||$errors)?'error':'success',$message);self::redirect(self::returnUrl('/quality-control'));
    }

    public static function previewSpecifications():void
    {
        AdminGuard::enforce('quality_results.complete');
        header('Content-Type: application/json; charset=UTF-8');
        if(!Csrf::validate($_POST['_csrf']??null)){http_response_code(419);echo json_encode(['ok'=>false,'message'=>'Sessão expirada. Atualize a página e tente novamente.']);return;}
        $rows=is_array($_POST['samples']??null)?$_POST['samples']:[];$only=self::id($_POST['sample_id']??null);
        if($only)$rows=isset($rows[$only])?[$only=>$rows[$only]]:[$only=>[]];
        else foreach(explode(',',(string)($_POST['visible_ids']??''))as$visibleId)if(($visibleId=self::id($visibleId))&&!isset($rows[$visibleId]))$rows[$visibleId]=[];
        $pdo=Database::connection();$samples=[];$errors=[];
        foreach($rows as$key=>$values){$id=self::id($key);$sample=$id?self::eligible($id,false):null;if(!$sample){$errors[]='Amostra #'.$id.' indisponível.';continue;}
            try{$pdo->beginTransaction();self::persistSample($sample,(array)$values);self::resolvePreservative($sample,false);if(self::componentCode((int)$sample['blood_component_id'])==='CRIO')CryoprecipitateResultService::recalculate($id);$evaluation=SpecificationEvaluator::evaluateSampleResults($id);$items=$evaluation['divergences'];$pdo->commit();$samples[]=['id'=>$id,'label'=>(string)($sample['donation_number']?:($sample['lcqh_code']?:('#'.$id))),'items'=>$items];}
            catch(\Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$errors[]='Amostra #'.$id.': '.($e instanceof DomainException?$e->getMessage():'não foi possível avaliar.');}
        }
        echo json_encode(['ok'=>!$errors,'samples'=>$samples,'nonconforming_count'=>array_sum(array_map(static fn($row)=>count($row['items']),$samples)),'errors'=>$errors],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    }

    private static function processBatch(bool $complete):array
    {
        $rows=is_array($_POST['samples']??null)?$_POST['samples']:[];foreach(explode(',',(string)($_POST['visible_ids']??'')) as $visibleId)if(($visibleId=self::id($visibleId))&&!isset($rows[$visibleId]))$rows[$visibleId]=[];$saved=$completed=0;$pending=[];$errors=[];$pdo=Database::connection();
        foreach($rows as $key=>$values){$id=self::id($key);$sample=$id?self::eligible($id,false):null;$label=trim((string)($values['lcqh_code']??''))?:('Amostra #'.$id);
            if(!$sample){$errors[]=$label.' — indisponível';continue;}
            try{$pdo->beginTransaction();self::persistSample($sample,(array)$values);if($complete){self::resolvePreservative($sample,true);SpecificationEvaluator::evaluateSampleResults($id);$nc=SpecificationEvaluator::nonconforming($id);if($nc&&!empty($_POST['specification_acknowledged']))SpecificationEvaluator::acknowledge($id,(int)(Auth::user()['id']??0));$missing=TestResultService::complete($id);if($missing)$pending[]=$label.' — aguardando '.self::pendingLabel($id,$missing);else$completed++;}else{SpecificationEvaluator::evaluateSampleResults($id);$saved++;}$pdo->commit();if($complete&&!$missing)QcNotificationService::deliverPendingForSample($id);}
            catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]=$label.' — '.($e instanceof DomainException?$e->getMessage():'não foi possível processar');}
        }
        return $complete?[$completed,$pending,$errors]:[$saved,$errors];
    }

    private static function persistSample(array $sample,array $values):void
    {
        self::resolvePreservative($sample,false);
        $componentCode=self::componentCode((int)$sample['blood_component_id']);
        if(WashedRedCellResultService::supports($componentCode)){
            $id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);WashedRedCellResultService::save($sample,$values);return;
        }
        if(PlateletResultService::supports($componentCode)){self::persistPlateletSample($sample,$values);return;}
        if(in_array($componentCode,['PF','PF24'],true)){self::persistFreshPlasmaSample($sample,$values);return;}
        if(in_array($componentCode,['PFC','PFC24'],true)){self::persistPlasmaSample($sample,$values);return;}
        if($componentCode==='CRIO'){self::persistCryoprecipitateSample($sample,$values);return;}
        $id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');
        if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');
        Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);
        if(($sample['lcqh_code']??null)!==($lcqh!==''?$lcqh:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']??null],['lcqh_code'=>$lcqh!==''?$lcqh:null]);
        $gross=trim((string)($values['gross_weight']??''));$ht=trim((string)($values['hematocrit']??''));$hb=trim((string)($values['hemoglobin']??''));
        if($gross!=='')self::saveVolume($sample,$gross);if($ht!=='')TestResultService::saveNumeric($id,TestResultService::CODES['hematocrit'],$ht);if($hb!=='')TestResultService::saveNumeric($id,TestResultService::CODES['hemoglobin'],$hb);
        TestResultService::recalculateHemoglobinPerUnit($id);if(RedCellResidualLeukocyteService::supports($componentCode))RedCellResidualLeukocyteService::save($id,$values);CalculatedTestService::recalculateHemolysis($id);
    }

    private static function saveVolume(array $sample,string $gross):void
    {
        WeightVolumeService::save($sample,$gross);
    }

    public static function complete():void
    {AdminGuard::enforce('quality_results.complete');if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada.');self::redirect('/quality-control');}$id=self::id($_POST['sample_id']??null);$sample=self::eligible($id,true);if(!$sample){Flash::set('error','Amostra não encontrada.');self::redirect('/quality-control');}$componentCode=self::componentCode((int)$sample['blood_component_id']);$pdo=Database::connection();try{$pdo->beginTransaction();if(isset($_POST['samples'][$id])&&is_array($_POST['samples'][$id]))self::persistSample($sample,$_POST['samples'][$id]);self::resolvePreservative($sample,true);if($componentCode==='CRIO')CryoprecipitateResultService::recalculate($id);$missing=TestResultService::complete($id);$pdo->commit();if(!$missing)QcNotificationService::deliverPendingForSample($id);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível concluir a análise.');self::redirect('/quality-control');}
$codes=array_column($missing,'code');if(in_array('FREE_HEMOGLOBIN',$codes,true))$message='Não é possível concluir. Aguardando resultados de Grau de Hemólise.';elseif(in_array('HEMOLYSIS_DEGREE',$codes,true)){$state=CalculatedTestService::hemolysisState($id);$message='Não é possível concluir. '.($state['missing']?'Aguardando '.implode(', ',$state['missing']).'.':'Grau de Hemólise pendente.');}elseif(in_array('SPECIFICATION_ACK',$codes,true))$message='Revise e confirme a ciência dos resultados fora da especificação.';elseif($missing)$message='Não é possível concluir. Faltam: '.implode(', ',array_column($missing,'name')).'.';else$message='Análise concluída com sucesso.';Flash::set($missing?'error':'success',$message);self::redirect('/quality-control');}

    public static function hemolysis():void
    {AdminGuard::enforce('quality_results.hemolysis');$pdo=Database::connection();SampleTestSynchronizer::syncOpenSamples();$f=self::filters();$where=["s.purpose='quality_control'","s.status IN ('received','in_analysis','partial_results')","calc.code='HEMOLYSIS_DEGREE'","calc.status='active'","hst.status IN ('pending','in_progress')"];$p=[];foreach([['origin','s.origin_unit_id'],['component','s.blood_component_id'],['status','hst.status']] as [$k,$c])if($f[$k]!==''){$where[]="$c=:$k";$p[$k]=$f[$k];}if($f['received_date']!==''){$where[]='DATE(s.received_at)=:received_date';$p['received_date']=$f['received_date'];}foreach([['donation','s.donation_number'],['lcqh','s.lcqh_code']] as [$k,$c])if($f[$k]!==''){$where[]="$c LIKE :$k";$p[$k]='%'.$f[$k].'%';}
        $sql="SELECT s.id,s.donation_number,s.lcqh_code,s.production_date,s.received_at,u.name origin_name,bc.id component_id,bc.code component_code,bc.name component_name,hst.status test_status FROM samples s JOIN blood_components bc ON bc.id=s.blood_component_id JOIN test_blood_components applicable ON applicable.blood_component_id=bc.id JOIN tests calc ON calc.id=applicable.test_id JOIN sample_tests hst ON hst.sample_id=s.id JOIN tests free_hb ON free_hb.id=hst.test_id AND free_hb.code='FREE_HEMOGLOBIN' LEFT JOIN units u ON u.id=s.origin_unit_id WHERE ".implode(' AND ',$where).' ORDER BY s.received_at DESC,s.id DESC';$q=$pdo->prepare($sql);$q->execute($p);$rows=$q->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row){$row['snapshot']=HemolysisResultService::state((int)$row['id']);$row['hemolysis']=CalculatedTestService::hemolysisState((int)$row['id']);}unset($row);
        self::view('hemolysis',['samples'=>$rows,'filters'=>$f,'components'=>$pdo->query("SELECT DISTINCT bc.id,bc.code,bc.name FROM blood_components bc JOIN test_blood_components x ON x.blood_component_id=bc.id JOIN tests t ON t.id=x.test_id AND t.code='HEMOLYSIS_DEGREE' ORDER BY bc.code")->fetchAll(PDO::FETCH_ASSOC),'origins'=>$pdo->query("SELECT id,name FROM units WHERE status='active' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC),'preview'=>$_SESSION['hemolysis_import_preview']??null,'canEdit'=>Permission::can('quality_results.edit'),'canComplete'=>Permission::can('quality_results.complete'),'canReplace'=>Permission::can('quality_results.hemolysis_replace'),'queueCounts'=>self::queueCounts(),'pageTitle'=>'Grau de Hemólise','pageSubtitle'=>'Absorbâncias do espectrofotômetro e cálculo rastreável de Hemoglobina Livre.']);}

    public static function saveHemolysis():void
    {AdminGuard::enforce('quality_results.edit');self::csrf('/quality-control/hemolysis');$all=$_POST['samples']??[];$single=isset($_POST['sample_id']);if($single){$chosen=(string)$_POST['sample_id'];$all=isset($all[$chosen])?[$chosen=>$all[$chosen]]:[];}$ok=0;$errors=[];$pdo=Database::connection();foreach($all as $id=>$values){if(!array_filter((array)$values,fn($v)=>trim((string)$v)!==''))continue;$sampleId=self::id($id);if(!$sampleId||!self::eligible($sampleId,false)){$errors[]='Amostra inválida.';continue;}try{$pdo->beginTransaction();HemolysisResultService::save($sampleId,(array)$values);if($single){$missing=HemolysisResultService::complete($sampleId);if($missing)throw new DomainException('Informe '.implode(', ',$missing).'.');}$pdo->commit();$ok++;}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$errors[]='Amostra #'.$sampleId.': '.($e instanceof DomainException?$e->getMessage():'não foi possível concluir.');}}Flash::set($errors?'error':'success',($ok?($single?'Hemoglobina Livre concluída.':"{$ok} amostra(s) salva(s) como parcial. "):'').implode(' ',$errors));self::redirect('/quality-control/hemolysis');}
    public static function completeHemolysis():void
    {AdminGuard::enforce('quality_results.complete');self::csrf('/quality-control/hemolysis');$id=self::id($_POST['sample_id']??null);$missing=HemolysisResultService::complete($id);Flash::set($missing?'error':'success',$missing?'Não é possível concluir. Aguardando '.implode(', ',$missing).'.':'Hemoglobina Livre concluída.');self::redirect('/quality-control/hemolysis');}
    public static function previewHemolysisImport():void
    {AdminGuard::enforce('quality_results.edit');self::csrf('/quality-control/hemolysis?mode=import');try{$file=$_FILES['excel']??null;if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new DomainException('Selecione um arquivo para analisar.');if((int)$file['size']>10*1024*1024)throw new DomainException('O arquivo excede o limite de 10 MB.');$name=(string)$file['name'];$ext=mb_strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['xlsx','xls'],true))throw new DomainException('Formato inválido. Envie um arquivo .xlsx ou .xls.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$allowed=['application/zip','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','application/xml','text/xml','application/octet-stream'];if(!in_array($mime,$allowed,true))throw new DomainException('O tipo real do arquivo não corresponde a uma planilha Excel.');$parsed=HemolysisSpreadsheetReader::read($file['tmp_name'],$ext);$preview=self::matchImport($parsed['rows']);$preview+=['ignored'=>$parsed['ignored'],'errors'=>$parsed['errors'],'filename'=>basename($name),'hash'=>hash_file('sha256',$file['tmp_name']),'size'=>(int)$file['size']];$pdo=Database::connection();$pdo->prepare('INSERT INTO hemolysis_imports(original_filename,file_hash,file_size,valid_rows,matched_rows,unmatched_rows,duplicate_rows,ignored_rows,created_by) VALUES(:name,:hash,:size,:valid,:matched,:unmatched,:duplicate,:ignored,:user)')->execute(['name'=>$preview['filename'],'hash'=>$preview['hash'],'size'=>$preview['size'],'valid'=>$preview['valid'],'matched'=>$preview['matched'],'unmatched'=>$preview['unmatched'],'duplicate'=>$preview['duplicates'],'ignored'=>$preview['ignored'],'user'=>Auth::user()['id']??null]);$preview['import_id']=(int)$pdo->lastInsertId();$_SESSION['hemolysis_import_preview']=$preview;Auth::registerAudit('HEMOLYSIS_IMPORT_PREVIEW','hemolysis_imports',$preview['import_id'],null,array_diff_key($preview,['rows'=>1]));Flash::set('success','Arquivo analisado. Confira as correspondências antes de aplicar.');}catch(\Throwable $e){Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível analisar a planilha.');}self::redirect('/quality-control/hemolysis?mode=import');}
    public static function applyHemolysisImport():void
    {AdminGuard::enforce('quality_results.edit');self::csrf('/quality-control/hemolysis?mode=import');$preview=$_SESSION['hemolysis_import_preview']??null;if(!$preview||!hash_equals((string)$preview['hash'],(string)($_POST['preview_hash']??''))){Flash::set('error','A prévia expirou. Analise o arquivo novamente.');self::redirect('/quality-control/hemolysis?mode=import');}$replace=!empty($_POST['replace_existing'])&&Permission::can('quality_results.hemolysis_replace');$pdo=Database::connection();try{$pdo->beginTransaction();$applied=0;foreach($preview['rows'] as $row){if($row['status']!=='found')continue;HemolysisResultService::save((int)$row['sample_id'],$row,'IMPORT',(int)$preview['import_id'],$replace);$applied++;}$pdo->prepare("UPDATE hemolysis_imports SET status='applied',applied_at=NOW() WHERE id=:id")->execute(['id'=>$preview['import_id']]);$pdo->commit();unset($_SESSION['hemolysis_import_preview']);Flash::set('success',"{$applied} resultado(s) importado(s). A análise não foi concluída automaticamente.");}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Falha ao aplicar resultados. Nenhum dado foi alterado.');}self::redirect('/quality-control/hemolysis?mode=import');}

    private static function matchImport(array $rows):array
    {$counts=[];foreach($rows as $r)$counts[self::identifier($r['sample_name'])]=($counts[self::identifier($r['sample_name'])]??0)+1;$pdo=Database::connection();$q=$pdo->prepare("SELECT s.id,s.lcqh_code,s.donation_number FROM samples s JOIN sample_tests st ON st.sample_id=s.id JOIN tests t ON t.id=st.test_id AND t.code='HEMOLYSIS_DEGREE' WHERE s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results')");$q->execute();$lcqh=[];$don=[];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $s){if($s['lcqh_code']!==null)$lcqh[self::identifier($s['lcqh_code'])]=$s;if($s['donation_number']!==null)$don[self::identifier($s['donation_number'])]=$s;}$matched=$unmatched=$duplicates=0;foreach($rows as &$r){$key=self::identifier($r['sample_name']);if(($counts[$key]??0)>1){$r['status']='duplicate';$r['sample_id']=null;$duplicates++;continue;}$s=$lcqh[$key]??$don[$key]??null;$r['status']=$s?'found':'not_found';$r['sample_id']=$s?(int)$s['id']:null;$r['match_by']=$s?(isset($lcqh[$key])?'LCQH':'DOAÇÃO'):null;$r['calculation']=HemolysisCalculator::calculate($r);$s?$matched++:$unmatched++;}unset($r);return ['rows'=>$rows,'valid'=>count($rows),'matched'=>$matched,'unmatched'=>$unmatched,'duplicates'=>$duplicates];}
    private static function identifier(string $v):string{return mb_strtoupper(trim(preg_replace('/\s+/u',' ',$v)));}
    private static function csrf(string $redirect):void{if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada. Tente novamente.');self::redirect($redirect);}}
    public static function bacteriology():void{AdminGuard::enforce('quality_results.view');$pdo=Database::connection();SampleTestSynchronizer::syncOpenSamples();$q=$pdo->prepare("SELECT s.id,s.donation_number,s.lcqh_code,s.production_date,s.received_at,st.status,u.name origin_name,bc.code component_code,bc.name component_name FROM sample_tests st JOIN tests t ON t.id=st.test_id AND t.code=:code AND t.status='active' JOIN samples s ON s.id=st.sample_id AND s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results') JOIN test_blood_components tbc ON tbc.test_id=t.id AND tbc.blood_component_id=s.blood_component_id JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN units u ON u.id=s.origin_unit_id WHERE st.status IN ('pending','in_progress') ORDER BY s.received_at,s.id");$q->execute(['code'=>SampleTestSynchronizer::BACTERIOLOGY_CODE]);self::view('bacteriology',['samples'=>$q->fetchAll(PDO::FETCH_ASSOC),'queueCounts'=>self::queueCounts(),'pageTitle'=>'Bacteriológico','pageSubtitle'=>'Amostras com ensaio bacteriológico ativo configurado e ainda pendente.']);}
    private static function queueCounts():array{$q=Database::connection()->query("SELECT t.code,COUNT(*) total FROM sample_tests st JOIN tests t ON t.id=st.test_id AND t.status='active' JOIN samples s ON s.id=st.sample_id AND s.purpose='quality_control' AND s.status IN ('received','in_analysis','partial_results') JOIN test_blood_components tbc ON tbc.test_id=t.id AND tbc.blood_component_id=s.blood_component_id WHERE st.status IN ('pending','in_progress') AND t.code IN ('HEMOLYSIS_DEGREE','BACTERIOLOGY') GROUP BY t.code");$counts=['hemolysis'=>0,'bacteriology'=>0];foreach($q->fetchAll(PDO::FETCH_ASSOC) as $row){if($row['code']==='HEMOLYSIS_DEGREE')$counts['hemolysis']=(int)$row['total'];if($row['code']==='BACTERIOLOGY')$counts['bacteriology']=(int)$row['total'];}return $counts;}
    private static function resolvePreservative(array $sample,bool $forCompletion):?int
    {$pdo=Database::connection();$q=$pdo->prepare('SELECT b.preservative_id FROM samples s LEFT JOIN bag_brands b ON b.id=s.bag_brand_id WHERE s.id=:id'.($pdo->inTransaction()?' FOR UPDATE':''));$q->execute(['id'=>$sample['id']]);$preservative=$q->fetchColumn();$preservative=$preservative!==false&&$preservative!==null?(int)$preservative:null;if($forCompletion&&!$preservative&&self::componentRequiresPreservative((int)$sample['blood_component_id']))throw new DomainException('Preservante não configurado para esta referência de bolsa. Ajuste o cadastro da referência antes de concluir a análise.');$before=(int)($sample['preservative_id']??0)?:null;$pdo->prepare("UPDATE samples SET preservative_id=:preservative WHERE id=:id AND status<>'completed'")->execute(['preservative'=>$preservative,'id'=>$sample['id']]);if($before!==$preservative)Auth::registerAudit('quality_sample.preservative.resolve','samples',(int)$sample['id'],['preservative_id'=>$before],['preservative_id'=>$preservative,'source'=>'bag_brand']);return $preservative;}
    private static function componentRequiresPreservative(int $componentId):bool
    {$q=Database::connection()->prepare("SELECT EXISTS(SELECT 1 FROM blood_component_preservative_shelf_lives WHERE blood_component_id=:c1 AND active=1) OR EXISTS(SELECT 1 FROM blood_component_test_specifications WHERE blood_component_id=:c2 AND active=1 AND condition_type='PRESERVATIVE')");$q->execute(['c1'=>$componentId,'c2'=>$componentId]);return(bool)$q->fetchColumn();}
    private static function eligible(int $id,bool $includeCompleted):?array{if(QcMonthlyClosureService::isSamplePeriodClosed($id))return null;$statuses=$includeCompleted?"'received','in_analysis','partial_results','completed'":"'received','in_analysis','partial_results'";$s=Database::connection()->prepare("SELECT * FROM samples WHERE id=:id AND purpose='quality_control' AND status IN ($statuses)");$s->execute(['id'=>$id]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
    private static function pendingLabel(int $sampleId,array $missing):string
    {$codes=array_column($missing,'code');if(in_array('BACTERIOLOGY',$codes,true))return 'Bacteriológico';if(in_array('FREE_HEMOGLOBIN',$codes,true)||in_array('HEMOLYSIS_DEGREE',$codes,true))return 'Grau de Hemólise';return implode(', ',array_column($missing,'name'));}
    private static function returnUrl(string $fallback):string
    {$url=(string)($_POST['return_to']??'');return str_starts_with($url,'/quality-control')&&!str_contains($url,"\r")&&!str_contains($url,"\n")?$url:$fallback;}
    private static function filters(string $defaultStatus=''):array{return ['origin'=>trim((string)($_GET['origin']??'')),'component'=>trim((string)($_GET['component']??'')),'received_date'=>trim((string)($_GET['received_date']??'')),'donation'=>trim((string)($_GET['donation']??'')),'lcqh'=>trim((string)($_GET['lcqh']??'')),'status'=>array_key_exists('status',$_GET)?trim((string)$_GET['status']):$defaultStatus];}
    private static function componentCode(int $id):string{$q=Database::connection()->prepare('SELECT code FROM blood_components WHERE id=:id');$q->execute(['id'=>$id]);return (string)$q->fetchColumn();}
    private static function persistPlateletSample(array $sample,array $values):void{$id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);if(($sample['lcqh_code']??null)!==($lcqh!==''?$lcqh:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']??null],['lcqh_code'=>$lcqh!==''?$lcqh:null]);PlateletResultService::save($id,$values);}
    private static function savePlateletRequest(array $sample,array $values):never{$pdo=Database::connection();try{$pdo->beginTransaction();self::persistPlateletSample($sample,$values);SpecificationEvaluator::evaluateSampleResults((int)$sample['id']);$pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível salvar os resultados.');}self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));}
    private static function persistFreshPlasmaSample(array $sample,array $values):void{$id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);if(($sample['lcqh_code']??null)!==($lcqh!==''?$lcqh:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']??null],['lcqh_code'=>$lcqh!==''?$lcqh:null]);FreshPlasmaResultService::save($id,$values);}
    private static function saveFreshPlasmaRequest(array $sample,array $values):never{$pdo=Database::connection();try{$pdo->beginTransaction();self::persistFreshPlasmaSample($sample,$values);SpecificationEvaluator::evaluateSampleResults((int)$sample['id']);$pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível salvar os resultados.');}self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));}
    private static function persistPlasmaSample(array $sample,array $values):void{$id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);if(($sample['lcqh_code']??null)!==($lcqh!==''?$lcqh:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']??null],['lcqh_code'=>$lcqh!==''?$lcqh:null]);$gross=trim((string)($values['gross_weight']??''));if($gross!=='')self::saveVolume($sample,$gross);}
    private static function savePlasmaRequest(array $sample,array $values):never{$pdo=Database::connection();try{$pdo->beginTransaction();self::persistPlasmaSample($sample,$values);SpecificationEvaluator::evaluateSampleResults((int)$sample['id']);$pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível salvar os resultados.');}self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));}
    private static function persistCryoprecipitateSample(array $sample,array $values):void{$id=(int)$sample['id'];$lcqh=array_key_exists('lcqh_code',$values)?trim((string)$values['lcqh_code']):(string)($sample['lcqh_code']??'');if(mb_strlen($lcqh)>80)throw new DomainException('Código LCQH deve ter no máximo 80 caracteres.');Database::connection()->prepare('UPDATE samples SET lcqh_code=:code WHERE id=:id')->execute(['code'=>$lcqh!==''?$lcqh:null,'id'=>$id]);if(($sample['lcqh_code']??null)!==($lcqh!==''?$lcqh:null))Auth::registerAudit('quality_sample.lcqh_code.update','samples',$id,['lcqh_code'=>$sample['lcqh_code']??null],['lcqh_code'=>$lcqh!==''?$lcqh:null]);CryoprecipitateResultService::save($sample,$values);}
    private static function storedGrossWeight(int $sampleId):string{$q=Database::connection()->prepare('SELECT gross_weight FROM sample_weight_results WHERE sample_id=:id');$q->execute(['id'=>$sampleId]);$gross=$q->fetchColumn();return $gross===false||$gross===null?'':(string)$gross;}
    private static function saveCryoprecipitateRequest(array $sample,array $values):never{$pdo=Database::connection();try{$pdo->beginTransaction();self::persistCryoprecipitateSample($sample,$values);SpecificationEvaluator::evaluateSampleResults((int)$sample['id']);$pdo->commit();Flash::set('success','Alterações da amostra salvas com sucesso.');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e instanceof DomainException?$e->getMessage():'Não foi possível salvar os resultados.');}self::redirect(self::returnUrl('/quality-control?component='.(int)$sample['blood_component_id']));}
    private static function decimal(string $value):float{$normalized=str_replace(',','.',trim($value));if(!preg_match('/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/',$normalized))throw new DomainException('O resultado deve ser numérico.');$number=(float)$normalized;if(!is_finite($number))throw new DomainException('Resultado numérico inválido.');return $number;}
    private static function id(mixed $v):int{$id=filter_var($v,FILTER_VALIDATE_INT);return $id&&$id>0?(int)$id:0;}
    private static function view(string $name,array $vars):void{extract($vars);$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__).'/Views/quality_control/'.$name.'.php';}
    private static function redirect(string $url):never{if($url==='/quality-control')$url=self::returnUrl($url);header('Location: '.$url);exit;}
}
