<?php
declare(strict_types=1);
namespace BloodHub\Controllers;

use BloodHub\Core\{AdminGuard,Auth,Csrf,Database,Flash,Permission,SampleAccess,SamplePurpose,ShipmentAccess,StatusLabel,ValidationAccess};
use PDO;
use PDOException;
use BloodHub\Services\{ShelfLifeResolver,SampleUniquenessService};

final class ShipmentController
{
    public static function index():void
    {
        AdminGuard::enforce('shipments.view');[$scope,$params]=ShipmentAccess::scopeSql('sh');
        $stmt=Database::connection()->prepare("SELECT sh.*,ou.name origin_name,du.name destination_name,u.name responsible_name,COUNT(s.id) sample_count FROM sample_shipments sh JOIN units ou ON ou.id=sh.origin_unit_id JOIN units du ON du.id=sh.destination_unit_id JOIN users u ON u.id=sh.responsible_user_id LEFT JOIN samples s ON s.sample_shipment_id=sh.id WHERE {$scope} GROUP BY sh.id ORDER BY sh.created_at DESC");$stmt->execute($params);
        self::view('index',['shipments'=>$stmt->fetchAll(),'samples'=>self::legacySamples(),'statuses'=>StatusLabel::all(),'pageTitle'=>'Amostras']);
    }
    public static function create():void {AdminGuard::enforce('shipments.create');self::form(null,[],self::postedRows(),self::postedBoxes());}
    public static function store():void {AdminGuard::enforce('shipments.create');self::persist(null,false);}
    public static function edit():void {AdminGuard::enforce('shipments.edit');$sh=self::requested();if(!$sh){self::notFound();return;}if(!ShipmentAccess::canMutate($sh)){http_response_code(409);Flash::set('error','A remessa não pode mais ser editada.');self::redirect('/samples/shipments/view?id='.$sh['id']);}self::form($sh,[],self::samples((int)$sh['id']),self::boxes((int)$sh['id']));}
    public static function update():void {AdminGuard::enforce('shipments.edit');$sh=self::requested(true);if(!$sh){self::notFound();return;}self::persist($sh,false);}
    public static function send():void
    {
        AdminGuard::enforce('shipments.send');
        if(empty($_POST['id'])){AdminGuard::enforce('shipments.create');self::persist(null,true);return;}
        $sh=self::requested(true);if(!$sh){self::notFound();return;}self::persist($sh,true);
    }
    public static function show():void {AdminGuard::enforce('shipments.view');$sh=self::requested();if(!$sh){self::notFound();return;}$samples=self::samples((int)$sh['id']);self::view('show',['shipment'=>$sh,'samples'=>$samples,'boxes'=>self::boxes((int)$sh['id']),'receptionBoxes'=>self::receptionBoxes((int)$sh['id']),'receptionHistory'=>self::receptionHistory($samples),'mutable'=>ShipmentAccess::canMutate($sh),'pageTitle'=>'Remessa '.$sh['shipment_code']]);}

    public static function checkDuplicate():void
    {
        AdminGuard::enforce('shipments.view');header('Content-Type: application/json; charset=UTF-8');
        $donation=trim((string)($_GET['donation_number']??''));$component=(int)($_GET['blood_component_id']??0);$exclude=(int)($_GET['sample_id']??0);
        if($donation===''||!$component){echo json_encode(['available'=>true]);return;}
        $existing=SampleUniquenessService::find($donation,$component,$exclude);
        echo json_encode(['available'=>!$existing,'message'=>$existing?SampleUniquenessService::message($existing):null,'existing'=>$existing?['purpose'=>$existing['purpose'],'origin'=>$existing['origin_name'],'date'=>$existing['registered_at']]:null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
    }

    public static function cancel():void
    {
        AdminGuard::enforce('shipments.cancel');self::csrf('/samples');$sh=self::requested(true);if(!$sh){self::notFound();return;}$reason=trim((string)($_POST['reason']??''));
        if($reason===''||mb_strlen($reason)>500){Flash::set('error',$sh['status']==='draft'?'Informe o motivo da exclusão com até 500 caracteres.':'Informe o motivo do cancelamento com até 500 caracteres.');self::redirect('/samples/shipments/view?id='.$sh['id']);}
        $pdo=Database::connection();$pdo->beginTransaction();try{$locked=ShipmentAccess::shipment((int)$sh['id'],true);if(!$locked||!ShipmentAccess::canMutate($locked))throw new \RuntimeException('A remessa não está mais disponível para cancelamento.');
            $pdo->prepare("UPDATE sample_shipments SET status='cancelled',cancelled_at=NOW(),cancelled_by=:u,cancellation_reason=:r WHERE id=:id")->execute(['u'=>Auth::user()['id'],'r'=>$reason?:null,'id'=>$sh['id']]);
            $pdo->prepare("UPDATE samples SET status='cancelled' WHERE sample_shipment_id=:id")->execute(['id'=>$sh['id']]);Auth::registerAudit('shipment.cancel','sample_shipments',(int)$sh['id'],['status'=>$sh['status']],['status'=>'cancelled','reason'=>$reason]);$pdo->commit();Flash::set('success',$sh['status']==='draft'?'Rascunho excluído com sucesso.':'Remessa cancelada com sucesso.');
        }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();Flash::set('error',$e->getMessage());self::redirect('/samples/shipments/view?id='.$sh['id']);}self::redirect('/samples/shipments/view?id='.$sh['id']);
    }

    public static function report():void
    {
        AdminGuard::enforce('shipments.print');$sh=self::requested();if(!$sh){self::notFound();return;}self::view('report',['shipment'=>$sh,'samples'=>self::samples((int)$sh['id']),'boxes'=>array_column(self::boxes((int)$sh['id']),'code'),'pageTitle'=>'Relatório '.$sh['shipment_code']]);
    }

    private static function persist(?array $current,bool $sending):void
    {
        self::csrf($current?'/samples/shipments/edit?id='.$current['id']:'/samples/shipments/create');$rows=self::postedRows();$boxes=self::postedBoxes();$errors=[];
        $origin=(int)($_POST['origin_unit_id']??0);$destination=$current?(int)$current['destination_unit_id']:self::lcqhDestination();$purpose=(string)($_POST['purpose']??'quality_control');$patientName=trim((string)($_POST['patient_name']??''));$checked=trim((string)($_POST['checked_by']??''));$notes=trim((string)($_POST['notes']??''));$validationId=(int)($_POST['validation_id']??0);$phaseId=(int)($_POST['validation_phase_id']??0);
        if($current&&!ShipmentAccess::canMutate($current))$errors[]='A remessa não pode mais ser alterada.';
        if(!$origin||!self::canUseProcessingUnit($origin))$errors[]='Selecione uma unidade de processamento autorizada.';
        if($current&&in_array($current['status'],['awaiting_receipt','partially_received'],true)&&$origin!==(int)$current['origin_unit_id'])$errors[]='A origem não pode ser alterada após o primeiro envio.';
        if(!$destination||!self::active('units',$destination))$errors[]='Nenhuma unidade LCQH ativa está configurada para receber a remessa.';if($origin===$destination)$errors[]='Origem e destino devem ser diferentes.';
        if(!SamplePurpose::isValid($purpose))$errors[]='Selecione uma finalidade válida.';
        if($purpose==='transfusion_reaction'&&($patientName===''||mb_strlen($patientName)>255))$errors[]='Informe o nome do paciente (até 255 caracteres).';
        if($purpose!=='transfusion_reaction')$patientName='';
        if($checked===''||mb_strlen($checked)>180)$errors[]='Informe quem conferiu a remessa.';
        if($purpose==='validation'){
            if(!$validationId||!$phaseId)$errors[]='Selecione a Validação / PV e a etapa.';
            else{$eligible=Database::connection()->prepare("SELECT v.unit_id FROM validations v JOIN validation_phases vp ON vp.validation_id=v.id AND vp.id=:phase AND vp.status='active' WHERE v.id=:validation AND v.unit_id=:origin AND v.unit_id IS NOT NULL AND v.status IN('planned','in_progress') LIMIT 1");$eligible->execute(['phase'=>$phaseId,'validation'=>$validationId,'origin'=>$origin]);$validationUnit=$eligible->fetchColumn();if($validationUnit===false)$errors[]='O PV não existe, não aceita amostras, não pertence à unidade selecionada ou a etapa é inválida.';elseif(!ValidationAccess::canUseUnit((int)$validationUnit))$errors[]='Você não possui acesso à unidade responsável por este PV.';else{$plan=Database::connection()->prepare("SELECT COUNT(*) FROM validation_tests WHERE validation_id=:v AND phase_id=:p AND status='active'");$plan->execute(['v'=>$validationId,'p'=>$phaseId]);if(!(int)$plan->fetchColumn())$errors[]='Esta validação ainda não possui plano de testes configurado.';else foreach($rows as$i=>$r){$ok=Database::connection()->prepare("SELECT 1 FROM validation_blood_components vbc JOIN validation_tests vt ON vt.validation_id=vbc.validation_id AND vt.phase_id=vbc.phase_id AND vt.blood_component_id=vbc.blood_component_id AND vt.status='active' WHERE vbc.validation_id=:v AND vbc.phase_id=:p AND vbc.blood_component_id=:c AND vbc.status='active' LIMIT 1");$ok->execute(['v'=>$validationId,'p'=>$phaseId,'c'=>$r['blood_component_id']]);if(!$ok->fetchColumn())$errors[]='Hemocomponente não configurado no PV na linha '.($i+1).'.';}}}
        }else{$validationId=0;$phaseId=0;}
        foreach($rows as $i=>$r){if(!self::active('blood_components',(int)$r['blood_component_id']))$errors[]='Hemocomponente inválido na linha '.($i+1).'.';if(!self::validDate($r['production_date']))$errors[]='Data de produção inválida na linha '.($i+1).'.';if(!self::usableBagBrand((int)$r['bag_brand_id'],(int)$r['id'],(int)($current['id']??0)))$errors[]='Marca de bolsa inválida na linha '.($i+1).'.';if($r['donation_number']===''||mb_strlen($r['donation_number'])>120)$errors[]='Nº da Doação obrigatório na linha '.($i+1).'.';}
        $errors=array_merge($errors,SampleUniquenessService::validateRows($rows));
        if($sending||($current&&in_array($current['status'],['awaiting_receipt','partially_received'],true))){foreach($rows as $i=>$r){try{ShelfLifeResolver::forBagBrand((int)$r['blood_component_id'],(int)$r['bag_brand_id'],$r['production_date']);}catch(\DomainException $e){$errors[]='Amostra '.($i+1).': '.$e->getMessage();}}}
        if($sending&&!$rows)$errors[]='Adicione pelo menos uma amostra antes de enviar.';
        $codes=array_values(array_filter(array_column($boxes,'code'),static fn($v)=>$v!==null&&$v!==''));if(count($codes)!==count(array_unique($codes)))$errors[]='Não repita a mesma caixa na remessa.';foreach($boxes as $b)if($b['code']!==null&&!preg_match('/^[A-Z]{3}[0-9]{2}$/',$b['code']))$errors[]="Código de caixa inválido: {$b['code']}.";
        $groups=self::transportGroups($rows);$errors=array_merge($errors,self::validateTransportBoxes($groups,$boxes,$sending));
        if($errors){self::form(array_merge($current??[],['origin_unit_id'=>$origin,'destination_unit_id'=>$destination,'purpose'=>$purpose,'patient_name'=>$patientName,'validation_id'=>$validationId,'validation_phase_id'=>$phaseId,'checked_by'=>$checked,'notes'=>$notes]),$errors,$rows,$boxes);return;}
        $pdo=Database::connection();$pdo->beginTransaction();try{
            SampleUniquenessService::assertRowsAvailable($rows,true);
            if($current){$locked=ShipmentAccess::shipment((int)$current['id'],true);if(!$locked||!ShipmentAccess::canMutate($locked))throw new \RuntimeException('A remessa foi recebida ou encerrada durante a edição. Nenhuma alteração foi salva.');$id=(int)$current['id'];$oldStatus=$locked['status'];
                $pdo->prepare('UPDATE sample_shipments SET purpose=:p,origin_unit_id=:o,client_id=(SELECT client_id FROM units WHERE id=:o2),destination_unit_id=:d,checked_by=:c,notes=:n WHERE id=:id')->execute(['p'=>$purpose,'o'=>$origin,'o2'=>$origin,'d'=>$destination,'c'=>$checked,'n'=>$notes?:null,'id'=>$id]);
            }else{$code=self::code();$pdo->prepare("INSERT INTO sample_shipments(shipment_code,purpose,origin_unit_id,client_id,destination_unit_id,responsible_user_id,checked_by,notes,status,created_by) VALUES(:code,:p,:o,(SELECT client_id FROM units WHERE id=:o2),:d,:u,:c,:n,'draft',:u2)")->execute(['code'=>$code,'p'=>$purpose,'o'=>$origin,'o2'=>$origin,'d'=>$destination,'u'=>Auth::user()['id'],'c'=>$checked,'n'=>$notes?:null,'u2'=>Auth::user()['id']]);$id=(int)$pdo->lastInsertId();$oldStatus='draft';Auth::registerAudit('shipment.create','sample_shipments',$id,null,['shipment_code'=>$code,'status'=>'draft']);}
            $pdo->prepare('UPDATE sample_shipments SET validation_id=:validation,validation_phase_id=:phase WHERE id=:id')->execute(['validation'=>$validationId?:null,'phase'=>$phaseId?:null,'id'=>$id]);
            self::syncSamples($pdo,$id,$rows,$oldStatus,$purpose,$patientName);$pdo->prepare('UPDATE samples s JOIN sample_shipments sh ON sh.id=s.sample_shipment_id SET s.validation_id=sh.validation_id,s.validation_phase_id=sh.validation_phase_id WHERE s.sample_shipment_id=:id')->execute(['id'=>$id]);if($purpose==='validation')foreach($pdo->query('SELECT id,validation_id FROM samples WHERE sample_shipment_id='.(int)$id)->fetchAll() as$linked)Auth::registerAudit('VALIDATION_SAMPLE_LINKED','samples',(int)$linked['id'],null,['validation_id'=>(int)$linked['validation_id'],'shipment_id'=>$id]);if($purpose==='transfusion_reaction')foreach($pdo->query('SELECT id FROM samples WHERE sample_shipment_id='.(int)$id)->fetchAll() as$linked)Auth::registerAudit('TRANSFUSION_REACTION_SAMPLE_REGISTERED','samples',(int)$linked['id'],null,['shipment_id'=>$id]);if($sending||in_array($oldStatus,['awaiting_receipt','partially_received'],true))ShelfLifeResolver::snapshotShipment($id);if($oldStatus!=='partially_received')self::syncBoxes($pdo,$id,$boxes,$oldStatus);
            if($sending){if($oldStatus!=='draft')throw new \RuntimeException('A remessa já foi enviada. Use Salvar alterações.');$pdo->prepare("UPDATE sample_shipments SET status='awaiting_receipt',sent_at=NOW(),sent_by=:u WHERE id=:id")->execute(['u'=>Auth::user()['id'],'id'=>$id]);$pdo->prepare("UPDATE samples SET status='awaiting_receipt',sent_at=NOW(),sent_by=:u WHERE sample_shipment_id=:id")->execute(['u'=>Auth::user()['id'],'id'=>$id]);Auth::registerAudit('shipment.send','sample_shipments',$id,['status'=>'draft'],['status'=>'awaiting_receipt']);}
            else Auth::registerAudit($oldStatus==='awaiting_receipt'?'shipment.update_after_send':'shipment.update','sample_shipments',$id,null,['samples'=>count($rows),'boxes'=>count($boxes)]);
            $pdo->commit();Flash::set('success',$sending?'Remessa finalizada e enviada ao LCQH.':'Remessa salva com sucesso.');self::redirect('/samples/shipments/view?id='.$id);
        }catch(\Throwable $e){
            if($pdo->inTransaction())$pdo->rollBack();
            error_log(sprintf(
                '[BloodHub][shipment.persist] action=%s shipment_id=%s samples=%d boxes=%d exception=%s message=%s at=%s:%d',
                $sending?'send':'save',
                $current['id']??'new',
                count($rows),
                count($boxes),
                $e::class,
                $e->getMessage(),
                $e->getFile(),
                $e->getLine()
            ));
            $message=$e instanceof PDOException
                ?'Não foi possível salvar a remessa devido a um erro de banco de dados. Consulte o log da aplicação.'
                :$e->getMessage();
            self::form($current,array_merge($errors,[$message]),$rows,$boxes);
        }
    }

    private static function syncSamples(PDO $pdo,int $shipmentId,array $rows,string $oldStatus,string $purpose,string $patientName=''):void
    {
        $existing=$pdo->prepare('SELECT id,status FROM samples WHERE sample_shipment_id=:id FOR UPDATE');$existing->execute(['id'=>$shipmentId]);$existingRows=$existing->fetchAll(PDO::FETCH_KEY_PAIR);$old=array_map('intval',array_keys($existingRows));$kept=[];$status=in_array($oldStatus,['awaiting_receipt','partially_received'],true)?'awaiting_receipt':'registered';
        foreach($rows as $r){$sid=(int)$r['id'];$payload=['bc'=>$r['blood_component_id'],'pd'=>$r['production_date'],'pd2'=>$r['production_date'],'bb'=>$r['bag_brand_id'],'dn'=>$r['donation_number'],'id'=>$sid,'sh'=>$shipmentId];
            if($sid&&in_array($sid,$old,true)){$payload['purpose']=$purpose;$payload['patient']=$patientName?:null;$pdo->prepare("UPDATE samples SET purpose=:purpose,patient_name=:patient,blood_component_id=:bc,production_date=:pd,collection_date=:pd2,bag_brand_id=:bb,donation_number=:dn WHERE id=:id AND sample_shipment_id=:sh AND status IN ('registered','awaiting_receipt')")->execute($payload);$kept[]=$sid;}
            else{$code=self::uniqueSampleCode($pdo,$r['donation_number']);$pdo->prepare("INSERT INTO samples(sample_shipment_id,sample_code,purpose,patient_name,origin_unit_id,client_id,blood_component_id,donation_number,collection_date,production_date,bag_brand_id,status,registered_by,registered_at,sent_at,sent_by) SELECT :sh,:code,:purpose,:patient,origin_unit_id,client_id,:bc,:dn,:collection_date,:production_date,:bb,:st,:u,NOW(),IF(:st2='awaiting_receipt',NOW(),NULL),IF(:st3='awaiting_receipt',:u2,NULL) FROM sample_shipments WHERE id=:sh2")->execute(['sh'=>$shipmentId,'code'=>$code,'purpose'=>$purpose,'patient'=>$patientName?:null,'bc'=>$r['blood_component_id'],'dn'=>$r['donation_number'],'collection_date'=>$r['production_date'],'production_date'=>$r['production_date'],'bb'=>$r['bag_brand_id'],'st'=>$status,'u'=>Auth::user()['id'],'st2'=>$status,'st3'=>$status,'u2'=>Auth::user()['id'],'sh2'=>$shipmentId]);$new=(int)$pdo->lastInsertId();$kept[]=$new;if($oldStatus==='awaiting_receipt')Auth::registerAudit('shipment.sample_added_after_send','samples',$new,null,['shipment_id'=>$shipmentId]);}
        }
        foreach(array_diff($old,$kept) as $removed){if(!in_array($existingRows[$removed]??'', ['registered','awaiting_receipt'],true))continue;if(in_array($oldStatus,['awaiting_receipt','partially_received'],true))Auth::registerAudit('shipment.sample_removed_after_send','samples',$removed,['shipment_id'=>$shipmentId],['status'=>'cancelled']);$pdo->prepare("UPDATE samples SET status='cancelled',sample_shipment_id=NULL WHERE id=:id AND sample_shipment_id=:sh AND status IN ('registered','awaiting_receipt')")->execute(['id'=>$removed,'sh'=>$shipmentId]);}
    }
    private static function syncBoxes(PDO $pdo,int $id,array $boxes,string $status):void {$old=$pdo->prepare('SELECT box_code FROM sample_shipment_thermal_boxes WHERE shipment_id=:id');$old->execute(['id'=>$id]);$before=$old->fetchAll(PDO::FETCH_COLUMN);$pdo->prepare('DELETE FROM sample_shipment_thermal_boxes WHERE shipment_id=:id')->execute(['id'=>$id]);$ins=$pdo->prepare('INSERT INTO sample_shipment_thermal_boxes(shipment_id,box_code,transport_temp_min_snapshot,transport_temp_max_snapshot) VALUES(:id,:code,:min,:max)');$link=$pdo->prepare('INSERT INTO sample_shipment_thermal_box_components(thermal_box_id,blood_component_id) VALUES(:box,:component)');foreach($boxes as $b){$ins->execute(['id'=>$id,'code'=>$b['code'],'min'=>$b['transport_min'],'max'=>$b['transport_max']]);$boxId=(int)$pdo->lastInsertId();foreach($b['component_ids'] as $componentId)$link->execute(['box'=>$boxId,'component'=>$componentId]);}if($status==='awaiting_receipt'&&$before!==array_column($boxes,'code'))Auth::registerAudit('shipment.boxes_changed_after_send','sample_shipments',$id,['boxes'=>$before],['boxes'=>array_column($boxes,'code')]);}
    private static function postedRows():array {$out=[];foreach((array)($_POST['samples']??[]) as $r){if(!is_array($r))continue;$dn=trim((string)($r['donation_number']??''));if($dn===''&&empty($r['blood_component_id'])&&empty($r['production_date'])&&empty($r['bag_brand_id']))continue;$out[]=['id'=>(int)($r['id']??0),'blood_component_id'=>(int)($r['blood_component_id']??0),'production_date'=>trim((string)($r['production_date']??'')),'bag_brand_id'=>(int)($r['bag_brand_id']??0),'donation_number'=>$dn];}return $out;}
    private static function postedBoxes():array {$out=[];foreach((array)($_POST['boxes']??[]) as $row){if(!is_array($row))continue;$code=strtoupper(trim((string)($row['code']??'')));$ids=array_values(array_unique(array_filter(array_map('intval',(array)($row['component_ids']??[])))));if(!$ids)continue;$out[]=['code'=>$code===''?null:$code,'component_ids'=>$ids,'transport_min'=>isset($row['transport_min'])&&$row['transport_min']!==''?(string)$row['transport_min']:null,'transport_max'=>isset($row['transport_max'])&&$row['transport_max']!==''?(string)$row['transport_max']:null];}return$out;}
    private static function samples(int $id):array {$s=Database::connection()->prepare("SELECT s.*,bc.code component_code,bc.name component_name,CONCAT(bb.name,IF(bb.reference_number IS NULL OR bb.reference_number='','',CONCAT(' | Ref. ',bb.reference_number))) bag_brand_name,p.code preservative_code,p.name preservative_name,ru.name received_by_name,xu.name rejected_by_name FROM samples s LEFT JOIN blood_components bc ON bc.id=s.blood_component_id LEFT JOIN bag_brands bb ON bb.id=s.bag_brand_id LEFT JOIN preservatives p ON p.id=s.preservative_id_snapshot LEFT JOIN users ru ON ru.id=s.received_by LEFT JOIN users xu ON xu.id=s.rejected_by WHERE s.sample_shipment_id=:id ORDER BY s.id");$s->execute(['id'=>$id]);return $s->fetchAll();}
    private static function boxes(int $id):array {$s=Database::connection()->prepare("SELECT b.box_code code,b.transport_temp_min_snapshot transport_min,b.transport_temp_max_snapshot transport_max,GROUP_CONCAT(x.blood_component_id ORDER BY x.blood_component_id) component_ids FROM sample_shipment_thermal_boxes b LEFT JOIN sample_shipment_thermal_box_components x ON x.thermal_box_id=b.id WHERE b.shipment_id=:id GROUP BY b.id ORDER BY b.id");$s->execute(['id'=>$id]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$row)$row['component_ids']=$row['component_ids']===''||$row['component_ids']===null?[]:array_map('intval',explode(',',$row['component_ids']));return$rows;}
    private static function receptionBoxes(int $id):array {$s=Database::connection()->prepare("SELECT b.box_code,b.transport_temp_min_snapshot,b.transport_temp_max_snapshot,b.sent_temperature,b.received_temperature,b.received_at,u.name received_by_name,GROUP_CONCAT(CONCAT(bc.code,' - ',bc.name) ORDER BY bc.code SEPARATOR '||') component_labels FROM sample_shipment_thermal_boxes b LEFT JOIN users u ON u.id=b.received_by LEFT JOIN sample_shipment_thermal_box_components x ON x.thermal_box_id=b.id LEFT JOIN blood_components bc ON bc.id=x.blood_component_id WHERE b.shipment_id=:id GROUP BY b.id ORDER BY b.id");$s->execute(['id'=>$id]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private static function form(?array $shipment,array $errors,array $samples,array $boxes):void {$shipment=$shipment??[];if(!isset($shipment['purpose']))$shipment['purpose']=$samples[0]['purpose']??'quality_control';self::view('form',compact('shipment','errors','samples','boxes')+['units'=>SampleAccess::units('processing'),'purposes'=>SamplePurpose::SHIPMENT_OPTIONS,'components'=>Database::connection()->query("SELECT id,code,name,density,transport_temperature_min,transport_temperature_max FROM blood_components WHERE status='active' ORDER BY code")->fetchAll(),'brands'=>self::bagBrands($samples),'pageTitle'=>!empty($shipment['id'])?'Editar Remessa':'Nova Remessa','pageSubtitle'=>'Organize os dados do envio, as amostras e as caixas térmicas em uma única remessa.']);}
    private static function transportGroups(array $rows):array {$ids=array_values(array_unique(array_filter(array_map('intval',array_column($rows,'blood_component_id')))));if(!$ids)return[];$marks=implode(',',array_fill(0,count($ids),'?'));$s=Database::connection()->prepare("SELECT id,code,name,transport_temperature_min,transport_temperature_max FROM blood_components WHERE id IN ($marks)");$s->execute($ids);$groups=[];foreach($s->fetchAll(PDO::FETCH_ASSOC) as $component){$min=$component['transport_temperature_min'];$max=$component['transport_temperature_max'];$key=$min===null||$max===null?'missing:'.$component['id']:number_format((float)$min,2,'.','').'|'.number_format((float)$max,2,'.','');if(!isset($groups[$key]))$groups[$key]=['min'=>$min,'max'=>$max,'components'=>[]];$groups[$key]['components'][(int)$component['id']]=$component;}return$groups;}
    private static function validateTransportBoxes(array $groups,array &$boxes,bool $sending):array {$errors=[];$componentGroup=[];foreach($groups as $key=>$group)foreach($group['components'] as $id=>$component)$componentGroup[$id]=$key;foreach($boxes as &$box){$label=$box['code']?:'sem identificação';$boxGroups=[];foreach($box['component_ids'] as $id){if(isset($componentGroup[$id]))$boxGroups[$componentGroup[$id]]=true;else$errors[]="A caixa {$label} contém um hemocomponente que não pertence à remessa.";}if(count($boxGroups)>1)$errors[]="A caixa {$label} não pode misturar hemocomponentes de faixas de temperatura distintas.";$key=array_key_first($boxGroups);if($key===null||str_starts_with($key,'missing:'))$errors[]="Associe a caixa {$label} a uma faixa de temperatura válida.";else{$group=$groups[$key];$box['transport_min']=$group['min'];$box['transport_max']=$group['max'];}}unset($box);return array_values(array_unique($errors));}
    private static function formatTemperature(mixed $value):string {return number_format((float)$value,1,',','.').' °C';}
    private static function receptionHistory(array $samples):array {$history=[];foreach($samples as $sample){$action=$sample['status']==='received'?'received':($sample['status']==='rejected'?'rejected':null);if(!$action)continue;$at=$sample[$action.'_at']??null;$user=$sample[$action.'_by_name']??null;if(!$at)continue;$key=$at.'|'.$action.'|'.$user;if(!isset($history[$key]))$history[$key]=['at'=>$at,'user'=>$user,'action'=>$action,'count'=>0];$history[$key]['count']++;}usort($history,static fn($a,$b)=>strcmp($a['at'],$b['at']));return array_values($history);}
    private static function bagBrands(array $samples):array {$ids=array_values(array_unique(array_filter(array_map('intval',array_column($samples,'bag_brand_id')))));$current="b.active=1 AND NOT EXISTS (SELECT 1 FROM bag_brands newer WHERE newer.active=1 AND LOWER(TRIM(newer.name))=LOWER(TRIM(b.name)) AND (newer.created_at>b.created_at OR (newer.created_at=b.created_at AND newer.id>b.id)))";$where="({$current})";if($ids)$where.=' OR b.id IN ('.implode(',',$ids).')';return Database::connection()->query("SELECT b.id,b.name,b.reference_number FROM bag_brands b WHERE {$where} ORDER BY b.name,b.reference_number")->fetchAll();}
    private static function usableBagBrand(int $brandId,int $sampleId,int $shipmentId):bool {if(self::active('bag_brands',$brandId,'active'))return true;if(!$sampleId||!$shipmentId)return false;$s=Database::connection()->prepare('SELECT 1 FROM samples WHERE id=:sample AND sample_shipment_id=:shipment AND bag_brand_id=:brand');$s->execute(['sample'=>$sampleId,'shipment'=>$shipmentId,'brand'=>$brandId]);return(bool)$s->fetchColumn();}
    private static function canUseProcessingUnit(int $id):bool {foreach(SampleAccess::units('processing') as $unit)if((int)$unit['id']===$id)return true;return false;}
    private static function lcqhDestination():int {$s=Database::connection()->query("SELECT id FROM units WHERE status='active' AND unit_type='lcqh' ORDER BY id LIMIT 1");return(int)$s->fetchColumn();}
    private static function active(string $table,int $id,string $column='status'):bool {$allowed=['units','blood_components','bag_brands'];if(!in_array($table,$allowed,true))return false;$value=$column==='active'?1:'active';$s=Database::connection()->prepare("SELECT 1 FROM {$table} WHERE id=:id AND {$column}=:v");$s->execute(['id'=>$id,'v'=>$value]);return(bool)$s->fetchColumn();}
    private static function validDate(string $v):bool {$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v;}
    private static function code():string {return 'REM-'.date('Ymd-His').'-'.strtoupper(bin2hex(random_bytes(2)));}
    private static function uniqueSampleCode(PDO $pdo,string $donation):string {$code=$donation;$s=$pdo->prepare('SELECT 1 FROM samples WHERE sample_code=:c');$s->execute(['c'=>$code]);return $s->fetchColumn()?$donation.'-'.strtoupper(bin2hex(random_bytes(3))):$code;}
    private static function legacySamples():array {[$scope,$params]=\BloodHub\Core\SampleAccess::scopeSql('s');$s=Database::connection()->prepare("SELECT s.*,u.name unit_name,bc.name component_name FROM samples s LEFT JOIN units u ON u.id=s.origin_unit_id LEFT JOIN blood_components bc ON bc.id=s.blood_component_id WHERE s.sample_shipment_id IS NULL AND {$scope} ORDER BY s.registered_at DESC");$s->execute($params);return $s->fetchAll();}
    private static function requested(bool $post=false):?array {$id=filter_var($post?($_POST['id']??null):($_GET['id']??null),FILTER_VALIDATE_INT);return$id?ShipmentAccess::shipment((int)$id):null;}
    private static function csrf(string $back):void {if(!Csrf::validate($_POST['_csrf']??null)){Flash::set('error','Sessão expirada. Tente novamente.');self::redirect($back);}}
    private static function view(string $name,array $vars):void {extract($vars);$flash=Flash::pull();$csrf=Csrf::token();$userAuth=Auth::user();require dirname(__DIR__).'/Views/shipments/'.$name.'.php';}
    private static function redirect(string $url):never {header('Location: '.$url);exit;}
    private static function notFound():void {http_response_code(404);echo'Remessa não encontrada ou fora do seu escopo.';}
}
