CREATE TABLE IF NOT EXISTS blood_component_test_specifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 blood_component_id BIGINT UNSIGNED NOT NULL,
 test_id BIGINT UNSIGNED NOT NULL,
 rule_type ENUM('GT','GTE','LT','LTE','BETWEEN','EQUAL_NUMERIC','EQUAL_TEXT','BOOLEAN') NOT NULL,
 min_value DECIMAL(30,10) NULL,
 max_value DECIMAL(30,10) NULL,
 expected_text VARCHAR(255) NULL,
 unit VARCHAR(80) NULL,
 preservative_id BIGINT UNSIGNED NULL,
 condition_type ENUM('PRESERVATIVE','PROCESS_METHOD','STORAGE_DAY','LEUKOREDUCED','PATHOGEN_REDUCTION','PRE_STORAGE_LEUKOREDUCTION','POOL_TYPE') NULL,
 condition_value VARCHAR(255) NULL,
 effective_from DATE NULL,
 effective_to DATE NULL,
 source_name VARCHAR(255) NULL,
 source_reference VARCHAR(500) NULL,
 notes TEXT NULL,
 sampling_requirement_notes TEXT NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_by BIGINT UNSIGNED NULL,
 updated_by BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_qspec_component FOREIGN KEY (blood_component_id) REFERENCES blood_components(id) ON DELETE CASCADE,
 CONSTRAINT fk_qspec_test FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
 CONSTRAINT fk_qspec_preservative FOREIGN KEY (preservative_id) REFERENCES preservatives(id) ON DELETE RESTRICT,
 CONSTRAINT fk_qspec_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
 CONSTRAINT fk_qspec_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX idx_qspec_lookup (blood_component_id,test_id,active,effective_from,effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS test_result_spec_evaluations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 test_result_id BIGINT UNSIGNED NOT NULL,
 specification_id BIGINT UNSIGNED NULL,
 rule_type VARCHAR(30) NULL,
 expected_min DECIMAL(30,10) NULL,
 expected_max DECIMAL(30,10) NULL,
 expected_text VARCHAR(255) NULL,
 unit VARCHAR(80) NULL,
 actual_value VARCHAR(255) NULL,
 conformity_status ENUM('CONFORMING','NONCONFORMING','NO_SPECIFICATION','NOT_EVALUATED') NOT NULL,
 evaluated_at DATETIME NOT NULL,
 specification_snapshot_text TEXT NULL,
 acknowledged_by BIGINT UNSIGNED NULL,
 acknowledged_at DATETIME NULL,
 CONSTRAINT fk_qeval_result FOREIGN KEY (test_result_id) REFERENCES test_results(id) ON DELETE CASCADE,
 CONSTRAINT fk_qeval_spec FOREIGN KEY (specification_id) REFERENCES blood_component_test_specifications(id) ON DELETE SET NULL,
 CONSTRAINT fk_qeval_ack FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL,
 UNIQUE KEY uk_qeval_result (test_result_id),
 INDEX idx_qeval_status (conformity_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
