<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$editing=!empty($brand['id']);$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<section class="content-card form-card"><div class="section-heading"><div><h2><?= $editing?'Editar marca de bolsa':'Cadastrar marca de bolsa' ?></h2><p><strong>Marca + Preservante</strong> identificam o cadastro operacional. A referência é opcional e apenas informativa.</p></div><a class="button button-secondary" href="/admin/bag-brands">Voltar</a></div>
<?php if($errors): ?><div class="alert alert-error"><ul><?php foreach($errors as $error): ?><li><?= $h($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="admin-form" method="post" action="<?= $editing?'/admin/bag-brands/edit':'/admin/bag-brands/create' ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><?php if($editing): ?><input type="hidden" name="id" value="<?= (int)$brand['id'] ?>"><?php endif; ?>
<div class="form-grid"><label><span>Marca *</span><input name="name" required maxlength="180" value="<?= $h($brand['name']??'') ?>" placeholder="Ex.: Fresenius"></label><label><span>Preservante *</span><select name="preservative_id" required><option value="">Selecione</option><?php foreach($preservatives as $p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)($brand['preservative_id']??0)===(int)$p['id']?'selected':'' ?>><?= $h(($p['code']?:$p['name']).($p['code']&&$p['name']!==$p['code']?' - '.$p['name']:'')) ?><?= !$p['active']?' · Inativo':'' ?></option><?php endforeach; ?></select></label><label><span>Referência <small>(opcional)</small></span><input name="reference_number" maxlength="120" value="<?= $h($brand['reference_number']??'') ?>" placeholder="Ex.: REF001"><small class="cell-subtitle">Informação administrativa; não altera a seleção operacional.</small></label><?php if($editing): ?><label><span>Status operacional</span><span class="status status-<?= $brand['active']?'active':'inactive' ?>"><?= $brand['active']?'Ativa':'Inativa' ?></span></label><?php endif; ?></div><?php if(!$editing): ?><p class="cell-subtitle">O novo cadastro será criado inativo. Use “Ativar” na listagem para torná-lo disponível.</p><?php endif; ?><div class="form-actions"><button class="button">Salvar cadastro</button></div></form></section>

<?php if($editing): ?>
<section class="content-card tare-section"><div class="section-heading"><div><h2>Perfis técnicos de tara</h2><p>Os vínculos com hemocomponentes existem somente para resolver a tara e permanecem independentes da referência informativa.</p></div><button class="button" type="button" data-open-tare>+ Adicionar tara</button></div>
<?php $configuredCount=count($configured); ?>
<div class="tare-config-summary <?= $configuredCount?'configured':'pending' ?>"><?php if($configuredCount): ?><strong><?= $configuredCount ?> hemocomponente(s) com tara configurada.</strong> Componentes sem vínculo continuam disponíveis para configuração.<?php else: ?><strong>Nenhum hemocomponente possui tara configurada.</strong> Crie ou edite um perfil para definir os vínculos.<?php endif; ?></div>
<div class="tare-list">
<?php foreach($tares as $tare): ?><article class="tare-card <?= !$tare['active']?'tare-card-inactive':'' ?>"><div class="tare-card-main"><div><small>Nome / identificação</small><h3><?= $h($tare['name']) ?></h3></div><div><small>Tara</small><strong><?= number_format((float)$tare['tare_weight'],3,',','.') ?> g</strong></div><div><small>Status</small><span class="status status-<?= $tare['active']?'active':'inactive' ?>"><?= $tare['active']?'Ativa':'Inativa' ?></span></div></div><div class="tare-components"><small>Hemocomponentes vinculados</small><div><?php foreach(array_filter(array_map('trim',explode(',',(string)$tare['component_codes']))) as $code): ?><span><?= $h($code) ?></span><?php endforeach; ?><?php if(!$tare['component_codes']): ?><em>Nenhum vínculo definido</em><?php endif; ?></div></div><div class="tare-card-actions"><?php if($tare['locked_at']): ?><span class="tare-locked">Uso analítico: perfil bloqueado</span><?php else: ?><button class="table-action tare-edit" type="button" data-tare='<?= $h(json_encode(['id'=>(int)$tare['id'],'name'=>$tare['name'],'tare_weight'=>$tare['tare_weight'],'active'=>(int)$tare['active'],'component_ids'=>$tare['component_ids']],JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)) ?>'>Editar</button><?php if($tare['active']): ?><form method="post" action="/admin/bag-brands/tares/deactivate" onsubmit="return confirm('Inativar este perfil de tara?')"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><input type="hidden" name="tare_id" value="<?= (int)$tare['id'] ?>"><button class="table-action table-action-danger" type="submit">Inativar</button></form><?php endif; ?><?php endif; ?></div></article><?php endforeach; ?>
<?php if(!$tares): ?><div class="section-empty">Nenhuma tara cadastrada para esta marca e preservante.</div><?php endif; ?></div></section>

<dialog class="shipment-cancel-dialog tare-dialog" id="tare-dialog"><form method="post" action="/admin/bag-brands/tares/create" id="tare-form"><div class="dialog-heading"><div><small class="eyebrow">Perfil de tara</small><h3 id="tare-dialog-title">Adicionar tara</h3></div><button class="dialog-close" type="button" data-close-tare>×</button></div><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><input type="hidden" name="bag_brand_id" value="<?= (int)$brand['id'] ?>"><input type="hidden" name="tare_id" value="">
<label><span>Nome / identificação *</span><input name="name" maxlength="180" required placeholder="Ex.: Bolsa de Hemácias"></label><label><span>Tara (g) *</span><input name="tare_weight" type="number" min="0.001" max="9999999.999" step="0.001" required placeholder="32,500"></label><label><span>Status *</span><select name="active"><option value="1">Ativa</option><option value="0">Inativa</option></select></label>
<fieldset class="tare-component-picker"><legend>Hemocomponentes vinculados</legend><p>Somente componentes ativos podem receber novos vínculos; vínculos inativos existentes são preservados para edição.</p><div><?php foreach($components as $component): ?><label><input type="checkbox" name="blood_component_ids[]" value="<?= (int)$component['id'] ?>"><span><strong><?= $h($component['code']) ?><?= $component['status']==='inactive'?' · Inativo':'' ?></strong><?= $h($component['name']) ?></span></label><?php endforeach; ?><?php if(!$components): ?><span class="empty">Nenhum hemocomponente ativo.</span><?php endif; ?></div></fieldset><div class="dialog-actions"><button class="button button-secondary" type="button" data-close-tare>Cancelar</button><button class="button" type="submit">Salvar tara</button></div></form></dialog>
<script>
(()=>{const dialog=document.getElementById('tare-dialog'),form=document.getElementById('tare-form'),title=document.getElementById('tare-dialog-title');if(!dialog)return;const reset=()=>{form.reset();form.action='/admin/bag-brands/tares/create';form.tare_id.value='';title.textContent='Adicionar tara';};document.querySelector('[data-open-tare]').addEventListener('click',()=>{reset();dialog.showModal();});document.querySelectorAll('[data-close-tare]').forEach(b=>b.addEventListener('click',()=>dialog.close()));document.querySelectorAll('.tare-edit').forEach(b=>b.addEventListener('click',()=>{reset();const t=JSON.parse(b.dataset.tare);form.action='/admin/bag-brands/tares/edit';form.tare_id.value=t.id;form.name.value=t.name;form.tare_weight.value=t.tare_weight;form.active.value=String(t.active);form.querySelectorAll('[name="blood_component_ids[]"]').forEach(c=>c.checked=t.component_ids.includes(Number(c.value)));title.textContent='Editar tara';dialog.showModal();}));dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});})();
</script><?php endif; ?>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
