<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$activeByName=[];foreach($brands as $item)if($item['active'])$activeByName[mb_strtolower(trim($item['name']))]=$item; ?>
<section class="content-card">
<div class="section-heading"><div><h2>Marcas de Bolsa</h2><p>Referências comerciais e seus perfis de tara.</p></div><a class="button" href="/admin/bag-brands/create">Nova Referência</a></div>
<div class="table-wrap"><table><thead><tr><th>Marca</th><th>Referência / Preservante</th><th>Quantidade de taras</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php foreach($brands as $brand): $current=$activeByName[mb_strtolower(trim($brand['name']))]??null; ?><tr><td><strong><?= $h($brand['name']) ?></strong></td><td><?= $h($brand['reference_number']?:'Pendente') ?><small class="cell-subtitle">Preservante: <?= $h($brand['preservative_code']?:'Pendente') ?></small></td><td><strong><?= (int)$brand['tare_count'] ?></strong><?php if((int)$brand['tare_count']!==(int)$brand['active_tare_count']): ?><small class="cell-subtitle"><?= (int)$brand['active_tare_count'] ?> ativa(s)</small><?php endif; ?></td><td><span class="status status-<?= $brand['active']?'active':'inactive' ?>"><?= $brand['active']?'Ativa':'Inativa' ?></span></td><td><div class="bag-brand-actions"><a class="table-action" href="/admin/bag-brands/edit?id=<?= (int)$brand['id'] ?>">Editar</a><button class="table-action <?= $brand['active']?'table-action-danger':'' ?>" type="button" data-toggle-brand data-id="<?= (int)$brand['id'] ?>" data-name="<?= $h($brand['name']) ?>" data-reference="<?= $h($brand['reference_number']) ?>" data-active="<?= (int)$brand['active'] ?>" data-current-reference="<?= $h(!$brand['active']&&$current?$current['reference_number']:'') ?>"><?= $brand['active']?'Inativar':'Ativar' ?></button></div></td></tr><?php endforeach; ?>
<?php if(!$brands): ?><tr><td colspan="5" class="empty">Nenhuma referência cadastrada.</td></tr><?php endif; ?></tbody></table></div>
</section>
<dialog class="shipment-cancel-dialog" id="brand-status-dialog"><form method="post" action="/admin/bag-brands/toggle-status"><div class="dialog-heading"><h3 id="brand-status-title"></h3><button class="dialog-close" type="button" data-close-status>×</button></div><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><input type="hidden" name="id"><input type="hidden" name="activate"><p id="brand-status-message"></p><div class="dialog-actions"><button class="button button-secondary" type="button" data-close-status>Cancelar</button><button class="button" type="submit" id="brand-status-confirm"></button></div></form></dialog>
<script>
(()=>{const d=document.getElementById('brand-status-dialog'),f=d.querySelector('form'),title=document.getElementById('brand-status-title'),message=document.getElementById('brand-status-message'),confirmButton=document.getElementById('brand-status-confirm');document.querySelectorAll('[data-toggle-brand]').forEach(b=>b.addEventListener('click',()=>{const active=b.dataset.active==='1';f.elements.id.value=b.dataset.id;f.elements.activate.value=active?'0':'1';if(active){title.textContent='Inativar referência';message.textContent='Esta referência deixará de aparecer em novos cadastros de amostras, mas continuará preservada nos registros históricos.';confirmButton.textContent='Inativar';}else{title.textContent='Ativar referência';message.textContent=b.dataset.currentReference?`Já existe uma referência ativa para a marca ${b.dataset.name}:\n\n${b.dataset.currentReference}\n\nDeseja ativar ${b.dataset.reference} e inativar automaticamente a referência atualmente ativa?`:`Deseja ativar ${b.dataset.reference} para a marca ${b.dataset.name}?`;message.style.whiteSpace='pre-line';confirmButton.textContent=b.dataset.currentReference?'Ativar e substituir':'Ativar';}d.showModal();}));d.querySelectorAll('[data-close-status]').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('click',e=>{if(e.target===d)d.close();});})();
</script>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
