<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); ?>
<section class="content-card">
<div class="section-heading"><div><h2>Marcas de Bolsa</h2><p>A combinação Marca + Preservante é a identidade operacional. A referência é apenas complementar.</p></div><a class="button" href="/admin/bag-brands/create">Nova Marca de Bolsa</a></div>
<div class="table-wrap"><table><thead><tr><th>Marca</th><th>Preservante</th><th>Referência</th><th>Taras</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php foreach($brands as $brand): ?><tr><td><strong><?= $h($brand['name']) ?></strong></td><td><strong><?= $h($brand['preservative_code']?:$brand['preservative_name']?:'Pendente') ?></strong></td><td><small class="cell-subtitle"><?= $h($brand['reference_number']?:'Não informada') ?></small></td><td><strong><?= (int)$brand['tare_count'] ?></strong><?php if((int)$brand['tare_count']!==(int)$brand['active_tare_count']): ?><small class="cell-subtitle"><?= (int)$brand['active_tare_count'] ?> ativa(s)</small><?php endif; ?></td><td><span class="status status-<?= $brand['active']?'active':'inactive' ?>"><?= $brand['active']?'Ativa':'Inativa' ?></span></td><td><div class="bag-brand-actions"><a class="table-action" href="/admin/bag-brands/edit?id=<?= (int)$brand['id'] ?>">Editar</a><button class="table-action <?= $brand['active']?'table-action-danger':'' ?>" type="button" data-toggle-brand data-id="<?= (int)$brand['id'] ?>" data-name="<?= $h($brand['name']) ?>" data-preservative="<?= $h($brand['preservative_code']?:$brand['preservative_name']) ?>" data-active="<?= (int)$brand['active'] ?>"><?= $brand['active']?'Inativar':'Ativar' ?></button><?php if(!$brand['is_used']): ?><form method="post" action="/admin/bag-brands/delete" onsubmit="return confirm('Excluir definitivamente este cadastro nunca utilizado e seus perfis de tara?')"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><input type="hidden" name="id" value="<?= (int)$brand['id'] ?>"><button class="table-action table-action-danger" type="submit">Excluir</button></form><?php endif; ?></div></td></tr><?php endforeach; ?>
<?php if(!$brands): ?><tr><td colspan="6" class="empty">Nenhuma marca de bolsa cadastrada.</td></tr><?php endif; ?></tbody></table></div>
</section>
<dialog class="shipment-cancel-dialog" id="brand-status-dialog"><form method="post" action="/admin/bag-brands/toggle-status"><div class="dialog-heading"><h3 id="brand-status-title"></h3><button class="dialog-close" type="button" data-close-status>×</button></div><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><input type="hidden" name="id"><input type="hidden" name="activate"><p id="brand-status-message"></p><div class="dialog-actions"><button class="button button-secondary" type="button" data-close-status>Cancelar</button><button class="button" type="submit" id="brand-status-confirm"></button></div></form></dialog>
<script>
(()=>{const d=document.getElementById('brand-status-dialog'),f=d.querySelector('form'),title=document.getElementById('brand-status-title'),message=document.getElementById('brand-status-message'),confirmButton=document.getElementById('brand-status-confirm');document.querySelectorAll('[data-toggle-brand]').forEach(b=>b.addEventListener('click',()=>{const active=b.dataset.active==='1';f.elements.id.value=b.dataset.id;f.elements.activate.value=active?'0':'1';title.textContent=active?'Inativar cadastro':'Ativar cadastro';message.textContent=active?'Este cadastro deixará de aparecer em novas operações, mas continuará preservado no histórico.':`Deseja ativar ${b.dataset.name} + ${b.dataset.preservative}? A ativação será bloqueada se essa combinação já estiver ativa.`;confirmButton.textContent=active?'Inativar':'Ativar';d.showModal();}));d.querySelectorAll('[data-close-status]').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('click',e=>{if(e.target===d)d.close();});})();
</script>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php'; ?>
