<?php
declare(strict_types=1);
use BloodHub\Core\Database;
if(PHP_SAPI!=='cli'){http_response_code(403);exit;}
spl_autoload_register(static function(string$class):void{$prefix='BloodHub\\';if(!str_starts_with($class,$prefix))return;$file=dirname(__DIR__).'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require$file;});
$pdo=Database::connection();
foreach(['bacteriology_positive_samples','bacteriology_positive_sample_records']as$table){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table');$q->execute(['table'=>$table]);if(!(int)$q->fetchColumn())throw new RuntimeException("Tabela ausente: $table");}
$columns=['bacteriology_result_id','sample_id','donation_number','status','conclusion','completed_at'];foreach($columns as$column){$q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bacteriology_positive_samples' AND COLUMN_NAME=:column");$q->execute(['column'=>$column]);if(!(int)$q->fetchColumn())throw new RuntimeException("Coluna ausente: $column");}
$columns=['client_id'];foreach($columns as$column){$q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bacteriology_positive_samples' AND COLUMN_NAME=:column");$q->execute(['column'=>$column]);if(!(int)$q->fetchColumn())throw new RuntimeException("Coluna ausente: $column");}
$columns=['blood_component_id','storage_unit_id','identified_bacteria_initial','identified_bacteria_retest'];foreach($columns as$column){$q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bacteriology_positive_sample_records' AND COLUMN_NAME=:column");$q->execute(['column'=>$column]);if(!(int)$q->fetchColumn())throw new RuntimeException("Coluna ausente: $column");}
$service=file_get_contents(dirname(__DIR__).'/src/Services/BacteriologyService.php');if(!str_contains($service,"if(\$result==='positive')PositiveBacteriologySampleService::createFromConfirmedResult"))throw new RuntimeException('Integração do reteste positivo ausente.');if(str_contains($service,"if(\$stage||\$result==='negative')"))throw new RuntimeException('Resultado pós-pool ainda ignora reteste.');
$positiveService=file_get_contents(dirname(__DIR__).'/src/Services/PositiveBacteriologySampleService.php');foreach(["WHERE status='active' ORDER BY code,name","client_id=:client AND status='active'","storage_unit_id"]as$expected)if(!str_contains($positiveService,$expected))throw new RuntimeException("Fonte dinâmica ausente: $expected");
$controller=file_get_contents(dirname(__DIR__).'/src/Controllers/BacteriologyController.php');if(!str_contains($controller,"if((int)\$r['position']===1)return false"))throw new RuntimeException('Registro original não está protegido da reimpressão.');
$modal=file_get_contents(dirname(__DIR__).'/src/Views/quality_control/bacteriology_positive_modal.php');foreach(['name="blood_component_id[]"','name="storage_unit_id[]"','name="identified_bacteria_initial[]"','name="identified_bacteria_retest[]"','Imprimir selecionados','in_stock','distributed','discarded']as$expected)if(!str_contains($modal,$expected))throw new RuntimeException("Controle do modal ausente: $expected");
$routes=file_get_contents(dirname(__DIR__).'/public/index.php');foreach(['bacteriology/retest/form','bacteriology/positive-samples/save','bacteriology/positive-samples/form']as$route)if(!str_contains($routes,$route))throw new RuntimeException("Rota ausente: $route");
echo "OK: positivo confirmado, persistência múltipla e rotas de impressão validados.\n";
