<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');?>
<section class="content-card form-card"><div class="section-heading"><div><h2>Nova vigência</h2><p>Nenhuma meta é presumida. A cor só é aplicada quando houver uma meta válida para o período.</p></div><a class="button button-secondary" href="/admin">Voltar</a></div>
<form class="admin-form" method="post" action="/admin/dashboard-targets"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><div class="form-grid">
<label><span>Hemocomponente *</span><select name="blood_component_id" required><option value="">Selecione</option><?php foreach($components as$c):?><option value="<?=$c['id']?>"><?=$e($c['code'].' — '.$c['name'])?></option><?php endforeach?></select></label>
<label><span>Teste final *</span><select name="test_id" required><option value="">Selecione</option><?php foreach($tests as$t):?><option value="<?=$t['id']?>" data-components=",<?=$e($t['component_ids'])?>,"><?=$e($t['name'])?></option><?php endforeach?></select></label>
<label><span>Meta mínima (%) *</span><input type="number" min="0" max="100" step="0.01" name="minimum_percentage" required placeholder="Ex.: 95,00"></label>
<label><span>Vigência a partir de *</span><input type="date" name="effective_from" value="<?=date('Y-m-d')?>" required></label>
<label><span>Ativo</span><select name="active"><option value="1">Sim</option><option value="0">Não</option></select></label></div><div class="form-actions"><button class="button">Salvar nova vigência</button></div></form></section>
<section class="content-card"><div class="section-heading"><div><h2>Histórico de metas</h2><p>Alterações futuras encerram automaticamente a vigência anterior do mesmo indicador.</p></div></div><div class="table-wrap"><table><thead><tr><th>Hemocomponente</th><th>Teste</th><th>Meta mínima</th><th>Vigência</th><th>Status</th></tr></thead><tbody><?php foreach($targets as$t):?><tr><td><b><?=$e($t['component_code'])?></b> <?=$e($t['component_name'])?></td><td><?=$e($t['test_name'])?></td><td><?=number_format((float)$t['minimum_percentage'],1,',','.')?>%</td><td><?=date('d/m/Y',strtotime($t['effective_from']))?><?=$t['effective_to']?' a '.date('d/m/Y',strtotime($t['effective_to'])):' em diante'?></td><td><span class="status status-<?=$t['active']?'active':'inactive'?>"><?=$t['active']?'Ativa':'Inativa'?></span></td></tr><?php endforeach?><?php if(!$targets):?><tr><td class="empty" colspan="5">Nenhuma meta configurada. O Dashboard permanecerá neutro.</td></tr><?php endif?></tbody></table></div></section>
<script>(()=>{const component=document.querySelector('[name="blood_component_id"]'),test=document.querySelector('[name="test_id"]');const sync=()=>{const id=component.value;[...test.options].forEach(o=>{if(!o.value)return;o.hidden=!o.dataset.components.includes(','+id+',')});if(test.selectedOptions[0]?.hidden)test.value=''};component.addEventListener('change',sync);sync()})();</script>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php';?>
