<?php require dirname(__DIR__,2).'/layouts/admin_start.php';$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');?>
<section class="content-card form-card"><div class="section-heading"><div><h2>Nova vigência</h2><p>Nenhuma meta é presumida. A cor só é aplicada quando houver uma meta válida para o período.</p></div><a class="button button-secondary" href="/admin">Voltar</a></div>
<form class="admin-form" id="target-form" method="post" action="/admin/dashboard-targets"><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id"><div class="form-grid">
<label><span>Hemocomponente *</span><select name="blood_component_id" required><option value="">Selecione</option><?php foreach($components as$c):?><option value="<?=$c['id']?>"><?=$e($c['code'].' — '.$c['name'])?></option><?php endforeach?></select></label>
<label><span>Teste final *</span><select name="test_id" required><option value="">Selecione</option><?php foreach($tests as$t):?><option value="<?=$t['id']?>" data-components=",<?=$e($t['component_ids'])?>,"><?=$e($t['name'])?></option><?php endforeach?></select></label>
<label><span>Meta mínima (%) *</span><input type="number" min="0" max="100" step="0.01" name="minimum_percentage" required placeholder="Ex.: 95,00"></label>
<label><span>Vigência a partir de *</span><input type="date" name="effective_from" value="<?=date('Y-m-d')?>" required></label>
<label><span>Ativo</span><select name="active"><option value="1">Sim</option><option value="0">Não</option></select></label></div><div class="form-actions"><button class="button">Salvar nova vigência</button></div></form></section>
<?php $filter=$_GET['status']??'current';?><section class="content-card"><div class="section-heading"><div><h2>Histórico de metas</h2><p>Metas vigentes são alteradas por nova versão; períodos anteriores permanecem intactos.</p></div><form method="get"><select name="status" onchange="this.form.submit()"><option value="current" <?=$filter==='current'?'selected':''?>>Vigentes</option><option value="future" <?=$filter==='future'?'selected':''?>>Futuras</option><option value="inactive" <?=$filter==='inactive'?'selected':''?>>Inativas</option><option value="all" <?=$filter==='all'?'selected':''?>>Todas</option></select></form></div><div class="table-wrap"><table><thead><tr><th>Hemocomponente</th><th>Teste</th><th>Meta mínima</th><th>Vigência</th><th>Versão</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php $versions=[];foreach(array_reverse($targets)as$x){$key=$x['blood_component_id'].'-'.$x['test_id'];$versions[$x['id']]=($versions[$key]??0)+1;$versions[$key]=$versions[$x['id']];}foreach($targets as$t):$today=date('Y-m-d');$future=$t['effective_from']>$today;$current=$t['active']&&$t['effective_from']<=$today&&(!$t['effective_to']||$t['effective_to']>=$today);if(($filter==='current'&&!$current)||($filter==='future'&&!$future)||($filter==='inactive'&&$t['active']))continue;?><tr><td><b><?=$e($t['component_code'])?></b> <?=$e($t['component_name'])?></td><td><?=$e($t['test_name'])?></td><td><?=number_format((float)$t['minimum_percentage'],1,',','.')?>%</td><td><?=date('d/m/Y',strtotime($t['effective_from']))?><?=$t['effective_to']?' a '.date('d/m/Y',strtotime($t['effective_to'])):' em diante'?></td><td>v<?=$versions[$t['id']]?></td><td><span class="status status-<?=$t['active']?'active':'inactive'?>"><?=$t['active']?($future?'Futura':'Ativa'):'Inativa'?></span></td><td><div class="table-actions"><button type="button" class="table-action" data-edit-target='<?=$e(json_encode($t,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'>Editar</button><button type="button" class="table-action" data-target-action="toggle" data-id="<?=$t['id']?>" data-active="<?=$t['active']?0:1?>"><?=$t['active']?'Inativar':'Ativar'?></button><button type="button" class="table-action table-action-danger" data-target-action="delete" data-id="<?=$t['id']?>">Excluir</button></div></td></tr><?php endforeach?><?php if(!$targets):?><tr><td class="empty" colspan="7">Nenhuma meta configurada. O Dashboard permanecerá neutro.</td></tr><?php endif?></tbody></table></div></section>
<dialog class="shipment-cancel-dialog" id="target-confirm"><form method="post"><div class="dialog-heading"><h3>Confirmar ação</h3><button class="dialog-close" type="button" data-close>×</button></div><input type="hidden" name="_csrf" value="<?=$e($csrf)?>"><input type="hidden" name="id"><input type="hidden" name="active"><p>Metas com vigência iniciada não serão excluídas; use a inativação para preservar o histórico.</p><div class="dialog-actions"><button class="button button-secondary" type="button" data-close>Cancelar</button><button class="button button-danger">Confirmar</button></div></form></dialog>
<script>(()=>{const form=document.querySelector('#target-form'),component=form.elements.blood_component_id,test=form.elements.test_id;const sync=()=>{const id=component.value;[...test.options].forEach(o=>{if(!o.value)return;o.hidden=!o.dataset.components.includes(','+id+',')});if(test.selectedOptions[0]?.hidden)test.value=''};component.addEventListener('change',sync);sync();document.querySelectorAll('[data-edit-target]').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.editTarget);Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v??''});sync();test.value=d.test_id;form.scrollIntoView({behavior:'smooth'})});const dialog=document.querySelector('#target-confirm'),df=dialog.querySelector('form');document.querySelectorAll('[data-target-action]').forEach(b=>b.onclick=()=>{df.action='/admin/dashboard-targets/'+b.dataset.targetAction;df.elements.id.value=b.dataset.id;df.elements.active.value=b.dataset.active??'';dialog.showModal()});dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close())})();</script>
<?php require dirname(__DIR__,2).'/layouts/admin_end.php';?>
