<?php $h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$query=['date_from'=>$filters['from'],'date_to'=>$filters['to'],'unit_id'=>$filters['unit']?:'','blood_component_id'=>$filters['component']?:'','donation'=>$filters['donation'],'lcqh'=>$filters['lcqh'],'conformity'=>$filters['conformity'],'per_page'=>$filters['perPage'],'sort'=>$filters['sort']];$url=fn($path,$extra=[])=>$path.'?'.http_build_query(array_merge($query,$extra));$statusLabel=fn($s)=>match($s){'CONFORMING'=>'Conforme','NONCONFORMING'=>'Fora da especificação','NO_SPECIFICATION'=>'Sem especificação aplicável',default=>'Não avaliado'};require dirname(__DIR__).'/layouts/admin_start.php';?>
<section class="report-period-note"><strong>Período de recebimento.</strong> A consulta usa a data em que a amostra foi recebida pelo LCQH.</section>
<form class="content-card qcr-filters" method="get" action="/reports/quality-control">
 <label><span>Data inicial *</span><input type="date" name="date_from" required value="<?=$h($filters['from'])?>"></label><label><span>Data final *</span><input type="date" name="date_to" required value="<?=$h($filters['to'])?>"></label>
 <label><span>Origem / Processamento</span><select name="unit_id"><option value="">Todos os processamentos</option><?php foreach($filters['units']as$u):?><option value="<?=$u['id']?>" <?=$filters['unit']==$u['id']?'selected':''?>><?=$h($u['name'])?></option><?php endforeach;?></select></label>
 <label><span>Hemocomponente</span><select name="blood_component_id"><option value="">Todos</option><?php foreach($filters['components']as$c):?><option value="<?=$c['id']?>" <?=$filters['component']==$c['id']?'selected':''?>><?=$h($c['code'].' — '.$c['name'])?></option><?php endforeach;?></select></label>
 <label><span>Nº da doação</span><input name="donation" value="<?=$h($filters['donation'])?>" placeholder="Pesquisa parcial"></label><label><span>Código LCQH</span><input name="lcqh" value="<?=$h($filters['lcqh'])?>" placeholder="Pesquisa parcial"></label>
 <label><span>Situação da conformidade</span><select name="conformity"><option value="">Todos</option><option value="conforming" <?=$filters['conformity']==='conforming'?'selected':''?>>Conformes</option><option value="nonconforming" <?=$filters['conformity']==='nonconforming'?'selected':''?>>Com resultado fora da especificação</option></select></label>
 <label><span>Ordenar por</span><select name="sort"><option value="date" <?=$filters['sort']==='date'?'selected':''?>>Data (mais recente)</option><option value="origin" <?=$filters['sort']==='origin'?'selected':''?>>Origem</option><option value="donation" <?=$filters['sort']==='donation'?'selected':''?>>Nº da doação</option></select></label>
 <div class="qcr-filter-actions"><button class="button">Buscar</button><a class="button button-secondary" href="/reports/quality-control">Limpar filtros</a></div><div class="qcr-export-actions"><a class="button button-secondary" href="<?=$h($url('/reports/quality-control/csv'))?>">Exportar CSV</a><a class="button button-secondary" target="_blank" rel="noopener" href="<?=$h($url('/reports/quality-control/pdf'))?>">Gerar PDF</a></div>
</form>
<section class="qcr-summary"><article><small>Registros</small><strong><?=number_format($summary['records'],0,',','.')?></strong></article><article><small>Conformes</small><strong><?=number_format($summary['conforming'],0,',','.')?></strong></article><article><small>Com alguma não conformidade</small><strong class="danger"><?=number_format($summary['nonconforming'],0,',','.')?></strong></article><article><small>Processamentos</small><strong><?=$summary['units']?></strong></article></section>
<div class="qcr-count"><strong><?=number_format($report['total'],0,',','.')?> registro(s) encontrado(s)</strong><label>Por página <select onchange="location.href=this.value"><?php foreach([25,50,100]as$n):?><option value="<?=$h($url('/reports/quality-control',['per_page'=>$n,'page'=>1]))?>" <?=$filters['perPage']===$n?'selected':''?>><?=$n?></option><?php endforeach;?></select></label></div>
<?php foreach($report['groups']as$group):?><section class="content-card qcr-group"><header><div><span><?=$h($group['component_code'])?></span><h2><?=$h($group['component_name'])?></h2></div><small><?=count($group['samples'])?> nesta página</small></header><div class="qcr-table-scroll"><table><thead><tr><th class="sticky-col">Nº da doação</th><th>Recebimento</th><th>Hemocomponente</th><th>Produção</th><th>Origem</th><th>Bolsa</th><th>Código LCQH</th><th>Preservante</th><?php foreach($group['columns']as$c):?><th><?=$h($c['name'])?></th><?php endforeach;?></tr></thead><tbody><?php foreach($group['samples']as$s):?><tr><td class="sticky-col"><a href="/reports/quality-control/detail?id=<?=$s['id']?>"><?=$h($s['donation_number']?:'—')?></a></td><td><?=$s['received_at']?date('d/m/Y H:i',strtotime($s['received_at'])):'—'?></td><td><?=$h($s['component_code'])?></td><td><?=$s['production_date']?date('d/m/Y',strtotime($s['production_date'])):'—'?></td><td><?=$h($s['origin_name']?:'—')?></td><td><?=$h($s['bag_brand']?:'—')?></td><td><?=$h($s['lcqh_code']?:'—')?></td><td><?=$h($s['preservative_name']?:'—')?></td><?php foreach($group['columns']as$c):$r=$s['results'][(int)$c['id']]??null;?><td><?php if(!$r):?>—<?php else:$tip='Resultado: '.$r['display']."\nReferência: ".$r['reference']."\nStatus: ".$statusLabel($r['status']);?><span class="qcr-result <?=$r['status']==='NONCONFORMING'?'is-out':''?>" tabindex="0" title="<?=$h($tip)?>"><?=$h($r['display'])?></span><?php if($canViewNotifications&&!empty($r['notification_id'])):?><a class="qcr-notification" href="/notifications?id=<?=$r['notification_id']?>" title="Notificação <?=$h($r['notification_code'])?>">Notificação</a><?php endif;?><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section><?php endforeach;?>
<?php if(!$report['total']):?><section class="content-card qcr-empty">Não foram encontrados resultados para os filtros selecionados.</section><?php endif;?>
<?php if($report['pages']>1):?><nav class="qcr-pagination" aria-label="Paginação"><?php if($report['page']>1):?><a class="button button-secondary" href="<?=$h($url('/reports/quality-control',['page'=>$report['page']-1]))?>">Anterior</a><?php endif;?><span>Página <?=$report['page']?> de <?=$report['pages']?></span><?php if($report['page']<$report['pages']):?><a class="button button-secondary" href="<?=$h($url('/reports/quality-control',['page'=>$report['page']+1]))?>">Próxima</a><?php endif;?></nav><?php endif;?>
<?php require dirname(__DIR__).'/layouts/admin_end.php';?>
