<?php
use BloodHub\Core\Auth;
use BloodHub\Services\IndicatorValueFormatter as F;
$h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$selectedIds=array_map('intval',array_column($selected['responsibles']??[],'user_id'));
$availableUsers=array_values(array_filter($users,fn($u)=>!in_array((int)$u['id'],$selectedIds,true)));
$isAdministrator=Auth::isAdministrator();
$operators=['GTE'=>'≥','GT'=>'>','LTE'=>'≤','LT'=>'<','EQ'=>'='];
require dirname(__DIR__,2).'/layouts/admin_start.php';
?>
<nav class="indicator-admin-tabs"><?php foreach($indicators as$i):?><a class="<?=($selected&&$i['id']===$selected['id'])?'active':''?>" href="/admin/indicators?id=<?=(int)$i['id']?>"><?=$h($i['name'])?><?php if(!$i['active']):?> <small>Inativo</small><?php endif;?></a><?php endforeach;?></nav>
<?php if($selected):?>
<section class="indicator-admin-grid">
 <form class="content-card indicator-config-form" method="post" action="/admin/indicators/metadata"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><header><div><h2>Metadados</h2><p>As informações exibidas no cabeçalho institucional.</p></div></header><div class="config-fields"><label class="span-2"><span>Nome</span><input class="bh-field" name="name" value="<?=$h($selected['name'])?>" required></label><label class="span-2"><span>Objetivo</span><textarea class="bh-field bh-textarea" name="objective" rows="3"><?=$h($selected['objective'])?></textarea></label><?php foreach(['sector'=>'Setor','regional'=>'Regional','category'=>'Categoria','subcategory'=>'Subcategoria','periodicity'=>'Periodicidade','value_unit'=>'Unidade exibida']as$key=>$label):?><label><span><?=$label?></span><input class="bh-field" name="<?=$key?>" value="<?=$h($selected[$key])?>"></label><?php endforeach;?><label><span>Tipo de valor</span><select class="bh-field bh-select" name="value_type"><?php foreach(['percentage'=>'Percentual','scientific'=>'Científico','number'=>'Numérico']as$v=>$label):?><option value="<?=$v?>" <?=$selected['value_type']===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label><span>Teste final configurado</span><select class="bh-field bh-select" name="configured_test_id"><option value="">Não se aplica</option><?php foreach($tests as$t):?><option value="<?=(int)$t['id']?>" <?=(int)$selected['configured_test_id']===(int)$t['id']?'selected':''?>><?=$h($t['name'].' ('.$t['code'].')')?></option><?php endforeach;?></select></label><label class="config-check"><input class="bh-switch-input" type="checkbox" name="active" value="1" <?=$selected['active']?'checked':''?>><span class="bh-switch" aria-hidden="true"></span><span>Indicador ativo</span></label></div><button class="button">Salvar metadados</button></form>
 <div class="indicator-admin-side">
  <?php if($isAdministrator):?><form class="content-card indicator-config-form" method="post" action="/admin/indicators/target"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><header><div><h2>Nova versão de meta</h2><p>A vigência anterior é encerrada automaticamente.</p></div></header><div class="target-fields"><label><span>Operador</span><select class="bh-field bh-select" name="target_operator"><?php foreach($operators as$v=>$label):?><option value="<?=$v?>"><?=$label?></option><?php endforeach;?></select></label><label><span>Valor</span><input class="bh-field" name="target_value" inputmode="decimal" placeholder="Ex.: 90 ou 5.5e10" required></label><label><span>Vigente desde</span><input class="bh-field" type="date" name="effective_from" value="<?=date('Y-m-01')?>" required></label></div><button class="button">Salvar nova meta</button></form><?php endif;?>
  <section class="content-card indicator-config-form responsible-manager"><header><div><h2>Responsáveis</h2><p>Usuários autorizados a editar análises e ações.</p></div></header><div class="responsible-list"><?php if(!$selected['responsibles']):?><p class="indicator-muted">Nenhum responsável vinculado.</p><?php else:foreach($selected['responsibles']as$responsible):?><article class="responsible-item"><div><strong><?=$h($responsible['name'])?></strong><span><?=$h($responsible['email'])?></span></div><?php if($isAdministrator):?><button type="button" class="button button-secondary button-compact responsible-remove" data-user-id="<?=(int)$responsible['user_id']?>" data-user-name="<?=$h($responsible['name'])?>">Remover</button><?php endif;?></article><?php endforeach;endif;?></div>
  <?php if($isAdministrator):?><form class="responsible-add" method="post" action="/admin/indicators/responsibles/add"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><label><span>Adicionar responsável</span><select class="bh-field bh-select" name="user_id" required><option value="">Selecione um usuário</option><?php foreach($availableUsers as$u):?><option value="<?=(int)$u['id']?>"><?=$h($u['name'].' · '.$u['email'])?></option><?php endforeach;?></select></label><button class="button" <?=$availableUsers?'':'disabled'?>>Adicionar</button></form><?php endif;?></section>
 </div>
</section>
<section class="content-card indicator-target-history"><header><div><h2>Histórico de metas</h2><p>Versões excluídas permanecem disponíveis para auditoria.</p></div></header><div class="table-wrap"><table><thead><tr><th>Meta</th><th>Vigente desde</th><th>Vigente até</th><th>Status</th><th>Registrada por</th><?php if($isAdministrator):?><th>Ações</th><?php endif;?></tr></thead><tbody><?php if(!$targets):?><tr><td colspan="<?=$isAdministrator?6:5?>">Nenhuma meta configurada.</td></tr><?php else:foreach($targets as$t):$deleted=$t['deleted_at']!==null;?><tr class="<?=$deleted?'target-deleted':''?>"><td><b><?=F::target($selected,$t)?></b><?php if($deleted&&$t['deletion_reason']):?><small class="target-deletion-reason">Motivo: <?=$h($t['deletion_reason'])?></small><?php endif;?></td><td><?=date('d/m/Y',strtotime($t['effective_from']))?></td><td><?=$deleted?'—':($t['effective_to']?date('d/m/Y',strtotime($t['effective_to'])):'Em aberto')?></td><td><span class="badge <?=$deleted?'badge-danger':($t['active']?'badge-success':'badge-neutral')?>"><?=$deleted?'EXCLUÍDA':($t['active']?'Ativa':'Inativa')?></span></td><td><?=$h($t['created_by_name']?:'Sistema')?></td><?php if($isAdministrator):?><td><div class="target-actions"><?php if(!$deleted):?><button type="button" class="button button-secondary button-compact target-edit" data-id="<?=(int)$t['id']?>" data-operator="<?=$h($t['target_operator'])?>" data-value="<?=$h($t['target_value'])?>" data-effective="<?=$h($t['effective_from'])?>">Editar</button><button type="button" class="button button-danger-outline button-compact target-delete" data-id="<?=(int)$t['id']?>" data-label="<?=$h(F::target($selected,$t))?>" data-effective="<?=date('d/m/Y',strtotime($t['effective_from']))?>">Excluir</button><?php else:?><span class="indicator-muted">Sem ações</span><?php endif;?></div></td><?php endif;?></tr><?php endforeach;endif;?></tbody></table></div></section>

<?php if($isAdministrator):?>
<dialog class="indicator-dialog admin-indicator-dialog" id="removeResponsibleDialog"><form method="post" action="/admin/indicators/responsibles/remove"><header><div><span>Responsáveis</span><h3>Remover responsável</h3></div><button type="button" data-close aria-label="Fechar">×</button></header><div class="dialog-scroll"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="user_id"><p><strong id="removeResponsibleName"></strong></p><p>Remover este usuário dos responsáveis pelo indicador?</p><p class="dialog-help">O usuário continuará podendo visualizar o indicador conforme suas permissões, mas não poderá editar análises e ações.</p></div><footer><button type="button" class="button button-secondary" data-close>Cancelar</button><button class="button button-danger">Remover</button></footer></form></dialog>
<dialog class="indicator-dialog admin-indicator-dialog" id="editTargetDialog"><form method="post" action="/admin/indicators/target/update"><header><div><span>Correção administrativa</span><h3>Editar meta</h3></div><button type="button" data-close aria-label="Fechar">×</button></header><div class="dialog-scroll modal-field-grid"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="target_id"><label><span>Operador</span><select class="bh-field bh-select" name="target_operator"><?php foreach($operators as$v=>$label):?><option value="<?=$v?>"><?=$label?></option><?php endforeach;?></select></label><label><span>Valor</span><input class="bh-field" name="target_value" inputmode="decimal" required></label><label class="span-2"><span>Vigente desde</span><input class="bh-field" type="date" name="effective_from" required></label></div><footer><button type="button" class="button button-secondary" data-close>Cancelar</button><button class="button">Salvar alterações</button></footer></form></dialog>
<dialog class="indicator-dialog admin-indicator-dialog" id="deleteTargetDialog"><form method="post" action="/admin/indicators/target/delete"><header><div><span>Correção administrativa</span><h3>Excluir meta</h3></div><button type="button" data-close aria-label="Fechar">×</button></header><div class="dialog-scroll"><input type="hidden" name="_csrf" value="<?=$h($csrf)?>"><input type="hidden" name="indicator_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="target_id"><dl class="delete-target-summary"><div><dt>Meta</dt><dd id="deleteTargetLabel"></dd></div><div><dt>Vigente desde</dt><dd id="deleteTargetEffective"></dd></div></dl><label><span>Motivo da exclusão *</span><textarea class="bh-field bh-textarea" name="deletion_reason" rows="4" maxlength="1000" required></textarea></label></div><footer><button type="button" class="button button-secondary" data-close>Cancelar</button><button class="button button-danger">Excluir meta</button></footer></form></dialog>
<script>
(()=>{const bind=(dialog,triggers,fill)=>{triggers.forEach(button=>button.addEventListener('click',()=>{fill(dialog,button);dialog.showModal();document.body.classList.add('modal-open')}));dialog.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>dialog.close()));dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));};
bind(document.getElementById('removeResponsibleDialog'),document.querySelectorAll('.responsible-remove'),(d,b)=>{d.querySelector('[name=user_id]').value=b.dataset.userId;d.querySelector('#removeResponsibleName').textContent=b.dataset.userName});
bind(document.getElementById('editTargetDialog'),document.querySelectorAll('.target-edit'),(d,b)=>{d.querySelector('[name=target_id]').value=b.dataset.id;d.querySelector('[name=target_operator]').value=b.dataset.operator;d.querySelector('[name=target_value]').value=b.dataset.value;d.querySelector('[name=effective_from]').value=b.dataset.effective});
bind(document.getElementById('deleteTargetDialog'),document.querySelectorAll('.target-delete'),(d,b)=>{d.querySelector('[name=target_id]').value=b.dataset.id;d.querySelector('#deleteTargetLabel').textContent=b.dataset.label;d.querySelector('#deleteTargetEffective').textContent=b.dataset.effective;d.querySelector('[name=deletion_reason]').value=''});})();
</script>
<?php endif;?>
<?php endif;require dirname(__DIR__,2).'/layouts/admin_end.php';?>
